### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Whitesttax** [sammchardy/python-binance#10]
Hello, I'm getting this error here and there. Not too frequently, but I'd appreciate if you'd take a look at it.
![capture](https://user-images.githubusercontent.com/20992483/31475940-06e8fb0c-aeda-11e7-8e9b-7aa2039f3cb3.PNG)

**Comment by sammchardy** [comment]
@Whitesttax looks like an invalid response from the Binance API. Have added a handler for this with BinanceResponseException in v0.3.2
