### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 37: invalid start byte

### ISSUE THREAD

**Issue by yusail** [sammchardy/python-binance#100]
My environment is Windows10，Python 3.7 (64-bit)

When I use pip install python-binance in CMD, This error is come up.

How can I fix it .

**Comment by SkylerX** [comment]
@yusail  Try to download and install Windows Visual C version 14 with the python package.
Another alternative that on the mid long run is always better is to download Vmware Workstation, download Ubuntu or any other linux you like and install it there. Trust me , this decision is going to avoid you so many headache in future. Hope this helps. Good luck

**Comment by yusail** [comment]
That's good idea, thx

**Comment by sammchardy** [comment]
Thanks @SkylerX 

@yusail if you are able to check that installing the correct Visual Studio package works please report back. See helpful link to related packages in the documentation https://python-binance.readthedocs.io/en/latest/overview.html#installation

**Comment by yusail** [comment]
@sammchardy 
I reinstall vs 2017 community with all package，but there is still a error:

  ModuleNotFoundError: No module named 'cffi'
    ----------------------------------------
Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\yyf\\AppData\\Local\\Temp\\pip-build-h9_vysb7\\cryptography\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\yyf\AppData\Local\Temp\pip-lkl2qx_g-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\yyf\AppData\Local\Temp\pip-build-h9_vysb7\cryptography\

**Comment by SkylerX** [comment]
You're welcome @sammchardy . @yusail not sure why with Visual is gives you this error, it's an hail Mary, but try to install separately the last module that tells you that it has an error, although usually as per my experience even if you solve this one on windows something new is gonna come up, also if you can try to find the windows visual 2015, disintall the 2017, clean c removing from c propoerties, remove all files including temporary, install 2015, restart, then try again to install it. 
Please let us know, has this could help other windows users. Good luck @yusail

**Comment by yusail** [comment]
I have install module cffi via  pip as follow, but it doesn't fix error. 

C:\Users\yyf>pip install cffi
Requirement already satisfied: cffi in d:\python\lib\site-packages
Requirement already satisfied: pycparser in d:\python\lib\site-packages (from cffi)

**Comment by SkylerX** [comment]
Hi @yusail , sorry to hear that! my last advise is to try with linux. Good luck @yusail
