### ISSUE TITLE
Paper trading support?

### ISSUE THREAD

**Issue by tienduccao** [sammchardy/python-binance#101]
Hi, I'd like to ask if you have plan to support paper trading?

**Comment by sammchardy** [comment]
Hi @tienduccao I think this is out of scope of the library itself and makes sense to be a separate package.

I am writing some articles around using this library and was looking at one around backtesting to start with. Paper trading could be an extension of that, let me know if you have particular ideas though.

**Comment by tienduccao** [comment]
Hi, you're right.
Look forward to seeing your articles.
I used to use Pyalgotrade for backtesting.

On Jan 11, 2018 11:48, "Sam McHardy" <notifications@github.com> wrote:

Hi @tienduccao <https://github.com/tienduccao> I think this is out of scope
of the library itself and makes sense to be a separate package.

I am writing some articles around using this library and was looking at one
around backtesting to start with. Paper trading could be an extension of
that, let me know if you have particular ideas though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sammchardy/python-binance/issues/101#issuecomment-356897650>,
or mute the thread
