### ISSUE TITLE
Unresolved import BinanceWithdrawException 

### ISSUE THREAD

**Issue by mayhem7** [sammchardy/python-binance#1014]
I'm trying to make a withdraw code but when i try to import the exception it says "Unresolved import", are the API docs not updated?

`from binance.exceptions import BinanceRequestException, BinanceAPIException, BinanceWithdrawException`

I have everything else working, placing/getting orders, assets, history... but i can't make the withdraw work because of that,
thanks!

**Comment by sammchardy** [comment]
Hi @mayhem7 this exception doesn't exist anymore so you don't need to import it.

I'll remove it from the docs, they have gotten out of sync there.

**Comment by mayhem7** [comment]
Thanks! i was getting mad, i have another question but i'll mark this one as resolved, thanks again!

> 
> 
> Hi @mayhem7 this exception doesn't exist anymore so you don't need to import it.
> 
> I'll remove it from the docs, they have gotten out of sync there.
