### ISSUE TITLE
invalid signature

### ISSUE THREAD

**Issue by LiYijin** [sammchardy/python-binance#102]
Hello, I met this problem just now, which never met before.
I guess, is this because that  sigature algorithm updated?
Thank you very much~

**Comment by SkylerX** [comment]
Hi @LiYijin , in which instance exactly did you get this error? at the initial connection to API or when you are try an client side buy or sell order? can you give more info please? Cheers

**Comment by pearsonkyle** [comment]
I am getting the same error trying to perform a test market order buy and sell. 

```
from binance.client import Client
from binance.enums import *

client = Client(settings['key'],settings['secret'])

order = client.create_test_order(
    symbol='XRPETH',
    side=SIDE_BUY,
    type=ORDER_TYPE_MARKET,
    quantity=20,
    timeInForce=TIME_IN_FORCE_GTC,
    recvWindow=6000000
)
```

**Comment by rxcod9** [comment]
https://github.com/jaggedsoft/php-binance-api#248
https://github.com/binance-exchange/php-binance-api#59
https://github.com/yasinkuyu/binance-trader#263
https://github.com/zoeyg/binance/pull/75

**Comment by MarcGoulding** [comment]
I've encountered this problem too calling
```
client.get_isolated_margin_account(symbols=['BTCUSDT,ETHUSDT']
```
