### ISSUE TITLE
Any way to pull all klines at once?

### ISSUE THREAD

**Issue by Sylentwolf8** [sammchardy/python-binance#103]
Hey this is less of an issue, and more of a question. Is there any way that I would be able to pull all klines at once instead of per trade pair? For example rather than looping through 10 trade pairs 10 times to get the klines for all of them, simply request all klines at once.

The reason I ask is because I am currently doing that looping method, and it really slows down the script having to do so many requests. 

Alternatively, any other best practices or ideas for speeding things up?

**Comment by SkylerX** [comment]
Hi @Sylentwolf8 , I personally did not see an option to retrive all the keylines simultaniously, also even if it was, i doubt that it would have speed up much the script as it's still needs to connect to all the symbol to gather their info from the API. Let me know if you find a work around it.
Was just thinking maybe to send the request out from separate scripts and gather the results back in the first, but again not sure if it will save time, maybe if your get different API keys for different account just to get the datas and not to acctually trade from the other accounts. Just a tought! let me know. Cheers

**Comment by sammchardy** [comment]
Hi @Sylentwolf8 you may want to use websockets instead.

See documentation around kline sockets here https://python-binance.readthedocs.io/en/latest/websockets.html#id3

If you have multiple you want to fetch, then you have the option of multiplexing them into one connection. https://python-binance.readthedocs.io/en/latest/websockets.html#id1
