### ISSUE TITLE
start_kline_futures_socket not working

### ISSUE THREAD

**Issue by renruojos** [sammchardy/python-binance#1040]
The start_kline_futures_socket() function does not work.  No call to the callback function was made.  Other ThreadedWebsocketManager functions work in the same environment, such as start_kline_socket() and start_futures_multiplex_socket(), which means both spot and futures websockets can be connected successfully.  It probably has to do with the way how the streams are formulated for subscription.

**To Reproduce**
```
from binance import ThreadedWebsocketManager, AsyncClient
from binance.enums import FuturesType, ContractType


def main():
    twm = ThreadedWebsocketManager()
    twm.start()

    def handle_socket_message(msg):
        print(msg)

    stream1 = twm.start_kline_futures_socket(callback=handle_socket_message, symbol='BTCUSDT', interval=AsyncClient.KLINE_INTERVAL_1MINUTE)
    print(str(stream1))
    stream2 = twm.start_kline_socket(callback=handle_socket_message, symbol='GALAUSDT', interval='1m')
    print(str(stream2))
    stream3 = twm.start_futures_multiplex_socket(callback=handle_socket_message, streams=['ltcusdt_perpetual@continuousKline_1m','adausdt_perpetual@continuousKline_1m'])
    print(str(stream3))
    twm.join()

if __name__ == "__main__":
   main()
```

**Expected behavior**
Expected to see kline messages printed for BTCUSDT, GALAUSDT, LTCUSDT and ADAUSDT.
Actual result was that no messages for BTCUSDT kline were printed.

**Environment (please complete the following information):**
 - Python version: 3.8.5 (I tried 3.9.x also)
 - Virtual Env: venv
 - OS: Windows 10
 - python-binance version: 1.0.14

**Comment by renruojos** [comment]
@wanth1997
I think I have found out what's wrong.  It's about the passing of the FuturesType and ContractType enums not handled consistently between the start_kline_futures_socket and start_futures_multiplex_socket invocation paths.  Also the default prefix of stream?streams= seems not correct when subscribing only to a raw stream.  The prefix should be ws/.

**Comment by wanth1997** [comment]
Nice catch but I still can't fix it
My not-calling-callback error happend when I call start_all_mark_price_socket
I print out my ws_url and it's like: wss://fstream.binance.com/ws/!markPrice@arr@1s (Already change prefix to ws/)

**Comment by renruojos** [comment]
@wanth1997 
I have submitted a PR to fix it.  I tested it locally and it worked.

**Comment by wanth1997** [comment]
Finally I found the solution here #1023
