### ISSUE TITLE
Websockets causing error surpression

### ISSUE THREAD

**Issue by kinsey1313** [sammchardy/python-binance#106]
When running the code below, simply connecting a websocket it causes my program to hang rather than show some error output, i.e a dividedbyzero error.
It seems as though the other threads are running and the main thread has stopped due to the error.
Is this expected? Is anyone else having this sort of issue?

```
from binance.client import Client
from binance.websockets import BinanceSocketManager
from twisted.internet import reactor

def process_message_tickers(msg):
    i = 0

def kill_threads():
        bm.stop_socket(conn_key_tickers)
        bm.close()
        reactor.stop()
        exit(0)

client = Client('', '')
bm = BinanceSocketManager(client)

conn_key_tickers = bm.start_ticker_socket(process_message_tickers)
        
bm.start()

print(10/0)
asdfsadfsdaf

kill_threads()
```

**Comment by SkylerX** [comment]
Hi @kinsey1313 , I advise you not to post your keys publicly online! for your issue, check out the documentation on exceptions. Cheers

**Comment by kinsey1313** [comment]
yeah woops long day of trying to fix this. What exception in particular? These would be python errors that are in the main thread. I don't see how an exception could handle this. Sorry if it seems like a silly question.

**Comment by kinsey1313** [comment]
So finally I found that it was a problem with visual studio code. It works fine in other editors and logs errors from the main thread. 
Thanks for having a look though :)

**Comment by sammchardy** [comment]
Hi @kinsey1313 this is expected.

The reactor loop is still running as the `kill_threads()` call hasn't executed.

Yes you should have seen the ZeroDivisionError exception, and still need to close the program with Ctrl+C

**Comment by kinsey1313** [comment]
Thanks! for whatever reason VS code wouldn't show the ZeroDivisionError which was confusing me.
