### ISSUE TITLE
Return orderID and executed quantity quickly

### ISSUE THREAD

**Issue by chhudson** [sammchardy/python-binance#107]
Is the response stored in the variable after I place the buy order?

`BUY_ORDER = client.order_limit_buy(symbol=TICKER, quantity=AMT_TO_BUY, price=BID)`

Such that I can pull the orderID and quantity executed. Just want to make sure I am reading the documentation correctly.

Thanks in advance

**Comment by jcageman** [comment]
Just test it :) do a buy order for a very low price to verify it works and check the reponse.

**Comment by sammchardy** [comment]
@chhudson  it will save the response into the variable `BUY_ORDER`.

A limit buy response won't have the quantity executed as the order won't have executed yet. You will need to get that info either from the user stream websocket, or by querying your trades.

**Comment by ozan-coursera** [comment]
What if it is is IOC or FOK type order? BUY_ORDER still doesn't have the quantity executed?
