### ISSUE TITLE
Is it possible to place batch order for futures in binance?

### ISSUE THREAD

**Issue by Chan0920** [sammchardy/python-binance#1075]
I do know that there is a post with regards to placing multiple orders but that was last year. I wish to check if this was updated and can now place multiple orders in binance? Because I do know that there is a  futures_place_batch_order function but it kept saying that it can only take in one positional argument with the following format below:

```
client.futures_place_batch_order(((client.futures_create_order(symbol=ticker, side=SIDE_BUY,type=ORDER_TYPE_LIMIT, quantity=noOfShares, price =buyPrice,timeInForce=TIME_IN_FORCE_GTC)),

(client.futures_create_order(symbol=ticker, side=SIDE_SELL, type=FUTURE_ORDER_TYPE_STOP_MARKET, stopPrice=stopLoss,workingType="MARK_PRICE",closePosition=True)),

(client.futures_create_order(symbol=ticker, side=SIDE_SELL, type=FUTURE_ORDER_TYPE_TAKE_PROFIT_MARKET, stopPrice=targetTwo,workingType= "MARK_PRICE",closePosition=True)))
)
```

**Comment by AnimusXCASH** [comment]
Hey @Chan0920 , 

did you by any chance figure it out?

thanks for answer 

brg

**Comment by Chan0920** [comment]
Hi,

I did not manage to figure out as I realise I do not require this method in the end.

Best Regards,
Deming
