### ISSUE TITLE
order call don't get the price value

### ISSUE THREAD

**Issue by beleriandcrises** [sammchardy/python-binance#108]
Hello there, so

* what I want to do: retrieve informations about my last order
* I expect to have all the values
* the "price" value is always 0.0000000

Like this, see that 'price': '0.00000000',

```
>>> orders = client.get_all_orders(symbol='BNBETH', limit=1)
>>> print orders
[{u'orderId': 11443693, u'clientOrderId': u'fwhRF2YwSGjNUKql6yNJ7e', u'origQty': u'5.00000000', u'icebergQty': u'0.00000000', u'symbol': u'BNBETH', u'side': u'BUY', u'timeInForce': u'GTC', u'status': u'FILLED', u'stopPrice': u'0.00000000', u'time': 1515761707955, u'isWorking': True, u'type': u'MARKET', u'price': u'0.00000000', u'executedQty': u'5.00000000'}]

```

Is this a bug or I am missing something? Does this happen because it's a market buy?

**Comment by themonio** [comment]
same problem here...

**Comment by SkylerX** [comment]
Hi guys, same here, tried both get all and get by symbol and id. @sammchardy hi, can you have a look into this please? cheers

**Comment by SkylerX** [comment]
in  trades = client.get_my_trades(symbol='BNBBTC') you will get the price, however is quite unpracticle, as you will have to look for your last one based on timestamp or others like qty etc. @sammchardy @themonio @beleriandcrises

**Comment by beleriandcrises** [comment]
@SkylerX , that could make it for me, but if it's a bug it should be fixed.

Thanks for your help!

**Comment by SkylerX** [comment]
Hi @beleriandcrises  try this one:     tickers = client.get_ticker(symbol='BNBBTC')
and print it afterwords. Let me know if this works. Cheers

**Comment by mwoodson** [comment]
I just hit this too. any updates?

**Comment by elbakai** [comment]
use **get_my_trades** instead example:
`client.get_my_trades(symbol = "DOGEUSDT")`

**Comment by mikedmasters** [comment]
TRADE_SYMBOL =  "ETHUSDT"

`client.get_my_trades(symbol=TRADE_SYMBOL, limit=1)`

That will pull up your last trade, that's what I do..

**Comment by GonzaloMurillo** [comment]
So, let me recap where we are right now.

If we try to use the call : client.get_all_orders(symbol)

We are getting a list where every item is a dictionary representing an order.

One example of a call for the symbol: BTCEUR which returns just an order:

{'symbol': 'BTCEUR', 'orderId': 1978618432, 'orderListId': -1, 'clientOrderId': '7lDxUqbROx38nCWGc6lglB', 'price': '0.00000000', 'origQty': '0.00165000', 'executedQty': '0.00165000', 'cummulativeQuoteQty': '33.06100050', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 
'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1656099328577, 'updateTime': 1656099328577, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}

However, as we can see in the example above, the price is 0.00000000. As others have stated, this bug will need to be fixed.

A way to know the price using client.get_all_orders(symbol) would be to divide the cummulativeQuoteQty / executedQty, but is a hassle.

The proposed workaround is to use: client.get_my_trades(symbol=TRADE_SYMBOL)

https://python-binance.readthedocs.io/en/latest/account.html?highlight=create_order#id12

It also returns a list, where every item is a dictionary representing an order, but the price is filled this time.

[{'symbol': 'BTCEUR', 'id': 89792882, 'orderId': 2054355763, 'orderListId': -1, 'price': '23282.07000000', 'qty': '0.00044000', 'quoteQty': '10.24411080', 'commission': '0.00000000', 'commissionAsset': 'BNB', 'time': 1659158413924, 'isBuyer': True, 'isMaker': False, 'isBestMatch': True}]

Can we have any commitment about whether or not this bug not displaying the price for client.get_all_orders(symbol), can be fixed or not?

Thanks

**Comment by Ram-Ram9** [comment]
The issue appears only when its a MARKET order. python-binance lib get_order() fuction does get the price, but, as it is a MARKET order the price its determined by the MARKET, that why to find the price of such order you need to look into the 'fills'. Here's the full order reponse from API binance:
{
  "symbol": "BTCUSDT",
  "orderId": 28,
  "orderListId": -1, //Unless OCO, value will be -1
  "clientOrderId": "6gCrw2kRUAF9CvJDGP16IP",
  "transactTime": 1507725176595,
  **"price": "0.00000000",**
  "origQty": "10.00000000",
  "executedQty": "10.00000000",
  "cummulativeQuoteQty": "10.00000000",
  "status": "FILLED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "strategyId": 1,               // This is only visible if the field was populated on order placement.
  "strategyType": 1000000,        // This is only visible if the field was populated on order placement.
  "workingTime": 1507725176595,
  "selfTradePreventionMode": "NONE",
  **"fills": [
    {
      "price": "4000.00000000",
      "qty": "1.00000000",
      "commission": "4.00000000",
      "commissionAsset": "USDT",
      "tradeId": 56
    }**

what i do to get it, not being the most efficient way is:

```
try:
  price = float(o['fills'][0]['price']) #if the price wants to be retrieved directly from a placed order (having saved it as an object)
except:
  data = self.client.get_my_trades(symbol=self.symbol, limit=1) #when needed to retrieve the price of an unsaved MARKET order 
  price = round(float(data[0]['price']),2)
```

Hope it helps!
