### ISSUE TITLE
Installation error against Python 2.7.6

### ISSUE THREAD

**Issue by caohunan** [sammchardy/python-binance#11]
Python Version: 2.7.6 
OS: Ubuntu 14 LTS
PIP: 1.5.4

The following error is seen when installing via pip install.

Downloading/unpacking cryptography>=1.9 (from pyOpenSSL->python-binance)
  Downloading cryptography-2.1.2.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/home/caof/.virtual_envs/biance_ve/build/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...

It seems like the dependent library cryptography doesn't support python 2.x

**Comment by sammchardy** [comment]
@caohunan can you try upgrading setuptools and see if that resolves the issue.

pip install --upgrade setuptools

**Comment by caohunan** [comment]
@sammchardy 

My bad...It works fine now. I forgot to upgrade setuptools. I used a pretty old version of setuptools.

**Comment by SomeGuyNamedJay** [comment]
On a Mac, you may need to add --user: sudo pip install --user --upgrade setuptools
