### ISSUE TITLE
how many API requests are multiplex sockets using?

### ISSUE THREAD

**Issue by ddeanto** [sammchardy/python-binance#110]
For example, say I want kline_30m streams for 100 symbols:
```
l = ['symbol_1@kline_30m', 'symbol_2@kline_30m',...,'symbol_100@kline_30m']
bm.start_multiplex_socket(l, process_m_message)
```

How do I know how many API requests I am using up? Am I using 100tickers*60updates/minute = 6000 requests per minute? I can't seem to find this information and I don't want to get banned. Thanks!

**Comment by limpkin** [comment]
I can't answer you... but I can tell you bans are nothing to worry about :D.
First ban gets you a minute, then 2....

**Comment by ddeanto** [comment]
cool @limpkin - I suppose I can just try pulling in 100 kline streams and see if I get blocked. I will report back here what happens.

**Comment by limpkin** [comment]
I've only tried around 40 trade streams, no problem... active queries are the problem.

**Comment by sammchardy** [comment]
Hi @ddeanto as far as I know the rate limits are only applicable to REST API calls, setting up streams shouldn't affect that at all.

Binance does control the throughput of the streams from their end, be interested to hear your results with 100 parallel kline streams.

**Comment by ddeanto** [comment]
Thank you for the responses. I will close this issue and follow up with my findings in a few days!

**Comment by ddeanto** [comment]
It's been ~25 hours and still streaming!

**Comment by hatefihadi** [comment]
> For example, say I want kline_30m streams for 100 symbols:
> 
> ```
> l = ['symbol_1@kline_30m', 'symbol_2@kline_30m',...,'symbol_100@kline_30m']
> bm.start_multiplex_socket(l, process_m_message)
> ```
> 
> How do I know how many API requests I am using up? Am I using 100tickers*60updates/minute = 6000 requests per minute? I can't seem to find this information and I don't want to get banned. Thanks!


> For example, say I want kline_30m streams for 100 symbols:
> 
> ```
> l = ['symbol_1@kline_30m', 'symbol_2@kline_30m',...,'symbol_100@kline_30m']
> bm.start_multiplex_socket(l, process_m_message)
> ```
> 
> How do I know how many API requests I am using up? Am I using 100tickers*60updates/minute = 6000 requests per minute? I can't seem to find this information and I don't want to get banned. Thanks!

could you share the complete code how to get Candle stick data of multiple coins by "bm.start_multiplex_socket"
