### ISSUE TITLE
APIError(code=-1104): Not all sent parameters were read; read '0' parameter(s) but was sent '1'.

### ISSUE THREAD

**Issue by Crimees** [sammchardy/python-binance#112]
I'm just trying to get ticker information using get_orderbook_tickers(), but I'm getting the above error. The no args method works fine: get_orderbook_tickers(). Either there is a problem with the kwargs method get_orderbook_ticker(**params), or I am doing something wrong

my_binance = BinanceClient(BINANCE_API_KEY_TEST, API_SECRET)
print("Running Binance tests")
print(my_binance.get_orderbook_ticker(t1="ETHBTC")) # doesn't work
print(my_binance.get_orderbook_tickers())  # this works

**Comment by sammchardy** [comment]
@Crimees the parameter name on `get_orderbook_ticker` is `symbol` and not `t1`

**Comment by Crimees** [comment]
That did it thanks :*
