### ISSUE TITLE
don't take all data for some pairs

### ISSUE THREAD

**Issue by hossain93** [sammchardy/python-binance#1139]
I get Historical Data with `client.get_historical_klines`
but when I use `toDate = str(datetime.datetime.strptime('02/02/2022', '%d/%m/%Y'))` to get data for today I get below data
![image](https://user-images.githubusercontent.com/77359545/152180766-4dd6bf34-af99-47e0-9de2-1e1df4993e12.png)
but it is for date 2020-06-20
how solve this problem

example pairs
MKRUSDT
SNXUSDT
DOTUSDT
DEFIUSDT
YFIUSDT
 BALUSDT
 CRVUSDT
 TRBUSDT
 YFIIUSDT

**Comment by varfigstar** [comment]
It's beacuse you set end date. API check for oldest available data, build dataset with range from [OLDEST_AVAILABLE_DATE] to your [toDate] and return it. 
It's mean, that api build dataset from 2020.06.20 to 2022.02.02

To fix it - set fromDate by toDate
