### ISSUE TITLE
TRAILING_STOP_MARKET

### ISSUE THREAD

**Issue by flydr2** [sammchardy/python-binance#1159]
Seems this one is missing... Or i'm doing something wrong.

 client.futures_create_order(symbol=TRADE_SYMBOL, side=SIDE_BUY, type=TRAILING_STOP_MARKET... etc

**Comment by mhawry** [comment]
The constant is missing from the library but you can still pass it on as a string and it will work:

```
client.futures_create_order(
    symbol=symbol,
    side=side,
    type='TRAILING_STOP_MARKET',
    quantity=quantity,
    activationPrice=activation_price,
    callbackRate=callback_rate
)
```

**Comment by flydr2** [comment]
Ok I will try this... It did not work before but will try again...
Tks

**Comment by flydr2** [comment]
Works perfectly when sent as a string... Thanks
