### ISSUE TITLE
ImportError: cannot import name 'Client'

### ISSUE THREAD

**Issue by queezyy** [sammchardy/python-binance#116]
In my screenshot below you can see i successfully installed python-binance (via pip), but when i run my script, it is not recognizing your module. I am using "from binance.client import Client"
![python-binance error](https://user-images.githubusercontent.com/35435653/34921595-ba87d864-f952-11e7-9d26-44f58649b836.png)

**Comment by iero** [comment]
Missing those lines in _init_.py file

from binance import client
from binance import depthcache
from binance import enums
from binance import exceptions
from binance import websockets

**Comment by queezyy** [comment]
I added those lines to __init__.py in \Lib\site-packages\binance, but still not working.
Also, __init__.py in the code base on this site is blank. Why wouldn't he include those lines in the base code?
Most modules run fine after a pip install, not seeing why an ini file would need updating. It's also not in his instructions.

**Comment by queezyy** [comment]
I am starting to think it is because i had another Python Binance wrapper installed.
https://github.com/cnfuyu/python-binance-api

I am going to work to make sure this module is completely removed and then re-install Sams.

**Comment by sammchardy** [comment]
Hi @queezyy if you can it may help to use a python environment like virtualenv to install packages into. This keeps things separated, you will run into issues like this if you start to install packages globally.

These links may help, it's much simpler in a Linux env
http://timmyreilly.azurewebsites.net/setup-a-virtualenv-for-python-3-on-windows/
http://timmyreilly.azurewebsites.net/python-pip-virtualenv-installation-on-windows/

**Comment by konstantindukakis** [comment]
Hi @queezyy, the problem is that you named your script "binance" and it interferes with the correct package import. Rename it to something different and try to re-run it. Hope this helps.

**Comment by Mak197** [comment]
> In my screenshot below you can see i successfully installed python-binance (via pip), but when i run my script, it is not recognizing your module. I am using "from binance.client import Client"
> ![python-binance error](https://user-images.githubusercontent.com/35435653/34921595-ba87d864-f952-11e7-9d26-44f58649b836.png)

I had the same issue.
A lot of the .py files were empty or largely commented out - I realised I had multiple instance of python installed, so I cleared them, then uninstalled python-binance "pip uninstall python-binance" then re-installed without cached files, making sure to use the last working version which is 0.7.4 "pip --no-cache-dir -v 0.7.4 python-binance" (I think that's how the command is structured)
Hope that helps!

**Comment by boctulus** [comment]
Same problem here !! It suddently fails

**Comment by lyongh** [comment]
update your pip and install python-binanece again,it will done.

**Comment by JIClaveria097** [comment]
from binance import *
api_key = 'you_key'
api_secret = 'you_key'
client = set(api_key,api_secret)

this work for me

**Comment by RBouhl** [comment]
> client = set(api_key,api_secret)
> 
> this work for me

Does it ?

```
    client = set(api_key, api_secret)
TypeError: set expected at most 1 argument, got 2
```

**Comment by kroksys** [comment]
For me the issue was fixed when I renamed local `binance.py` file to something else `.py`
