### ISSUE TITLE
stepSize ADAUSDT

### ISSUE THREAD

**Issue by den2doc** [sammchardy/python-binance#1168]
Good afternoon, I don’t know who to write to, but
symbol_info = client.get_symbol_info('ADAUSDT')

or

info = client.get_exchange_info()

{'filterType': 'LOT_SIZE', 'minQty': '0.10000000', 'maxQty': '900000.00000000', 'stepSize': '0.10000000'}

where should be 'stepSize': '1.00000000'

Otherwise I get an error APIError(code=-1111): Precision is over the maximum defined for this asset.

**Comment by halfelf** [comment]
`where should be 'stepSize': '1.00000000'`

What makes you think that?  And no matter what, it is not a issue of this library.  The information is got by [https://api.binance.com/api/v3/exchangeInfo?symbol=ADAUSDT](https://api.binance.com/api/v3/exchangeInfo?symbol=ADAUSDT), and parsed by this SDK directly.
