### ISSUE TITLE
LIMIT_MAKER orders not supported

### ISSUE THREAD

**Issue by alanimgur** [sammchardy/python-binance#117]
LIMIT_MAKER orders are not supported by the `ValidateLimitOrder` function. They are described on the Binance API docs here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

(I also don't quite understand the purpose of client side checks like that because they easily get out of sync with the server.)

**Comment by 1-NoLimits** [comment]
Same. Found any workaround?
