### ISSUE TITLE
`start_kline_socket` fails quietly if `interval` argument is set wrong

### ISSUE THREAD

**Issue by mikkokotila** [sammchardy/python-binance#1193]
**Describe the bug**
If the `interval` argument is set wrong (e.g. `1s`) then everything seems to run fine, but there is no data coming in.

**To Reproduce**
```
f = open('test.csv', 'a')
  
stream = ThreadedWebsocketManager(api_key=api_key, api_secret=api_secret)

stream.start()

def handle_socket_message(msg):
        f.write('test.csv')

stream.start_kline_socket(callback=handle_socket_message, symbol=symbol, interval='1s')

stream.join()
```

**Expected behavior**
Should throw an exception/error instead of failing silently.

**Environment (please complete the following information):**
 - Python version: **3.8.12**
 - Virtual Env: **conda**
 - OS: **Mac (M1)**
 - python-binance version: **1.0.15**

**Comment by halfelf** [comment]
Websocket is not like http, for it won't tell you what's going wrong.  This is an expected behavior. 

One can check this behavior by connect to `wss://stream.binance.com:9443/ws/btcusdt@kline_1s`.

**Comment by mikkokotila** [comment]
Thanks for clarifying, I anticipated that this was due to the way in which Binance handles it (well in this case doesn't handle it).
