### ISSUE TITLE
Did you opt for the 1000 BNB reward program

### ISSUE THREAD

**Issue by fieldfoxWim** [sammchardy/python-binance#12]
The C++ and Java reward are already granted, so with this repo lying around, would be a pitty not to get some reward for it. Great work

https://support.binance.com/hc/en-us/articles/115001909972

**Comment by sammchardy** [comment]
Hi @fieldfoxWim I did submit this repo, haven't heard anything so far.

Would be a nice bonus, I've been working on this repo since the Binance API was opened up and I'll keep working on it after regardless.

**Comment by fieldfoxWim** [comment]
Congrats on the Binance Reward! 

Nice work
Cheers!

**Comment by sammchardy** [comment]
Thanks @fieldfoxWim
