### ISSUE TITLE
Spot batch orders

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [sammchardy/python-binance#1208]
I'm familiar with futures_place_batch_order() on futures, but is there a way to set batch orders on Spot? Can't find any information on it

**Comment by halfelf** [comment]
No, not yet.

For any function you can't find on python-binance, check if there is an API listed in [binance-doc](https://binance-docs.github.io/apidocs/) first. 

If binance-doc has any interface which is missing here, you could submit a feature request or even better, a pull request.
