### ISSUE TITLE
Stop-loss Order Functionality

### ISSUE THREAD

**Issue by KamuelaFranco** [sammchardy/python-binance#124]
Does your API wrap the endpoints regarding `STOP_LOSS` or `STOP_LOSS_LIMIT` market orders listed here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

Would this be trivial enough to add with a PR?

**Comment by sammchardy** [comment]
Hi @KamuelaFranco, yes the python-binance library supports all the order types if they are supported by the trading pair.

Use the `create_order` function for full flexibility, see documentation here https://python-binance.readthedocs.io/en/latest/account.html#id2

and link to code here https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.create_order

Just pass the type you want as the `type` parameter.
