### ISSUE TITLE
How to get all tickers just for spot ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [sammchardy/python-binance#1249]
Hi, 
how can i get all the tickers for just spot trading ?
Thank you

**Comment by sirfrank** [comment]
from binance import Client

client = Client()

exchange_info = client.get_exchange_info()

spot_markets = []
for market in exchange_info['symbols']:
    if 'SPOT'in market['permissions']:
        spot_markets.append(market['symbol'])
print(spot_markets)


Adeel ***@***.***> ezt írta (időpont: 2022. szept. 19., H,
19:18):

**Comment by Adeel-Intizar** [comment]
Thank you for your help

**Comment by Adeel-Intizar** [comment]
I got this same response earlier but there are some tickers in response which are not available in binance spot trading but are shown in response from this library

**Comment by Adeel-Intizar** [comment]
these are not even in any trading (spot, futures, margin) on binance

**Comment by Adeel-Intizar** [comment]
@sirfrank  is this is a bug or something in this library ?

**Comment by sirfrank** [comment]
My bad ... 

from binance import Client

client = Client()

exchange_info = client.get_exchange_info()

spot_markets = []
for market in exchange_info['symbols']:
    if 'SPOT'in market['permissions'] and market['status'] == 'TRADING':
        spot_markets.append(market['symbol'])


print(spot_markets)
print(len(spot_markets))

**Comment by sirfrank** [comment]
from binance import Client

client = Client()

exchange_info = client.get_exchange_info()

spot_markets = []
for market in exchange_info['symbols']:
    if 'SPOT'in market['permissions'] and market['status'] == 'TRADING':
        spot_markets.append(market['symbol'])


print(spot_markets)
print(len(spot_markets))


## see the added : and market['status'] == 'TRADING'


Adeel ***@***.***> ezt írta (időpont: 2022. szept. 19., H,
19:41):

**Comment by Adeel-Intizar** [comment]
It is working just fine, Thank you for your help, really appreciated @sirfrank

**Comment by sirfrank** [comment]
No problem ! I am playing around with Binance API for a while, i just restarted working with it (hobby level, thou ...).
If you wish to cooperate .. ferenc.bedo74@biggestemailproviderByGoogle_trying_to_avoid_spam_by_this_silly_way.com .
