### ISSUE TITLE
Wesocket Multiplex - Question

### ISSUE THREAD

**Issue by endrewlai** [sammchardy/python-binance#125]
Hello,

Anyone can help? How can we get the **msg** with the prices of two pairs at the same time? 

--
from binance.websockets import BinanceSocketManager
bm = BinanceSocketManager(client)

def process_m_message(msg):
    print(msg) # How can we get the msg with the depth of two pairs (bnbbtc@depth5 & ethbtc@depth5) at the same time? 

conn_key = bm.start_multiplex_socket(['bnbbtc@depth5', 'ethbtc@depth5'], process_m_message)
bm.start()
--

Thanks
Andrew

**Comment by msieg** [comment]
If you only want the current prices you can use a single orderbook socket. Other than that don't know

**Comment by sammchardy** [comment]
Hi @endrewlai what you're doing is correct.

In your `process_m_message` function you will get messages for both 'bnbbtc@depth5' and 'ethbtc@depth5'. To determine the difference the this is a sample from the docs which I think you're using? https://python-binance.readthedocs.io/en/latest/websockets.html#id1

```
def process_m_message(msg):
    print("stream: {} data: {}".format(msg['stream'], msg['data']))
```

Where the `stream` value will tell you if it's come from 'bnbbtc@depth5' or 'ethbtc@depth5'.

The messages will come in independently though, it won't send one message with info for 'bnbbtc@depth5' and 'ethbtc@depth5'. You'll get one for 'bnbbtc@depth5' to process and then one for 'ethbtc@depth5', the other may or may not be in sync, just depends on what Binance feeds you.

Hope that clarifies things.
