### ISSUE TITLE
getting banned too often, does v1/v3 has anything to do with it?

### ISSUE THREAD

**Issue by hamkline** [sammchardy/python-binance#126]
A few days back I started to get response 418, it seems they changed something and now I can barely run 1 process of my algorithm, instead of 5.  
I know this isn't something on your part, but looking for solutions I found this:  
"I was previously using /api/v1/ticker/allPrices which isn't even listed. It may be heavily weighted because of v1? Switched to GET /api/v3/ticker/price and this is working fine."  
Could this be a problem? I tried confirming and get_orderbook_tickers(), which probably has a good weight to it, uses v1.  

I think websocket doesn't really count for being banned, isn't there a way for me to get that information through it? (sorry if it's a stupid question, never really used websocket before)   
What other work around would you suggest? I already checked their documentation and really, this is all I could think of.

**Comment by msieg** [comment]
I also started getting banned a lot and my solution was to run multiple websockets, now I don't get banned.

**Comment by hamkline** [comment]
@msieg Mind telling me which functions I should start trying to use websockets for? Or maybe all of them?  
I really don't know anything about it, gonna study hard tomorrow.

**Comment by msieg** [comment]
It reaallllyyy depends on what you're trying to do. For instance I use the ticker socket to monitor current bid / ask every coin at once, then when I find a coin to trade, I use the depth socket for that specific coin

**Comment by hamkline** [comment]
I see! But then for buy and sell orders you'd just mix rest requests or you'd still use websocket? Think I might have to redo most of my code.

**Comment by msieg** [comment]
Yea I've never had a problem buying / selling / canceling within a websocket. It's just when two non-web-socket requests are called simultaneously that I've had trouble.

**Comment by hamkline** [comment]
I'm already excited to start learning tomorrow. Do you know which is more efficient for trading, websocket or rest?

**Comment by msieg** [comment]
No idea, good luck though

**Comment by hamkline** [comment]
Thanks for letting me know :]

**Comment by sammchardy** [comment]
Yes I think the old v1 endpoints may be the cause of it, I'll look to remove them as there should be alternatives in the new documentation

**Comment by chhudson** [comment]
![image](https://user-images.githubusercontent.com/11526817/35189553-33b278c0-fe12-11e7-9be9-3d588fbce7d6.png)

This might have something to do with it. It is definitely affecting me.

**Comment by CyberMew** [comment]
This wrapper doesn't seem to support v3 endpoints for getting all symbols (e.g. v3/ticker/bookTicker and v3/ticker/price for all symbols), any plans to add that in the future @sammchardy ?

**Comment by sammchardy** [comment]
@CyberMew it does support these functions

`get_orderbook_ticker` is v3/ticker/bookTicker

`get_symbol_ticker` is v3/ticker/price

**Comment by sammchardy** [comment]
Closing this issue.
