### ISSUE TITLE
How to use websocket function in flask

### ISSUE THREAD

**Issue by microwood** [sammchardy/python-binance#1274]
How to use websocket function in flask？

@bp.route("/")
@login_required
def index():
        def handle_socket_message(msg):
            print(f"message type: {msg['e']}")
            print(msg)
        symbol = 'BNBBTC'
        twm = ThreadedWebsocketManager(api_key=API_KEY, api_secret=API_SECRET)
        twm.start()
        twm.start_kline_socket(callback=handle_socket_message, symbol=symbol)
        twm.join()
        return render_template("dashboard/index.html")

the error is：RuntimeError: There is no current event loop in thread 'Thread-2'.

**Comment by sirfrank** [comment]
When i built a flask app , i took the websocket out from flask, made a system process which handled websocket and saved result to txt, and flask was reading the txt files.
