### ISSUE TITLE
Avoiding API ban

### ISSUE THREAD

**Issue by msieg** [sammchardy/python-binance#128]
Has someone come up with a way to avoid or at least limit the the API ban? Would perhaps upgrading to level2 or level3 on binance prevent API bans? I have a very low order fill rate because of constantly canceling orders, and I used to get banned for 5 minutes at a time but now it's 24 hours. Thanks.

**Comment by Chingis-Khan** [comment]
any more info on  this API ban?  How many cancels are you doing

**Comment by david0429** [comment]
I'm having the same issue.  Apparently you should be allowed 1200 requests/minute, but I'm getting banned after ~10 requests.

**Comment by Chingis-Khan** [comment]
maybe having another client open is multiplying the number, like having a web page on a market open so they are being counted too?

**Comment by dxsh** [comment]
From their [REST API docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)

>Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (http status 418).
>IP bans are tracked and scale in duration for repeat offenders, from 2 minutes to 3 days.

**Comment by david0429** [comment]
Switching market data watching to websockets seems to have drastically helped.  Try using the REST calls just for orders.

**Comment by jcageman** [comment]
Yes, just use websockets for data watching (faster anyways) and only use rest for orders. Not getting any api bans after switching to sockets.

**Comment by sammchardy** [comment]
Closing this issue.
