### ISSUE TITLE
Looks like Withdrawals via API are now available - perhaps a new feature?

### ISSUE THREAD

**Issue by CharlieVerwer** [sammchardy/python-binance#13]
Hey there, let me start by saying that I absolutely love this project of yours!

Looks like Binance is exposing this for withdrawals: 
/wapi/v1/withdraw.html

Perhaps that feature could be added now? :D

**Comment by sammchardy** [comment]
@CharlieVerwer v0.3.0 now supports the withdraw endpoints. Check it out.
