### ISSUE TITLE
Closing and re-opening web sockets

### ISSUE THREAD

**Issue by msieg** [sammchardy/python-binance#130]
I would like to understand whether there is a method for closing and re-opening websockets within one script. My script is set up to first run the ticker socket to monitor the current maximum bid and minimum ask for every symbol simultaneously, and once it identifies a symbol / coin to pursue, I move on to a depth socket for that specific symbol. Right now, I am blocking the original ticker socket with an if statement once I move on, without actually closing it. How can I close the ticker socket and re-open it once I'm done with the depth socket? Thanks.

**Comment by sammchardy** [comment]
Hi @msieg check the websocket docs https://python-binance.readthedocs.io/en/latest/websockets.html#id10

When you open a socket, you will get back a connection key string, to close the socket just call `stop_socket` with that connection key.
