### ISSUE TITLE
No Futures - Taker buyer seller volume ?

### ISSUE THREAD

**Issue by ck0099** [sammchardy/python-binance#1325]
It seems I cannot find any way to retrieve Taker buyer/seller volume for Futures?

**Comment by plinki** [comment]
Hi. I believe you're looking for `get_aggregate_trades(symbol, fromId, startTime, endTime, limit)`
From there look `trade['m']` to check whether it's a sell order or not, and `trade['q']` for the quantity

**Comment by Paw2Pom** [comment]
hi @plinki , I am referring to the specific exchange data offered by Binance:

B.S Vol. - Buyer Seller Volume
Taker Buy Volume: the total volume of buy orders filled by takers within the period. Taker Sell Volume: the total volume of sell orders filled by takers within the period.

It is similar to:
Long/Short Account Ratio
Long/Short Position Ratio
Long/Short Ratio
