### ISSUE TITLE
Order status

### ISSUE THREAD

**Issue by Chingis-Khan** [sammchardy/python-binance#133]
Hi, 

Does order status Filled always get set for orders  that are partially filled. By that I mean if I check back and receive PARTIALLY_FILLED and then check latter will I eventually get FILLED (assuming it does actually fill at the exchange)

**Comment by beleriandcrises** [comment]
If it's filled you should receive status:FILLED. if it's partially filled you'll receive a status:PARTIALLY_FILLED. Maybe I don't understand the question though. What are you trying to do that doesn't work as expected?

**Comment by Chingis-Khan** [comment]
I think it is ok, I was worried that some orders might never actually fill, and be forever stuck at partially filled, but I haven't ever seen it happen like that
