### ISSUE TITLE
Doesn't work funding_wallet and get_user_asset methods

### ISSUE THREAD

**Issue by mixartemev** [sammchardy/python-binance#1339]
**Describe the bug**
Doesn't work funding_wallet and get_user_asset methods

**To Reproduce**
Code snippet to reproduce the behavior:
```python
bc = Client(KEY, SECRET)
fund_assets = bc.funding_wallet()
bc = AsyncClient(KEY, SECRET)
assets = await bc.get_user_asset()
fund_assets = await bc.funding_wallet()
```

**Expected behavior**
get the data

**Environment (please complete the following information):**
 - Python version: 3.11
 - Virtual Env: virtualenv
 - OS: Ubuntu
 - python-binance version: 1.0.17

**Logs or Additional context**
```
 File "/home/dev/af_core/venv/lib/python3.11/site-packages/binance/client.py", line 8717, in get_user_asset
    return await self._request_margin_api("get", "asset/getUserAsset", True, data=params, version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/af_core/venv/lib/python3.11/site-packages/binance/client.py", line 7613, in _request_margin_api
    return await self._request(method, uri, signed, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/af_core/venv/lib/python3.11/site-packages/binance/client.py", line 7566, in _request
    return await self._handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/af_core/venv/lib/python3.11/site-packages/binance/client.py", line 7574, in _handle_response
    raise BinanceAPIException(response, response.status, await response.text())
binance.exceptions.BinanceAPIException: APIError(code=-1000): Request method 'GET' not supported
```

**Comment by PJV0043** [comment]
Thank you for the comprehensive bug report. The error message you provided states: APIError(code=-1000): Request method 'GET' not supported. This suggests that the method associated with the API endpoint you're trying to access is no longer accepting GET requests, or perhaps never did.

**Comment by mixartemev** [comment]
> Thank you for the comprehensive bug report. The error message you provided states: APIError(code=-1000): Request method 'GET' not supported. This suggests that the method associated with the API endpoint you're trying to access is no longer accepting GET requests, or perhaps never did.

Yes, I know, I already fixed it, but I forgot to close the issue:)
