### ISSUE TITLE
v1/balance is retired, please use GET /fapi/v2/balance

### ISSUE THREAD

**Issue by ProKirill999** [sammchardy/python-binance#1349]
**Describe the bug**
Hello, while getting futures account balance, get this error: APIError(code=-5000): GET /fapi/v1/balance is retired, please use GET /fapi/v2/balance

**Comment by dennislwy** [comment]
i also start facing the same error since a day ago

**Comment by zweix123** [comment]
This [PR](https://github.com/sammchardy/python-binance/pull/1342) is solving this problem.

**Comment by alexrmacleod** [comment]
got the same error
