### ISSUE TITLE
can't get the asset balance of a coin

### ISSUE THREAD

**Issue by DaniZz** [sammchardy/python-binance#135]
when I use:

`client.get_asset_balance(asset='BTC')['free']
`
I get:

```
Traceback (most recent call last):
  File "<pyshell#116>", line 1, in <module>
    client.get_asset_balance(asset='BTC')['free']
AttributeError: 'Client' object has no attribute 'get_asset_balance'

```

am I getting something wrong here (e.g. do I have to import something other than the client module?)

**Comment by coire1** [comment]
Check the package version and update it to latest. You're probably using an older version. 😃

**Comment by DaniZz** [comment]
@coire1   you are probably right :/
my problem is that I installed anaconda via Bash shell on the mac, and everytime I update python-binance it only updates the version for anaconda and not the one running on IDLE.

so the new functions don't work when I launch any script with IDLE, any idea on how to solve this problem against which I'm always crashing my head?

**Comment by coire1** [comment]
I don't really know too much about Anaconda and IDLE. If I understand you should run IDLE from the anaconda environment to use the packages that you install in anaconda (like python-binance).

**Comment by DaniZz** [comment]
thanks Lucio.
well this is not really python-binance problem but my problem  :P 
I'll try to fix it myself!
