### ISSUE TITLE
Post Calculations on WebSocket data

### ISSUE THREAD

**Issue by chhudson** [sammchardy/python-binance#136]
I am trying to store the stream data from `conn_key = bm.start_ticker_socket(process_message)` into a variable so I can do some quick calculations to determine spreads.

```
def initiate():
    # Connect to client
    client = Client(credentials.API_KEY, credentials.API_SECRET)

    # Print incoming data
    def process_message(msg):
        print(msg)


    # Setup Socket
    bm = BinanceSocketManager(client)

    # then start the socket manager
    conn_key = bm.start_ticker_socket(process_message)

    # start the socket
    bm.start()

print(initiate())
```

So, I guess instead of `print(msg)` I am trying to store the msg into a variable for later calculations.

I've tried `return msg` and some other things but keep getting empty lists/dataframes.

Thanks for any help! :)

**Comment by SkylerX** [comment]
@chhudson have you tried to put the bm = Binance................ above the defenition of the process_msg?

**Comment by sammchardy** [comment]
Hi @chhudson you'll have to define your own structure to do it as I don't know exactly what you want to do. The following code appends messages to an array for a count of 10. Maybe this gives you some ideas. You need to use the `global` keyword here to access the global variables.

```
res_array = []
count = 0
bm = None


# Save incoming data
def process_message(msg):
    global count, res_array, bm
    print("count:{}".format(count))
    # append message to array
    res_array.append(msg)
    count += 1
    if count == 10:
        print(len(res_array))
        # ...save to a file


def initiate():
    global bm
    # Connect to client
    client = Client("", "")

    # Setup Socket
    bm = BinanceSocketManager(client)

    # then start the socket manager
    conn_key = bm.start_ticker_socket(process_message)

    # start the socket
    bm.start()


initiate()
```

**Comment by chhudson** [comment]
@sammchardy Thanks for the replies. 

The end goal is to be able to lookup tokens that have spreads > 0.01 (1%) and place (hopefully) extremely quick orders that yield about 0.5% profit after a trade. 

I have already completed the REST version of this but it just takes about 2-3 seconds to execute completely. So maybe I could get some time savings by utilizing the WebSocket.

**Comment by coire1** [comment]
Hi @chhudson, I suggest you to place the order with REST api and check for order updates through the User Stream Websocket. You will get an update for every executionReport of an order. 
These responses are faster than polling the order status. If you need really faster updates consider to use a VPS near server the location (Tokio), it will drastically increase speed.

**Comment by chhudson** [comment]
@coire1 Awesome thanks for the suggestion.

The reason why I want to use the socket `start_ticker_socket` is so I can avoid the REST API limits. Do you have any suggestions about how to parse this? Do I need to simply just store the `msg` into an array frist?

Modified version of @sammchardy script above:
```
res_array = []
bm = None


# Save incoming data
def process_message(msg):
    global count, res_array, bm
    
    # append message to array
    res_array.append(msg)
    return res_array


def initiate():
    global bm
    # Connect to client
    client = Client("", "")

    # Setup Socket
    bm = BinanceSocketManager(client)

    # then start the socket manager
    conn_key = bm.start_ticker_socket(process_message)

    # start the socket
    bm.start()


initiate()
```

Afterwards I could put `res_array` into a dataframe (i think) and do my post processing there.

**Comment by coire1** [comment]
Hi @chhudson, consider that `process_message` will be executed on every socket message, so your `res_array` will grow during time. So I suggest you to use the `res_array` as a stack of fixed size and apply your post calculations to this stack on every new message (that will generate a new different stack).

    def process_message(msg):
      global count, res_array, bm 
      # Insert at first position
      res_array.insert(0, msg)
      if (len(res_array) > FIXED_SIZE):
        # Remove last message when res_array size is > of FIXED_SIZE
        del res_array[-1]
      make_post_calculations(res_array)

**Comment by Technorocker** [comment]
So I'm still learning websockets and I got the stream working. I'm trying to capture the 'p' price out of the res_array. but it keeps printing out the whole stream. Is there a better way to call the price out as I need it?

**Comment by veenodp** [comment]
Hello @all @sammchardy 
ticektname = 'TRXBTX' 
def process_message(msg):
    global count, res_array, bm
    
    # append message to array
    res_array.append(msg)
    return res_array

in above function i need to retrieve the specific ticker price.
i tried this print('res_array['ticker]['a']') but failed so.. any idea how to i get current price of the coin in above metod
