### ISSUE TITLE
dateparser is unmaintained

### ISSUE THREAD

**Issue by gholam-deblan** [sammchardy/python-binance#1370]
_dateparser_ library has been unmaintained for a while and depends on _hijri-converter_ 2.3.1. This package has been deprecated and will not receive future updates. Please use the [hijridate](https://pypi.org/project/hijridate/) package instead.
Consider switching to other libraries.

**Comment by luk0y** [comment]
`dateparser` is mantained. You can verify it here `https://github.com/scrapinghub/dateparser`

Dateparser supports Python >= 3.7. You can install it by doing:

`$ pip install dateparser`

If you want to use the jalali or hijri calendar, you need to install the calendars extra:

`$ pip install dateparser[calendars]`

Source : https://github.com/scrapinghub/dateparser#installation
