### ISSUE TITLE
Anaconda \\ 'str' object has no attribute 'get_klines'`

### ISSUE THREAD

**Issue by archuff** [sammchardy/python-binance#138]
Hey;

i would lie to use your package to get the historical price of different currencies.

I use Anaconda. I have installed the package with
`pip install git+git:.//url_of_the_package`
Then, running spyder the following command returns an error message:
`klines = Client.get_historical_klines("ETHBTC", Client.KLINE_INTERVAL_30MINUTE, "December 01, 2017", "January 01, 2018")
`

`File "/home/user1/anaconda3/lib/python3.6/site-packages/binance/client.py", line 652, in get_historical_klines
    temp_data = self.get_klines(

AttributeError: 'str' object has no attribute 'get_klines'`

Did I miss something? Thanks a lot for your help.

Best

**Comment by DaniZz** [comment]
ha.
I  have the same problem with client.get_asset_balance. (I get the same error)

I guess you have to update the package (run pip install update).
However, if you have Anaconda installed on a mac OS you might run into my same problem, that is, two different versions of python and you can only update one of them...

keep me posted.

**Comment by spierre91** [comment]
Hi, I am having this issue with client.get_aggregate_trades, where I get the error "'str' object has no attribute 'get_aggregate_trades'" . I am also using Spyder in Anaconda. Does 'pip install update' resolve the issue?
