### ISSUE TITLE
No module error

### ISSUE THREAD

**Issue by monomikike** [sammchardy/python-binance#140]
Hi, 

I'm trying so hard to use it, but can't make the first step... :( 
I have Python 3.6, put "pip install python-binance" into the command, and at the end it's red, and said: ...failed with error code 1

Tried with using Administrator mode, tried to update setuptools, tried with pip3, but nothing helps. 

Couls someone help me please? 

Thanks, 
Miklos

**Comment by michja** [comment]
Try pip2 (pip for python 2.7)

**Comment by monomikike** [comment]
pip2 not recognized. Tried with pip3, same result...:(

**Comment by monomikike** [comment]
![binance](https://user-images.githubusercontent.com/33835304/35330920-aa8d7558-0105-11e8-9996-24ee7d6224f2.jpg)

**Comment by SkylerX** [comment]
@monomikike I'm using windows, and given up on windows, always gives some issue one way or another, the solution workaround for windows is to download vmware and install any linux distro, ubuntu or kali are the one that works the best in my opinion on vmware. Then you can install pycharm on it and just work normally on it and close the vmware workstation once you are finish. Alternatively to create a partition on your harddisk and install linux there and make a dual boot perhaps, or you could do it on an external hard drive! Hope this helps. Good luck

**Comment by michja** [comment]
You might need to install pip2 then try using it to get the packages. I have a similar error on ubuntu using pip3. It all works fine sticking to 2.7

**Comment by monomikike** [comment]
Sorry for the silly question but how can I install pip2?

**Comment by michja** [comment]
https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation
this might help. 
I don't use windows sorry

**Comment by monomikike** [comment]
Solved! 
Downloaded the visual C++ from the error log, and worked! 
Thanks for the help!
