### ISSUE TITLE
GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk

### ISSUE THREAD

**Issue by AnimusXCASH** [sammchardy/python-binance#1400]
How can i change to use v2 not v1 when calling 

futures_position_information() ?

it loads by default V1.

  FUTURES_API_VERSION = 'v1'
  FUTURES_API_VERSION2 = "v2"

Thank you for your help

**Comment by tsunamilx** [comment]
It should be using the version 2 already, are you using the latest version which is 1.0.19?

See [    async def futures_position_information(self, **params):
        return await self._request_futures_api('get', 'positionRisk', True, version=2, data=params)](https://github.com/sammchardy/python-binance/blob/e974c34cb1e48d2c98da4c71c5c14dc2e8ff56e6/binance/client.py#L9307C1-L9308C100)

**Comment by carlosmiei** [comment]
Hello @AnimusXCASH, it's using v2 already: https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L7472

Please make sure your python-binance version is updated!
