### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by Zhongkai939** [sammchardy/python-binance#1407]
Dear,

I cann't use testnet to Binance, it always say  (APIError(code=-2008): Invalid Api-Key ID).

Meanwhile, I found the future testnet url had changed to https://testnet.binancefuture.com, the old one now is just for spot, there might be some potential problems.

Therefore, I tried to use testnet for spot. However, while running the following code (client = Client(api_key, api_secret, testnet=True), ps: the api of mine had been updated to the one get from testnet spot ), it still report a wrong code: BinanceAPIException: APIError(code=-2008): Invalid Api-Key ID.

What should I do to use the testnet? specially on future testnet?

**Comment by carlosmiei** [comment]
Hello @Zhongkai939, as long as you call a futures method like `futures_create_order`, etc the correct testnet url will be used.

I will close this issue now but feel free to reopen it if anything!
