### ISSUE TITLE
User Socket always does not work

### ISSUE THREAD

**Issue by yusail** [sammchardy/python-binance#141]
I want to receive Order Update Event through User Socket, however its msg from callback function is empty. How can I fix this? THX

**Comment by perozu** [comment]
Same problem here... need to find good and simple example. 
Anyone?

**Comment by lixiaosi33** [comment]
Same problem.

**Comment by seanrz** [comment]
So you're callback is getting called, but with an empty msg? My callback is not getting called at all. And I'm using the code straight from the examples.
