### ISSUE TITLE
Failed when try to place an order

### ISSUE THREAD

**Issue by Zhongkai939** [sammchardy/python-binance#1411]
when I try to place an order, it returns 
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: PERCENT_PRICE_BY_SIDE

by using the code like :
from binance.enums import *

order = client.create_order(
    symbol='BNBBTC',
    side=SIDE_BUY,
    type=ORDER_TYPE_LIMIT,
    timeInForce=TIME_IN_FORCE_GTC,
    quantity=100,
    price='0.00001')

could you help me with that? thx

**Comment by carlosmiei** [comment]
Hello @Zhongkai939,

That error means you're using a price that is outside of the range for prices the exchange allows. (it's too far from the current price)
