### ISSUE TITLE
getting Slippage even with small market orders

### ISSUE THREAD

**Issue by DaniZz** [sammchardy/python-binance#142]
I'm getting an average slippage of 0.22% per trade (including both buy and sell) even with small market orders.

do you know if this is due to the Binance system (e.g. intrinstic delay to the system, spread, other reasons..) or to some delay that I have in submitting my order? I tried to simplify my code as much as possible so that there's no delay between the moment at which the decision to buy/sell is made and the order is sent off. 

do you know of any simple ways to check this out? 
did you experience a similar problem?

**Comment by Aaahh** [comment]
https://github.com/sammchardy/python-binance/issues/91

**Comment by Aaahh** [comment]
on another note don't forget fees
