### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [sammchardy/python-binance#1421]
### Description:

In the "python-binance/binance/client.py", I have identified a security vulnerability about insecure cryptographic algorithm. PKCS1v1.5  is vulnerable to the chosen-ciphertext attack.

### Location:

https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L255

```python
signature = pkcs1_15.new(self.PRIVATE_KEY).sign(h)
```

### Reference

- **CWE-780: Use of RSA Algorithm without OAEP**

### Recommendations:

Use other padding(OAEP) instead of PKCS1v1.5.

**Comment by carlosmiei** [comment]
@lialon Out-of-scope
