### ISSUE TITLE
python 3.7,python-binance latest, simple example report this error in china

### ISSUE THREAD

**Issue by mingmingshiliyu** [sammchardy/python-binance#1430]
(<class 'requests.exceptions.ProxyError'>, ProxyError(MaxRetryError("HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))")), <traceback object at 0x000001FC7BA6A188>)

![image](https://github.com/user-attachments/assets/be1d1c4b-ffc0-47ab-bf6c-76055b4519af)
![image](https://github.com/user-attachments/assets/dd2c675c-9363-48ef-a449-cd5fb819ce55)

**Comment by carlosmiei** [comment]
Hello @mingmingshiliyu, you should provide proxies like this:

```Python
proxies = {"http": proxy_url, 'https': proxy_url }
client = Client("api_key", "api_secret", {'proxies': proxies})
```

If that does not work, most likely, it's an issue with the proxies.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
