### ISSUE TITLE
Multiple User Websockets - No Unique Account Identifier in Output

### ISSUE THREAD

**Issue by uneasyguy** [sammchardy/python-binance#144]
So when I open multiple user websockets, it'll listen and output messages from the various accounts but I don't see a way to output the listen key or some other unique identifier for each account. Could anyone point me in the correct direction on this one?

And thanks for all of your hard work, really appreciated @sammchardy

**Comment by SkylerX** [comment]
Hi @uneasyguy , have you tried to use    bm.ident    ?

**Comment by uneasyguy** [comment]
Hi Skyler, I have not will look into it now. If you have example uses that you could share, I would be grateful for those as well.

Thanks for the reply!

**Comment by SkylerX** [comment]
Hi @uneasyguy 

` bm = BinanceSocketManager(client) # you should have created the client previously linked with your api key

def process_message(msg):
    print(msg)
    print(bm.ident)

conn_key = bm.start_trade_socket('GTOBTC', process_message)
bm.start()

`

It will print out the number of your socket manager for that client.
Hope this helps

**Comment by uneasyguy** [comment]
Well I did manage to get that info to print out but:

VEN BTC {'e': 'executionReport', 'E': 1516829359551, 's': 'VENBTC', 'c': 'tUenLb9RO1m9E31AqL3UZo', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '5.00000000', 'p': '0.00168805', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': 'null', 'x': 'NEW', 'X': 'NEW', 'r': 'NONE', 'i': 8480388, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1516829359552, 't': -1, 'I': 19824069, 'w': True, 'm': False, 'M': False, 'O': -1, 'Z': '-0.00000001'}
140497708381952
TNT BTC {'e': 'executionReport', 'E': 1516829531080, 's': 'TNTBTC', 'c': 'AU9MdD00I8U0joaqAcKQ4k', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '2506.00000000', 'p': '0.00001000', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': 'null', 'x': 'NEW', 'X': 'NEW', 'r': 'NONE', 'i': 3843464, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1516829531079, 't': -1, 'I': 8452036, 'w': True, 'm': False, 'M': False, 'O': -1, 'Z': '-0.00000001'}
140497708381952

But those two orders were placed on two separate accounts and the same number printed out

**Comment by uneasyguy** [comment]
from binance.client import Client
from binance.websockets import BinanceSocketManager
import binancesecrets as b


def process_message(msg)
	if msg['e'] in ['executionReport']:
		trading_pair = str(msg['s'])
		if trading_pair[-3:] in ['BTC','ETH','BNB']:
			individual_currencies = trading_pair.split(trading_pair[-3])
			quote_currency = individual_currencies[0]
			base_currency = trading_pair[-3:]
		else:
			individual_currencies = trading_pair.split(trading_pair[-4])
			quote_currency = individual_currencies[0]
			base_currency = trading_pair[-4:]
		print (str(quote_currency),str(base_currency),str(msg))
		print (bm.ident)

i=0
for user in range(0,len(b.users)):
	user_id = b.users[i]['user_id']
	username = b.users[i]['username']
	name_f = b.users[i]['name_f']
	name_l = b.users[i]['name_l']
	
	api_key = b.users[i]['key']
	api_secret = b.users[i]['secret']
	client = Client(api_key, api_secret)
	bm = BinanceSocketManager(client)
	conn_key = bm.start_user_socket(process_message,user_id,username,name_f,name_l)
	bm.start()
	i+=1

**Comment by uneasyguy** [comment]
`from binance.client import Client
from binance.websockets import BinanceSocketManager
import binancesecrets as b


def process_message(msg)
	if msg['e'] in ['executionReport']:
		trading_pair = str(msg['s'])
		if trading_pair[-3:] in ['BTC','ETH','BNB']:
			individual_currencies = trading_pair.split(trading_pair[-3])
			quote_currency = individual_currencies[0]
			base_currency = trading_pair[-3:]
		else:
			individual_currencies = trading_pair.split(trading_pair[-4])
			quote_currency = individual_currencies[0]
			base_currency = trading_pair[-4:]
		print (str(quote_currency),str(base_currency),str(msg))
		print (bm.ident)

i=0
for user in range(0,len(b.users)):
	user_id = b.users[i]['user_id']
	username = b.users[i]['username']
	name_f = b.users[i]['name_f']
	name_l = b.users[i]['name_l']
	
	api_key = b.users[i]['key']
	api_secret = b.users[i]['secret']
	client = Client(api_key, api_secret)
	bm = BinanceSocketManager(client)
	conn_key = bm.start_user_socket(process_message,user_id,username,name_f,name_l)
	bm.start()
	i+=1
`

**Comment by uneasyguy** [comment]
![image](https://user-images.githubusercontent.com/29230265/35358627-40b1c2b8-0125-11e8-8353-633fa7397026.png)

**Comment by SkylerX** [comment]
Hi @uneasyguy  i see.
Not sure but I recon that the identity from bm.ident actually gives you the main binance socket manager id ( basically bm id) have you tired with bm.name to see if it show as a different thread or just a single thread?

**Comment by uneasyguy** [comment]
VEN BTC {'e': 'executionReport', 'E': 1516831474684, 's': 'VENBTC', 'c': 'tYhfnRmkunTXAR8I5bitBK', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '5.00000000', 'p': '0.00166688', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': 'XwP3mtUeMkusdoC15eru2f', 'x': 'CANCELED', 'X': 'CANCELED', 'r': 'NONE', 'i': 8494446, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1516831474685, 't': -1, 'I': 19863335, 'w': False, 'm': False, 'M': False, 'O': -1, 'Z': '-0.00000001'}
bm ident: 140615253460736 bm name: Thread-3
TNT BTC {'e': 'executionReport', 'E': 1516831483351, 's': 'TNTBTC', 'c': 'Szw5Sj7EAHLfEppNxWXJ7t', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '835.00000000', 'p': '0.00001500', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': 'TEsVUgG2iqxK8g7teKsGqh', 'x': 'CANCELED', 'X': 'CANCELED', 'r': 'NONE', 'i': 3847090, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1516831483352, 't': -1, 'I': 8460671, 'w': False, 'm': False, 'M': False, 'O': -1, 'Z': '-0.00000001'}
bm ident: 140615253460736 bm name: Thread-3
![image](https://user-images.githubusercontent.com/29230265/35359626-d5b71572-0128-11e8-9ae9-5c7546b45e51.png)

**Comment by sammchardy** [comment]
Hi @uneasyguy currently the messages don't come back with any identifier, I may look at adding an optional string you can pass through so you can identify it.

For now you could create a class that handles unknown functions and then make up a separate function for each user socket you create. The example below is for a trade, ticker and kline socket, but you can easily modify it for your user example.

```
class MessageHandler(object):
    """Generic class to handle any messages that come through
    
    """
    def __getattr__(self, name):
        """Method to handle unknonwn method calls.
        
        :param name: name of function called
        :return: 
        """
        def method(*args):
            print("tried to handle method " + name)
            if args:
                print("it had arguments: " + str(args))
        return method


mh = MessageHandler()
trade_func = getattr(mh, 'trade_socket')
ticker_func = getattr(mh, 'ticker_socket')
kline_func = getattr(mh, 'kline_socket')

bm = BinanceSocketManager(client)
trade_key = bm.start_trade_socket('BNBBTC', trade_func)
ticker_key = bm.start_symbol_ticker_socket('BNBBTC', ticker_func)
kline_key = bm.start_kline_socket('BNBBTC', kline_func, '1m')

bm.start()
```

**Comment by uneasyguy** [comment]
Thank you Sam, I'll see what i can do and appreciate your help.

**Comment by uneasyguy** [comment]
Have to run to a meeting but ended up with this for a single user account:
![image](https://user-images.githubusercontent.com/29230265/35361703-5e6576be-0130-11e8-817c-d2b5d53237d9.png)

with code that looks like this:
![image](https://user-images.githubusercontent.com/29230265/35361855-e1452520-0130-11e8-9fc0-4fdffd6df130.png)

If you have anyone has thoughts/improvements/etc, i'll be back later on to check them out. Thank you again @sammchardy  & @SkylerX

**Comment by sammchardy** [comment]
Closing this issue now.
