### ISSUE TITLE
[Help] How to specify socket type when using BinanceSocketManager?

### ISSUE THREAD

**Issue by yitian-reevo** [sammchardy/python-binance#1455]
**Describe the bug**
Hi folks, I found that the default `socket_type` in [_get_socker()](https://github.com/sammchardy/python-binance/blob/26a0792aca612368b9fb8c2828357e8bb7546332/binance/streams.py#L344) is BinanceSocketType.SPOT, but there is no way in higher to specify this param. Looks like If I want to subscribe all Futures market tickers stream and it goes by default SPOT ws urls? Is it expected?

**To Reproduce**
N/A

**Expected behavior**
Perhaps a method to specify socket type when init  BinanceSocketManager

**Environment (please complete the following information):**
 - Python version: 3.7
 - Virtual Env: conda
 - OS: Ubuntu
 - python-binance version: 1.0.19

**Logs or Additional context**
N/A

**Comment by carlosmiei** [comment]
Hello @yitian-reevo,

Can you please post the code you're running?

**Comment by yitian-reevo** [comment]
@carlosmiei thanks for the response and here is the code:
```
import asyncio
import time

from binance import AsyncClient, BinanceSocketManager
from redis import StrictRedis
from binance.client import BaseClient

redis = StrictRedis(connection_pool=ConnectionPool(...))

def process_message(msg):
    for each in msg:
        key = 'binance_f:ticker:' + each['s']
        redis.set(key, str(each))

async def main():
    client = await AsyncClient.create()
    bm = BinanceSocketManager(client)
    ts = bm.ticker_socket()
    async with ts as tscm:
        while True:
            try:
                res = await tscm.recv()

                process_message(res)
            except Exception as e:
                print(f"An error occurred: {e}")
                break

    await client.close_connection()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

It's quite simple, I want to subscribe all **Futures** market tickers via streams and store them in a Redis. 

But when I dig a bit deeper in the code and found this:
* if I init both the `AsyncClient` and `BinanceSocketManager` **with default params**, then calls` ticker_socket()`, it calls `_get_socket() `in lower level also with default params. and the default value for `socket_type` param of `_get_socket` is `inanceSocketType.SPOT.`
* Does this mean I am subscribing to the SPOT stream, and if yes, how shoud I change to subscribe Furutes streams. Looks like there is no params can be used when init Client or SocketManager.

Correct me if I was wrong, I have't used this pkg for a couple of years, maybe I misunderstood something.  Great work, btw.

**Comment by carlosmiei** [comment]
@yitian-reevo You're right we're missing that stream. 

I will be adding `futures_ticker_socket` and `futures_coin_ticker_socket` in the linked PR.

If you need a solution right now (or if you don't want to wait for the next release) you can add this workaround to your code:

```Python
class BinanceSocketManagerExtended(BinanceSocketManager):
    def futures_ticker_socket(self):
        return self._get_socket('!ticker@arr', self.FSTREAM_URL, 'stream?streams=', False, Literal['USD_M_Futures'])


async def main():
    client = await AsyncClient.create()
    bm = BinanceSocketManagerExtended(client)
    ts = bm.futures_ticker_socket()
    async with ts as tscm:
        while True:
            try:
                res = await tscm.recv()
                process_message(res)
            except Exception as e:
                print(f"An error occurred: {e}")
                break

    await client.close_connection()
```

Please let us know if that works for you.

**Comment by yitian-reevo** [comment]
@carlosmiei it should work for sure, thanks! 

--
Regarding the PR. If I may, I'd like to respectfully suggest considering a more generic approach in the long run.  Given that similar challenges could arise across almost all interface methods. This is just a suggestion based on my perspective. Please feel free to consider or disregard as you see fit. appreciate!

**Comment by carlosmiei** [comment]
@yitian-reevo I agree with you (I'm not the original author but I'm working to keep the library updated) and I would like to consider a more generic and future-proof approach.

What do you suggest?  A public `get_socket` method where users can provide the stream name and

**Comment by yitian-reevo** [comment]
@carlosmiei  hold on a bit! There is actually a `all_ticker_futures_socket() `method provided already, so your idea about the fixing (by adding methods to specific cases) is correct. see https://github.com/sammchardy/python-binance/blob/0781051355d8a2dd4a4945ef0b7cfedb35a0b85b/binance/streams.py#L922


--- 
But this brings me another question: it looks like `all_ticker_futures_socket()` appears to be exactly what I'm seeking, by its literal interpretation. But it is mapped to the stream `!bookTicker`, which seems to diverge from what the method name suggests.  Do you know any reasons about why they are mapped like this?

**Comment by carlosmiei** [comment]
@yitian-reevo I have no idea and I agree that it is inconsistent, but changing it now could be a breaking change.

**Comment by carlosmiei** [comment]
@yitian-reevo We can, however update it to accept the stream name as an optional arg like making it "overridable" 

```Python
def all_ticker_futures_socket(self, stream='!bookTicker', futures_type: FuturesType = FuturesType.USD_M):
```

**Comment by yitian-reevo** [comment]
@carlosmiei yep, it will be a break change, not a good idea, looks like a legacy bug. 

I have no preferences on the way to support this, either add new methods to support stream !ticker@arr, or add params to override the existing ones, both have trade offs. 

Can you discuss with other owners to determine the best path forward?

**Comment by carlosmiei** [comment]
@yitian-reevo 

> an you discuss with other project owners to determine the best path forward?

I will try to do that


> I have no preferences on the way to support this, either add new methods to support stream !ticker@arr, or add params to override the existing ones, both have trade offs

To minimize the impact I think we can do both 😅

**Comment by carlosmiei** [comment]
@yitian-reevo If you upgrade your `python-binance` to the latest `futures_ticker_socket` should be available now.
Let us know if anything!
