### ISSUE TITLE
python-binance ThreadedWebsocketManager not working with Python 3.11 or 3.12?

### ISSUE THREAD

**Issue by XiaoWXHang** [sammchardy/python-binance#1459]
**Describe the bug**

When I run the following code in PyCharm, it doesn’t print any information. However, if I run it in debug mode, the information appears. This causes the code to not function properly on Python 3.11 or 3.12.

**To Reproduce**

```
from binance import ThreadedWebsocketManager


def handle_socket_message(msg):
    print(msg)
    print(1, flush=True)


def main():
    # socket manager using threads
    twm = ThreadedWebsocketManager()
    twm.start()

    twm.start_multiplex_socket(callback=handle_socket_message, streams=['!miniTicker@arr'])
    twm.start_futures_multiplex_socket(callback=handle_socket_message, streams=['!miniTicker@arr'])

    # join the threaded managers to the main thread
    while True:
        twm.join(3)
        print("join")


if __name__ == '__main__':
    main()

```

**Expected behavior**
I need Python-binance to work properly on python3.11or3.12 and to print information

**Environment (please complete the following information):**
 - Python version: 3.11 or 3.12
 - Virtual Env: conda
 - OS: Mac, Ubuntu
 - python-binance version 1.0.21

**Logs or Additional context**
This is running
![image](https://github.com/user-attachments/assets/d6a0cb40-8890-438f-8d52-6adc2d6bf713)
This is debug
![image](https://github.com/user-attachments/assets/70d9764c-a4b1-445f-bf1e-008d97d10f5a)

**Comment by XiaoWXHang** [comment]
This problem has been bothering me for a week, because there was no problem when I used 3.8 before, but it still reported an error when I just switched to 3.8. Then I lowered version 1.0.19 and miraculously it worked

**Comment by carlosmiei** [comment]
Hello @XiaoWXHang 

Thanks for reporting it. We will take a look and get back to you asap.

**Comment by carlosmiei** [comment]
@XiaoWXHang Can you please check if adding this line fixes the issue?

```Python
    # socket manager using threads
    twm = ThreadedWebsocketManager()
    twm._loop = asyncio.get_event_loop() # added here
```

**Comment by carlosmiei** [comment]
@XiaoWXHang Can you please upgrade your `python-binance` version and try again?

We released a version with a fix.

**Comment by XiaoWXHang** [comment]
Problem solved, thank you
