### ISSUE TITLE
orderId vs id in trade history response

### ISSUE THREAD

**Issue by mcelhennyi** [sammchardy/python-binance#146]
I cannot determine what the two different IDs correspond to. I assumed one was an ID representing this transaction against all other transactions of the same coin...and the other was this transaction against all transactions globally in binance. But through testing I did, I could not confirm either theory.

I am using the `client.get_my_trades(symbol=, fromId=)`. The reason i started down this rabbit hole was to be able to pull down all my current trades, then in a couple days pull down the trades that I did since last pull. I need a way to say..here is where you can start pulling from. Time would work, but would also pull down everything, which would just waste time.

Any help would be greatly appreciated. I am in the process of making a system to pull down and log trade by trade in a form that the IRS would like for tax purpose.

EDIT: Also is there a place that defines what each field actually is, I cant seem to find that anywhere.

Thanks,
Ian

**Comment by AntoineGS** [comment]
Hey, 
It sounds like the same issue/question as #159 .

**Comment by mcelhennyi** [comment]
ya sorry, did this a couple days ago and didnt realize i put it here also ... whoops
