### ISSUE TITLE
ERROR: CANCEL read_loop, websocket updates loss

### ISSUE THREAD

**Issue by Ramesses3** [sammchardy/python-binance#1465]
**Bug description**
I'm trying to get kline data via a web socket. Interested in closing candles. I noticed that some of the data is lost, although if you check in parallel through postman, then all updates come there.
Also, my python script periodically throws a **CANCEL read_loop** error. I think the data loss is related to it.

**To Reproduce**
Run my simple code:
```
#!/usr/bin/env python3
import re
import time
import asyncio
from datetime import datetime
from binance import AsyncClient, BinanceSocketManager

async def websocket(client=None, symbol=None):
  bm = BinanceSocketManager(client)
  symbol = symbol.lower()
  ms = bm.multiplex_socket([
    f'{symbol}@kline_1m',
    f'{symbol}@kline_5m',
    f'{symbol}@kline_15m'
  ])
  while True:
    async with ms as stream:
      msg = await stream.recv()
      if msg.get('data').get('k').get('x'):
        interval = re.search(r'kline_(.+)', msg.get('stream')).group(1)
        otime = datetime.fromtimestamp(msg.get('data').get('k').get('t')/1000)
        print(f'{interval} {otime}\n{msg}\n')

async def main():
  client = await AsyncClient.create(testnet=False)
  await asyncio.gather(
    websocket(client=client, symbol='TRBUSDT'),
  )

asyncio.run(main())
```

**Expected behavior**
Continuous acquisition of all data from the stream(s) without loss.

**Environment:**
 - Python version: **3.11.9**
 - Virtual Env: **no**
 - OS: **CentOS**
 - python-binance version **1.0.22**

**Comment by Ramesses3** [comment]
I just wrote my simple multiplex socket using pure websockets version 13.1. It works just great, no errors, no data loss.
It turns out that the problem is in python-binance.

**Comment by pcriadoperez** [comment]
Hi @Ramesses3 , 

I was able to reproduce the error. The issue is that the while loop needs to be inside the stream context:
```py
    async with ms as stream:
        while true:
```

If not the stream will continuously connect and reconnect on each message, and this is whats causing the Cancel read loop log and the probable loss of data

**Comment by Ramesses3** [comment]
Hi @pcriadoperez ,
Thank you! I'll give it a try.

**Comment by Ramesses3** [comment]
@carlosmiei thank you one more time. Now it works fine!

**Comment by Ramesses3** [comment]
@carlosmiei thank you one more time. Now it works fine!
