### ISSUE TITLE
Please list test dependencies in setup.py or pyproject.toml

### ISSUE THREAD

**Issue by yurivict** [sammchardy/python-binance#1466]
aioresponses, requests-mock are test dependencies, but there is no complete list anywhere.
Porters need a complete list to add test dependenies properly.

**Comment by carlosmiei** [comment]
Hello @yurivict, thanks for reporting it, we will update `test-requirements.txt` shortly.

**Comment by carlosmiei** [comment]
@yurivict Actually I think all the test dependencies are available here: https://github.com/sammchardy/python-binance/blob/master/test-requirements.txt
