### ISSUE TITLE
testnet order returns nothing but also doesn't throw any error

### ISSUE THREAD

**Issue by trueToastedCode** [sammchardy/python-binance#1468]
**Describe the bug**
A test market order doesn't throw any error but also returns nothing.

**To Reproduce**
```
with open('<path to private key>', 'rb') as f:
    private_key = f.read()

client = Client(
    api_key='<api key>',
    private_key=private_key,
    testnet=True
)

order = client.create_test_order(
    symbol='BTCUSDT',
    side=SIDE_BUY,
    type=ORDER_TYPE_MARKET,
    quoteOrderQty=10.0
)
print(order)
```
Returns: `{}`

**Expected behavior**
Here is an equivalent bash script with returns the expected details.
```
#!/usr/bin/env bash

# Set up authentication:
API_KEY="<api key>"
PRIVATE_KEY_PATH="<path to private key>"

# Set up the request:
API_METHOD="POST"
API_CALL="api/v3/order"
API_PARAMS="symbol=BTCUSDT&side=BUY&type=MARKET&quoteOrderQty=10.0"

# Sign the request:
timestamp=$(date +%s000)
api_params_with_timestamp="$API_PARAMS&timestamp=$timestamp"
signature=$(echo -n "$api_params_with_timestamp" \
            | openssl dgst -sha256 -sign "$PRIVATE_KEY_PATH" \
            | openssl enc -base64 -A)

# Send the request:
curl -H "X-MBX-APIKEY: $API_KEY" -X "$API_METHOD" \
    "https://testnet.binance.vision/$API_CALL?$api_params_with_timestamp" \
    --data-urlencode "signature=$signature"
```
Returns: `{"symbol":"BTCUSDT","orderId":2619482,"orderListId":-1,"clientOrderId":"20ud4QwBKKePm9tLFcp1Kb","transactTime":1731324546617,"price":"0.00000000","origQty":"0.00012000","executedQty":"0.00012000","cummulativeQuoteQty":"9.85717920","status":"FILLED","timeInForce":"GTC","type":"MARKET","side":"BUY","workingTime":1731324546617,"fills":[{"price":"82143.16000000","qty":"0.00012000","commission":"0.00000000","commissionAsset":"BTC","tradeId":817269}],"selfTradePreventionMode":"EXPIRE_MAKER"}`

**Environment:**
 - Python version: 3.12.3
 - Virtual Env: virtualenv
 - OS: MacOS 12.7
 - python-binance 1.0.21

**Comment by carlosmiei** [comment]
Hello @trueToastedCode,

Thanks for reporting it, we will take a look and get back to you.

**Comment by trueToastedCode** [comment]
> Hello @trueToastedCode,
> 
> Thanks for reporting it, we will take a look and get back to you.

Thank you, i figured out the scripts aren't actually equivalent. The correct method to call is 'order_market_buy' but not 'create_test_order'.
