### ISSUE TITLE
Async place batch order gives an invalid signature error

### ISSUE THREAD

**Issue by pcriadoperez** [sammchardy/python-binance#1474]
**Describe the bug**
Async place batch order gives an invalid signature error

**To Reproduce**
async call to place batch order

**Comment by pcriadoperez** [comment]
From my tests in the last branch of add-tests, yes.  I also found delete batchOrders, is also failing on the sync side.
It seems there is some special logic for the signature when using batchOrders. I'm looking into it :)

**Comment by pcriadoperez** [comment]
I saw this is a duplicate of: #1099

**Comment by carlosmiei** [comment]
@pcriadoperez Alright, please follow up on this
