### ISSUE TITLE
ImportError: cannot import name 'AsyncClient' from 'binance.client'

### ISSUE THREAD

**Issue by XiaoWXHang** [sammchardy/python-binance#1483]
**Describe the bug**
When using **streams.py,** I encountered an import error related to the **AsyncClient** class. Specifically, the following line in **streams.py** is causing the issue:

`from .client import AsyncClient  `

However, upon inspecting **client.py**, I couldn't find any definition for the **AsyncClient** class. This results in a runtime error when attempting to use **streams.py**.

**To Reproduce**

1. Import **streams.py** in a Python project.
2. Attempt to use a feature or method that relies on **AsyncClient**.
3. Observe the error.

**Expected behavior**
The **AsyncClient** class should either be defined in **client.py** or the import should be adjusted to reference the correct class or module.

**Environment (please complete the following information):**
 - Python version: 3.11
 - Virtual Env: conda
 - OS: Mac
 - python-binance: 1.0.23

**Logs or Additional context**
![image](https://github.com/user-attachments/assets/cb95fe7f-9120-408c-aa51-9bc43c6f33df)

**Comment by carlosmiei** [comment]
Hello @XiaoWXHang,

Thanks a lot for reporting it. We will take a look asap.

**Comment by carlosmiei** [comment]
@XiaoWXHang Actually I'm unable to reproduce the issue, can you please post the code used?

**Comment by XiaoWXHang** [comment]
It only takes a single line of code:

`from binance import streams`

**Comment by carlosmiei** [comment]
@XiaoWXHang But what do you want to import exactly?

**Comment by carlosmiei** [comment]
@XiaoWXHang You can import every class from streams by doing `from binance import BinanceSocketManager, ThreadedWebsocketManager,BinanceSocketType`

**Comment by XiaoWXHang** [comment]
I need to use some classes from it to implement additional functionality, such as ReconnectingWebsocket.
Currently, streams.py is importing the incorrect AsyncClient. This can be resolved by simply adjusting the import statement.

Change:

`from .client import AsyncClient  `

To:

`from .async_client import AsyncClient  `

**Comment by carlosmiei** [comment]
@XiaoWXHang But why can't you do something like this? ` from binance import BinanceSocketManager, ThreadedWebsocketManager,BinanceSocketType` ?

**Comment by carlosmiei** [comment]
@XiaoWXHang Right now you can import it by doing `
from binance.ws.reconnecting_websocket import ReconnectingWebsocket`

**Comment by XiaoWXHang** [comment]
Thank you for your solution!
But，the incorrect import in streams.py still needs to be fixed.

**Comment by carlosmiei** [comment]
@XiaoWXHang I'm not sure the import is incorrect, we just changed the structure of the package a bit, splitting large files into smaller ones, and adding the `ws/` folder

**Comment by carlosmiei** [comment]
@XiaoWXHang Ok I just noticed what you're saying, but that's being done automatically by the package bundler, we don't have that import in the code as you can see inside `stream.py`  we have `from binance.async_client import AsyncClient` and not `from .client import AsyncClient` 

https://github.com/sammchardy/python-binance/blob/master/binance/ws/streams.py#L12

**Comment by carlosmiei** [comment]
@XiaoWXHang I'm checking it right now, and I will let you know as soon as we patch it.

**Comment by XiaoWXHang** [comment]
Thank you! I'll wait for your update.

**Comment by carlosmiei** [comment]
@XiaoWXHang I just released a new version (1.0.24) with the fix. Can you please upgrade and check again?

**Comment by XiaoWXHang** [comment]
Thank you for the quick fix! I’ve upgraded to version 1.0.24, and I’ve successfully verified that the issue is resolved. I also noticed that you’ve exported `ReconnectingWebsocket`—I really appreciate it!

**Comment by carlosmiei** [comment]
@XiaoWXHang No problem, just let us know if anything!
