### ISSUE TITLE
Websocket example doesn't work

### ISSUE THREAD

**Issue by k128** [sammchardy/python-binance#1489]
**Describe the bug**
At https://python-binance.readthedocs.io/en/latest/websockets.html, the following example code is given:
client.ws_get_order_book(symbol="BTCUSDT")

**To Reproduce**
from binance import Client
client=Client()
client.ws_get_order_book(symbol="BTCUSDT")

Out: AttributeError: 'Client' object has no attribute 'ws_get_order_book'

**Environment (please complete the following information):**
 - Python version: 3.13
 - Virtual Env: venv
 - OS: Windows
 - python-binance version 1.0.21

**Comment by carlosmiei** [comment]
Hello @k128,

Your python-binance version is severaly outdated and does not include these features yet.

Can you please upgrade and try again?

**Comment by k128** [comment]
> Hello @k128,
> 
> Your python-binance version is severaly outdated and does not include these features yet.
> 
> Can you please upgrade and try again?

1.0.21 was released a month ago.  I can try upgrading anyway.
