### ISSUE TITLE
'Connection aborted.', BadStatusLine("''",)

### ISSUE THREAD

**Issue by hsachdevah** [sammchardy/python-binance#149]
I'm using python-binance project which is internally using requests module. 
I keep on getting some or other exceptions from requests module. 

Here is what I received few times when I tried to create a new order
('Connection aborted.', BadStatusLine("''",))

It works most of the times but occasionally throws out exception.

**Comment by KNizaev** [comment]
it's common problem:
https://github.com/requests/requests/issues/2364

**Comment by narendraj9** [comment]
Is there a solution to this common problem? Or is the cause understood? What did you guys end up doing about it? I am facing the same issue.

**Comment by narendraj9** [comment]
This is most likely happening because of a misbehaving proxy or the server for me.

**Comment by xiandong79** [comment]
> This is most likely happening because of a misbehaving proxy or the server for me.

so how do you solve it
