### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by theolux** [sammchardy/python-binance#15]
I started getting this error randomly but constantly today, sometimes combined with:
APIError(code=-1001): Internal error; unable to process your request. Please try again.
This wasn't an issue up until yesterday and I didn't mess with the code in any way. What is going on?

**Comment by sammchardy** [comment]
@theolux looks like there have been some ongoing issues with the Binance API in the last few hours. Check their Telegram channel https://t.me/binance_api_english

**Comment by theolux** [comment]
I see, thanks for the link.

**Comment by sammchardy** [comment]
Closing the issue, temporary problem with Binance exchange.
