### ISSUE TITLE
APIError(code=-2015): Invalid API-key, IP, or permissions for action.

### ISSUE THREAD

**Issue by FabianInf** [sammchardy/python-binance#1504]
Hello,
I tried to make limit order over REST with endpoint /api/v3/order and over     
order = client.order_limit_buy(
    	symbol='ETHUSDT',
    	side='BUY',
    	type='LIMIT',
    	timeInForce='GTC',
    	quantity=100,
    	price=200
    )
, both produces the same error from the title. 
I also tried different combination tld='us', tld='com' or leaving it at initializing the Client class:
client = Client(api_key, api_secret).

IP-Address and API-Keys are correct, because I'm able to read the data. Also, permissions are set:
<img width="789" alt="image" src="https://github.com/user-attachments/assets/35fa0cd2-f4d4-4a57-b112-a9a525f8bab8">

I also tried creating new key multiple times. Some more info: I live in germany, started account couple days ago, testnet "https://testnet.binance.vision/api" produces same error

Could anyway help me? I already scanned whole internet und tried every solution I found on my way.

@edit: get_asset_balance doesn't work either with the same error. I was only able to read the overall data from the market

**Comment by carlosmiei** [comment]
Hello @FabianInf,

Unfortunately the problem must be related with the keys and not python-binance,  locally I can place orders normally, and we have thousands of users that can too, please ensure your IP is not blocked, your keys are properly set, etc

**Comment by FabianInf** [comment]
Hello @carlosmiei ,

thank you for the quick reply. Indeed I got wrong IP in my ipconfig so that is why it didn't work. Thank you
