### ISSUE TITLE
First 

### ISSUE THREAD

**Issue by Andrepalisha** [sammchardy/python-binance#1507]
**Describe the bug**

**To Reproduce**
Code snippet to reproduce the behavior:

**Expected behavior**

**Environment (please complete the following information):**
 - Python version: [e.g. 3.5]
 - Virtual Env: [e.g. virtualenv, conda]
 - OS: [e.g. Mac, Ubuntu]
 - python-binance version

**Logs**
Please set logging to debug and paste any logs here, or upload `debug.log` file to the issue.
```python
import logging
# This will log to both console and file
logging.basicConfig(level=logging.DEBUG,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
handlers=[
logging.FileHandler('debug.log'),
logging.StreamHandler()
]
)
```

**Additional context**

**Comment by carlosmiei** [comment]
Hello @Andrepalisha this issue has no information whatsoever so I'm going to close it.
