### ISSUE TITLE
kline stream not working with @+8:00

### ISSUE THREAD

**Issue by kp0987654321** [sammchardy/python-binance#1509]
python3.9, python-binance v1.0.25

#!/usr/bin/env python
import websocket
import json
from binance.client import Client

def on_message(ws, message):
      json_message = json.loads(message)
      print(json_message)
socket = "wss://stream.binance.com:9443/stream?streams=btcusdt@kline_15m@+8:00"
ws = websocket.WebSocketApp(socket, on_message=on_message)
ws.run_forever()

**Script not working with code line :  socket = "wss://stream.binance.com:9443/stream?streams=btcusdt@kline_15m@+8:00"
Script working well with code :          socket = "wss://stream.binance.com:9443/stream?streams=btcusdt@kline_15m"****

**Comment by pcriadoperez** [comment]
Hi @kp0987654321, 
Connecting directly to binance I also get the error 400 when use +08:00. I am able to connect using 08:00 or -08:00 but no messages are sent through the stream.
Unfortunately as this is on binance's side I'm not sure we can do much to help.
My recommendation would be to listen the the UTC channel and then adjust in your code for the timezone.
I'll close this issue for now, but feel free to reach out or open any other issue you might find.
