### ISSUE TITLE
how to place a limited convert order?

### ISSUE THREAD

**Issue by blatoo** [sammchardy/python-binance#1514]
Hello everyone,

How can I place or cancel a limited convert order?

I noticed there are two functions: `client.convert_request_quote()` and `client.convert_convert_accept_quote()`. Can someone explain what these functions do?

Thank you very much for your help!

**Comment by pcriadoperez** [comment]
Hi @blatoo 

The two endpoints call these two endpoints of binance:

https://binance-docs.github.io/apidocs/spot/en/#change-fixed-activity-position-to-daily-position-user_data

https://binance-docs.github.io/apidocs/spot/en/#send-quote-request-user_data

For any function you should be able to find here the reference:
https://python-binance.readthedocs.io/en/latest/binance.html#client-module


I'll close this issue for now but feel free to reach out with any questions
