### ISSUE TITLE
using websocket without api [Question]

### ISSUE THREAD

**Issue by idrispendisbey** [sammchardy/python-binance#152]
Hello people,

Noob programmer here. First, I would to thank all of you here contributing to the community and enabling us beginners to learn from your knowledge and efforts.

My question is about using websockets without an API. As far as I have read about websockets, our browsers are already receiving live trading data from the exchanges by using websockets. Therefore, even if an exchange does not support websocket connection via its API, I thought that it should be possible to receive all live data from an exchange by simulating the browser experience ( for example selenium? ) and parsing the page or using whatever the code our browsers are sending to the exchange server. Is there anything I am missing? I would appreciate it if you can guide me about this.

Kind Regards

**Comment by sammchardy** [comment]
Hi @idrispendisbey you can get all the information the website receives through the python-binance websocket functions.

**Comment by michja** [comment]
I think definitions might help. Websocket is one connection that keeps pushing through new data. 
e.g. lrcbtc@kline_1m will send you the current 1m candlestick data for LRCBTC a few times a minute for as long as you are connected to the socket

REST API is an address that you visit to get something one time.
e.g. /api/v1/klines?symbol=LRCBTC&interval=1m&startTime=1504717200000&limit=5
will give you a set of five 1m data points for LRCBTC from the startTime requested.

Can you discover undocumented websockets? Sure. Use your browser dev tools network tab and look for WS streams. e.g. https://i.imgur.com/VBKKJhD.png

**Comment by idrispendisbey** [comment]
Thank you for the information
