### ISSUE TITLE
high latency for placing order

### ISSUE THREAD

**Issue by endrewlai** [sammchardy/python-binance#153]
Hello All,

My code below is placing two order in sequence and found that the time gap between two orders is around 90ms, do we have any faster way to place two consecutive orders? Thanks!
--
order = client.order_limit_buy(
    symbol='BNBBTC',
    quantity=2.3,
    price='0.001')

order = client.order_limit_buy(
    symbol='BNBBTC',
    quantity=2.3,
    price='0.00101')
--

**Comment by limpkin** [comment]
In my experience 90ms is not bad at all...

**Comment by sammchardy** [comment]
@endrewlai make sure you're as close to the exchange as possible, their servers are located in AWS Tokyo region.

You can always try async methods to run multiple calls at once.

**Comment by akaniklaus** [comment]
Dear @sammchardy, I moved to Azure Tokyo servers in order to have even better latency. I wasn't getting any errors previously (when I was at Azure USA servers) but now I am getting "Signature for this request is not valid" error. Could that be because requests are too fast? What can I do about it?
