### ISSUE TITLE
Improving network performance by enabling TcpNoDelay

### ISSUE THREAD

**Issue by phroekazoid** [sammchardy/python-binance#157]
Hello,

I've noticed some very big received queue size on multiplex websocket or multiple single websockets with a lot of data transferred:
[root@ site-packages]# netstat -tulpna | grep pyth
tcp   425354      0 192.168.2.17:36992      52.198.175.81:9443      ESTABLISHED 32413/python

Would be very useful to have the option to set the TcpNoDelay for the websockets.

Update: difference in last received feed time vs local time:
Last feed time: 2018-01-31 17:37:07
Local time: 31-01-2018 17:40:03
Last feed time: 2018-01-31 17:37:07
Local time: 31-01-2018 17:40:03
Last feed time: 2018-01-31 17:37:07
Local time: 31-01-2018 17:40:04
Last feed time: 2018-01-31 17:37:07
Local time: 31-01-2018 17:40:04

**Comment by limpkin** [comment]
oh.... and setting high priority sockets on windows would be great as well...

**Comment by limpkin** [comment]
s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

from

https://stackoverflow.com/questions/31826762/python-socket-send-immediately

**Comment by phroekazoid** [comment]
thanks limpkin! found the issue, it was actually inside the socket message manager.
Bassicaly it was doing another stuff which was taking more than a second, consequently causing delay in parsing the websocket feed

**Comment by limpkin** [comment]
still, would be a nice improvement anyway :)

**Comment by sammchardy** [comment]
Hi @limpkin and @phroekazoid the tcpNoDelay is already set to True as it is.

The WebSocketClientFactory base class sets it True by default. You can inspect the source here, note the `self.resetProtocolOptions()` call
https://github.com/crossbario/autobahn-python/blob/7ccee1b4e70c3fc189d5bfb6fe8fa500647f6fa7/autobahn/websocket/protocol.py#L3764

**Comment by sammchardy** [comment]
Closing this issue.

**Comment by irreverentperson** [comment]
The aggtrade and trade sockets are now showing the same prices 'p' as binance website.

**Comment by irreverentperson** [comment]
*Different prices

**Comment by irreverentperson** [comment]
trxbtc prices showing 489 satoshi on binance.com but sockets returning 'p' as 499 satoshi.

**Comment by irreverentperson** [comment]
Nevermind. My code was lagging. Thank you for python-binance!
