### ISSUE TITLE
Ubuntu: depth socket not started

### ISSUE THREAD

**Issue by limpkin** [sammchardy/python-binance#158]
Hey there!

I have the very same code running on windows, but am encountering a problem when migrating over linux.
In short, in this line: start_depth_socket(exchange, binance_order_book_message_listener), binance_order_book_message_listener gets never called.

**Comment by michja** [comment]
Hey, 

This might just be variable naming but depth socket expects a market symbol not the exchange name. I can confirm it's working for me on ubuntu passing "LTCBTC"

**Comment by limpkin** [comment]
yes, this is actually what i'm passing.
As i said, code is working on windows :)

**Comment by michja** [comment]
Does this do anything?
https://gist.github.com/michja/c082c8bc65fe2471299264222b26ab17

**Comment by limpkin** [comment]
damn... it does.

**Comment by michja** [comment]
haha damn! I guess you got the good news... and the bad news

**Comment by limpkin** [comment]
I don't get it... the only difference is that the access to bm is done through another thread, using a global var :/

**Comment by limpkin** [comment]
Found my problem!
If bm.start() is called from the same thread that starts the depth socket, then there's no problem.
However, if a thread calls bm.start then a thread starts the depth socket... nothing.

any clue?

**Comment by limpkin** [comment]
it seems to be a problem related to the socket library used.
I'm afraid I need to reformat my code to accomodate that.

**Comment by limpkin** [comment]
wow, it is even stranger than that.... if the bm.start is not called from the same **function** then the depth socket doesn't start.

**Comment by limpkin** [comment]
I guess I can close that issue given it's more of a socket issue :)
