### ISSUE TITLE
client.get_my_trades has two IDs

### ISSUE THREAD

**Issue by mcelhennyi** [sammchardy/python-binance#159]
This may not be the best place for this question, but unfortunately I cannot find another.

I cant seem to figure out the difference in the two id fields in the `get_my_trades(symbol)` call. It returns an `id` and an `orderId` for each trade that the call returns. 

The reason I ask is I am automating pulling down and storing my trade history for tax reasons, and want to be able to say "Well I know I have pulled trades **up to** 'this' trade, so give me everything **after** 'this' trade" for each currency type/symbol.

Also if this project interests you check out my page, [CryptoTaxBot](https://github.com/mcelhennyi/CryptoTaxBot).

Thanks ahead of time, 
Ian

**Comment by AntoineGS** [comment]
Hi,

Each id refers to a fill for a given orderid. For example if you put a sell order (referred to by the orderid) for 100 coins and 2 buyers each buy 50, you will have two different ids for quantities of 50 (2 fills). Hopefully that's helps!

**Comment by mcelhennyi** [comment]
@AntoineGS so you are saying id is a child of orderid essentially?

So if I wanted to say "Give me all the trades after this order" I would send the 'orderid' and not the 'id' to binance api?

**Comment by AntoineGS** [comment]
Correct, the id would be the child, though as per the API documentation the
fromId parameter takes a tradeid (aka id) and not an orderid.

**Comment by mcelhennyi** [comment]
@AntoineGS Ok, so to get the trades after a given trade i pass the 'id' to the 'formId' field...gotcha. Thanks

**Comment by mcelhennyi** [comment]
@AntoineGS One last question...if I have multiple fills per one order...would it return to me multiple trades all with the same 'orderid' but different 'id's or would it return to me one trade with one 'orderid' and an array of 'id's?...my guess is the first, so it would kinda look like I made multiple trades but really..if I correlate the 'orderid's then I can rebuild the many sub trades into one.

Then if this is true I would expect the qty to be unevenly dispersed between the sub trades but the fee evenly dispersed.

**Comment by AntoineGS** [comment]
Sorry I had not seen your second post, it would be the former. The fee will be a percentage of the qty * trade price (0.05% with BNB coins)

**Comment by sammchardy** [comment]
Thanks @AntoineGS, closing now.
