### ISSUE TITLE
Writing data to a file from WB not working

### ISSUE THREAD

**Issue by techietrader** [sammchardy/python-binance#161]
```
def process_message(msg):
    with open('output.txt', 'w') as file:
             file.write(msg + '\n')
```
        
This gives me error of ' object has not attribute of append 

What am I doing wrong?

**Comment by michja** [comment]
I think that msg will be an object which doesn't like being printed to a file. 

Example format:
https://github.com/sammchardy/python-binance/blob/master/binance/websockets.py#L186

You could import json module and use json.dumps() for a text representation

**Comment by sammchardy** [comment]
@techietrader please reopen if you're still having issues.
