### ISSUE TITLE
worng signature in wapi function deposit_address

### ISSUE THREAD

**Issue by AlexGitRod** [sammchardy/python-binance#162]
when i make a call to function  depositaddress i get the message, {'msg': '{"code":-1022,"msg":"Signature for this request is not valid."}', 'success': False}. I tried to make an api call with the other wapi function and it works fine.Whats the problem cause i only pass two parameters(asset,timestamp)

**Comment by sammchardy** [comment]
Hi @AlexGitRod sometimes the error messages are a bit cryptic. The `get_deposit_address` function only has one required parameter `asset`, and optional `recvWindow`

See the documentation here https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_deposit_address
