### ISSUE TITLE
APIError(code=-1013): Stop loss orders are not supported for this symbol.

### ISSUE THREAD

**Issue by wkniffin** [sammchardy/python-binance#166]
Hello,

I am testing stop-loss orders, and I am getting the titled APIError.

Here is the code:

```python
bclient.create_order(symbol='BNBBTC', side='BUY', type='STOP_LOSS', quantity=11.0, stopPrice=0.0001)
```

The same thing happened with BNBUSDT.

If these are truly unsupported symbols, is there a list of the supported symbols somewhere?

Thanks!

update:
I tried a STOP_LOSS_LIMIT order as well, but I keep getting APIError(code=2010): Order would trigger immediately. I've tried with different combinations and get the error every time.

```python
bclient.create_order(symbol='BNBBTC', side='SELL', type='STOP_LOSS_LIMIT', quantity=11.0, price=1.0 stopPrice=1.0, timeInForce='GTC')
```
^ an example

**Comment by sammchardy** [comment]
Hi @wkniffin use the `bclient.get_exchange_info()` function to see the order types supported by each trading pair.

**Comment by limbat** [comment]
Hello 
I m getting the error
I tried a STOP_LOSS_LIMIT order as well, but I keep getting APIError(code=2010): Order would trigger immediately. I've tried with different combinations and get the error every time.
What can be the solution?
Regards

**Comment by anson-vandoren** [comment]
APIError 2010 is for "NEW_ORDER_REJECTED". See [official Binance API documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md)

As mentioned earlier on this thread, did you confirm that stop loss orders are permitted for the symbol pair you are using, and that you have sufficient balance to enter the order?

**Comment by Karlheinzniebuhr** [comment]
getting this error when sending a OCO order without stopLimitPrice
```
client.create_margin_oco_order(
                        symbol=SYMBOL_TO_TRADE,
                        side=tp_sl_side,
                        quantity=quantity,
                        price=tp_price,
                        stopPrice=tp_stop_price,
                        isIsolated=isIsolated,
                        sideEffectType="AUTO_REPAY")
```
