### ISSUE TITLE
functions returning exponential numbers instead of floats

### ISSUE THREAD

**Issue by Technorocker** [sammchardy/python-binance#168]
Hey everyone. So I have a method thats calculates maxquantity... actually there have been a few instances where I am trying to get back a float value and it comes out as an exponential number. I have read that python should read both float and axp numbers the same but now I am getting an error in my get_asset_balance call like so...

``Balances 5.76e-06 and  49.35
Traceback (most recent call last):
  File "D:/Programming Projects/Python Courses/BinanceBot/testing.py", line 56, in <module>
    maxqty = Orders.maxquantity(midbalances['1'], pairprice)
  File "D:\Programming Projects\Python Courses\BinanceBot\Orders.py", line 80, in maxquantity
    balance = Balance.assetbalance(asset)
  File "D:\Programming Projects\Python Courses\BinanceBot\Balance.py", line 37, in assetbalance
    balance = client.get_asset_balance(asset)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\binance\client.py", line 1467, in get_asset_balance
    if bal['asset'].lower() == asset.lower():
AttributeError: 'float' object has no attribute 'lower'

Do I need to somehow make the value back to an actual float first?
I have done this a few times in other areas on my coding and if I turn a float thats shows as an exp than it turns it back to  a string which I then try to float and it just shows the exponential value once again

**Comment by Technorocker** [comment]
Also since I'm still new to api calls to begin with can we send a string of numbers or does it have to be type float? cause that might solve alot of those exponential return problems if so.

**Comment by harambe623** [comment]
You should be casting all of the numbers you get from binance
float(incoming["number"])

**Comment by harambe623** [comment]
ALSO read the documentation within the binance python files on your computer. All the types are discussed

**Comment by Technorocker** [comment]
ee every response I get from binance I do turn into a float in order to do
any calculations in my functions. if i do a call to get balance and print
it it will give me a float number value, then when I try to convert it to
say... lot size and print the same result it comes out as exponential. Ive
been doing some more reading and I'm going to try and turn it into decimal
before i send it back in a order call

**Comment by harambe623** [comment]
Your "exponential" values are actual floats, which is how python displays floats with a lot of decimal places. A few functions with binance require you send that decimal as a string, you can do a format like "{:1.7f}".format(yourFloat)

**Comment by Technorocker** [comment]
hey thanks for youre reply. Ive done that before but then it turns it into a str and I cant do any calculations on it. Ive been searching on the web for reasons or ways to NOT have my float be represented as an exp value but I'm still stumped.

Im trying to
1. Get balance
2. adjust balance to lotsize with  math.floor function
3. place result into a buy or sell order

so im stumped at this point. yes I understand that python reads both float and exp as the same but I cant send an exp value into an order cause it errors out the the value is not in range by range it means its reading the "e" in the exp number im assuming

**Comment by harambe623** [comment]
you should be doing math on your float BEFORE turning it into a string.

You are also probably printing a raw float. You should convert to a string like I mentioned above when printing

**Comment by Technorocker** [comment]
So... just to clarify. we are able to send back a number as a string? cause Ive just assumed the price and quantities all had to be numeric values before they got sent back to the API. Well... thank you for the enlightenment. That'll make things a whole lot simpler in the long run

**Comment by harambe623** [comment]
That depends on the function. You need to read the documentation, everything is specified

**Comment by emestee** [comment]
Don't be silly, use decimal.Decimal

**Comment by Technorocker** [comment]
excellent help thank you so much
