### ISSUE TITLE
get_open_orders not working

### ISSUE THREAD

**Issue by harambe623** [sammchardy/python-binance#169]
get_open_orders(symbol) not returning anything! .. did something break?

**Comment by harambe623** [comment]
get_account also acting weird - data is not correct

**Comment by LucasSimpson** [comment]
get_all_tickers() is giving me an empty list, might be related?

**Comment by AntoineGS** [comment]
It is most likely related to the maintenance Binance is doing at the
moment.

**Comment by sammchardy** [comment]
This was an issue with the Binance exchange being down.
