### ISSUE TITLE
Socket Issue

### ISSUE THREAD

**Issue by jpdvi** [sammchardy/python-binance#171]
Socket seems to work on windows but not linux.

**Comment by TraderVK** [comment]
Having a similar issue on OS X, while it seems to work fine on Windows.

**Comment by jpdvi** [comment]
Resolved issue by changing WEBSITE_URL to WEBSITE_URL = 'https://us.binance.com'

**Comment by sammchardy** [comment]
This was an issue with the Binance exchange being down.

**Comment by jpdvi** [comment]
@sammchardy  If you give the option for regional dns it will prevent library from crashing when they disable main the main endpoint (they did this before due to ddos after the exchange came back online).  just suggestion though.
