### ISSUE TITLE
get_klines: Not all sent parameters were read; read '2' parameter(s) but was sent '4'.

### ISSUE THREAD

**Issue by LeoIannacone** [sammchardy/python-binance#172]
Hi,

I'm try to know if a symbol has a young or old market. To do that, I was thinking about klines and check the length of the response/array.

I'm using this::
```
        time_1y_ago = (
            datetime.datetime.now() - datetime.timedelta(days=365)
        )
        time_1y_ago = time.mktime(time_1y_ago.timetuple()) * 1000
        time_now = time.mktime(datetime.datetime.now().timetuple()) * 1000
        resp = client.get_klines(
            symbol=self.symbol,
            interval=Client.KLINE_INTERVAL_1MONTH,
            star_time=time_1y_ago,
            end_time=time_now,
        )
```

But I always receive this error:
```
BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '2' parameter(s) but was sent '4'.
```

Any help?

Is there anyway to guess if a market is old/young?

**Comment by sammchardy** [comment]
Hi @LeoIannacone the parameter names are `startTime` and `endTime`, see the documentation for `get_klines` here
https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_klines

**Comment by LeoIannacone** [comment]
Alright, thanks!
