### ISSUE TITLE
Crossing ask bid prices with depthcache

### ISSUE THREAD

**Issue by tobltobs** [sammchardy/python-binance#177]
Sooner or later I get crossing bid ask prices from a depthcache. The bids are higher then the asks.
This happens sometimes after a few minutes, sometimes after an hour. I am running ~100 DCMs concurrently.
I am using the 0.6.2 version from pip.

**Comment by sammchardy** [comment]
Hi @tobltobs I haven't tested with that many DCM's going.

Do you have the same issue if you run one DCM?

Each DCM opens a new websocket, so for your use case it may be more efficient using [websocket multiplexing](https://python-binance.readthedocs.io/en/latest/websockets.html#id1) and combining the depth cache messages for a number of markets. This would require a new class though, but you could re-use a lot of the code from the existing DCM class.

**Comment by tobltobs** [comment]
I am currently testing with less concurrently DCMs. I was able to provoke a crossing bid ask when running 10 DCMs and causing a congested network. However it could be that all the problems are somehow caused by me using multiple threads to start the DCMs.
Or maybe the binances api sometimes sends trash, because when I called
```
depth_cache_managers[symbol]._depth_cache = DepthCache(symbol)
depth_cache_managers[symbol]._init_cache()
```
after detecting crossing bids asks for a symbol the error went away (sometimes) after a few more messages.

However, while looking at the code for a way to recover from the situation I wondered if `_init_cache` shouldn't also reset `_depth_cache`.

If I don't find a solution I will look into your multiplexing solution. One problem with this (at least for a solution which could be integrated into python-binance) would be that I have been running into ratelimits when I started >200 DCM concurrently. Binance API docs says there is a rate limit about 300 per second, but somehow the `get_order_book` calls of the initializing DCMs did trigger this reply far earlier.

I guess you can close this issue as I can't provide a way to reproduce this problem currently and it might be caused by some inappropriate usage patterns.

Thank your for your work on python-binance.
