### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by CryptoZorro** [sammchardy/python-binance#179]
Hello, I'm running Python3.6 on my QNAP NAS and my crypto bot has been working fine till now (handles auto trading with bittrex till now). I'm trying to enhance my bot to handle binance as well and tried installing the module: pip3 install python-binance and the install gets stuck around this line which mentions creation of wheel for the dependancies like cffi & cryptography. 

Any help to fix my installation will be appreciated. I'm including the full log. Thank you! 
[python binance install.txt](https://github.com/sammchardy/python-binance/files/1722502/python.binance.install.txt)
............
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /opt/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/share/CACHEDEV1_DATA/.qpkg/Entware-ng/tmp/pip-build-30_un6xp/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /opt/tmp/tmph7r2zkmmpip-wheel- --python-tag cp36:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  warning: build_py: byte-compiling is disabled, skipping.
  
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "/unixccompiler.py", line 118, in _compile
    File "/ccompiler.py", line 909, in spawn
    File "/spawn.py", line 36, in spawn
    File "/spawn.py", line 159, in _spawn_posix
  distutils.errors.DistutilsExecError: command 'x86_64-openwrt-linux-gnu-gcc' failed with exit status 1
  
  ...
------------

**Comment by sammchardy** [comment]
Hi @CryptoZorro you need the dev headers for ffi

check this out https://stackoverflow.com/questions/31508612/pip-install-unable-to-find-ffi-h-even-though-it-recognizes-libffi

The second answer shows you how to install the dev headers for various distributions, not sure exactly what QNAP is running.

**Comment by CryptoZorro** [comment]
I have already got libffi package installed. Correct me if i'm wrong, so in addition, I need get libffi-dev / libffi-devel also installed? I don't see these dev headers available for my NAS. So does this mean I can't use your binance wrapper? Is this dev headers optional or a must to have your binance wrapper work? Kindly advise. Cheers!
