### ISSUE TITLE
Seems like it isn't possible to use websocket and api clients at same time

### ISSUE THREAD

**Issue by nodeYoda** [sammchardy/python-binance#182]
I'm looking to use the websocket for getting ticker into and the api to make orders but the api gives:  Signature for this request is not valid when using websocket.  Is this a limitation or can you give a simple example of how to get this two pieces to work in harmony?

**Comment by Chingis-Khan** [comment]
I am using the web socket for klines, and user data socket, and place buy and sells with the api.   Perhaps you can share a code sample to help us see what you are doing?

**Comment by golangninja** [comment]
I was able to get around the issue using binance websocket api directly.  I
feel the problem with the python lib was that it passed in client with
credentials to both the websocket connection and was being used for all
requests.  The websocket would work but then all request had an error about
my signature.  I be already made the code changes so can't reproduce at
moment for easy traceback or share my code. By the way, python-binance is
awesome.

Best Regards

**Comment by Technorocker** [comment]
@Chingis-Khan I was wondering how you use your websocket kline data? I'm currently using the API for kline data and I get back the proper intervls as I cal for, but I'm trying to convert over to websocket and I'm getting second by second no matter what interval time I pass to it. Any suggestions on how to catch the proper intervals? I'm getting connection problems that I think are from using the API too often in issue #195

**Comment by Chingis-Khan** [comment]
Web sockets feed data to you when they are ready, in theory should be once a seconds from binance but it's not 100% reliable becasue of the internet being not 100% reliable among other things.

So I have it feed to a queue and poll the queue when I am ready.

```
        self.bm = BinanceSocketManager(self.binance_client)
        self.socket_queue = queue.Queue()
        self.kline_conn_key = self.bm.start_kline_socket(self.pair_code, self.kline_socket_error_check, KLINE_INTERVAL_1MINUTE)
        self.bm.start()
       
    def kline_socket_error_check(self, msg):
        if msg['e'] == 'error':
            logger .info('Error on ticker socket: %s ' % (self.pair_code)
           # handle errror
        else:
            self.socket_queue.put(msg, block=False)

```

**Comment by HarveyWolfstein** [comment]
Hi, I have an issue related to this topic:
I couldn't figure out how can I get prices from websocket and put an order.
My code sample goes like this:

`class Klass(object):

    def __init__(self, bm):
        self.bm = bm
        self.bm.start()

    def depth(self):
        depth_key = self.bm.start_depth_socket('NEOBTC', self.process_message_lean, depth=WEBSOCKET_DEPTH_10)

        order_book = {
            'buys': [item[:2] for item in msg['bids']],
            'sells': [item[:2] for item in msg['asks']]
        }

        table_lines = []
        for item, item2 in zip(order_book["buys"], order_book["sells"]):
            item.append(item2[0])
            item.append(item2[1])
            table_lines.append(item)

        return(table_lines)`

then putting buy order:

`DX = Klass(BinanceSocketManager(Client))

buy_price=DX.depth()[0][1]
binance_client.order_limit_buy(timeInForce=TIME_IN_FORCE_GTC,
                               symbol='NEOBTC',
                               quantity=2,
                               price=buy_price
                               )`
