### ISSUE TITLE
IndexError when requesting multiples of 500 from get_historical_klines()

### ISSUE THREAD

**Issue by Fisherck** [sammchardy/python-binance#183]
Today I got the error "IndexError: list index out of range"  at line 749 in get_historical_klines() (specifically on "start_ts = temp_data[-1][0]").

I had requested 1 minute granularity data going back 500 minutes from get_historical_klines() when I got this error. After some experimenting, it appears that this happens only when requesting multiples of 500 (which I believe is how many rows the Binance API returns on the single call?), but doesn't affect anything else (like for example, requesting 499 or 500 data points). I am using v0.6.5

**Comment by sammchardy** [comment]
This has been resolved in v0.6.7
