### ISSUE TITLE
Using Binance Precision of 8 from symbol data gives error, using a manual value of 6 works.

### ISSUE THREAD

**Issue by Chingis-Khan** [sammchardy/python-binance#184]
Hi. 

I am getting the following data from  client.get_symbol_info('BNBBTC')

```{'symbol': 'BNBBTC', 'status': 'TRADING', 'baseAsset': 'BNB', 'baseAssetPrecision': 8, 'quoteAsset': 'BTC', 'quotePrecision': 8, 'orderTypes':```

But when placing an order I get an error code -1111 Precision is over the maximum defined for this asset

~~Where is the mistake, I think BNB should be 2 decimal places and not 8 but I don't know~~

**Comment by Chingis-Khan** [comment]
ok, it seems I need to round the price down to 7 decimals and not 8.  Does any one know why?

**Comment by Chingis-Khan** [comment]
to get this to work for now I am doing this
```
self.base_precision = symbol['baseAssetPrecision'] - 1
self.quote_precision = symbol['quotePrecision'] - 1
```

**Comment by Chingis-Khan** [comment]
And that does not work for ETH /BTC, where the Binance client displays 6 decimal places.  Is it the data from Binance that is wrong?  It says Precicosn is 8 for ETH/BTC but their own client shows 6.

If I manually set the value to 6 it works.

**Comment by Chingis-Khan** [comment]
Closing this as it's too rambling and opening a new more coherent issue

**Comment by 15chrjef** [comment]
Have you found a solution to this @Chingis-Khan ?

**Comment by Chingis-Khan** [comment]
Yes, I re-read the documentation :)

**Comment by mkaand** [comment]
I guess you should consider tickSize instead of Precision @Chingis-Khan 

For example : BCCBTC tickSize = 0.00000100 That means Precision is 6 actually and it is correct. What I did:

Just send $coin ticker (BCC) and get 0.000001 instead of 0.00000100  for BCCBTC

$symbols = json_decode(file_get_contents("https://www.binance.com/api/v1/exchangeInfo"),TRUE);
$findKey = search_revisions($symbols["symbols"], $coin."BTC", "symbol");
$minPrice = clean_num($symbols["symbols"][$findKey[0]]["filters"][0]["tickSize"]);

Function search_revisions($dataArray, $search_value, $key_to_search, $other_matching_value = null, $other_matching_key = null) {
    // This function will search the revisions for a certain value
    // related to the associative key you are looking for.
    $keys = array();
    foreach ($dataArray as $key => $cur_value) {
        if ($cur_value[$key_to_search] == $search_value) {
            if (isset($other_matching_key) && isset($other_matching_value)) {
                if ($cur_value[$other_matching_key] == $other_matching_value) {
                    $keys[] = $key;
                }
            } else {
                // I must keep in mind that some searches may have multiple
                // matches and others would not, so leave it open with no continues.
                $keys[] = $key;
            }
        }
    }
    return $keys;
}

function clean_num( $num ){
	$pos = strpos($num, '.');
	if($pos === false) { // it is integer number
		return $num;
	}else{ // it is decimal number
		return rtrim(rtrim($num, '0'), '.');
	}
}

**Comment by akildemir** [comment]
> Yes, I re-read the documentation :)

This was incredibly useful  😒😒

**Comment by Rob-bb** [comment]
> > Yes, I re-read the documentation :)
> 
> This was incredibly useful 😒😒

I was misunderstanding a lot of how it worked, I re-read the docs and thought about it and then did it properly and it worked.  Not much else to say as I don't know what you are doing wrong.

**Comment by MaxYari** [comment]
> > > Yes, I re-read the documentation :)
> > 
> > 
> > This was incredibly useful 😒😒
> 
> I was misunderstanding a lot of how it worked, I re-read the docs and thought about it and then did it properly and it worked. Not much else to say as I don't know what you are doing wrong.

It's not about what he is doing wrong. This thread was created by you and people reading it most likely are interested in a solution for the same problem as yours. Your solution may or may not fit them but anyway it's quite counter-productive for the community and absolutely frustrating for the readers to state that you've solved your issue without presenting any explanations/solutions whatsoever.

**Comment by Rob-bb** [comment]
Dude, I read the documentation and did it as the documentation said, and it worked, before that I wasn't following the docs properly and it didn't work.  My solution was to study the docs and understand them properly.  I don't even know what I did wrong, it was two years ago, I probably deleted the whole function and started again with my new understanding of how it was supposed to work.

**Comment by Rob-bb** [comment]
Look on the bright side, you know it does work :)

**Comment by dapsi0404** [comment]
Hello, You can show in the code where you need to make a change to make the program work correctly, thank you in advance!

**Comment by Rob-bb** [comment]
Sorry no, I no longer have the code for this.  But my mistake was a simple misreading of the documentation, follow the steps and read the binance documentation and it will make sense

**Comment by Keref** [comment]
The Binance API doc isn't clear, it just lists the response but doesn't explain why that doesn't work. So to replace this idiot who asks but refuses to answer, the error is to use baseAssetPrecision which is not meant for placing orders, it's just a precision of display/record for the asset, that's what you'll see in your wallet overview or asset balance but isn't the precision you can give for an order, that precision actually depends on the type of order, and is described in filters.

`{
  "symbol":"OMGUSDT",
 "status":"TRADING",
"baseAsset":"OMG",
"baseAssetPrecision":8,
...
"filters":
[{"filterType":"PRICE_FILTER","minPrice":"0.00010000","maxPrice":"1000.00000000","tickSize":"0.00010000"},
{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},
{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"900000.00000000","stepSize":"0.01000000"},
{"filterType":"MIN_NOTIONAL","minNotional":"10.00000000","applyToMarket":true,"avgPriceMins":5},
{"filterType":"ICEBERG_PARTS","limit":10},
{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"236783.60641221","stepSize":"0.00000000"},
{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},
{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],
"permissions":["SPOT","MARGIN"]}`

So e.g OMG-USDT, what you want to use is the PRICE_FILTER parameter tickSize as mentioned by mkaand, here with tickSize = 0.000100000 you can give a price precision of 10e-4.

**Comment by Rob-bb** [comment]
>  So to replace this idiot who asks but refuses to answer, 

I replied honestly, I don't have the code, I deleted the project years ago, what do you want me to do, rebuild the whole thing to help you when literally reading the documentation answered my original question?
