### ISSUE TITLE
client.get_asset_balance(asset='BTC') returning None

### ISSUE THREAD

**Issue by hsachdevah** [sammchardy/python-binance#190]
I'm expecting some response as I have valid balance in my account. But receiving None as the response

**Comment by DaniZz** [comment]
it works with me.
make sure you have updated python-binance to the last version.

**Comment by sammchardy** [comment]
Hi @hsachdevah I'd say this may have been an error on the Binance server side, it is working as expected.

**Comment by enrique200** [comment]
I have the same problem, but the same code, same version of python-binance works with another keyapi, it is possible that there is some restriction that prevents showing the balance when performing get_asset_balance
