### ISSUE TITLE
Reactor not restartable

### ISSUE THREAD

**Issue by TwistedReactor** [sammchardy/python-binance#194]
I have the following code which ran correctly the first time:

`def process_message(msg):
    print("message type: {}".format(msg['e']))
    print(msg)

bm= BinanceSocketManager(client)

conn_key= bm.start_trade_socket('BTCUSDT', process_message)
bm.start()
time.sleep(500)
bm.stop_socket(conn_key)
bm.close()
reactor.stop()`

Now I get the following error:
raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable

How can I restart the reactor?

**Comment by michja** [comment]
You could keep reactor running and test it to make sure that you don't try and start twice.

if not reactor.running:
        reactor.run()

Maybe this isn't the best advice but since no one has suggested anything else in over two weeks... :smiley:

**Comment by sammchardy** [comment]
Hi @TwistedReactor why do you need to stop the reactor? According the the Twisted docs, it can't be restarted, so you should only really stop it if you want to exit the script gracefully.

The reactor is started in the BinanceSocketManager if it's not already running.
