### ISSUE TITLE
Implement destructor for Depth Cache Manager

### ISSUE THREAD

**Issue by sammchardy** [sammchardy/python-binance#20]
Allow socket to be stopped manually and cleaned up properly when deleted.

**Comment by Radnyx** [comment]
Until this is implemented, my current workaround is checking `depth_cache._symbol` in the case of previous conflicting DepthCacheManagers.

**Comment by sammchardy** [comment]
@Radnyx  v0.4.3 goes some way to fixing this, but it's not quite complete.
Individual sockets can be stopped using the bm.stop_socket(conn_key) call, all sockets can be stopped using the bm.close() call.
After a close() call, a socket can be restarted again on the same BinanceSocketManager instance.

**Comment by sammchardy** [comment]
@Radnyx going to close this one now with the recent releases resolving this.
