### ISSUE TITLE
get_recent_trades

### ISSUE THREAD

**Issue by kieranflynn** [sammchardy/python-binance#201]
get_recent_trades returns a dictionary with a several keys including one labelled: u'time'

I have just returned the value from a u'time' key and got: 1519891560702

What is the format of this value?

**Comment by sammchardy** [comment]
This is a unix timestamp in milliseconds. 

https://en.wikipedia.org/wiki/Unix_time

**Comment by laurobmb** [comment]
import time
x = 1549915402112 
print (time.strftime('%H:%M:%S', time.gmtime(x)))

**Comment by laurobmb** [comment]
import time
x = 1519891560702 
print (time.strftime('%H:%M:%S', time.gmtime(x)))
