### ISSUE TITLE
Unable to restart websocket, and reconnection issues.

### ISSUE THREAD

**Issue by ikubay** [sammchardy/python-binance#202]
When attempting to end a single websocket with bm.close() or bm_.stop_socket(conn_key), after attempting to start a new socket I do not receive any data from the callback, meaning the socket is not connecting, and BinanceSocketManager must not be working correctly. 

```
bm = BinanceSocketManager(client)
conn_key = bm.start_trade_socket('BNBBTC', process_message)
bm.start()
#Runs fine until I would like to stop and connect.
bm.stop_socket(conn_key)
conn_key = bm.start_trade_socket('BNBBTC', process_message )
```

or if I used bm.close():

```
bm = BinanceSocketManager(client)
conn_key = bm.start_trade_socket('BNBBTC', process_message)
bm.start()
bm.close()
bm = BinanceSocketManager(client)
conn_key = bm.start_trade_socket('BNBBTC', process_message)
bm.start()
```

I have added time.sleep(60) lines between the stop and start calls, but they don't seem to help. I still end up receiving no more data from the websocket after disconnecting and trying to reconnect. conn_key returns an actual connection key and not an error.

I am attempting to reconnect sockets for multiple reasons.
1. I want to reconnect every 23 hours so I am not automatically disconnected by Binance due to their 24 hour connection policy.
2. I am currently developing my program on a home PC. I want to make sure my program works correctly in case my internet goes down. Of course, with the Rest API, I have been able to do so by simply looping the API call request until I'm back online and it is sent.

I made a short looping function which checks for internet connectivity, and ends when it's back up. I would like to end Binance socket(s) prior to this, and start a new socket connection afterwards when I'm back online.

Please do not suggest I get a VPS; that is not a solution, that's a workaround. The solution in question is being able to disconnect and connect to Binance websockets. I don't mean that in a rude way, I would just like to make my program as versatile as possible.

**Comment by ash09** [comment]
I've got the same issue, I cannot restart a socket after closing it.

**Comment by lambi9891** [comment]
Same here - I've been battling with this issue for a month now.

To provide a bit more of context - this is the status of BinanceSocketManager:

before first bm.start():

<BinanceSocketManager(Thread-1, initial)>

after first bm.start():

<BinanceSocketManager(Thread-1, started 123145480900608)>

so far so good.

After bm.stop_socket(conn_key):

I don't receive data from Binance anymore so the connection it severed at some point but still:

<BinanceSocketManager(Thread-1, started 123145480900608)>

After bm.close():

No change:
<BinanceSocketManager(Thread-1, started 123145480900608)>
 
After reactor.stop():

No change.
It is interesting to note that quitting python env at this point needs CMD-D + CMD-C which most probably means that a loop is still running.

After setting up a new client and linking the BinanceSocketManager to it:

<BinanceSocketManager(Thread-2, initial)>
 Thread-2 here makes sense.

After bm.start():

<BinanceSocketManager(Thread-2, stopped 123145491410944)>

Interesting, Thread-2 is automatically stopped, I can only guess because like the doc states: 

"Only one instance of each socket type will be created, i.e. only one BNBBTC Depth socket can be created and there can be both a BNBBTC Depth and a BNBBTC Trade socket open at once."

Will investigate the source code and see where the problem lies. My intuition tells me that the problem lies in reactor's feedback loop actually never stopping.

Any help welcome.

**Comment by sammchardy** [comment]
Hey @dingoyabuki and @lambi9891 thanks for the examples, I'll have a look into this and see what we can do.

I'll test it with the current code and the proposed pull request #192

**Comment by sammchardy** [comment]
This is a simple example which I have used for a while to reconnect, it closes the particular socket after 3 messages are received and then reconnects.

```
from binance.client import Client

from binance.websockets import BinanceSocketManager

client = Client("", "")


def process_trade_message(message):
    global count, conn_key
    count = count + 1
    print("got ticker message:{}:{}".format(count, message))
    if count >= 3:
        print('closing socket')
        # use either stop_socket or close, or both
        bm.stop_socket(conn_key)
        bm.close()
        # restarting the socket
        conn_key = bm.start_trade_socket('BNBBTC', process_trade_message)
        # reset the count
        count = 0


bm = BinanceSocketManager(client)
count = 0
conn_key = bm.start_trade_socket('BNBBTC', process_trade_message)

bm.start()
```

Can you check if that works for you. Does it provide what you need?

**Comment by apovall** [comment]
@sammchardy's example worked for me when copy and pasted as is. Didn't need to stop the reactor as others have suggested. 

I had a slightly different issue, but writing it here just in case it helps someone. If running multiplex sockets, you need to close symbol (e.g. 'eosusdt@trade') individually, you can't pass in the entire conn_key to stop_socket(). This at least wasn't obvious to me. When I individually cycled through each pair, ran bm.close() and restarted the multiplex socket, everything worked fine.

**Comment by youstanzr** [comment]
I've had the same issue as I couldn't restart any socket that I disconnected. Following the snippet given in the original question
```
bm = BinanceSocketManager(client)
conn_key = bm.start_trade_socket('BNBBTC', process_message)
bm.start()
bm.close()
bm = BinanceSocketManager(client)
conn_key = bm.start_trade_socket('BNBBTC', process_message)
bm.start()
```
The problem with this is that bm.start() was called after it was already started. The BinanceSocketManager is just a manager for sockets. When you start a socket it gets added to the manager and after you add the sockets you want, you can start the manager. When attempting to restart the socket, you only close the sockets but keep the manager is still alive which means you don't need to start it again using bm.start(). So, here is the new code
```
bm = BinanceSocketManager(client)  # init the manager
bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket manager
bm.start()  # started the manager
bm.close()  # closed the sockets handled by the manager
bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket manager
```
This way you shouldn't have any problems connecting and reconnecting to a socket

**Comment by CarretillaRoja** [comment]
Thanks, all. It worked for me. Here is with a slight modification so it can stop after some time:

`from binance.client import Client
from binance.websockets import BinanceSocketManager
import datetime

api_key=''
api_secret=''
client = Client(api_key, api_secret)

def process_message(message):
    datos=message['data']
    print("got ticker message: {}".format(datos['s'])) 
    #
    # Here main code
    #
    if datetime.datetime.now() > stop:
        print('closing socket')
        bm.close()
        bm.start_multiplex_socket(coins_lower, process_message)
        clock_reset()

def clock_reset():
    global stop
    stop = (datetime.datetime.now() + datetime.timedelta(seconds=15)) 

coins_lower=['xlmbtc@trade', 'xrpbtc@trade', 'ethbtc@trade']

clock_reset()
bm = BinanceSocketManager(client)
bm.start_multiplex_socket(coins_lower, process_message)
bm.start()
bm.close()
bm.start_multiplex_socket(coins_lower, process_message)`

**Comment by ikubay** [comment]
Thanks to everyone for the help, there are multiple solutions here that work along with explanations as to why.

**Comment by iUmarov** [comment]
I tried the solutions given above, but not always these solutions could reconnect. I end up having a cron job that checks for the timestamp of last received data. If timestamp of last received data is old, then it kills script with PID and restarts it.

**Comment by dashko** [comment]
Indeed, did not work for me either. Implementing the solution of iUmarov:
1. started a process
2. if no message in 60 secs
3. kill the process and start again

**Comment by MSigno** [comment]
Same problem here. The 'kill process' solution is not viable for me as this is run as a thread concurrently with others, within the same python program. Any other solution?

**Comment by mkjmkjmkj** [comment]
Same problem here. Restart is not reliable, having the process killed and restarted from outside is not feasible (neither is it a proper solution). Does anyone know the cause for this behavior?

**Comment by pisulski** [comment]
> I've had the same issue as I couldn't restart any socket that I disconnected. Following the snippet given in the original question
> 
> ```
> bm = BinanceSocketManager(client)
> conn_key = bm.start_trade_socket('BNBBTC', process_message)
> bm.start()
> bm.close()
> bm = BinanceSocketManager(client)
> conn_key = bm.start_trade_socket('BNBBTC', process_message)
> bm.start()
> ```
> 
> The problem with this is that bm.start() was called after it was already started. The BinanceSocketManager is just a manager for sockets. When you start a socket it gets added to the manager and after you add the sockets you want, you can start the manager. When attempting to restart the socket, you only close the sockets but keep the manager is still alive which means you don't need to start it again using bm.start(). So, here is the new code
> 
> ```
> bm = BinanceSocketManager(client)  # init the manager
> bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket manager
> bm.start()  # started the manager
> bm.close()  # closed the sockets handled by the manager
> bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket manager
> ```
> 
> This way you shouldn't have any problems connecting and reconnecting to a socket

That doesnt work for me.

**Comment by diazagasatya** [comment]
I've tried the solution from above:
```
Any other solutibm = BinanceSocketManager(client)  # init the manager
bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket manager
bm.start()  # started the manager
bm.close()  # closed the sockets handled by the manager
bm.start_trade_socket('BNBBTC', process_message)  # start a new socket for the socket managerons? 
```
It still doesn't work overtime, any other approach for this issue?

**Comment by JosephLeon13** [comment]
Same issue here
raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once


```    # Initializes websocket stream
    def start_websocket(self):
        # Clean and prepare list of pairs for socket stream
        crypto = [f"{trading_pair.lower()}@kline_{self.interval}" for trading_pair in self.pair_list]
        # Streams pairs sent in list
        # Contains callback to handle data after each request
        self.connection_key = self.user_socket.start_multiplex_socket(crypto, self.socket_manager)
        # Start web socket
        self.user_socket.start()

    # Initializes websocket stream
    def stop_websocket(self):
        # Stop web socket
        self.user_socket.stop_socket(self.user_socket)```

**Comment by ZENALC** [comment]
Same issue here. Price does not update after about 2 hours on my end. It just keeps showing the old values.

**Comment by JosephLeon13** [comment]
I ended up rebuilding the asyncio version of the package. The maintainers version had some extra steps that weren't required.

**Comment by JosephLeon13** [comment]
```import asyncio
import websockets
import json

class WebSocketServer():
    
    STREAM_URL = 'wss://stream.binance.com:9443/'
    MAX_RECONNECTS = 5
    MAX_RECONNECT_SECONDS = 60
    MIN_RECONNECT_WAIT = 0.1
    TIMEOUT = 5
    
    def __init__(self, path, callback, prefix='ws/'):
        self.socket = None
        self.path = path
        self.prefix = prefix
        self.callback = callback
        self.connect()
        
    def connect(self):
        asyncio.ensure_future(self.consume())
        
    async def consumer_handler(self, websocket):
        async for message in websocket:
            self.callback(json.loads(message))
            
    async def consume(self):
        websocket_resource_url = f"{self.STREAM_URL}{self.prefix}{self.path}"
        
        async with websockets.connect(websocket_resource_url) as websocket:
            self.socket = websocket
            
            await self.consumer_handler(websocket)
            
class WebSocketManager():
    WEBSOCKET_DEPTH_5 = '5'
    WEBSOCKET_DEPTH_10 = '10'
    WEBSOCKET_DEPTH_20 = '20'

    user_timeout = 30 * 60  # 30 minutes

    def __init__(self, client, loop):
        self.connections = {}
        self.user_timer = None
        self.user_listen_key = None
        self.user_callback = None
        self.client = client
        self.loop = loop
    
    async def start_socket(self, path, callback, prefix):
        if path in self.connections:
            return False

        self.connections[path] = WebSocketServer(path, callback, prefix)

        return path
    
    async def start_multiplex_socket(self, streams, callback):
        path = f"streams={'/'.join(streams)}"
        await self.start_socket(path, callback, 'stream?')
        
        return path

**Comment by JosephLeon13** [comment]
```    
   # Cleans data and writes data to csv file
    def socket_manager(self, payload):
        data = self.web_socket_data(self.pair_list, self.interval, self.df_manager, payload)
        # Check result and assing dataframe
        if data["df"] is not None:
            self.df_manager[data["crypto"]] = data["df"]

    # Initializes websocket stream
    async def start_websocket(self):
        now = datetime.now()

        scheduled_run = now.replace(minute=int(now.minute / 5) * 5, second=0, microsecond=0) + timedelta(minutes=5)
        timer = (scheduled_run - now).total_seconds()
        
        self.loop.call_later(timer, self.init_loop, self.loop)
        # Clean and prepare list of pairs for socket stream
        crypto = [f"{trading_pair.lower()}@kline_{self.interval}" for trading_pair in self.pair_list]
        # WebSocket Manager 
        # Streams pairs sent in list
        # Contains callback to handle data after each request
        await self.user_socket.start_multiplex_socket(crypto, self.socket_manager)

**Comment by dpcwee** [comment]
Try remove bm, client and etc var. It helped me.

`while True: 
    reconnect = 0
    num_conn = 0
    while True:
        try:
            client = Client(str(c_api), str(c_secret))
            tickers = client.get_ticker()
            balances = client.get_account()['balances']
            exchange = client.get_exchange_info()['symbols']
            bm = BinanceSocketManager(client)
            conn_start_user_socket = bm.start_user_socket(start_user_socket)
            conn_search_pair = bm.start_ticker_socket(search_pair)
            if num_conn == 0:
                bm.start()
                filter_trade_pairs()
                num_conn += 1
            break
        except:
            reconnect += 1
    time.sleep(86000)
    bm.stop_socket(conn_start_user_socket)
    bm.stop_socket(conn_search_pair)
    **del client, tickers, balances, exchange, bm, conn_start_user_socket, conn_search_pair**
    time.sleep(5)`

**Comment by dpcwee** [comment]
Try remove bm, client variables. It helped me.
```py
while True:
    try:
        client = Client(str(c_api), str(c_secret))
        bm = BinanceSocketManager(client)
        conn_start_user_socket = bm.start_user_socket(start_user_socket)
        conn_search_pair = bm.start_ticker_socket(search_pair)
        # other user start_socket's
        bm.start()
        # other user function
        break
    except:
        pass
time.sleep(86000)
bm.stop_socket(conn_start_user_socket)
bm.stop_socket(conn_search_pair)
bm.close()

# delete all variables
del client, bm, conn_start_user_socket, conn_search_pair
```

**Comment by AGIinspired** [comment]
so, i dont know if this helps considering the op is using BinanceSocketManager
but I found using ThreadedSocketManager or " from binance import ThreadedWebsocketManager "
and then using this code to initiate: 
     
        sym1_price = {'time': 'str', 'price': 'str', 'error': False, 'change': False} //I use change for bool purposes in rest of code
        
        def sym1_trade_history(msg):
                if msg['e'] != 'error':
                    sym1_price['time'] = msg['E']
                    sym1_price['price'] = msg['c'
                    sym1_price['error'] = False
                    sym1_price['change'] = True
                else:
                    sym1_price['error'] = True
        
        bsm = ThreadedWebsocketManager()
        bsm.start()
        bsm.start_symbol_ticker_socket(callback=sym1_trade_history, symbol=title)

then if wanting to close and restart:

        bsm.stop()
        bsm = ThreadedWebsocketManager()
        bsm.start()
        bsm.start_symbol_ticker_socket(callback=sym1_trade_history, symbol=title)

Major imposter syndrome with this answer but it works for me
