### ISSUE TITLE
List of latest trades

### ISSUE THREAD

**Issue by Michelgard** [sammchardy/python-binance#203]
Hello,
How to have the list of the last trades (buy / sell) since a given date. Without going through several API requests which then make a mistake of time (1021 INVALID_TIMESTAMP)
Thank you

**Comment by DipDuo** [comment]
Been looking for something like this as well. I need to get the recent trades without knowing the coin or market.
I also really do not want to iterate through all the options. I would quickly reach the request limit with the number of users on my app.
