### ISSUE TITLE
Problem with pip install python-binance

### ISSUE THREAD

**Issue by aaasakkura** [sammchardy/python-binance#206]
Hi, I installed Microsoft Visual Studio 2015, then 2017, and problem is still here.
I see red text with "Twisted" ending in the cmd.
binance.client doesn't exist for python..
Windows 10, 64 bit, python 3.6.4
Thank you!

**Comment by DipDuo** [comment]
I got this same issue. Look harder in the return.
You're missing a dependency.

I'm 75% sure its this:
http://landinghub.visualstudio.com/visual-cpp-build-tools

but like i said, it's in the return of "pip install python-binance" in powershell (admin)

**Comment by aaasakkura** [comment]
I have istalled Visual Studio 17

**Comment by DipDuo** [comment]
can you post the entire return of "pip install python-binance"?

**Comment by aaasakkura** [comment]
Command "c:\users\vishniakov\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VISHNI~1\\AppData\\Local\\Temp\\pip-build-o6uovkfi\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record C:\Users\VISHNI~1\AppData\Local\Temp\pip-7g7f27qe-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\VISHNI~1\AppData\Local\Temp\pip-build-o6uovkfi\Twisted\

**Comment by tablego00** [comment]
try to install twisted using wheel , then install python-binance again: 
https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted

**Comment by pandaoknight** [comment]
If you are developing on Windows like me. That you should install Twisted by wheel

**Comment by IbnNafis007** [comment]
Just install matplotlib and mpl-finance.

**Comment by sheeeev66** [comment]
Hey I am trying to install in on vscode but it always gives me this error. no matter what I try to install it gives me the same error: 
`Fatal error in launcher: Unable to create process using '"c:\users\roi\appdata\local\programs\python\python38-32\python.exe"  "C:\Users\Roi\AppData\Local\Programs\Python\Python38-32\Scripts\pip.exe" install python-binance': The system cannot find the file specified.   `

how can I fix this?

**Comment by arlucio** [comment]
`pip install python-binance` was not working because of twisted
tried to install twisted alone using pip dind't worked as well
so I used  `conda install twisted` and then `pip install python-binance`
and it installed sucessfully

**Comment by sheeeev66** [comment]
Yay thanks!!!

**Comment by jehoiakimkingne** [comment]
Thanks @arlucio !

**Comment by cryptokcmo** [comment]
@arlucio Thanks helped a lot was stuck for 2 days..

**Comment by sheeeev66** [comment]
@cryptokcmo lol I was stuck for a week
