### ISSUE TITLE
STOP_LOSS TAKE_PROFIT orders

### ISSUE THREAD

**Issue by akaniklaus** [sammchardy/python-binance#207]
Hello,

I was unable to understand how those works based on the documentation and I couldn't find any single example over Github where these orders are utilized so I guess that they can be unclear for other ppl as well. I want to basically buy an asset but sell it automatically when the price increase by x% using a single order. If I am able to define a stop loss simultaneously (selling when the price decrease by y%) that would even be better but I am guessing that's not possible. I would be glad if you can explain.

Sincerely,
Kamer

**Comment by michja** [comment]
Hey,

It's not possible. What you're describing is called a one cancels other (OCO) order which binance doesn't support. Bitfinex can do it. Maybe some other sites, I'm not sure. 

If you're collecting current price data in python you can calculate which of the two conditions is closer to being met and manually place the corresponding trade, then if the market moves back you cancel and place the other order. It's not perfect but better than not having it. 

Note: a naive implementation could cause you to place and cancel a tonne of trades if a market is hovering at the midpoint between your two conditions, flicking from one to the other with each data point that comes through.

**Comment by akaniklaus** [comment]
@michja In that case, can you please explain me what STOP_LOSS and TAKE_PROFIT order types over Binance does? especially what is their difference? What would happen if I use either of them while giving a BUY_LIMIT or SELL_LIMIT order?

**Comment by michja** [comment]
Sorry my answer was a bit unclear. Stop loss, take profit do what you think
they do. Sell if < price or > price. What you can't do is place both orders
at once because the funds get locked when you place the first order so you
don't have the balance to place the other.
