### ISSUE TITLE
Get current open orders without symbol

### ISSUE THREAD

**Issue by dade80vr** [sammchardy/python-binance#208]
Hi guys, great work.
Is it possible to get all open orders without provide any symbol?

Now i need symbol
`orders = client.get_all_orders(symbol='BNBBTC')`

Official API say yes, https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#current-open-orders-user_data

Thank you, bye.

**Comment by michja** [comment]
Hey,

Try client.get_open_orders()

.get_all_orders is for something different. 
It includes cancelled and filled orders, so you have to give a symbol to narrow down your request a bit

**Comment by dade80vr** [comment]
Yes, it works, confused a function line :) Sorry

**Comment by saidab71** [comment]
how can I import that client from binance.us not binance.com?
