### ISSUE TITLE
API DELETED :0

### ISSUE THREAD

**Issue by bestinthewest** [sammchardy/python-binance#209]
so i decided to delete my profit trailer as i ended up with multiple downloads of profit trailer i had files everywhere. i started again redownloaded pt put my licence key in and tradeing api key and now it doesnt work.
will Profit trailer issue me a new licence api?

**Comment by sammchardy** [comment]
Hi @bestinthewest this library is not associated with profit trailer. Best to ask them, whoever they are.

**Comment by bestinthewest** [comment]
ok thank you
