### ISSUE TITLE
enums WEBSOCKET_DEPTH_20 was wrong

### ISSUE THREAD

**Issue by jianglijie** [sammchardy/python-binance#21]
in enums file, the `WEBSOCKET_DEPTH_20` is 5 not 20. and can i config it by myself? when i use `bm.start_depth_socket(symbol='BTCUSDT', depth='20, callback=depth_tick)` it cannot work

**Comment by sammchardy** [comment]
@jianglijie I have released v0.3.8 which fixes the value of `WEBSOCKET_DEPTH_20`.
When starting a depth socket you can send any integer value through as a `depth`. Whether Binance supports that or not is up to them.
