### ISSUE TITLE
APIError: code=1100. Illegal characters found in parameter 'price'

### ISSUE THREAD

**Issue by Obehi** [sammchardy/python-binance#212]
Hi,

I seem to have a problem using small floats as parameters with the Client.create_order() function.
It seems like if the float is small enough to be printed as scientific notation(with the print() function), I get an APIError:
BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
I believe the illegal characters are 'e-'

for example: 
This works:
client.create_order(symbol = 'STORMETH', price = '0.0004252')
But if I add one zero:
client.create_order(symbol = 'STORMETH', price = '0.00004252')
I get an error.

coincidentally
print(0.0004252) prints >> 0.0004252 
print(0.00004252) prints >>  4.252-05

I looked into the Client class and it looks like the request parameter gets sent in the scientific notation  format aswell. This is a part of the kwargs dictionary in the _request function, just before the request:
{'data': [('newOrderRespType', 'FULL'), ('price', 4.288e-05), ('quantity', 817), ('recvWindow', 10000), ('side', 'SELL'), ('stopPrice', 4.328e-05)

I believe this is a problem on my end, since I have not seen any other complaints, but I cant find a solution.
Any tips?

-Stian

**Comment by sammchardy** [comment]
Hi @Obehi 

Try formatting your price like

```
precision = 8
price = 0.0004252
price_str = '{:0.0{}f}'.format(price, precision)
```

Send the price_str as the parameter.

Then just change the precision based on the requirement for the trading pair.

**Comment by Obehi** [comment]
Yea, that worked. Easy fix. Thanks!

**Comment by kinucris** [comment]
Hi
I have the same error, but I do understand whats you make to fix it?

I will open a client.py file but nothing to edit, help?

**Comment by Obehi** [comment]
This was quite some time ago so don't know how much I can help, but can you share some code?

**Comment by safciplak** [comment]
```
def _buy_alt(self, origin_coin: Coin, target_coin: Coin):
        """
        Buy altcoin
        """
        trade_log = self.db.start_trade_log(origin_coin, target_coin, False)
        origin_symbol = origin_coin.symbol
        target_symbol = target_coin.symbol

        with self.cache.open_balances() as balances:
            balances.clear()

        origin_balance = self.get_currency_balance(origin_symbol)
        target_balance = self.get_currency_balance(target_symbol)
        from_coin_price = self.get_ticker_price(origin_symbol + target_symbol)
        **from_coin_price_s = "{:0.0{}f}".format(from_coin_price, 8) // i added this line**

        order_quantity = self._buy_quantity(origin_symbol, target_symbol, target_balance, **from_coin_price_s**) // changed last param
        self.logger.info(f"BUY QTY {order_quantity} of <{origin_symbol}>")
```

**Comment by jlixfeld** [comment]
print("...") all of the variables that make up your API calls and I'm sure you will find the cause of the error.
