### ISSUE TITLE
Aggregate trades list startTime

### ISSUE THREAD

**Issue by kieranflynn** [sammchardy/python-binance#214]
I wish to use client.get_aggregate_trades to return all trades over the past hour, by default this returns 500 trades.

How can I use startTime to achieve this end? What format / timezone should it be in? 

Is endTime also required? Or does it default to the present if it is not specified?

**Comment by sammchardy** [comment]
The format should be in UTC. If you specify a date like "1st Jan 2018" it will assume UTC.

endTime is not required, by default it fetches everything up until now.
