### ISSUE TITLE
Fault with aggregate_trade_iter

### ISSUE THREAD

**Issue by kieranflynn** [sammchardy/python-binance#215]
print datetime.utcnow() currently gives me: 2018-03-15 02:56:43.517000

When I attempt this:

agg_trades = client.aggregate_trade_iter(symbol='ETHBTC', start_str='0253')
for trade in agg_trades:
    print(trade)

I receive this error:

BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'startTime'; legal range is '^[0-9]{1,20}$'.

**Comment by kieranflynn** [comment]
print datetime.utcnow() currently gives me: 2018-03-19 00:16:57.887000

When I attempt this:

`agg_trades = client.aggregate_trade_iter(symbol='ETHBTC', start_str='0010')
for trade in agg_trades:
    print(trade)`

This is the complete error message I get:

---------------------------------------------------------------------------
BinanceAPIException                       Traceback (most recent call last)
<ipython-input-6-03e16d3b1350> in <module>()
      1 agg_trades = client.aggregate_trade_iter(symbol='ETHBTC', start_str='0010')
----> 2 for trade in agg_trades:
      3     print(trade)

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in aggregate_trade_iter(self, symbol, start_str, last_id)
    625                     symbol=symbol,
    626                     startTime=start_ts,
--> 627                     endTime=start_ts + (1000 * 86400 / 2))
    628             for t in trades:
    629                 yield t

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in get_aggregate_trades(self, **params)
    574 
    575         """
--> 576         return self._get('aggTrades', data=params)
    577 
    578     def aggregate_trade_iter(self, symbol, start_str=None, last_id=None):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _get(self, path, signed, version, **kwargs)
    204 
    205     def _get(self, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):
--> 206         return self._request_api('get', path, signed, version, **kwargs)
    207 
    208     def _post(self, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _request_api(self, method, path, signed, version, **kwargs)
    178         uri = self._create_api_uri(path, signed, version)
    179 
--> 180         return self._request(method, uri, signed, **kwargs)
    181 
    182     def _request_withdraw_api(self, method, path, signed=False, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _request(self, method, uri, signed, force_params, **kwargs)
    173 
    174         response = getattr(self.session, method)(uri, **kwargs)
--> 175         return self._handle_response(response)
    176 
    177     def _request_api(self, method, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _handle_response(self, response)
    197         """
    198         if not str(response.status_code).startswith('2'):
--> 199             raise BinanceAPIException(response)
    200         try:
    201             return response.json()

BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'startTime'; legal range is '^[0-9]{1,20}$'.

**Comment by kieranflynn** [comment]
I have just imported parse from dateparser.

This code:

x = parse('5 mins ago UTC')
str(x)

gives this result:

'2018-03-19 00:22:53.579000+00:00'

When I attempt this:

agg_trades = client.aggregate_trade_iter(symbol='ETHBTC', start_str=str(x))
for trade in agg_trades:
    print(trade)

I receive this error:

---------------------------------------------------------------------------
BinanceAPIException                       Traceback (most recent call last)
<ipython-input-25-a604cc8204a0> in <module>()
      2 
      3 agg_trades = client.aggregate_trade_iter(symbol='ETHBTC', start_str=str(x))
----> 4 for trade in agg_trades:
      5     print(trade)

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in aggregate_trade_iter(self, symbol, start_str, last_id)
    625                     symbol=symbol,
    626                     startTime=start_ts,
--> 627                     endTime=start_ts + (1000 * 86400 / 2))
    628             for t in trades:
    629                 yield t

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in get_aggregate_trades(self, **params)
    574 
    575         """
--> 576         return self._get('aggTrades', data=params)
    577 
    578     def aggregate_trade_iter(self, symbol, start_str=None, last_id=None):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _get(self, path, signed, version, **kwargs)
    204 
    205     def _get(self, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):
--> 206         return self._request_api('get', path, signed, version, **kwargs)
    207 
    208     def _post(self, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _request_api(self, method, path, signed, version, **kwargs)
    178         uri = self._create_api_uri(path, signed, version)
    179 
--> 180         return self._request(method, uri, signed, **kwargs)
    181 
    182     def _request_withdraw_api(self, method, path, signed=False, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _request(self, method, uri, signed, force_params, **kwargs)
    173 
    174         response = getattr(self.session, method)(uri, **kwargs)
--> 175         return self._handle_response(response)
    176 
    177     def _request_api(self, method, path, signed=False, version=PUBLIC_API_VERSION, **kwargs):

C:\Users\kieran\Anaconda2\lib\site-packages\binance\client.pyc in _handle_response(self, response)
    197         """
    198         if not str(response.status_code).startswith('2'):
--> 199             raise BinanceAPIException(response)
    200         try:
    201             return response.json()

BinanceAPIException: APIError(code=-1127): More than 1 hours between startTime and endTime.

**Comment by tamycova** [comment]
@kieranflynn I fixed this problem in #222 , you can check the files changed.

**Comment by kieranflynn** [comment]
Changes from #222 solve this issue.
