### ISSUE TITLE
Need help with Depth orders  using websockets

### ISSUE THREAD

**Issue by ArjulaRanjithReddy** [sammchardy/python-binance#218]
Dear All, I would appreciate if anybody can help me with how to get the depth order book for all symbols instead of calling DepthCachemanager for each symbol separately. I want to pull all the depth order book for all symbols at once. I have tried multiplex socket, but it is not working as I expected. Thank you in advance...!!

**Comment by snapo** [comment]
Im currently working on the same problem this is my try:

```
import time
import settings
from binance.client import Client
from binance.depthcache import DepthCacheManager
client = Client(settings.pubkey, settings.privkey)

symbols=['BTCUSDT', 'ETHUSDT', 'NEOUSDT', 'LTCUSDT', 'ETHBTC', 'LTCBTC', 'NEOBTC', 'LTCETH', 'NEOETH']

def process_depth(depth_cache):
    if depth_cache is not None:
        print("symbol {}".format(depth_cache.symbol) + " - BIDS: " + ''.join(str(e) for e in depth_cache.get_bids()[:1]) + " - ASKS: " + ''.join(str(e) for e in depth_cache.get_asks()[:1]))
    else:
        print("error")


for symbol in symbols:
    dcm = DepthCacheManager(client, symbol, callback=process_depth, refresh_interval=10)


depth_cache = dcm.get_depth_cache()
```


Hope it helps you... i still have the problem that it does not output it every 10 seconds....
Currently i dont know how i can solve that....
