### ISSUE TITLE
Shouldn't  DepthCacheManager._first_update_id be updated each time a new depth arrives?

### ISSUE THREAD

**Issue by duduzhu** [sammchardy/python-binance#22]
att?

**Comment by sammchardy** [comment]
This may be required if you expect socket events to be received out of order.

If that is the case then you would be ignoring an event. Ignoring or actioning the event causes issues either way, and the depth cache would be incorrect.

It is used here to ignore any events that are before the initial order book fetch.

**Comment by Beskhue** [comment]
Perhaps a check should be built to make sure the order book does not get skewed, as per [Binance's documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/0bdfec264ba5ac2d741d9a78c028ef1ccd3a241d/web-socket-streams.md#how-to-manage-a-local-order-book-correctly) (point 6).

**Comment by Beskhue** [comment]
I made an initial PR to start to address this issue, see #55.

**Comment by sammchardy** [comment]
Merged pull request with updates, thanks @Beskhue
