### ISSUE TITLE
error -1013 msg filter failrue LOT_SIZE

### ISSUE THREAD

**Issue by nihow666** [sammchardy/python-binance#23]
Hi guys, i want sell  ETH and give me error -1013 msg filter failrue LOT_SIZE, but if i make it manual on webpage it works normaly

**Comment by sammchardy** [comment]
Hi @nihow666 this is a response from the Binance server indicating that you are using too much precision for your price or amount. Some pairs only allow a whole number,  and some 6 digits etc.

If you use the new `get_exchange_info()` endpoint you can find the details about precision for each pair.
