### ISSUE TITLE
Strange price returned by order

### ISSUE THREAD

**Issue by csdenboer** [sammchardy/python-binance#230]
`{'fills': [{'commissionAsset': 'BNB', 'price': '0.00112970', 'qty': '0.87000000', 'commission': '0.00033109'}], 'timeInForce': 'FOK', 'executedQty': '0.87000000', 'status': 'FILLED', 'type': 'LIMIT', 'symbol': 'NEBLBTC', 'origQty': '0.87000000', 'orderId': 12265292, 'price': '0.00115390', 'side': 'BUY'}`

How is the price of an order calculated? As far as I know the price should be 0.87000000 * 0.00112970 = 0.000982839. On what is the price 0.00115390 based? 

When I check the order by logging in on binance it tells me 'total: 0.00098283 BTC'. This is also confusing, because 0.000982839 should be rounded to 0.00098284 right?

**Comment by ThomasHuw** [comment]
I believe 0.00115390 (a) is the price you sent to the API. You posted is a limit buy order and the lowest ask price at the time was 0.00112970 (b) - Your order was executed at the lower price (a) and this is displayed in 'fills'

**Comment by csdenboer** [comment]
Thanks, I see that that is indeed true. Do you also know the answer to the rounding question?
