### ISSUE TITLE
How to listen to multiple streams of same coin, at different intervals using websocket?

### ISSUE THREAD

**Issue by slix88** [sammchardy/python-binance#234]
Hi

Firstly I would like to thank Sam a million times for this wonderful wrapper!

My question is basically how I can open multiple streams and listen to them at different intervals. Using this as an example, I am initiating a multiplex socket for 'ethbtc@ticker' and 'neobtc@ticker'. I tried creating 5 threads, with each thread opening a unique multiplex socket on the two streams above (have verified with bm.ident that each of the 5 are unique). Have attempted to use `time.sleep(0.2)` in order to space each request out but in the end, all 5 sockets listen to the same stream one after another (a few ms delay). Oddly, the ethbtc@ticker and neobtc@ticker streams are spaced out (about 0.5s between each one).

Is this a limitation of the code, of the exchange's websocket or is there a way to implement this relatively easily? Curious to know if it's possible and if it's been done.

Many thanks in advance!

**Comment by sammchardy** [comment]
Not quite sure I understand the question.

When you open a websocket Binance will push you data when it is available. Generally this will be once per second.

You can multiplex streams into one as well if that fits your use case, read more about that in the docs here https://python-binance.readthedocs.io/en/latest/websockets.html#id1
