### ISSUE TITLE
callback with function arguments

### ISSUE THREAD

**Issue by willgu903** [sammchardy/python-binance#235]
I did a little bit research so hopefully my question is not too dumb.

Right now the callback function can only be defined with one input argument `message`. I was wondering if we can use other function arguments with the defined callback functions. for example, the classical `process_message` would be something like `process_message(msg, order_book, ...)` and then register it to the websocket manager.

**Comment by sammchardy** [comment]
Hi @gdm-willgu,

Currently you can't do that as you have noted, what use case do you have for that?

Generally the process_message callback function would be within some kind of scope of other variables or objects you want to access.

You can see the [DepthCacheManager](https://github.com/sammchardy/python-binance/blob/49b2cca7bf6df8e077e743a715623f1232547d06/binance/depthcache.py#L119) class and how it utilises a websocket connection and callback within the class so you have access to all the class variables.

**Comment by gdm-willgu** [comment]
I'm currently defining the callback function at module level. I guess I _could_ initiate all the variables at module level as well, and I can't think of a case for now when no work-around exists.
