### ISSUE TITLE
after install, no module named client

### ISSUE THREAD

**Issue by number9387** [sammchardy/python-binance#236]
after installing used the following code from the examples:

> from binance.client import Client

got the following:

> result is "ImportError: No module named client"

**Comment by gdm-willgu** [comment]
do you have a local directory called `binance`?

**Comment by number9387** [comment]
No.  The install didn't appear to create one.

**Comment by sammchardy** [comment]
@number9387 do you have a python file binance.py or a directory in the same path there that is causing the conflict?

If `import binance` works then you could try printing the location like

```
import binance
print(binance.__file__)
```

to see what the issue is.

**Comment by number9387** [comment]
@sammchardy You totally nailed it, now I understand what @gdm-willgu was trying to say.  I can't believe I didn't notice the file conflict.  Solved.  Thank you.

**Comment by djangoboy18feb2018** [comment]
i am having the same issue..
by printing binance.__file__ gives me a '/home/djangoboy/crypto_bot_env_3.6/lib/python3.6/site-packages/binance.py' as crypto_bot_env_3.6 is the environment...but i don't know what can i do next to resolve it.. please some one help me.. Thank you!

**Comment by andrewlam109** [comment]
same here whats the way to resolve this please?
