### ISSUE TITLE
Calculating the EMA

### ISSUE THREAD

**Issue by Bl4ckDoT** [sammchardy/python-binance#240]
Trying to implement a simple trading strategy that uses the EMA to trade and so the EMA is essential for everything else to work. I got my closing prices right (checked) and then went on to try and calculate the EMA. I get similar results with the official EMA calculated by binance on their website/client (and also tradingview) but my EMA is slightly off. 
![sublime_text_2018-04-07_11-54-09](https://user-images.githubusercontent.com/11063272/38457957-7d155ad4-3a65-11e8-8e0e-25f59e35f797.jpg)

As you can see in the picture, my result is different than the one from binance, I suspect that the cause for the disparity might be the weights -- but that is just speculation on my part. Thanks.

Edit: fixed by using Ta-Lib

**Comment by K-Kit** [comment]
Probably not the answer you're looking for but i'd just use TA-lib
https://github.com/mrjbq7/ta-lib
I was running into rounding errors when I was first calculating EMA however I was using a different method but might be worth a shot to do values * 10000, testlist / 10000
also why are you pointing to testlist[1] instead of testlist[0]? sorry if its obvious

**Comment by Bl4ckDoT** [comment]
Because testlist[0] will return the live EMA which is constantly changing on binance and so for demonstration purposes, it's easier with a closed candle. If it's not too much to ask, could you share the code on how you calculate the EMA using TA-lib? I'm not familiar with it and it might help other people with the same question. If not, that's okay thanks for the response anyway, very helpful.

**Comment by K-Kit** [comment]
from the readme on the github i linked:

import numpy as np

# note that all ndarrays must be the same length!
inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}

# uses close prices (default)
output = EMA(inputs, timeperiod=25)

# uses open prices
output = EMA(inputs, timeperiod=25, price='open')

**Comment by K-Kit** [comment]
lol didnt realize those were going to come out as headers

**Comment by janv93** [comment]
Binance seems to use an EMA smoothing factor of around 20. The charts seem similar then. Normal is a factor of 2.

**Comment by yumewebs** [comment]
Can you show me the code of how could you calc the EMAs? Thanks you so much
