### ISSUE TITLE
Connection related errors

### ISSUE THREAD

**Issue by Bl4ckDoT** [sammchardy/python-binance#244]
Initially I was getting this error:
![applicationframehost_2018-04-10_19-18-42](https://user-images.githubusercontent.com/11063272/38588496-305f191e-3cf4-11e8-8847-26be86ee1c82.jpg)

I tried synchronizing time by using an application that syncs time every 15 mins.

I also added recvWindow= 604800000 wherever I could (tried several delays). I tried client = Client(api_key,api_secret , {"verify": False, "timeout": 10000})

Which gave me an error that the connection was not secure or something like that. I switched it to client = Client(api_key,api_secret , {"verify": True, "timeout": 10000})

Now I'm getting a new error every 1-6h:

![code_2018-04-09_20-41-06](https://user-images.githubusercontent.com/11063272/38588617-d44b76f8-3cf4-11e8-972c-f12462ea40cb.jpg)

I've only been using python for a week or so and have tried searching on how to fix this problem but didn't find any solution that I could implement.

**Comment by nocciolate** [comment]
I am also getting the same, but just ignoring it with a "try - pass", but if there is an answer, I am definitely also interested.
