### ISSUE TITLE
install python-binance

### ISSUE THREAD

**Issue by scalpounet** [sammchardy/python-binance#246]
Hello, I installed Visual Studio Build Tools 2017 and tried pip install python-binance. 

I have the following message:   Failed building wheel for Twisted in the middle of the installation 

And at the end I have 

Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Pascal\\AppData\\Local\\Temp\\pip-build-j_mn0o78\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Pascal\AppData\Local\Temp\pip-zv1gwvc0-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Pascal\AppData\Local\Temp\pip-build-j_mn0o78\Twisted\ 

Is there anyone who would be kind to help me?

Many thanks,
Pascal

**Comment by ShervinDD** [comment]
I just got the same error when installing (pip install python-binance).

**Comment by scalpounet** [comment]
ShervinDD, thank you very much for your help, it works now. Many thanks for your time, I really appreciate the community

**Comment by Tuixote** [comment]
ShervinDD, thank you very much!

**Comment by HarveyWolfstein** [comment]
ShervinDD, thanks a lot.

**Comment by MathisPeyronne** [comment]
@ShervinDD, i love you so much. <3

**Comment by Seigneur774** [comment]
Thanks!!
