### ISSUE TITLE
binance order book - python 3.5

### ISSUE THREAD

**Issue by scalpounet** [sammchardy/python-binance#253]
Hi, I am getting the order book with the below code:

depth = client.get_order_book(symbol='XVGBTC')                          #get order book for selected coin
df_depth = pd.DataFrame(depth)                                                     #transform order book datadf
df_depth_ask = df_depth.iloc[:,0]                                                       #select the first column (ask)
df_depth_ask = df_depth_ask.apply(lambda x: pd.Series(str(x).split(',')))     #split df_depth_ask in 3 cols 
df_depth_ask = df_depth_ask[df_depth_ask.columns[0:2]]                             #take the first two columns

I can't transform the data from the order book in "float". It reads them as a dictionary. Can anyone help what to do 

Many thanks

**Comment by gdm-willgu** [comment]
from the official [api doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md), `depth` looks like this

```
{
  "lastUpdateId": 1027024,
  "bids": [
    [
      "4.00000000",     // PRICE
      "431.00000000",   // QTY
      []                // Ignore.
    ]
  ],
  "asks": [
    [
      "4.00000200",
      "12.00000000",
      []
    ]
  ]
}
```
so you can't just call `df_depth = pd.DataFrame(depth)`

**Comment by Roibal** [comment]
I believe, based on the info provided by @gdm-willgu , second line/third line should be:

`df_depth_asks = pd.DataFrame(depth['asks'])`

and similarly 

`df_depth_bids = pd.DataFrame(depth['bids'])`

**Comment by scalpounet** [comment]
Thank you for your answers, I have created the functions below:

def get_order_book_val(ccy):
    depth = client.get_order_book(symbol=ccy)
    df_depth = pd.DataFrame(depth) 
    return df_depth

def fct_order_book_val(df,col):
    df_depth_ask = df[col]
    df_depth_ask = df_depth_ask.apply(lambda x: pd.Series(str(x).split(',')))
    df_depth_ask_price = df_depth_ask[0]
    df_depth_ask_price = df_depth_ask[0].apply(lambda x:float(x[2:12]))
    df_depth_ask_qty = df_depth_ask[1]
    df_depth_ask_qty = df_depth_ask_qty.apply(lambda x:float(x[2:12]))
    ask_bids_value = pd.DataFrame()
    ask_bids_value['value'] = df_depth_ask_price * df_depth_ask_qty
    value_col = ask_bids_value['value'].sum()
    return value_col

def get_bids_asks_ratio(ccy):
    col = 'bids'
    order_book_ccy = get_order_book_val(ccy)
    order_book_val_bids = fct_order_book_val(order_book_ccy,col)
    col = 'asks'
    order_book_val_asks = fct_order_book_val(order_book_ccy,col)
    ratio_bids_asks = order_book_val_bids/order_book_val_asks
    return ratio_bids_asks

client = Client(api_key, api_secret)                                               
ccy = 'LTCUSDT'
col = 'bids'
order_book_ccy = get_order_book_val(ccy)
order_book_val_bids = fct_order_book_val(order_book_ccy,col)
col = 'asks'
order_book_val_asks = fct_order_book_val(order_book_ccy,col)
