### ISSUE TITLE
Order price not correct

### ISSUE THREAD

**Issue by songer1993** [sammchardy/python-binance#254]
The market order price is always '0.00000000', for example: 

{'symbol': 'BTCUSDT', 'orderId': 87970972, 'clientOrderId': 'vNG6LpxYRwdz9X8MIGCzvV', 'transactTime': 1523993136813, 'price': '0.00000000', 'origQty': '0.01000000', 'executedQty': '0.01000000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY'}

**Comment by Roibal** [comment]
what is the function you are calling?

**Comment by songer1993** [comment]
I'm using order_market_buy() and order_market_sell().

**Comment by iUmarov** [comment]
I have the same issue when I call order_market_buy().

**Comment by songer1993** [comment]
I think it's probably due to Binance's API. I have used ccxt, the same problem exists there.
