### ISSUE TITLE
APIError(code=-1100): Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

### ISSUE THREAD

**Issue by psh6615** [sammchardy/python-binance#255]
from client import *                                    
api_key = ''
api_secret = ''
client = Client(api_key, api_secret)

sat_zec = decimal.Decimal(Z).quantize(decimal.Decimal('1.000000'))
zec_amount = decimal.Decimal('0.2')

    class BinaZecSell:
        def set_info(self, zec_amount, sat_zec):
            order = client.create_order(
              symbol = "ZECBTC",
              price = sat_zec,
              quantity = zec_amount,
              side = Client.SIDE_BUY,
              type = Client.ORDER_TYPE_LIMIT,              
              timeinForce = Client.TIME_IN_FORCE_GTC) 

File "C:\Users\esther\Anaconda3\Lib\idlelib\bitfinex_binance\client.py", line 170, in _handle_response raise BinanceAPIException(response) exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

---------------------------------------------------------------------------------------------------

I got the error message as above and I do not know what is wrong. The type of parameter 'quantity' is decimal, so I converted it into decimal type(decimal.Decimal('0.2'). But it says illegal characters found in parameter 'quantity'... As far as I know, the error message is given when other type of value is given to the parameter 'quantity' than decimal type. But I made it right. 

I am a beginner coder so if I have made it wrong, please understand and thanks in advance for the kind responses.

**Comment by rrodrig003** [comment]
I got that error too.

Resolved by first converting to float, and then correcting my unit parameter.. there was an error in my unit calculation, i.e. I calculated price instead of unit.. lastly, use the 'round' function to get the correct amount of decimals.

**Comment by psh6615** [comment]
Sorry for the late reply. Many thanks for your help. It was helpful :-)
 
-----Original Message-----

**Comment by kieranflynn** [comment]
I am unable to get any quantity to work so I have been testing simpley buying and selling the smallest possible quantity I can. I am attempting this and receive the same error as above:

client.order_market_sell(symbol='BTCUSDT', quantity=0.000001)

**Comment by nicoan777** [comment]
I got this error too. 
The problem was the float type with very small numbers, as you'd get scientific notation.

**Comment by NathanEzraSchmidt** [comment]
See `float` and `ceil` functions of [this module](https://github.com/NathanEzraSchmidt/Binance-Arbitrage-Bot/blob/master/binance_arb_bot.py) for converting any number to string while avoiding scientific notation.

**Comment by garbios** [comment]
qt= f"{qt:.9f}"
print(qt)
