### ISSUE TITLE
Import client problem

### ISSUE THREAD

**Issue by AdvancedVision** [sammchardy/python-binance#257]
I have an error whilest simple import: from binance.client import client
says importError: cannot import name 'client'
how can i pass this problem?

**Comment by AdvancedVision** [comment]
Guys. terribly sorry. Be watchfull when type all the object from library. It Case sensitive.
To agregate all the troubles with installing and using python-binance you should notice:
1. You must sure that you really has installed the python-binance (if its not installed so cannot be used). The most common trouble with installation on win 7\10 is the installer asks for "microsoft visual c++14v needed" and says error code 1. -> problem appears as twisted is not goes with the package (and it takes the wrong package when you try to "pip install twisted"). To solve it you should download the version of "twisted" for your Platform and install it as "pip install {twisted name that you downloaded}.whl"
2. There are several other libraries - must sure that you use python-binance (there is at least python-binance-api and its differs)
3. Must sure that all the letters written case sensitive (Client should be written with first big C, not client).
Thanks

**Comment by knowledgecomputer2018** [comment]
hi 
from binance import Client, ThreadedWebsocketManager, ThreadedDepthCacheManager
god willing
