### ISSUE TITLE
Avoid Connection pool is full, discarding connection: api.binance.com

### ISSUE THREAD

**Issue by LeoIannacone** [sammchardy/python-binance#259]
Hi,

how can I avoid this 

```
urllib3.connectionpool - Connection pool is full, discarding connection: api.binance.com
```

?

**Comment by wranai** [comment]
from requests.adapters import HTTPAdapter    
    client = BinanceClient(key, secret)
    client.session.mount('https://', HTTPAdapter(pool_maxsize = REALLY_BIG_POOL_SIZE))
