### ISSUE TITLE
client name

### ISSUE THREAD

**Issue by 8L08FISH** [sammchardy/python-binance#260]
#when i plug in my API info and try to call the site it I get that.#
NameError: name 'client' is not defined

#i put my keys in here and deleted the api_key etc...#
client = Client(api_key, api,_secret)

 I do have python-binance installed correctly, that was a battle. Im a noob to this, so any help would be greatly appreciated.

**Comment by p2psg** [comment]
Hi I am also exploring how to use this client library, and am also noob. I found this tutorial to be working fine. 
Remember to use double quotes for symbol (i.e trades = client.get_my_trades(symbol="ETHBTC") )

http://casualcrypto.tech/binance-api-and-python-part-1/
