### ISSUE TITLE
How to avoid API errors using except?

### ISSUE THREAD

**Issue by cc345** [sammchardy/python-binance#261]
One of the errors I keep running into is this:

`binance.exceptions.BinanceAPIException: APIError(code=-1000): An unknown error occured while processing the request.`

I was just wondering if there is a way to pass this in a try statement? Here is what I use to pass timeout errors.

```
from requests.exceptions import Timeout

try:
    #Insert code here
except Timeout:
    pass
```

Are there any except functions like " except Timeout" for the other error codes that I could use?

**Comment by Roibal** [comment]
you can just leave 'except' by itself 

try:
     code
except:
     pass

**Comment by wranai** [comment]
That `binance.exceptions.BinanceAPIException` is the name of the exception you're asking about, actually:

```python
try:
    stuff()
except binance.exceptions.BinanceAPIException as e:
    print(e)

**Comment by Chuox** [comment]
I try that and I only get "NameError: name 'binance' is not defined"

**Comment by Chuox** [comment]
I manage this to work

```
    try:
        SellSta=client.get_order(symbol=Symb,orderId=SellOrderNum,recvWindow=Delay)
    except Exception as e:
        print ("{}".format(e.status_code ))
        print ("{}".format(e.response ))
        print ("{}".format(e.code))
        print ("{}".format(e.message))
        print ("{}".format(e.request))
```
Now I'm trying to get different exceptions for differents errors

**Comment by olivierbl** [comment]
try importing all of binance not just client then:  except binance.exceptions.BinanceAPIException as e:

**Comment by kimchirichie** [comment]
closing because this is unrelated to lib. rather it is related to how to handle errors.

for clarity on above:
@Chuox you should have imported binance like 
`from binance import exceptions.BinanceAPIException`

**Comment by dvdkitay** [comment]
> closing because this is unrelated to lib. rather it is related to how to handle errors.
> 
> for clarity on above: @Chuox you should have imported binance like `from binance import exceptions.BinanceAPIException`

@[kimchirichie](https://github.com/kimchirichie) No bro... 

- [ ] from binance.exceptions import BinanceAPIException

**Comment by Shinizlc** [comment]
But how can I specify particular error(code)? For instance I get occasionally binance.exceptions.BinanceAPIException: APIError(code=-2010) error. How can I handle it?

**Comment by lindomar-oliveira** [comment]
> But how can I specify particular error(code)? For instance I get occasionally binance.exceptions.BinanceAPIException: APIError(code=-2010) error. How can I handle it?

@Shinizlc You can handle the error as follows:

```python
try:
    pass
except BinanceAPIException as err:
    if err.code == -2010:
        pass
    else:
        raise err

**Comment by Shinizlc** [comment]
@lindomar-oliveira  thank you a lot!
