### ISSUE TITLE
User listen key SHOULD NOT be deleted

### ISSUE THREAD

**Issue by wranai** [sammchardy/python-binance#264]
The user listen key is deleted upon closing the socket, but the key is shared between clients, so it has the unintended consequence that all clients (including the web client) stop receiving updates.

The offending line:

https://github.com/sammchardy/python-binance/blob/45f869b5636e34ae2d9fbd3928f62cd827e8f267/binance/websockets.py#L505

**Comment by wranai** [comment]
Yup. I just proposed an update to the documentation.

**Comment by sammchardy** [comment]
I've removed this line in v0.6.9
