### ISSUE TITLE
websocket user socket

### ISSUE THREAD

**Issue by thober35** [sammchardy/python-binance#266]
Hello,
I have an issue regarding the websocket:
Just a simple code:

```
def process_message(msg):
	print (msg)
	
def initiate():
	client = Client('key', 'secret')
	bm = BinanceSocketManager(client)
	conn_key = bm.start_user_socket(process_message)
	bm.start()

initiate()
```
but if i run this code the system returns no values. I've tried another socket e.g. start_ticket_socket it will work as intended.

Am I doing something wrong?
Thanks in advance!

**Comment by wranai** [comment]
Have you tried placing an order or cancelling one, e.g. from the web interface? The user socket doesn't return anything until there's something to return.

**Comment by GameOver51** [comment]
Hi, 
I faced this issue as well. Even I m placing order while running subscript websocket, but nothing response back.

**Comment by nikky78** [comment]
any news on the topic? cause i'm having the same...

**Comment by kbai** [comment]
Hi, change     STREAM_URL = 'wss://stream.binance.com:9443/'
to  'wss://stream.binance.us:9443/' would work if your account is on binance.us

**Comment by taylormcclenny** [comment]
I'm having an issue as well.  I'm running this socket and placing orders, there is no response through the socket.

Are any additional parameters/conditions needed to return a response?  Other than (1) having the start_user_socket() socket open and (2) placing orders?

**Comment by ddroguett** [comment]
from binance.client import Client
from binance.websockets import BinanceSocketManager

def process_message(msg):
	print (msg)
	
def initiate():
	client = Client('public', 'secret')
	bm = BinanceSocketManager(client)
	conn_key = bm.start_user_socket(process_message)
	bm.start()

salir = ''
while salir != 'q':
    salir = input("'q' for exit: ")

**Comment by ddroguett** [comment]
[binance_example.txt](https://github.com/sammchardy/python-binance/files/6439172/binance_example.txt)

>from binance.client import Client
>from binance.websockets import BinanceSocketManager

>def process_message(msg):
>>	print (msg)
	
>def initiate():
>>	client = Client('public', 'secret')
>>	bm = BinanceSocketManager(client)
>>	conn_key = bm.start_user_socket(process_message)
>>	bm.start()

>salir = ''
>while salir != 'q':
>>    salir = input(" 'q' for exit: ")
