### ISSUE TITLE
mini_sockets work on some intervals and not on others

### ISSUE THREAD

**Issue by uneasyguy** [sammchardy/python-binance#267]
from binance.client import Client
from binance.websockets import BinanceSocketManager

def process_message(msg):
    print("message type: {}".format(msg[0]['e']))
    print(msg)

if __name__ == "__main__":
	time_interval = 5000
	client = Client(None,None)
	bm = BinanceSocketManager(client)
	conn_key = bm.start_miniticker_socket(process_message, time_interval)
	bm.start()

This does not product output, but if i change time_interval to 1000 or 3000 it works just fine. The docs show 5000 as example given. Anyone have any insights on this? 

I understand mini_sockets aren't in the official Binance docs so sort of flying blind.

**Comment by frozenranger** [comment]
same problem

**Comment by chinnaxs** [comment]
Same problem here

**Comment by kimchirichie** [comment]
anyone wanna open a PR for this?
