### ISSUE TITLE
Websocket Account Update

### ISSUE THREAD

**Issue by delware1** [sammchardy/python-binance#269]
Hello,

I've noticed that there isn't a websocket stream similar to 
```
info = client.get_account()
```
Basically I want a constant update on available Asset Balances but the API takes to much time.

In the official API docs i found a user data stream;
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md
It is called the ``` outboundAccountInfo ```

Since I am not that familiar with API wrappers, how can I implement this stream? What has to be considered?

regards

**Comment by wranai** [comment]
It's the [user socket](https://python-binance.readthedocs.io/en/latest/websockets.html#id10).

**Comment by delware1** [comment]
I see so there is no other way to get my asset balances without risking time.
Thanks for clearing that up!

**Comment by delware1** [comment]
alright will try that thanks !
