### ISSUE TITLE
Enhancement - Example of how to maintain the correct state of the order book using the feeds

### ISSUE THREAD

**Issue by skeller88** [sammchardy/python-binance#27]
Either creating an example in this repo or referencing another would be awesome. 

For example, GDAX has [documentation](https://docs.gdax.com/#the-code-classprettyprintfullcode-channel) on how to get order book snapshots and then sync the "full" channel websocket feed data with the snapshot. 

Ideally Binance would have explained how to do this, but they don't. The [depth channel](https://www.binance.com/restapipub.html#depth-wss-endpoint) contains order book deltas, but it's unclear how you'd tell if those deltas are order book fills or cancellations, and how these deltas would reflect a partial fill. Also it looks like it's only possible to [get 100 order book entries](https://www.binance.com/restapipub.html#user-content-market-data-endpoints), so that's an interesting challenge of how to match up those 100 order book entries in the snapshot with the order book entries in the channel.

**Comment by sammchardy** [comment]
Hi @skeller88 I have saved some notes from Telegram around the Binance Depth Cache which may be helpful. I'm not completely sure what you're asking for though. Does my [DepthCache](https://github.com/sammchardy/python-binance/blob/4f1004dcf803feecb083d6fd1194b12c0a502805/binance/depthcache.py#L9) Class not follow this process? Or are you just interested in better documentation around it?

https://gist.github.com/sammchardy/5515afe1dff84475098f669a62558860

**Comment by skeller88** [comment]
Yes, that's helpful. I was initially confused until I realized that order book deltas are actually absolute, not relative. 

I'm confused by this statement in the Telegram notes: 

> But yes, if the order book shifts 500 levels up from when you got it, you will be missing levels.

If the order book shifted 500 levels up, does that mean 500 [price levels](https://en.wikipedia.org/wiki/Order_book_(trading)#Price_levels)? Wouldn't all of those shifts in price levels be sent through the depth channel?

 Your DepthCache class follows the process for keeping things in sync, yea. The only issue I see is since the initial order book snapshot you get only has a [depth of 10](https://github.com/sammchardy/python-binance/blob/4f1004dcf803feecb083d6fd1194b12c0a502805/binance/depthcache.py#L143), it's more likely that the depth channel will get deltas that are many levels away from the other orders in the DepthCache. For example, say the initial snapshot of bids is

49
...
40

The depth channel could get a bid for 56, and you wouldn't know that there are already bids for 52 and 53. That's not ideal because then you have a skewed view of the order book. So if it's not too much memory, getting a 100 level initial snapshot seems better. What do you think?

**Comment by sammchardy** [comment]
@skeller88 sorry I missed your comment, yes I'll have a look at increasing the depth of the initial fetch to improve that snapshot.

**Comment by sammchardy** [comment]
@skeller88 initial depth has been increased in later versions, also updated to open the socket and buffer messages before requesting book from REST API.
