### ISSUE TITLE
IndexError when asking for cryptocurrency Price

### ISSUE THREAD

**Issue by Esisxnem** [sammchardy/python-binance#270]
Dear all,
Tonight I've experienced an unexpected error during a long run simulation.
I've done the same simulation several times in the past without errors. The error occurred when the code checks for a cryptocurrency price.
The error is:

Traceback (most recent call last):
  File "Test.py", line 1101, in <module>
    CryptoNEO_USDT = float(list(filter(lambda x: x['symbol'] == 'NEOUSDT', ticker))[0]['price'])
IndexError: list index out of range

Each 1s my program checks for the prices of several cryptocurrencies. In the same loop there are other cryptocurrencies acquired, in the same way, before NEOUSDT.
The error occurred after about 6 hours of regular run of the program. As said before generally I had ran the same program for several times (each time generally 10 hours) without problems.

I haven't had the chance to execute my program again.

Tonight I'll test it again.

Seems to be a problem related to the information acquired from Binance. If so, can I prevent my program from exiting/crashing?
Is there a better way to coding/extracting prices information?

Thanks in advance.

**Comment by wranai** [comment]
The ticker does not always lists all symbols, only the ones that were changed since the last update. In effect, your list may be empty, which renders index 0 invalid. I suspect the reason it usually works is that NEOUSDT gets frequent updates so it's almost always has an entry in the ticker.

**Comment by EneaMapelli** [comment]
Hi, 
same problem here, tonight calling get_all_tickers return many times a list far shorter than normal, usually there's over 300 couples and tonight only about 100. I don't know if it's a problem from binance or from this library. For now i resolved raising an exception when the list is shorter the 300 in a try enclosure.

**Comment by nocciolate** [comment]
getting the same problem since yesterday as well. when calling all tickers sometimes I get the full list of, as of now, 308 pairs.. but sometimes the list is just 112 elements long instead.

**Comment by nocciolate** [comment]
Wranai, can the speed at which the string of data is received back through a websocket based mini ticker be increased from the current ca. 1sec that the websocket offers? I am aiming to have an update every 0.1sec.

**Comment by Esisxnem** [comment]
I'm trying to use the mini ticker (start_miniticker_socket) as suggested, but I'm having some hard time extracting the data form the message. 
I can print the message on the screen, but I'd like to do some statistical calculation on it.
Can someone teach me how to correctly extract data from the message?
Thanks in advance

**Comment by Esisxnem** [comment]
Never mind, I've done it myself

**Comment by nocciolate** [comment]
Hi @Esisxnem, I am struggling exactly with the same. Would you be willing to show me how you managed to "extract data from the message"? Could provide an email address.

**Comment by Esisxnem** [comment]
Hi nocioalte,
I'll start saying that I'm far to be a skilled programmer, I'll show my test code to extract the price in float format for the desired pair.

```
def process_miniticker_message(message):
    global count, conn_key
    if (message == False):
        # close and restart the socket
        print('closing socket')
        # use either stop_socket or close, or both
        bm.stop_socket(conn_key)
        bm.close()
        # restarting the socket
        conn_key = bm.start_miniticker_socket(process_miniticker_message)
        # reset the count
        count = 0
    else:
        # process message normally
        # print("got ticker message:{}:{}".format(count, message))
        
        print("Message length ", len(message))
        for Dictionary in message:
            if Dictionary['s'] == 'BNBUSDT':
                DictionaryBNB_USDT = Dictionary
                print("got ticker message:{}:{}".format(count, DictionaryBNB_USDT))
                print("Closing Price", float(DictionaryBNB_USDT.get('c')))
                break
        
        count = count + 1
        
        # Test for exit
        if(10 == count):
            reactor.callFromThread(reactor.stop)
            count = 0
			
bm = BinanceSocketManager(client)
count = 0
# start any sockets here, i.e a trade socket
conn_key = bm.start_miniticker_socket(process_miniticker_message)
# then start the socket manager
bm.start()
```

I'm not sure about the condition  **if (message == False):**. I didn't test it, the API reference said that start_miniticker_socket will returns: connection key string if successful, False otherwise.

For the **else** condition, I have extracted the price from the message in  a custom way. Probably there is a better way to do it. I need help to improve this solution.

There is also a command to exit **reactor.callFromThread(reactor.stop)** if a desired condition is met. Same here, I need help to improve this solution.

**Comment by nocciolate** [comment]
That len(get_all_tickers) issue seems to be fixed. I have been running successfully my code for the past couple of hours without any further issues.

Regarding the websocket: I couldn't manage to make the stream faster than 1000ms. Tried both passing update_time as argument and also going to the websockets.py file and adjusting there the pre-built argument to less than 1000ms. Both didn't work. Turned now to the binance CS and asked them if there is a way to do it. Can happily let you know what they said.
