### ISSUE TITLE
v1 vs v3 are not about public vs private calls, and ticker calls use obsolete API

### ISSUE THREAD

**Issue by wranai** [sammchardy/python-binance#271]
v1 and v3 are treated as if they were related to public vs private (and widthraw) calls:

https://github.com/sammchardy/python-binance/blob/852b2561b62702524dba37926fc720a2f399de09/binance/client.py#L17-L19

I believe this is a mistake, proven by that the v1 ticker endpoints (used by the client) have been retired in favor of v3 versions with the same functionality:

* v1/ticker/allPrices => v3/ticker/price
* v1/ticker/allBookTickers => v3/ticker/bookTicker

#270 _may_ be the result of undocumented changes to the (now unofficial) v1 endpoints that the client is still using:

https://github.com/sammchardy/python-binance/blob/852b2561b62702524dba37926fc720a2f399de09/binance/client.py#L407
https://github.com/sammchardy/python-binance/blob/852b2561b62702524dba37926fc720a2f399de09/binance/client.py#L438

Both of the above functions reference documentation that no longer exists.

EDIT: the v3 version is probably just an alias to v1 because it exhibits the same bug that #270 is about.

**Comment by aghamir** [comment]
Is there any progress in this issue?
