### ISSUE TITLE
Fake prices with binance.get_symbol_ticker(symbol='BTCUSDT')

### ISSUE THREAD

**Issue by maxreis86** [sammchardy/python-binance#272]
Hi dear All,

I am using the following simple code with python 3 to get all Binance prices:

`from binance.client import Client as client_binance`
`import datetime`

`api_key = "xxxx"`
`secret_key = "xxxx"`

`while True:`
`     binance_aut = client_binance(api_key, secret_key)`
`     ticker_binance = binance_aut.get_symbol_ticker(symbol='BTCUSDT')`
`     lastPriceBinance = ticker_binance["price"]`
`     print(str(datetime.datetime.now())[:19] + '|' + str( lastPriceBinance ))`

And this is an output example (Please take a look on price at 13:00:11)

02May2018 13:00:08 | 9158.17
02May2018 13:00:09 | 9158.17
**02May2018 13:00:11 | 9038.79**
02May2018 13:00:12 | 9155
02May2018 13:00:14 | 9158.18

Can you see how different is that price?
It is 119.38 USD lower than the previews one and now I am going to prove that it is wrong.

I have been use for long time a JavaScript API wich read all Binance prices using the following WebSoket:
'wss://stream.binance.com:9443/ws/btcusdt@trade'

I have confirmed that this WebSocket works right comparing all prices with the Binance web site and I found no differences.
Below you can see all price collected at the same period. Please take a look on prices at 02May2018 13:00:11:

dateTime | tradeId | price | amount | date | time
02May2018 13:00:08 | 40212221 | 9158.17 | 0.002612 | 2018-05-02 | 13:00:08
02May2018 13:00:08 | 40212222 | 9158.17 | 0.027527 | 2018-05-02 | 13:00:08
02May2018 13:00:09 | 40212223 | 9155 | 0.182403 | 2018-05-02 | 13:00:09
02May2018 13:00:09 | 40212224 | 9155 | 0.01436 | 2018-05-02 | 13:00:09
02May2018 13:00:09 | 40212225 | 9158.17 | 0.02185 | 2018-05-02 | 13:00:09
02May2018 13:00:09 | 40212226 | 9155 | 0.0257 | 2018-05-02 | 13:00:09
02May2018 13:00:09 | 40212227 | 9155 | 0.003985 | 2018-05-02 | 13:00:09
02May2018 13:00:10 | 40212228 | 9155 | 0.042042 | 2018-05-02 | 13:00:10
02May2018 13:00:10 | 40212229 | 9158.17 | 0.0197 | 2018-05-02 | 13:00:10
02May2018 13:00:10 | 40212230 | 9158.17 | 0.0054 | 2018-05-02 | 13:00:10
02May2018 13:00:10 | 40212231 | 9158.18 | 0.016378 | 2018-05-02 | 13:00:10
**02May2018 13:00:11 | 40212232 | 9158.18 | 0.0099 | 2018-05-02 | 13:00:11
02May2018 13:00:11 | 40212233 | 9158.18 | 0.0197 | 2018-05-02 | 13:00:11
02May2018 13:00:11 | 40212234 | 9155 | 0.002602 | 2018-05-02 | 13:00:11
02May2018 13:00:11 | 40212235 | 9155 | 0.000276 | 2018-05-02 | 13:00:11**
02May2018 13:00:12 | 40212236 | 9158.18 | 0.003015 | 2018-05-02 | 13:00:12
02May2018 13:00:12 | 40212237 | 9158.18 | 0.007 | 2018-05-02 | 13:00:12
02May2018 13:00:12 | 40212238 | 9155 | 0.028632 | 2018-05-02 | 13:00:12
02May2018 13:00:12 | 40212239 | 9155 | 0.061245 | 2018-05-02 | 13:00:12
02May2018 13:00:12 | 40212240 | 9155 | 0.008536 | 2018-05-02 | 13:00:12

As we can see there is no trade with the price **9038.79** and there is no missing trade id. They are all there. 
So, it means that python-binance API is giving me fake prices and it is horrible.

Have anyone  the same problem?
Why this API this python library gives fake prices?

Can anybody help me with this issue please?

**Comment by wranai** [comment]
If you look at the code, you can see that not only does it not fake anything, it's not even processing the data in any way: it just sends a request to Binance, takes whatever it gets in response, then uses the standard json library to decode it before it returns it.

Raising this issue with Binance would help us all better than inventing conspiracy theories: ***"So, it means that python-binance API is giving me fake prices and it is horrible.** [...] **Why this API this python library gives fake prices?"***

As for your code snippet, there's really no need to make a new client for each request, so maybe you wanna move that line outside the loop.
