### ISSUE TITLE
SSL Handshake Failure

### ISSUE THREAD

**Issue by msieg** [sammchardy/python-binance#273]
Hello,
I am stuck on this requests error...

"requests.exceptions.SSLError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/ping (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'),)):

...this just started happening and I haven't changed my code at all. Can someone please help me fix this? I've seen that there have been related issues posted, but those solutions have not helped me. Thanks a bunch.
-M

**Comment by axelv** [comment]
Same problem here! And I didn't change any code since the last time it was working.

**Comment by snackycracky** [comment]
+1 pulled master branch, seems to be an invalid ssl cert

**Comment by nipwd** [comment]
can solve this problem?
