### ISSUE TITLE
On Ubuntu, ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

### ISSUE THREAD

**Issue by legoly** [sammchardy/python-binance#279]
I was able to run fine on macOS, but after I installed python-binance and try to run, I get this error:

ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

I found some descriptions how to fix, but they're for Amazon Linux, not Ubuntu. I'm on version 16.0 on EC2. 

Can anyone point me in the right direction?

**Comment by junw3i** [comment]
Try running `sudo apt-get install build-essential libssl-dev libffi-dev python-dev` to ensure you have python build essentials installed.

source: https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py

**Comment by rexovas** [comment]
I'm having this issue on Windows as well.
