### ISSUE TITLE
Does at least 1 socket always have to be open for BinanceSocketManager?

### ISSUE THREAD

**Issue by skeebuzz** [sammchardy/python-binance#282]
Seems like if I call start() on the BinanceSocketManager before calling start_xxx_socket, nothing seems to happen. So:

bm = BinanceSocketManager(client)
bm.start()
bm.start_aggtrade_socket('BNBBTC', process_message)

... nothing.

Also, if after it's started (correctly and I'm getting messages), I call stop_socket(conn_key) on the only open socket, and then try to start a new socket, I don't get any messages on the new socket. My solution for now is to just always have 1 socket open, which is fine, but I'm wondering if there's something I'm missing or doing wrong.

**Comment by JSRossiter** [comment]
I have same functionality, I use this where I want to connect multiple streams:
```
if not bm.is_alive():
    bm.start()
```

**Comment by skeebuzz** [comment]
Hmm... yea I just start the thread once and don't bother with the check. It doesn't seem like the thread dies if there aren't any open sockets...
