### ISSUE TITLE
Depth cache spamming API when messages are duplicated

### ISSUE THREAD

**Issue by Rustacon** [sammchardy/python-binance#283]
You have a line in the depth cache manager which is causing major problems for users today.  Binance are sending duplicate messages and this causes the depth cache manager to reset where in fact it should ignore them which in turn spams the API and hits the rate limiter.  The change needed is below, rather than != which would reset on old messages you only want to reset if messages have jumped ahead.  Line 228 needs to be a more than.

elif msg['U'] > self._last_update_id + 1

**Comment by trade-data** [comment]
Actually I think you can lose the buffer parameter completely and in the if/else block have:

        if msg['u'] <= self._last_update_id:
            # ignore any updates before the initial update id
            return
        elif msg['U'] > self._last_update_id + 1:
            # if not buffered check we get sequential updates
            # otherwise init cache again
            self._init_cache()

This basically will only process the next sequential update, ignore any old ones either when starting up or after and reset if the sequence number skips ahead.
