### ISSUE TITLE
Sell order is placed but returns REJECTED through user websockets

### ISSUE THREAD

**Issue by mmm3bbb** [sammchardy/python-binance#285]
After I confirm a buy, I am placing a sell order:

order = binance_client.order_limit_sell(
        symbol='ENJBTC',
        quantity=123,
        price='0.00001685')

I am monitoring user messages with websockets and I get REJECTED messages. However, as you will see below, the order is actually being placed and even filled sometime later. What does this REJECTED status mean? Why do I get two of them? 

# These are messages from my buy order (last column is timestamp)
BUY ENJBTC NEW 30110380 0.00000000 1526834929378
BUY ENJBTC PARTIALLY_FILLED 30110381 0.00001679 1526834929378
BUY ENJBTC FILLED 30110383 0.00001682 1526834929378

# These are messages from my sell order 
# sell order is placed ~ 0.2 sec after buy is filled; and the sell fill is about 510 sec after sell order
SELL ENJBTC NEW 30110385 0.00000000 1526834929571
SELL ENJBTC REJECTED -1 0.00000000 1526834929726
SELL ENJBTC REJECTED -1 0.00000000 1526834929915
SELL ENJBTC FILLED 30111358 0.00001685 1526835439878

I thought maybe it had something to do with price string, but it seems like it is formatted correctly:
"tickSize": "0.00000001"

**Comment by darkblank** [comment]
You mean that after you had placed a order, the order rejected and then filled? If so, it's really confusing.
You did check the Binance trading rule, right?
