### ISSUE TITLE
SocketManager connection will die when all sockets are closed and can't be re-started.

### ISSUE THREAD

**Issue by leftys** [sammchardy/python-binance#287]
Hi all,

when I create a websocket, close it and create again, no data will come as the manager thread will get stopped after the last socket is closed. Python thread can't be restarted, so I can't start it again. Moreover when I create new SocketManager, new socket and start the new manager, no data will come too.

Thanks for checking!
Jan

**Comment by darkblank** [comment]
I have simillar issue.
Maybe I think maybe the problem is comes from library 'Twisted'.

**Comment by legoly** [comment]
I have this issue with the user socket on macOS... although the same problem is not happening on Windows.

**Comment by mmm3bbb** [comment]
This is happening to me for user sockets. It just stops after some time and I can't start it again.

**Comment by hfinger** [comment]
Has anyone managed to solve this? This problem is bothering me for many months now. Both of the suggestions of @K-Kit are not working for me. After much debugging I am not really closer to any solution. There is never any message coming in from Autobahn/Twisted after the socket restart.

**Comment by ftuyama** [comment]
Any workaround about this issue? Keeping always one socket open mitigates the issue, but the websocket still freezes at some time.
