### ISSUE TITLE
What's the best way to 'Depth Socket' when want move to another symbol?

### ISSUE THREAD

**Issue by darkblank** [sammchardy/python-binance#288]
Hello. 
I hope you understand that I'm not good at English because I'm Korean  .
I'm using this library because it is so useful, but I got a trouble.

The trouble came out when I tried to use 'Depth Socket' function as below.

```
partial_key = bm.start_depth_socket('BNBBTC', process_message, depth=BinanceSocketManager.WEBSOCKET_DEPTH_5)
```

When I'm trying to disconnect socket connection about 'BNBBTC' symbol and 
then trying to connect socket about market depth like 'ETHBTC' or another symbol
(same as above function but only symbol is diffrent, BNB -> ETH),
I think this library is making new thread without removing previous thread.
So when I tried this action(move to another symbol depth) several times, socket data wasn't
passed to me.(First time that I moved to another symbol, socket data passed to me. But after about
fourth or fifth time I moved to another symbol, socket data wasn't passed to me.)

The cause of why I'm thinking that the libarary is making new thread without removing previous thread is when I printed variable `partial_key` above in the code, it shows me below letters increasing thread number.
```
# print first time
 <BinanceSocketManager(Thread-1, stopped 139790748387072)>
# print second time
 <BinanceSocketManager(Thread-2, stopped 139790748388083)>
# print third time
 <BinanceSocketManager(Thread-3, stopped 139790749398083)>
...
...
...
``` 

The function used when I want to disconnect socket connection is `closed()` as below.
```
bm.close()
```
And the code used when I want to connect to new market depth socket
(another symbol differ to previous symbol) is as below.
```
partial_key = bm.start_depth_socket('ETHBTC', process_message, depth=BinanceSocketManager.WEBSOCKET_DEPTH_5)
```

so anyone can tell me the best way to use 'Depth Socket' when want move to another symbol?

**Comment by CJ1976** [comment]
I have this same issue and have to restart my kernel to receive info on a new pair. Why was this closed? Is there a solution I am not seeing?
