### ISSUE TITLE
Websockets on EC2

### ISSUE THREAD

**Issue by ianmere** [sammchardy/python-binance#291]
I understand this is not really a python-binance issue, although I'm not sure where else to post. 

On Amazon EC2 I have a ubuntu 16.04 machine running my python. 

`    conn_key = socket.start_symbol_ticker_socket(ticker, process_message)
`
I don't get any error but "process_message" is never called.. 

Any help would be greatly appreciated. 
Have been using the lib for a few months now and really love it!

**Comment by dstaeger** [comment]
I had the same issue so let me ask you:
Did you follow the order of commands as in the documentation [https://python-binance.readthedocs.io/en/latest/websockets.html#websocket-usage](url):
`from binance.websockets import BinanceSocketManager`
`bm = BinanceSocketManager(client)`
`conn_key = bm.start_trade_socket('BNBBTC', process_message)`
`bm.start()`

I observed (Ubuntu 16.04), that I have to start at least one socket such as 
`conn_key = bm.start_trade_socket('BNBBTC', process_message)`,
before I call
`bm.start()`.

After that I can open and close any socket during runtime, but if I start the manager thread before the socket such as
`from binance.websockets import BinanceSocketManager`
`bm = BinanceSocketManager(client)`
`bm.start()`
`conn_key = bm.start_trade_socket('BNBBTC', process_message)`,
nothing happens. I would greatly appreciate if anyone can explain the reason for this behavior.

**Comment by ianmere** [comment]
Hey thanks so much for your response!

The only difference between what I did was: I called start on the socket before starting a ticker socket. I will experiment with what you have done and see if it makes any difference. Did you do any port forwarding with the group security rules or left it default?

**Comment by dstaeger** [comment]
You are welcome.

I have never done any port forwarding.

**Comment by ianmere** [comment]
dstaeger, you were absolutely right, for some reason on EC2 it works  if I called something like this before calling start:

`conn_key = bm.start_trade_socket('BNBBTC', process_message),
`
I have no idea about why this works but I'm truly grateful for you pointing it out to me!

**Comment by ianmere** [comment]
I learnt a little more about these sockets.
Basically it works well following the order for the first time.
But then if there is a wait period of over 5mins, the next time it fails to start again, for me atleast

Has anyone else experienced this? happens with the use case of needing to stop and start sockets infrequently? 

A wild guess would be that something is timing out?

**Comment by dstaeger** [comment]
Same here.

I have to keep at least one socket open all the time, then everything seems fine. If I close all sockets and open one afterwards, **sometimes it works**, but most of the time it does not work (no messages incoming).

I don't know what is the issue, but I see that restarting the whole program always works like a charm.

Would be awesome to understand this behavior better.

**Comment by ianmere** [comment]
Interesting work around! I opted for switching to a windows server on EC2 (also free) that solved things for me.. does seem like if its inactive in Linux there is a timeout.. I was reading somewhere about 300 seconds which from my quick testing  did seem to cause an issue. But hey at-least we found some workarounds

**Comment by ianmere** [comment]
oh I see, hmm that rules that out then. We need someone who understands the lower level classes to provide some insight, anyway happy your able to get up and running.

**Comment by lionheart117** [comment]
yeah, I almost have the same issue about the WebSocket API. 
I used codes from the Quick Start as below：
`# start aggregated trade websocket for BNBBTC
def process_message(msg):
    print("message type: {}".format(msg['e']))
    print(msg)
    # do something

from binance.websockets import BinanceSocketManager
bm = BinanceSocketManager(client)
bm.start_aggtrade_socket('BNBBTC', process_message)
bm.start()`

but when I ran the code there was nothing happened

**Comment by msujithk** [comment]
I cannot thank you guys enough. I was struggling with this issue

**Comment by xiaods** [comment]
use the latest version, it should be working like a charm.

**Comment by maxreis86** [comment]
Hi guy,

I have the same problem here. Run both codes bellow (with bm.start() after and before conn_key) in AWS EC2 with python3.7 and ubuntu18.04 and  it does not work (no messages incoming).

`from binance.websockets import BinanceSocketManager`
`bm = BinanceSocketManager(client)`
`conn_key = bm.start_trade_socket('BNBBTC', process_message)`
`bm.start()`

or 

`from binance.websockets import BinanceSocketManager`
`bm = BinanceSocketManager(client)`
`bm.start()`
`conn_key = bm.start_trade_socket('BNBBTC', process_message)`

In EC2 with windows it works.
I could not understand how did you fix this. Can you explaim me how did you do please?
Thank you so much.

**Comment by xiaods** [comment]
@maxreis86 
please check this issue, do you have add timeout option:
client = Client(api_key, api_secret, {"verify": True, "timeout": 10000})

**Comment by maxreis86** [comment]
Hi @xiaods

Thank you so much for your help. Now it is woking. I would never could do it by myself.
It always works when I start with timeout option and the dm.start() after the conn_key as shown below:

`client = client_binance(api_key, api_secret,{"verify": True, "timeout": 10000})`
`bm = BinanceSocketManager(client)`
`def process_message(msg):`
`     print(msg)`
`conn_key = bm.start_trade_socket('BTCUSDT', process_message)`
`bm.start()`

Thank you. I really apretiate that.

**Comment by xiaods** [comment]
@maxreis86 welcome
