### ISSUE TITLE
'Connection aborted.', error(10054,The connection has been refused by the remote host)

### ISSUE THREAD

**Issue by phereafter** [sammchardy/python-binance#294]
Good afternoon,
yesterday I had a problem with the following error "APIError(code=-1021): Timestamp for this request is outside of the recvWindow." and I solved it following one of the suggestion I found on github (https://github.com/ccxt/ccxt/issues/761):

``import ccxt`

`exchange = ccxt.binance()`

`exchange_time = exchange.public_get_time()['serverTime']`

`your_time = exchange.milliseconds()`

`print('Exchange UTC time:', exchange_time, exchange.iso8601(exchange_time))`

`print('Your UTC time:', your_time, exchange.iso8601(your_time))`

Since then, I run twice my code and it stopped after a while showing me the error in the title. I searched online and I could not really find nothing about it, is it possible that the two things are related?

Thank you very much

**Comment by jmcnab57** [comment]
In my opinion the connection has been refused error and the timestamp are separate issues. One is a network error and the other a request format error. Could you revert your code to when you were receiving the 'Connection aborted' error and see if the error returns? Provide the code sample for testing.
Thanks!
