### ISSUE TITLE
get_orderbook_ticker but with multiple tickers?

### ISSUE THREAD

**Issue by MikeAnthonyG** [sammchardy/python-binance#299]
Firstly, thanks for everything and this is probably a stupid question. I want to use get_orderbook_ticker() to return multiple symbols as it says it is able:

![image](https://user-images.githubusercontent.com/16274160/41941746-84d939de-7962-11e8-86a3-97114c05c9a3.png)

How do you pass **params to return two symbols? Something like:

`client.get_orderbook_ticker(symbol=['ETHBTC', 'BNBBTC`]) `

`Traceback (most recent call last):
  File "C:\Users\Mikey\Documents\Python Projects\Binance Bot\sublime_test_run.py", line 8, in <module>
    x = bb.client.get_orderbook_ticker(symbol=['ETHBTC','LINKBTC'])
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 938, in get_orderbook_ticker
    return self._get('ticker/bookTicker', data=params, version=self.PRIVATE_API_VERSION)
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 175, in _request
    return self._handle_response(response)
  File "C:\Users\Mikey\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 199, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1101): Duplicate values for a parameter detected.`

That is only one of the methods I've tried.

**Comment by jmcnab57** [comment]
@MikeAnthonyG  Hey Mike good question! Don't quote me but I think the documentation is wrong on this matter or there is a mixup in the language. `get_orderbook_ticker()` accepts a single symbol if not it returns the orderbook tickers for all of the symbols. Which is what I think it means by returning "symbols".
When i do a direct request to the api using: https://api.binance.com/api/v3/ticker/bookTicker?symbol=ETCBTC&LTCBTC
The return is
`{
"code": -1101,
"msg": "Too many parameters; expected '1' and received '2'."
}`
From this i conclude that only 1 symbol is expected else it gives you all symbols.
My advice is to just grab all symbols and then traverse the resulting list and pick out the data just for the symbols you want. Alternatively you can do a loop and make a request per coin that you want.
`#Option 1
my_coins=["LTCBTC","EOSBTC","ETHBTC"]
all_orderbooks = client.get_orderbook_ticker()
my_data = [book for book in all_orderbooks if book["symbol"] in my_coins]

#Option 2
for coin in my_coins:
    orderbook = client.get_orderbook_ticker()
    #Do something with the order book`

**Comment by MikeAnthonyG** [comment]
Thanks, but I'm trying to limit the number of API calls. Maybe you're right and it's not possible but I was hoping to make one API call and for it to return 3 tickers. Maybe just writing a custom URL would be easier.

**Comment by jmcnab57** [comment]
@MikeAnthonyG Option 1 that i provided is a single call that will return all orderbook tickers and all you have to do index for the ones you need. A custom URL won't work because you can't expand the /api/v3/ticker/bookTicker?symbol=ETCBTC to include more than one symbol which is why you experience the problem with  `get_orderbook_ticker()`

**Comment by MikeAnthonyG** [comment]
Oh, that's great. Thanks so much.
