### ISSUE TITLE
Not all sent parameters were not read issue

### ISSUE THREAD

**Issue by Sylentwolf8** [sammchardy/python-binance#3]
Thanks for the great project. 

Running into a bit of an issue when trying to place a buy/sell, particularly when attempting to specify order ID's. When trying to do so the following exception is raised:

> binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were not read; read '8' parameter(s) but was sent '9'.

Here's an example of my sell/buy function:

```
def sell(price, asset, quantity, orderid):
    client.create_order(
        symbol=asset,
        side=SIDE_SELL,
        type=ORDER_TYPE_LIMIT,
        timeInForce=TIME_IN_FORCE_GTC,
        quantity=quantity,
        price=price,
        newClientOrderID=orderid)
```

```
def buy(price, asset, quantity, orderid):
    client.create_order(
        symbol=asset,
        side=SIDE_BUY,
        type=ORDER_TYPE_LIMIT,
        timeInForce=TIME_IN_FORCE_GTC,
        quantity=quantity,
        price=price,
        newClientOrderID=orderid)
```

And here's an example of calling those functions which is resulting in the above exception:

```
buy("{0:.6f}".format(round((priceYVal[tradePair]), 6)), tradePair, int(float(amountPurchased * 0.95)), str(orderInt))
```

Note: I have orderInt (the desired order ID) formatted as string on account of Binance specifying that in the API.

Any ideas?

**Comment by sammchardy** [comment]
Hey Sylentwolf8,

You just need to change newClientOrderID to newClientOrderId then you're good to go.

**Comment by Sylentwolf8** [comment]
Ah such a simple solution always. Thanks again!
