### ISSUE TITLE
'exchangeInfo' not working anymore since of today

### ISSUE THREAD

**Issue by Schwambo** [sammchardy/python-binance#30]
`info = client.get_exchange_info()` returns following error message from the JSON decoder:

```
File "c:\python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This issue is consistent for me since this morning, where Binance did a planned maintenance

**Comment by sammchardy** [comment]
Hi @Schwambo yes you're right. Binance changed the spelling of the endpoint.

v0.5.0 has just been released to fix this.

**Comment by Schwambo** [comment]
Great, thanks for checking. I assumed something along them lines but couldn't figure it out, must have missed the different spelling.
Thanks for keeping this wrapper up-to-date, it is really helpful for less talented coders like myself!
