### ISSUE TITLE
Error: binance order price exceeds allowed price precision or invalid, use this.priceToPrecision 

### ISSUE THREAD

**Issue by alexgpark** [sammchardy/python-binance#303]
I get the following error...

> Error: binance order price exceeds allowed price precision or invalid, use this.priceToPrecision (symbol, amount) {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}

when attempting to create Stop Loss with the following code:

```
function precisionRound(num, precision) {
  precision = Math.pow(10, precision)
  return Math.round(num * precision) / precision
}

var buyLimitPrice = precisionRound((lowestPriceExchange.askPrice * 1.005), 8);
const stopPrice = precisionRound((buyLimitPrice * 0.9), 8);
const limitPrice = precisionRound((buyLimitPrice * 0.89), 8);

lowestPriceExchange.exchange.createOrder(coinPair, 'stop_loss_limit', 'sell', quantity, limitPrice, { 'stopPrice' : stopPrice })

```

Initially I had
`
const stopPrice = buyLimitPrice * 0.9;
const limitPrice = buyLimitPrice * 0.89;
`

and got that error above, so I interpreted the error to mean I didn't have the correct number of decimal places, which is why I added the rounding function with a precision of 8 places after decimal point. 

But now even with the rounding function, I still get the same error and struggling to identify what the root issue is.

Any code examples of using the recommended `this.priceToPrecision (symbol, amount)` in the context of setting a Stop Loss order?

**Comment by K-Kit** [comment]
check out the code here, has worked great for me 
https://github.com/dmackenz/Binance-Automated-Trading-Client/blob/master/BinanceHelper.py
