### ISSUE TITLE
Connection timeout when initializing client

### ISSUE THREAD

**Issue by Excalibur614** [sammchardy/python-binance#304]
Hello,

I'm simply initializing the client, `client = Client(api_key, api_sec)`, but keep receiving below connection timeout errors. I have double checked and confirmed my key and secret are correct. Not sure if anyone got the errors and know how to resolve it? many thanks

```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    client = Client(api_key, api_sec)
  File "C:\Python27\lib\site-packages\binance\client.py", line 94, in __init__
    self.ping()
  File "C:\Python27\lib\site-packages\binance\client.py", line 362, in ping
    return self._get('ping')
  File "C:\Python27\lib\site-packages\binance\client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Python27\lib\site-packages\binance\client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Python27\lib\site-packages\binance\client.py", line 174, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04CB8390>, 'Connection to api.binance.com timed out. (connect timeout=10)'))
```

**Comment by Jeremy614** [comment]
Very occasionally, the client initialization works fine and connect to binance (i can query the orderbook, etc). But most of time the initialization failed with the above connection errors.

**Comment by Jeremy614** [comment]
The error is Failed to establish a new connection: [Errno 10060]
Run `r = requests.get('https://api.binance.com/api/v1/ping')`, I got following errors

```
Traceback (most recent call last):
  File "<pyshell#26>", line 1, in <module>
    r = requests.get('https://api.binance.com/api/v1/ping')
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04CBF070>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

```

**Comment by Navaneth** [comment]
Hi Jeremy614,
I am also facing the same problem. 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/klines?endTime=1514764800000&interval=30m&limit=500&startTime=1512086400000&symbol=ETHBTC (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02E315B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Did you manage to find any solution to the same?
Thanks

**Comment by DjangoPeng** [comment]
@scalpounet I faced the same problem. I has tried many times but always get the `ConnectionTimeoutError` as below:

```python
ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10fcc2438>, 'Connection to api.binance.com timed out. (connect timeout=10)'))
```

My env info:

```shell
python-binance 0.7.1
Python 3.6.3
```

Does anyone have a solution for this issue?

**Comment by DjangoPeng** [comment]
It may caused by the difference of timestamp between Binance server and local client. 

```python
time_res = client.get_server_time()
print(datetime.utcfromtimestamp(time_res['serverTime'] // 1000).strftime('[serverTime]%Y-%m-%d %H:%M:%S'))
print(datetime.fromtimestamp(time.time()).strftime('[clientTime]%Y-%m-%d %H:%M:%S'))
```

Out:
```shell
[serverTime]2019-03-18 13:25:31
[clientTime]2019-03-18 21:25:31
```

WDYT

**Comment by DjangoPeng** [comment]
Ref: [Timing security](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#timing-security)

## Timing security
* A `SIGNED` endpoint also requires a parameter, `timestamp`, to be sent which
  should be the millisecond timestamp of when the request was created and sent.
* An additional parameter, `recvWindow`, may be sent to specify the number of
  milliseconds after `timestamp` the request is valid for. If `recvWindow`
  is not sent, **it defaults to 5000**.
* The logic is as follows:
  ```javascript
  if (timestamp < (serverTime + 1000) && (serverTime - timestamp) <= recvWindow) {
    // process request
  } else {
    // reject request
  }

**Comment by DjangoPeng** [comment]
Still occurred the problem again after setting timezone.

**Comment by knowledgecomputer2018** [comment]
hi
i have @Jeremy614 same you. but i work with colab.research.google.com is ok .
i think install microsoft visual studio is good solution but i do not install if my install then send you annocement.
god willing
