### ISSUE TITLE
get_all_tickers() stopped working since about Jul. 3rd/4th, 2018.  

### ISSUE THREAD

**Issue by hduxw4iq** [sammchardy/python-binance#305]
This function runs fine on July 2nd, 2018. 

It currently uses the https://api.binance.com/api/v1/ticker/allPrices URI.  

The official v3 API doc about https://api.binance.com/api/v3/ticker/price says "If the symbol is not sent, prices for all symbols will be returned in an array."

**Comment by sammchardy** [comment]
Hi @hduxw4iq the `get_symbol_ticker` uses the /api/v3/ticker/price endpoint if you want to switch to that.

`get_all_tickers` is a legacy function and may not work.
