### ISSUE TITLE
ImportError: No module named 'binance'

### ISSUE THREAD

**Issue by 15chrjef** [sammchardy/python-binance#316]
Hi Guys,

Trying to get passed an import error. I have seen similar import error being reported that seem to stem from conflicting files/directories in the path, however I believe the error is something different.

I initially tried doing

```
from binance.client import Client

```
which threw the ImportError: No module named 'binance'. This file was nestled a few directories deep, but i did not name any files or directories 'binance'. I then decided to create a blank file at the root of the directory and try to run 

```import binance```

This attempt also threw the same error

```ImportError: No module named 'binance```

I am struggling to find the issue now, I have tried to install 'python-binance' and 'python-binance-api' individually with pip and still i have this issue. I am running on Ubuntu 16.04.5.

Thanks.

**Comment by K-Kit** [comment]
Are you using python 2 or 3, if so you might just need to do pip3 install python-binance 
or just do `python -m pip install SomePackage` to make sure you don't have multiple versions of pip messing it up

**Comment by freskpe** [comment]
try  **sudo -H pip install python-binance.** (on python 2.x)
or  **sudo -H pip3 install python-binance** (on python 3.x)

**Comment by priyakumariengineer** [comment]
Thanks @K-Kit , doing python -m pip install SomePackage works in my case.

**Comment by Nsandomeno** [comment]
@priyakumariengineer Was this by any chance because you had anaconda running elsewhere?

**Comment by Pierro06** [comment]
HI, I have the same issue here, created a conda virtual environment within my folder project, tried to run just "from binance.client import Client" but renders me this error in VS Code : "{
	"resource": "/home/pierre/TradingBinBot/first.py",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "unresolved-import",
	"severity": 4,
	"message": "unresolved import 'binance.client'",
	"source": "Python",
	"startLineNumber": 7,
	"startColumn": 6,
	"endLineNumber": 7,
	"endColumn": 20
}"

Any idea ??

**Comment by kimchirichie** [comment]
i suppose installing thru pip is unrelated to library itself. closing.

**Comment by aerrowfar** [comment]
I had a similar issue, for me the problem was my IDE was trying to run the code in a different version of python than that of the library. Running manually from terminal python3 bot.py worked

**Comment by J-cyber0** [comment]
> I had a similar issue, for me the problem was my IDE was trying to run the code in a different version of python than that of the library. Running manually from terminal python3 bot.py worked

yes this as well worked for me. Then, restarting VS in my venv and it's back to normal.
