### ISSUE TITLE
Best approach for placing and canceling ~ 30 buy orders every minute

### ISSUE THREAD

**Issue by mmm3bbb** [sammchardy/python-binance#321]
I am placing around 30 buy orders at the beginning of each 1m candle. At the end, I am canceling any unfilled buy orders and then doing the same for the next minute. 

I tried to put these requests in an async function but it seems like the api is executing them sequentially and it's taking 5-10 seconds to cancel and resubmit. 

Is there a way to execute these orders/cancels asynchronously so performance is improved?

**Comment by wranai** [comment]
I put the orders in a queue (queue.Queue or queue.PriorityQueue), set up a pool for the client's session (e.g. `client.session.mount('https://', HTTPAdapter(pool_maxsize = 50))`) then start a bunch of worker threads to read from the queue. You're not allowed to open more than 10 orders a second though so you may wanna add a token bucket or that sort of thing.

**Comment by mmm3bbb** [comment]
ok, cool... thanks. I was wondering if there was some sort of async interface, but threads should be fine. btw, are order limits on ip, token or account? Thanks!

**Comment by wranai** [comment]
Here: https://support.binance.com/hc/en-us/articles/360004492232-API-Frequently-Asked-Questions-FAQ-#%E2%80%9Cexceedlimits%E2%80%9D

**Comment by thePapan** [comment]
Hey, 

this 10 orders limit per second mentioned, does it apply to new orders only or does cancelling orders also count for these 10 orders?

Thanks
