### ISSUE TITLE
Can not install in 'pipenv'

### ISSUE THREAD

**Issue by cm-abhijit** [sammchardy/python-binance#323]
I am using python 3 on Linux. 
I get following error while trying to install `python-binance` using `pipenv`:

```Installing python-binance...
Collecting python-binance
  Using cached https://files.pythonhosted.org/packages/e4/2d/17ad94d13ff59e6d77d1a205d9b3f0db9eca326f49444cdd97600c0e183d/python_binance-0.7.0-py2.py3-none-any.whl
Collecting chardet (from python-binance)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting Twisted (from python-binance)

Error:  An error occurred while installing python-binance!
  Could not find a version that satisfies the requirement Twisted (from python-binance) (from versions: )
No matching distribution found for Twisted (from python-binance)```

**Comment by anson-vandoren** [comment]
pipenv actually has errors like this on many different packages, and this is one of the biggest reasons I don't use it much. I'd suggest using a different environment manager (virtualenvwrapper, venv, conda, etc) and installing either with those tools if available, or directly with pip/pip3 after setting up an environment.

This isn't a problem with the python-binance library, but with pipenv instead.
