### ISSUE TITLE
APIError(code=-2010): Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by ticketself** [sammchardy/python-binance#326]
I have enough USDT balance (+1000 USDT) but I can't work with the API in any USDT/other pair.

buy = client.order_limit_buy(symbol='IOTAUSDT',quantity=30,price=0.5)

It returns APIError(code=-2010): Account has insufficient balance for requested action.

Seems that there is something wrong with USDT and api wrapper.

**Comment by duduzhu** [comment]
This has nothing to do with the code. You have insufficient balance.

**Comment by legoly** [comment]
I trade lots with USDT so not a systemic problem. I see that message when I forget that I have tied up funds in other outstanding limit buy orders that have not been filled.
