### ISSUE TITLE
Websockets is not working

### ISSUE THREAD

**Issue by galloclaudio** [sammchardy/python-binance#33]
After the binance update, websockets do not work. I try to use the code of bm.start_trade_socket and cant get the values of last trades

**Comment by sammchardy** [comment]
@galloclaudio best to ask in the Binance API telegram channel. I do see the same behaviour which is strange.

There have been some updates to the Binance API recently, this include a new aggregated trades socket which is now implemented in v0.5.0 of this python-binance lib.

bm.start_aggtrade_socket('BNBBTC')

I can confirm that this one does return data.
