### ISSUE TITLE
Can the API Key and secret be made optional? I just want to read the public channel data

### ISSUE THREAD

**Issue by dhanunjayalakshmi** [sammchardy/python-binance#330]
Currently I am using this module to collect public sockets data but without the key and secret, the client object does not seem to get any data from the exchange. Is there a way to provide None objects? or no key to the client class and still use this to get public channel data from binance?

**Comment by jmcnab57** [comment]
In theory they are already optional. There is no validation of the provided key and secret so you can pass empty string.s Any public call will work and those requiring the key and secret will return with an error.
Example:
`from binance.client import Client
client = Client("","")
response="client.get_symbol_info(symbol="ETHBTC")
print(response)`

**Comment by dhanunjayalakshmi** [comment]
Thanks for the info. I had issues getting the data on the binance websockets.
