### ISSUE TITLE
Restarting websockets connection after losing network access

### ISSUE THREAD

**Issue by legoly** [sammchardy/python-binance#331]
I occasionally lose network connectivity for a second or two and handle this exception when, say, placing an order. But once this happens, I no longer get any websockets messages. I have tried to stop/restart user and multiplex sockets with no luck. Have tried to reinitialize binance client and create new websockets connections and no new messages flow.

Is there a way to get messages flowing again once there's a network error?

**Comment by jmcnab57** [comment]
Have you attempted to stop the twisted reactor and then restart it?

**Comment by mmm3bbb** [comment]
No, sorry, wouldn't even know where to look for that.

**Comment by mfurlend** [comment]
@jmcnab57 That does not work. The reactor throws an exception saying that it can't be restarted. I have this same issue.

**Comment by matze19999** [comment]
Same problem here.. Did you find a solution for this?

**Comment by EdgarPE** [comment]
Someone had any luck with this? I have the same problem. Even without network error, I can not stop and restart BinanceWebsocketManager again.
