### ISSUE TITLE
get_historical_klines cutting the data at a limit multiplier before the end_str

### ISSUE THREAD

**Issue by nicoan777** [sammchardy/python-binance#332]
With this:
https://github.com/sammchardy/python-binance/blob/master/examples/save_historical_data.py

Try this:
get_historical_klines("ETHBTC", Client.KLINE_INTERVAL_15MINUTE, "2018-8-20")

If we don't use the end time, it should get the data till now: 2018-9-14. 
But instead, the data is being cut at 2000 lines (limit multiplier) on 2018-9-9, leaving the rest out.

This may be the problem:
```
       # check if we received less than the required limit and exit the loop
        if len(temp_data) < limit:
            # exit the while loop
            break
```

How do we fix it @sammchardy ?

**Comment by Charly-Empereur-mot** [comment]
I have the same issue. Does it work correctly when you set the end data to date of today ?
