### ISSUE TITLE
ticker = client.get_all_tickers('BTCUSDT') Returning Error

### ISSUE THREAD

**Issue by quadricanna** [sammchardy/python-binance#334]
Hi there, 
I'm trying to get current price of BTCUSDT but it is returning following error. Please help.

TypeError: get_all_tickers() takes 1 positional argument but 2 were given

**Comment by janandraczko** [comment]
Hi,

I recommend to use different function client.get_symbol_ticker(symbol="BTCUSDT")

Hope that helps?

**Comment by quadricanna** [comment]
Great! Thanks, it works
