### ISSUE TITLE
Websocket, stop terminal, ping socket?

### ISSUE THREAD

**Issue by Githubuser0007** [sammchardy/python-binance#342]
Hi guys. I'm fairly new to python. I've gone through every post posted in "issues" inhere that contained the word "websocket" to try and educate myself. But a few things are still not clear to me. 

I am using the standard code used in the examples (see bottom of this post)

1. Reconnect to same socket? (edited question, figured out the stop-terminal part)
Using the code in bottom of this post. If during a session of coding I run the script and stop it using ctrl + break/pause button maybe 10+ times. Do I start a brand new websocket each time? If I do, is this frowned upon? I intend my script to run 24/7 when it's done. But while testing it and only planning on running it for 5-10 sec should I put in something like this into my code?
sleep(20)
bm.stop_socket(conn_key)
bm.close()
reactor.stop()
So that I can test my code in 20 sec and then it shuts down all websockets. Should I do this, or can I just connect to the same over and over again while testing?

2. Keep websocket from closing?
I read in the binance rest-api document:
link: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#keepalive-user-data-stream-user_stream
that to keep a stream open it was recommended to ping it once every 30 min. This is in the rest-api doc though. I did not find information about this in the websocket doc (only this quote "A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark"). I also checked https://python-binance.readthedocs.io/en/latest/websockets.html#websocket-usage
So I'm unsure how to keep the stream alive running 24/7.

---- Code below -----
from binance.client import Client
from binance.websockets import BinanceSocketManager

client = Client("", "")

def process_m_message(msg):
    print("stream: {} data: {}".format(msg['stream'], msg['data']))

bm = BinanceSocketManager(client)

conn_key = bm.start_multiplex_socket(['btcusdt@miniTicker', 'bnbusdt@miniTicker'], process_m_message)

bm.start()

**Comment by anson-vandoren** [comment]
Hi @Githubuser0007,

1. Whenever you fully exit your code, the websocket connection is dropped. There's nothing wrong with reconnecting again on your next test, and the API doesn't care. If you just want a more graceful way to exit, though, you could try something like:
```python
# ... start your socket, process messages, etc.
# At the end of your script, add this:
while True:
    time.sleep(60 * 60 * 24)
except KeyboardInterrupt:
    print('Exiting the script')
    break
# Note that you don't need need bm.close_socket(conn_key) in this case since
# bm.close() does that already (for all open connections)
bm.close()
# Note that below is the correct way to stop twisted reactor, since it is running on a
# separate thread from the main thread your script is on. This will let everything
# close more quickly instead of the delay with simply reactor.stop()
reactor.callFromThread(reactor.stop)
```

2. I don't have a definitive answer for you regarding running a socket past the Binance API limitation of 24 hours, but based on the `BinanceSocketManager` and `twisted` code, I believe the socket manager will automatically reconnect after the API drops the connection at the 24 hour point. This should work the same as if you had a temporary internet connection loss that caused the disconnect, and it will retry up to 5 times (with varying delay periods). If the connection is regained inside those 5 attempts, it resets attempt count, and everything proceeds as normal.

Hope that helps, and please let me know if any of this is unclear.

Regards,
Anson
