### ISSUE TITLE
client.get_all_tickers() returning an empty array

### ISSUE THREAD

**Issue by mlasy** [sammchardy/python-binance#343]
Hey, since few minutes,

client.get_all_tickers() is returning an empty array.
I dont know where the issue is.

Thanks

Jerry

**Comment by mtm85** [comment]
I have the same issue, I tried another approach (through the API from Toshima: https://github.com/toshima/binance), yet gives the same response. So looks like the issue os with the Binance API(though I am no expert). Anybody have any other ideas?

**Comment by mlasy** [comment]
found it:
https://twitter.com/cz_binance
binance is under maintenance ...

**Comment by anson-vandoren** [comment]
@mlasy, since this was an issue with the API being offline instead of a `python-binance` library issue, would you mind closing the ticket? Thanks!
