### ISSUE TITLE
Can't fetch the symbol in socket depth method

### ISSUE THREAD

**Issue by ticketself** [sammchardy/python-binance#346]
I'm opening some sockets with:

c = bm.start_depth_socket(symbol, setCOIN,depth=BinanceSocketManager.WEBSOCKET_DEPTH_5)

The problem is that the response is:

{'lastUpdateId': 44067858, 'bids': [['0.00001431', '695.00000000', []], ['0.00001430', '846.00000000', []], ['0.00001428', '892.00000000', []], ['0.00001427', '1141.00000000', []], ['0.00001426', '13650.00000000', []]], 'asks': [['0.00001436', '8354.00000000', []], ['0.00001437', '1155.00000000', []], ['0.00001438', '3977.00000000', []], ['0.00001439', '73.00000000', []], ['0.00001440', '1856.00000000', []]]}

How can I know which is the current symbol depth?

**Comment by cemuney** [comment]
Hi ticketself. 
Sorry to write here. i cannot PM you.
How did you solve "SignData Invalid" error in bitforex api. Please help thanks

[https://github.com/bitforexapi/API_Doc_en/issues/4](https://github.com/bitforexapi/API_Doc_en/issues/4)

import hashlib
import hmac
import base64
accessKey = 'ACCESS_KEY'
secretKey = 'SECRET_KEY'
nonce = int(round(time.time() * 1000))
message = bytes("/api/v1/trade/placeOrder?accessKey="+accessKey+"&amount=0.5&nonce="+str(nonce)+"&price=240&symbol=coin-usd-eth&tradeType=2","utf8")
secret = bytes(secretKey,"utf8")
signature = hmac.new(secret, message, digestmod=hashlib.sha256).digest().hex()
r = requests.post("https://api.bitforex.com/api/v1/trade/placeBuyOrder", data={'accessKey': accessKey, 'nonce': nonce, 'amount': '0.5', 'prices': '240', 'symbol': 'coin-usd-eth', 'signData': signature})
print(r.text)

But I'm receiving:

{"code":"1016","success":false,"time":1538406752449,"message":"SignData Invalid"}

Thanks
