### ISSUE TITLE
Can't get current symbol

### ISSUE THREAD

**Issue by ticketself** [sammchardy/python-binance#347]
I'm opening some sockets with:

c = bm.start_depth_socket(symbol, setCOIN,depth=BinanceSocketManager.WEBSOCKET_DEPTH_5)

The problem is that the response is:

{'lastUpdateId': 44067858, 'bids': [['0.00001431', '695.00000000', []], ['0.00001430', '846.00000000', []], ['0.00001428', '892.00000000', []], ['0.00001427', '1141.00000000', []], ['0.00001426', '13650.00000000', []]], 'asks': [['0.00001436', '8354.00000000', []], ['0.00001437', '1155.00000000', []], ['0.00001438', '3977.00000000', []], ['0.00001439', '73.00000000', []], ['0.00001440', '1856.00000000', []]]}

How can I know which is the current symbol depth?

**Comment by wranai** [comment]
That stream just keeps pushing you the 5 highest bids and the 5 lowest asks as advertised.

_I'm not sure what you mean by "current symbol depth" though._

If you want to know how many levels exist in the order book, there's no way to get that. You may try to get the "full" order book with the [`GET /api/v1/depth`](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#order-book) API endpoint but even that will only return at most a thousand levels. More importantly, knowing the full order book would give you little actionable information over the first few levels.

**Comment by ticketself** [comment]
> That stream just keeps pushing you the 5 highest bids and the 5 lowest asks as advertised.
> 
> _I'm not sure what you mean by "current symbol depth" though._
> 
> If you want to know how many levels exist in the order book, there's no way to get that. You may try to get the "full" order book with the [`GET /api/v1/depth`](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#order-book) API endpoint but even that will only return at most a thousand levels. More importantly, knowing the full order book would give you little actionable information over the first few levels.

I've opened some depth sockets, but I can't manage them because in the response, I get for example:
{'lastUpdateId': 34903772, 'bids': [['0.00000338', '34259.00000000', []], ['0.00000337', '24508.00000000', []], ['0.00000336', '22921.00000000', []], ['0.00000335', '10647.00000000', []], ['0.00000334', '76175.00000000', []]], 'asks': [['0.00000340', '11362.00000000', []], ['0.00000341', '15832.00000000', []], ['0.00000342', '13650.00000000', []], ['0.00000343', '39376.00000000', []], ['0.00000344', '74779.00000000', []]]}

But in the response can't get the symbol of this response.

Thanks
