### ISSUE TITLE
incorrect order book interpretation

### ISSUE THREAD

**Issue by vldslvk** [sammchardy/python-binance#349]
python 3

Let's say that I want to get order book. I run code like this:

#---------------------------------------------code---------------------------------------------
order_book = client.get_order_book(symbol=symbol, limit=10)
order_book = pd.DataFrame(order_book)
order_book.to_excel('order_book.xlsx')
#----------------------------------------------------------------------------------------------

and .xslx file looks like (look at attachments)
According to the table ask price exceed bid price. So, name of columns(asks, bids) are incorrect.
Because asks(buyers) always want to buy at less price and bids(sellers) always  want to sell at high price.

[order_book.xlsx](https://github.com/sammchardy/python-binance/files/2585929/order_book.xlsx)

**Comment by tropo84** [comment]
no you just got it wrong. Ask and bid refers to price. So sellers, ASK for a certain (high) price and buyers BID a certain (low) price

**Comment by vldslvk** [comment]
Got it, thank you.
