### ISSUE TITLE
Websocket stops getting data

### ISSUE THREAD

**Issue by CarretillaRoja** [sammchardy/python-binance#353]
I start any socket and behave as expected. BUT some random time later, it stops getting info. I just print(msg) and it suddenly stops printing it. I only use ticker and trade sockets, if that matters.

I know that sockets have a 24 hour limit, but never reach that time. There is no error message nor the code fails, it just stops getting updates. Tested with two computers and a raspberry pi. I have no firewall at home, I will try from another place to discard Internet provider issues.

Has anyone had this issue before? Thanks.

**Comment by rafaelribeiro** [comment]
The same occurred to me. Has taken no more than one hour for data stopped from getting cautgh. I'm considering restarting the whole script after a certain time or even every time the data is received.

**Comment by CarretillaRoja** [comment]
After some tests, I realized the problem was that my internet connection was not stable. The ISP fixed it.

**Comment by anson-vandoren** [comment]
@CarretillaRoja since you found this was an issue with your ISP (and not python-binance library), would you mind marking this issue as resolved? Thanks!

**Comment by CarretillaRoja** [comment]
Of course!
