### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by 1221328** [sammchardy/python-binance#354]
How to fix this error?

(starting*0.999)/float(ask1)
ZeroDivisionError: float division by zero

**Comment by anson-vandoren** [comment]
ZeroDivisionError means that your variable `ask1` is 0, which means that (starting*0.999)/0.0 is undefined. Depending on exactly what you are trying to accomplish, you could check for a valid denominator before doing the division, like:

```python
if ask1 != 0:
    result = (starting * 0.999) / float(ask1)
else:
    print('Cannot divide by zero!')
    result = None
```

Exact implementation depends on what you are using the resulting value for, but hopefully that gets you pointed in the right direction.

**Comment by 1221328** [comment]
Thanks.
