### ISSUE TITLE
TypeError: start_aggtrade_socket() missing 1 required positional argument: 'callback'

### ISSUE THREAD

**Issue by JMedon** [sammchardy/python-binance#36]
Hi

I tried to run example code but I received error:

`from binance.websockets import BinanceSocketManager'
'bm = BinanceSocketManager(client)'
'bm.start_aggtrade_socket(symbol='BTCUSD')'
'bm.start()`

Traceback (most recent call last):
  File "C:/Users/JM/Documents/GitHub/python-binance/main.py", line 20, in <module>
    bm.start_aggtrade_socket(symbol='BTCUSD')
TypeError: start_aggtrade_socket() missing 1 required positional argument: 'callback'

Process finished with exit code 1

Can you help fix the issue?

**Comment by duduzhu** [comment]
Because you must indicate a callback function for the socketmanager to call back.
```
from binance.websockets import BinanceSocketManager
def mycallback(msg):
    print("I will do something will the msg")

bm = BinanceSocketManager(client)
bm.start_aggtrade_socket(symbol='BTCUSD',callback = mycallback)
bm.start()
```

**Comment by JMedon** [comment]
Thanks, but when I run your code I don't receive print info print("I will do something will the msg") and I don't receive any message.
I would like to export every order/trade to txt file. How can I do that?
