### ISSUE TITLE
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')]

### ISSUE THREAD

**Issue by ArneVanham** [sammchardy/python-binance#361]
I receive an SSL error when calling the get_asset_balance function. Any idea what is causing this and how I can resolve it?

**Comment by anson-vandoren** [comment]
What OS are you using? If Debian (or a derivative like Ubuntu), this seems to be something of a known issue, although not with `python-binance`, `requests`, `urllib` or Python itself, but rather with the underlying OpenSSL implementation.

There's some more details on various threads on StackOverflow [like this one](https://stackoverflow.com/questions/21497591/urllib2-reading-https-url-failure) and [all of these](https://stackoverflow.com/search?q=SSL+routines%3ASSL3_GET_RECORD%3Adecryption+failed+or+bad+record+mac), and also a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=678353) on debian.org.

Reading through several of the issue reports, I don't see that there is a clear fix yet that anyone has proposed. There are a few workarounds that people have used in various cases, but depends on how involved you want to get with it. Easiest may be trying a later build of Debian/Ubuntu, or else choosing a different distro altogether if that's an option for you.

Regards,
Anson

**Comment by ArneVanham** [comment]
I am on macOS  Mojave version 10.14.2

**Comment by anson-vandoren** [comment]
Interesting. Based on the SO thread regarding issues with Xcode and Python, do you see the same issue if you run the script from an up-to-date Python version (e.g. latest 3.7) from the terminal?
