### ISSUE TITLE
Get Order - filter

### ISSUE THREAD

**Issue by PythonNewbie101** [sammchardy/python-binance#362]
Hello people!

Absolutely LOVE this API :-)

I have a question with getting specific data from a request. 

How would i get the OrderID if i ran this?

orders = client.get_all_orders(symbol='BNBBTC')

Many Thanks!

**Comment by anson-vandoren** [comment]
Per the [documentation](https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_all_orders), this call will return a list of dictionary objects that have your orders, like this:
```
[
    {
        "symbol": "LTCBTC",
        "orderId": 1,
        "clientOrderId": "myOrder1",
        "price": "0.1",
        "origQty": "1.0",
        "executedQty": "0.0",
        "status": "NEW",
        "timeInForce": "GTC",
        "type": "LIMIT",
        "side": "BUY",
        "stopPrice": "0.0",
        "icebergQty": "0.0",
        "time": 1499827319559
    }
]
```
So, to get OrderID from each order, you could do something like this:
```python
orders = client.get_all_orders(symbol='BNBBTC')
for order in orders:
    print(order['orderId'])
```

Is that what you're looking for?

**Comment by PythonNewbie101** [comment]
Mate that was *exactly* what i was looking for!

Thank you SO much! 

:-)

**Comment by anson-vandoren** [comment]
Glad I could help. If this solved your issue, please mark this issue as closed 😄 Thanks!
