### ISSUE TITLE
Can't close websockets

### ISSUE THREAD

**Issue by frangte** [sammchardy/python-binance#363]
Hi every one,

I wrap binance.websocket in my custom class (for my usecase).

```
class BinanceSocket(object):
    def __init__(self, api_key, api_secret):
        self.connection_key = ''
        self.binance_client = Client(api_key=api_key, api_secret=api_secret)
        self.binance_stream = BinanceSocketManager(self.binance_client)
        self.__transactions = []
        self.timer = Timer(INTERVAL, lambda: self._auto_trigger())

    def start(self):
        self.connection_key = self.binance_stream.start_user_socket(lambda msg: self._handle_message(msg))
        self.binance_stream.start()
        self.timer.start()

    def stop(self):
        self.binance_stream.stop_socket(self.connection_key)

    def _handle_message(self, msg):
        if self._is_filled_event(msg):
            self.__transactions.append(msg)
            if len(self.__transactions) == MAX_LEN_MESSAGE:
                self._send_task()

    def _send_task(self):
        if len(self.__transactions) == 0:
            return
        print(self.__transactions)
        self.__transactions = []

    def _auto_trigger(self):
        self._send_task()
        self.timeout = Timer(INTERVAL, lambda: self._auto_trigger())
        self.timeout.start()

    @staticmethod
    def _is_filled_event(msg: dict) -> bool:
        if msg['e'] == 'executionReport':
            if msg['x'] == 'TRADE' and msg['X'] == 'FILLED':
                return True
        return False

if __name__ == '__main__':
    worker = BinanceSocket(
        api_key='****',
        api_secret='****'
    )

    worker.start()
    time.sleep(2)
    worker.stop()
```
 as you can see in `stop()` function i call to `binance_stream.stop_socket(self.connection_key)` but this thread still running and not exit.

Anyone can help me stop socket correctly in my usecase.

Thanks!

**Comment by frangte** [comment]
And this is result after using `Ctrl` + `c`.

![image](https://user-images.githubusercontent.com/19859575/51623748-f4c4a300-1f6b-11e9-8fc9-a1d51d9b9f92.png)

**Comment by CJ1976** [comment]
I have never had luck with stop_socket working. I have always used bm.close per this issue. https://github.com/sammchardy/python-binance/issues/202

Bm.close will close the socket but leave the socket manager open. You can add new sockets to the socket manager at any time. One word of warning. If you close the socket you used to open the socket manager with, it runs like a fat lazy dog on reconnect. I always just leave my opening socket open and ignore values until I want them. That way other sockets don't take several seconds to reconnect and you have some responsiveness.

**Comment by frangte** [comment]
Resolve this issue with `canel()` timer.
