### ISSUE TITLE
Websocket stops randomly

### ISSUE THREAD

**Issue by joshuar87** [sammchardy/python-binance#364]
Hi, I run the python binance websocket 24/7. Sometimes the socket will run fine for a few days and sometimes for a few hours before pausing (closing?). Is it possible to autostart the socket everytime this happens or would you simply recommend setting a timer/chron to restart the socket on the hour every hour just in case?

**Comment by mfurlend** [comment]
I have the same issue/question

**Comment by henboss** [comment]
Hi guys, I am also experiencing this issue. Did you make any progress on it?

**Comment by thiblab** [comment]
Hi,
Same problem here... Any news about this issue ?
