### ISSUE TITLE
I got **error: command 'C:\\.....\\Microsoft visual Studio\\2017\\community\\VC\\Tools\\MSVN\\14.16.27023\\bin\\HostV86\\cl.exe' failed with exit code 2** while installing a module.

### ISSUE THREAD

**Issue by raokiran841** [sammchardy/python-binance#365]
I got **error: command 'C:\\.....\\Microsoft visual Studio\\2017\\community\\VC\\Tools\\MSVN\\14.16.27023\\bin\\HostV86\\cl.exe' failed with exit code 2** , while installing the **module** **lulu**.
i have installed **Microsoft Visual Studio,** also tried downloading **Twisted-18.9.0-cp37-cp37m-win32.whl** but none of them worked. i am on Windows 7. Any idea what exactly is th eproblem?

_Originally posted by @raokiran841 in https://github.com/sammchardy/python-binance/issues/148#issuecomment-458383642_

**Comment by nshiff** [comment]
can you please provide a list of the steps to reproduce, along with a short description of the expected and observed behavior?

**Comment by 7549brijesh** [comment]
hi check this out i found something that could help you out?
[https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158/44563421](url)

**Comment by Narjous** [comment]
Hi , i have same problem ! 
    c:\users\atia\anaconda3\include\pyconfig.h(59): fatal error C1083: Impossibl
e d'ouvrir le fichier include : 'io.h' : No such file or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2017\\BuildTools
\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit stat
us 2

    ----------------------------------------
  Rolling back uninstall of pocketsphinx
  Moving to c:\users\atia\anaconda3\lib\site-packages\pocketsphinx-0.1.15.dist-i
nfo\
   from c:\users\atia\anaconda3\lib\site-packages\~ocketsphinx-0.1.15.dist-info
  Moving to c:\users\atia\anaconda3\lib\site-packages\pocketsphinx\
   from c:\users\atia\anaconda3\lib\site-packages\~ocketsphinx
  Moving to c:\users\atia\anaconda3\lib\site-packages\sphinxbase\
   from c:\users\atia\anaconda3\lib\site-packages\~phinxbase
Command "c:\users\atia\anaconda3\python.exe -u -c "import setuptools, tokenize;_
_file__='C:\\Users\\ATIA\\AppData\\Local\\Temp\\pip-install-i73feizv\\pocketsphi
nx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace(
'\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
C:\Users\ATIA\AppData\Local\Temp\pip-record-czf8kgzn\install-record.txt --single
-version-externally-managed --compile" failed with error code 1 in C:\Users\ATIA
\AppData\Local\Temp\pip-install-i73feizv\pocketsphinx\


Any solution please ! 
Ps : i have installed visual studion 2017 , but still the same problem .
Thanks ,
