### ISSUE TITLE
Order with type ORDER_TYPE_STOP_LOSS causes API Error code 1106

### ISSUE THREAD

**Issue by kenneho** [sammchardy/python-binance#367]
Hi.

I'm trying to create a stop loss order, using this code (with other values than in the example): 

`order = self.client.create_order(
           symbol="ETHBTC",
           side=SIDE_SELL,
           type=ORDER_TYPE_STOP_LOSS,
           quantity="1.000",
           price="1.000")`

Running the code causes this error from the Binance API: `binance.exceptions.BinanceAPIException: APIError(code=-1106): Parameter 'price' sent when not required.`

How can I place a stop loss order?

**Comment by anson-vandoren** [comment]
If you want a stop loss, try `order_limit_sell` instead. Relevant [documentation here](https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.order_limit_buy), and you'd use the parameter `stopPrice`

**Comment by kenneho** [comment]
> If you want a stop loss, try `order_limit_sell` instead. Relevant [documentation here](https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.order_limit_buy), and you'd use the parameter `stopPrice`

Thanks for the quick reply!

I tried this code: `order = self.client.order_limit_sell(
            symbol=trade_pair_name,
            quantity=quantity,
            stopPrice=price)`

The result was this:  `binance.exceptions.BinanceAPIException: APIError(code=-1106): Parameter 'stopPrice' sent when not required.`

What am I missing?

**Comment by kenneho** [comment]
By the way, I think I got this to work: 
`order = self.client.create_order(symbol=trade_pair_name, side=SIDE_SELL, type=ORDER_TYPE_STOP_LOSS, quantity=quantity, stopPrice=price)`.

If I'm not mistaking, the `stopPrice` parameter is not documentet in [the API documentation](https://python-binance.readthedocs.io/en/latest/_modules/binance/client.html#Client.create_order).

**Comment by jiwoongim** [comment]
I don't think STOP_LOSS is supported anymore, only STOP_LOSS_LIMIT

**Comment by avatar-lavventura** [comment]
I keep having `*** binance.exceptions.BinanceAPIException: APIError(code=-1116): Invalid orderType.` for :

```
 client.futures_create_order(symbol=_symbol, side=client.SIDE_SELL,
type=client.ORDER_TYPE_STOP_LOSS_LIMIT, quantity=1, stopPrice=80.0)
```

**Comment by jvzl** [comment]
> I don't think STOP_LOSS is supported anymore, only STOP_LOSS_LIMIT
 
It is actually the opposite.

**Comment by jinglescode** [comment]
I'm testing on hedge mode. I aim to create a new order (market open) and set stop loss at 1% below the `avgPrice`.

What I am currently doing to achieve this:

- open a long position on hedge mode
```
order = client.futures_create_order(
    symbol=trade_symbol,
    side=Client.SIDE_BUY,
    type=Client.ORDER_TYPE_MARKET,
    quantity=quantity,
    positionSide="LONG"
)
```

- wait for order to get filled: `order["status"] == "FILLED"`
- get the `order["avgPrice"]` and calculate the price 1% below `avgPrice` call `stopPrice`
- create a stop loss order
```
order = client.futures_create_order(
    symbol=trade_symbol,
    side=Client.SIDE_SELL,
    type=Client.ORDER_TYPE_STOP_LOSS,
    quantity=quantity,
    positionSide="LONG",
    stopPrice=stopPrice,
)
```

I cant get the stop loss order to work, getting this error `APIError(code=-1116): Invalid orderType.`. I have tried both `ORDER_TYPE_STOP_LOSS_LIMIT` and `ORDER_TYPE_STOP_LOSS`. What am I missing? Or is there a easier way to achieve what I want to?
