### ISSUE TITLE
Functions that retrieve exchange info are not formatted 

### ISSUE THREAD

**Issue by scrapweston** [sammchardy/python-binance#369]
I'm not sure what this is related to but when I run the functions in terminal such as getting exchange information about a certain trading pair, there are no newlines or formatting thus rendering things like the order book impossible to read. Does anybody know what the issue might be?

**Comment by sammchardy** [comment]
If you're printing out the dict response it will be unformatted, one option I like is the json indent output format

```
import json
print(json.dumps(res_dict, indent=2))
```

**Comment by scrapweston** [comment]
That's really cool, thank you
