### ISSUE TITLE
TypeError: get_klines() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by italodesouzacolombi** [sammchardy/python-binance#373]
Good night!

When I play my code in this part:

**klines = get_historical_klines("BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC")**

the error msg show me this:

**TypeError                                 Traceback (most recent call last)**
**<ipython-input-8-2de6df5af4de> in <module>**
**----> 1 klines = get_historical_klines("BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC")**

**<ipython-input-7-e7988433c9c1> in get_historical_klines(symbol, interval, start_str, end_str)**
     **26             interval=interval,**
     **27             startTime=start_ts,**
**---> 28             endTime=end_ts,**
    **29**
     **30         )**

**TypeError: get_klines() missing 1 required positional argument: 'self'**

I didn't know how can i fix it. Did anyone can help me, please?
What is argument 'self'?

**Comment by anthonytxie** [comment]
This is because you're not instantiating client. 

client = Client(api_key, api_secret)

after that write

client.get_historical_klines("BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC")

**Comment by tsagkarakis17** [comment]
Thanks bro!!!

**Comment by zks511** [comment]
Thnak you that was helpful
