### ISSUE TITLE
Meaning of 'isBuyerMaker' and 'isBestMatch'?

### ISSUE THREAD

**Issue by combstraight** [sammchardy/python-binance#374]
Hello, I am currently pulling historical data and get the following dictionary key:value pair from Binance: 

`'isBuyerMaker': True `

and 

`'isBestMatch': True.`

I was wondering what the pairs signified.

I'm guessing if `'isBuyerMaker'` is `True`, that means the order was filled by seller market selling into a maker and if it's `False`, the order was filled by a buyer market buying into a maker?  

I'm also guessing `isBestMatch` just means that the price of the buyer was matched with a seller, but am wondering when this would return `False`.

**Comment by farzadso** [comment]
Yes, both your assumptions are completely correct. Sadly the API docs don't state this.

**Comment by Sabrebar** [comment]
Does anyone know when `isBestMatch` would return `False`?

**Comment by tuncel3** [comment]
Maybe it means the best match quantity was not enough and the second match is used to complete the trade.

**Comment by hgfernan** [comment]
Very enlightening post, that solved my doubts. Thanks, guys !
