### ISSUE TITLE
pip python-binance install issue

### ISSUE THREAD

**Issue by lee12121** [sammchardy/python-binance#377]
#include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-BFCwfK/Twisted/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Kxr7jJ/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-BFCwfK/Twisted/

im fairly new to this and im using linux fed 29

**Comment by lee12121** [comment]
python 3.7.1

**Comment by alpalwal** [comment]
Figured it out:
https://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet

sudo yum install python-devel
