### ISSUE TITLE
Timestamp offset recommendation

### ISSUE THREAD

**Issue by hockeyadc** [sammchardy/python-binance#379]
Recommend modifying the following to the if signed: portion of the _request function, in order to accommodate for any server/local time difference.:

`if signed:`    
`     local_time = int(time.time() * 1000)`  
`     server_time = self.get_server_time()`  
`     time_diff = server_time['serverTime'] - local_time`  
`     kwargs['data']['timestamp'] = int(time.time() * 1000 - time_diff)`  
`     kwargs['data']['signature'] = self._generate_signature(kwargs['data'])`

**Comment by florentduchesne** [comment]
Isn't it the same as : 
`if signed:`
`server_time = self.get_server_time()['serverTime']`
`kwargs['data']['timestamp'] = server_time`
?
It worked for me.
What you are doing is "localTime - (serverTime - localTime)", which is the same as "serverTime" alone.

**Comment by shifatul-i** [comment]
> Isn't it the same as :
> `if signed:`
> `server_time = self.get_server_time()['serverTime']`
> `kwargs['data']['timestamp'] = server_time`
> ?
> It worked for me.
> What you are doing is "localTime - (serverTime - localTime)", which is the same as "serverTime" alone.

how can we make this change without touching the library?
