### ISSUE TITLE
ethbtc@depth20@0ms can't stream uncompressed updates 

### ISSUE THREAD

**Issue by JMedon** [sammchardy/python-binance#38]
Hi
I would like to receive socket data without compressed updates like descripted in below notes
https://gist.github.com/sammchardy/5515afe1dff84475098f669a62558860

Unfortunately I didn't receive anything, ethbtc@depth20 works but ethbtc@depth20@0ms not.
conn_key = bm.start_multiplex_socket(['ethbtc@depth20@0ms'], process_m_message)

@sammchardy
how can I develop it?
thanks in advance

**Comment by sammchardy** [comment]
Hi @JMedon unfortunately Binance have discontinued the @0ms parameter.
All endpoints will update about once per second.
I would suggest asking for it on the Binance API Telegram channel https://t.me/binance_api_english
