### ISSUE TITLE
 ORDER_TYPE_STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT'

### ISSUE THREAD

**Issue by maysam19** [sammchardy/python-binance#380]
Hello there!

Had a simple question. Trying to understand API syntax for placing a market order to go long any symbol, but using the  ORDER_TYPE_STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT' in order to set a limit to exit and a stop to preserve loss downside at same time. Looking through the api docs, I do not see a clear example of this in practice. 

Was thinking something like this:

# Create market order first: 

order = client.create_order(
    symbol='BNBBTC',
    side=SIDE_BUY,
    type=ORDER_TYPE_MARKET,
    timeInForce=TIME_IN_FORCE_GTC,
    quantity=100)

# Create stop loss limit order:

order = client.create_order(
    symbol='BNBBTC',
    side=SIDE_BUY,
    type=ORDER_TYPE_STOP_LOSS_LIMIT,
    timeInForce=TIME_IN_FORCE_GTC,
    quantity=100,
    **limit=?
    stop =?)**

I have bolded above, because for the stop loss limit order, what do we define , or how do we define the actual stop price and limit price in terms of syntax? (what I have bolded above) Appreciate the kind help as always!

Best,

Sam

**Comment by eelith** [comment]
Hi.

Here are some examples of orders:

case the price drop down:

client.create_oco_order(
        symbol='BTCUSDT',
        side='SELL',
        stopLimitTimeInForce='GTC',
        quantity= 1,
        stopPrice= 9891.55,
        stopLimitPrice= 9890.55,  
        price= 9908.18)


if the price goes up:

client.create_oco_order(
        symbol='BTCUSDT',
        side='BUY',
        stopLimitTimeInForce='GTC',
        quantity= 1,
        stopPrice= 9958.70,
        stopLimitPrice= 9957.70,  
        price= 9908.18)

i hope this helps

**Comment by jinglescode** [comment]
Hello! I'm testing on hedge mode. I aim to create a new order (market open) and set stop loss at 1% below the `avgPrice`.

What I am currently doing to achieve this:

- open a long position on hedge mode
```
order = client.futures_create_order(
    symbol=trade_symbol,
    side=Client.SIDE_BUY,
    type=Client.ORDER_TYPE_MARKET,
    quantity=quantity,
    positionSide="LONG"
)
```

- wait for order to get filled: `order["status"] == "FILLED"`
- get the `order["avgPrice"]` and calculate the price 1% below `avgPrice` call `stopPrice`
- create a stop loss order
```
order = client.futures_create_order(
    symbol=trade_symbol,
    side=Client.SIDE_SELL,
    type=Client.ORDER_TYPE_STOP_LOSS,
    quantity=quantity,
    positionSide="LONG",
    stopPrice=stopPrice,
)
```

I cant get the stop loss order to work, getting this error `APIError(code=-1116): Invalid orderType.`. I have tried both `ORDER_TYPE_STOP_LOSS_LIMIT` and `ORDER_TYPE_STOP_LOSS`. What am I missing? Or is there a easier way to achieve what I want to?
