### ISSUE TITLE
Replace Twisted with a native Python library

### ISSUE THREAD

**Issue by hANSIc99** [sammchardy/python-binance#382]
I'm working on an app ([Pythonic](https://github.com/hANSIc99/Pythonic)) which enables you to create your own trading bots very easy.
Because I also use the python-binance for communication with the exchange, I figured out that the installation process often failes because of the depency twisted (it requires a compiler and some source files on the target system).

Is it possible to replace twisted with some native Python code?

**Comment by globophobe** [comment]
Twisted is a dependency for autobahn, which is for websockets.

**Comment by hANSIc99** [comment]
Nice to see!
I made my own trimmed version now containing only
the REST-api for my project:
[https://github.com/hANSIc99/pythonic-binance](https://github.com/hANSIc99/pythonic-binance)
