### ISSUE TITLE
Speeding up opening of depthcachemanagers

### ISSUE THREAD

**Issue by skazazes** [sammchardy/python-binance#387]
Hello,

I'm writing a program that is heavily reliant on DepthCacheManagers. I am trying to start ~50 of them at once and do to the blocking nature of the underlying requests library this is currently taking ~3-5 minutes.

I have seen some issues suggesting threadpools to speed up large quantities of requests but am unsure how to implement them in this case.

Any help would be appreciated

**Comment by sammchardy** [comment]
Hi @skazazes I have an asyncio branch that may resolve your issue.

Try it out here, there's examples in the README.rst on the branch
https://github.com/sammchardy/python-binance/tree/feature/asyncio
