### ISSUE TITLE
Non-catched Connection aborted.', OSError("(104, 'ECONNRESET')") error

### ISSUE THREAD

**Issue by MarcelBeining** [sammchardy/python-binance#389]
Hi there,
if I run the websocket for a while I occassionally get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 1158, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/binance/websockets.py", line 473, in _keepalive_user_socket
    user_listen_key = self._client.stream_get_listen_key()
  File "/usr/local/lib/python3.7/site-packages/binance/client.py", line 2036, in stream_get_listen_key
    res = self._post('userDataStream', False, data={})
  File "/usr/local/lib/python3.7/site-packages/binance/client.py", line 210, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/binance/client.py", line 175, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
```

Unfortunately, since that error happens in the thread at arbitrary times I cannot catch it. Could you please implement a catch for that kind of exception? @sammchardy

**Comment by MarcelBeining** [comment]
PS: I found in this issue
https://stackoverflow.com/questions/43165341/python3-requests-connectionerror-connection-aborted-oserror104-econnr
that the error could be because of non-specified headers.

**Comment by bithon** [comment]
What OS are you running, Mac?

I experienced that OSError and ConnectionResetError seems to be very Mac specific (they dont get thrown on my win and linux, only on mac) and the reason on my system is "no internect connection".

It seems you need an exception in:
  File "/usr/local/lib/python3.7/site-packages/binance/client.py", line 175, in _request
    response = getattr(self.session, method)(uri, **kwargs)

**Comment by charlesdarkwind** [comment]
Hi occasionally get this too with REST on windows. Could be Binance's side?

**Comment by fqlx** [comment]
I'm seeing this error on CentOS so it's not OSX specific

**Comment by miketrimmel** [comment]
I get this error on Ubuntu.

**Comment by xjpf** [comment]
It cannot be headers, because requests/sockets works for period of time. But after you leave it for a minutes and try request again - it will give this error.
It definetely from server side. Probably binance-python do not making pong anwers as Binance requires?

**Comment by goodyjoon** [comment]
I also get this at least once a day, in Ubuntu

**Comment by goldan** [comment]
Same here, ubuntu, every 10 min or so.

**Comment by ChaosEmpire** [comment]
same here, telegram bot script, every 10 seconds polled, with sometimes edit or  new messages,,mostly runs the whole day..mostly at night (not only night) suddenly it crshes..

also a crash always happens at dsl disconnect time, but why does t crash outside of the disconenc,t why mostly at night..

and why i cant get this catched

**Comment by baeriswyld** [comment]
just seeing this error the first time. (ubuntu). Any idea what it is?

**Comment by emceef94** [comment]
Still same issue, has anyone solved it? It happens at random times, sometimes it works minutes, sometimes hours, and sometimes days without giving this error

**Comment by xuelabi123** [comment]
Has anyone solved it?

**Comment by oliver-zehentleitner** [comment]
I had this also now on a very stable internet connection. Maybe its on binance side when they deploy an update and restart their services...

**Comment by miketrimmel** [comment]
Could be the reason yes...the binance system had problems today.

**Comment by emceef94** [comment]
I suggest you read the dates posted, nothing to do with today

**Comment by miketrimmel** [comment]
Oliver wrote had it now...und he postet it 2hours ago so I assumed he got it today

**Comment by emceef94** [comment]
Yes but the problem has been happening for months, this is not the only thread with the same problem and no one has been able to solve it

**Comment by oliver-zehentleitner** [comment]
finally it just means, the endpoint resetet the connection. binance docs are saying, they will do it every ~24 hours. so thats ok. it should get fetched and the connection reestablished..

**Comment by ddeanto** [comment]
Has anyone been able to figure this out? I've tried resetting the connection every 30 minutes which seems to mitigate the issue but not completely solve it.

**Comment by Mindeliu** [comment]
Having the same problem

**Comment by Ad4mk0** [comment]
same issue, looks like it appeared at utc midnight time but I am not sure...
Is it some kind of  binance api reset or have somebody found out how to fix this?

**Comment by WHug0** [comment]
Hi,
I have the exact same issue... my script is the same as exposed here.
Have someone a solution ?
Thanks

**Comment by Mindeliu** [comment]
@WHug0 If possible switch to Websockets instead of using REST API. At least thats what I did and now it seems to be working fine.

**Comment by WHug0** [comment]
@Mindeliu what's the difference between WebSockets and Rest API ? I'm new here ^^

**Comment by Mindeliu** [comment]
@WHug0 

> WebSockets provide a persistent connection between a client and server that both parties can use to start sending data at any time.

In other words, instead of making a request to a server every time you need to get data (In my case every couple seconds), you open a connection to a said server and it send the data to you when something changes without any additional requests.

**Comment by WHug0** [comment]
@Mindeliu ok understood, thx a lot for all the explanations !

**Comment by WHug0** [comment]
Websockets doesn't solve this issue...

**Comment by 2pd** [comment]
anyone can help to provide a script that reproduce this issue? thanks

**Comment by topp** [comment]
I got today the same error when using client.aggregate_trade_iter() to get historical trades from BNBBTC market.
I explicitly mention the symbol here, since I had no probs at all with the exact same procedure and versions reading other symbols data.
Python: 3.8.2
python-binance: 0.7.5

**Comment by 37dev** [comment]
Also did get it when using CoinGecko python wrapper.. The code where this error happened is commented but previously wasn't.. This might be common. A temporary solution would be a try/except  with a retry

**Comment by beatslikeahelix** [comment]
Does anyone get this issue while using CCXT or just python-binance?

**Comment by ingega** [comment]
Hi It´s november and the same error raise every time, some times it´s every hours, some times it's every days, so, i try to do something like

try:
    my_code
except:
    time.sleep(1)  
   #return to my _code here

but appears doesn´t work, so, it´s awfull because your bot stop work  ;(

Some one has found a solution?

**Comment by beatslikeahelix** [comment]
Yeah, it’s fairly soul destroying. If we knew this error was exclusive to this library I’d consider rewriting in ccxt or something, but don’t really want to do that in case it’s actually a Binance issue.

**Comment by ingega** [comment]
mmmm i think in this solution, what´s your opinion, first i try ping, if work, run my rutine, else i can wait 100 ms, something like:

try:
   client.ping
  #run my rutine
except:
   time.sleep(0.1) #100 ms would be enough?

maybe?

**Comment by ingega** [comment]
i just write to binance help, but i've receveid these one:

CS Land (Binance)

Nov 19, 2020, 0:20 GMT+8

Dear user,

Thanks for reaching out.

Since the error you provided has been processed by your program, we couldn't for sure whether it caused by the incorrect request or the network issue. 

We recommend you record the raw error message that responds from the server. Then we could check for you further.

Thank you for your understanding, we are looking forward to hearing from you soon.

Best Regards,
Binance Support Team

mmmm souspicius!!!! a lot of users had the same error? i don't think so!!!

**Comment by ddeanto** [comment]
@ingega what is the error/traceback you sent them? I've been getting this error on a weekly basis for 3 years now and have tried sleeping then reconnecting which only works sometimes. I wonder if we are getting throttled?

**Comment by ingega** [comment]
Yeahhh @ddeanto i think the same, and maybe exist posibilitie, this API (python-binance) raise the error? maybe we must try with another api and tried it, but sincerily, this is the most complete api for binance, well, maybe worth it

**Comment by kimchirichie** [comment]
in my experience, i had a better time using `oliver-zehentleitner/unicorn-binance-websocket-api` for websockets

**Comment by blacksabbather** [comment]
Need to re-initialize the session after encountering this problem which means you should re-do below:
client = Client('xxxx','xxxx')

**Comment by anubis-ii** [comment]
@blacksabbather Does that always work? Or it can still fail sometimes, like the other workarounds?

**Comment by blacksabbather** [comment]
> @blacksabbather Does that always solve it? Or it can still fail sometimes, like the other workarounds?

I advised one user to do that and the user never complained about it ever since

**Comment by beatslikeahelix** [comment]
@blacksabbather Do you have a working catch in your own code?
I tried filtering each endpoint in my  my bot Class through a function like this:

```python
def handle_connection_error(self, endpoint, timeout = 60):
    start_time = time.time()
    while True:
        try:
            return endpoint
        except ConnectionError:
            if time.time() > start_time + timeout:
                raise Exception(f'Unable to get updates after {timeout} seconds of ConnectionError.')
            else:
                self.init_client()
                time.sleep(1)
```

but I always get the ECONRESET error without it reconnecting or raising my own exception. Anyone got ideas as to what might be going wrong?

**Comment by AntShestak** [comment]
> Need to re-initialize the session after encountering this problem which means you should re-do below:
> client = Client('xxxx','xxxx')

Thanks, this works for me. Catch exception, sleep some, re-initialize Client. It still doesn't solve issue, but is a good workaround.



> i just write to binance help, but i've receveid these one:
> 
> CS Land (Binance)
> 
> Nov 19, 2020, 0:20 GMT+8
> 
> Dear user,
> 
> Thanks for reaching out.
> 
> Since the error you provided has been processed by your program, we couldn't for sure whether it caused by the incorrect request or the network issue.
> 
> We recommend you record the raw error message that responds from the server. Then we could check for you further.
> 
> Thank you for your understanding, we are looking forward to hearing from you soon.
> 
> Best Regards,
> Binance Support Team
> 
> mmmm souspicius!!!! a lot of users had the same error? i don't think so!!!

More likely issue is on our side (python-binance)

**Comment by ddeanto** [comment]
Dear lord can somebody fix this, I will pay them a BNB coin. This bug is ruining my life. If not, I will have time to look into it maybe in April. @kimchirichie you seem active lately, do you have any thoughts on this?

**Comment by danotrilogic** [comment]
> Dear lord can somebody fix this, I will pay them a BNB coin. This bug is ruining my life. If not, I will have time to look into it maybe in April. @kimchirichie you seem active lately, do you have any thoughts on this?

Hi, 

I'm facing this issue. I'll let you know if I figure out what's happening on the back stage, checking python-binance at the moment.

Regards.

**Comment by jimrough** [comment]
could this be related to the X-MBX-USED-WEIGHT values in the headers' response ? I haven't seen any test on this in the python code (_handle_response())

my 2 cents...

**Comment by sammy1193** [comment]
I'm having the same issue only on Ubuntu. Running my code on windows doesn't produce this issue at all

**Comment by greyfoxamine** [comment]
I HAVE been facing and dealing with this issue since last march , the only workaround i've found is to rerun my script after crash to the point he where !!

**Comment by OAI17** [comment]
Hey anyone  could fix it ?? I try the reconnection in the beginning of the while and in the end but nothing

**Comment by beatslikeahelix** [comment]
Looks like python-binance is due for a major update in May. Here's hoping this issue might be resolved, but I'm not holding my breath.

**Comment by ddeanto** [comment]
@beatslikeahelix re https://github.com/sammchardy/python-binance/issues/389#issuecomment-830238464 where are you seeing this? May you share the link? thanks

**Comment by beatslikeahelix** [comment]
It’s currently the first thing in the README.rst on the main page. Mentions asychio updates and ditching legacy to make everything Python 3.6+. My hopes are not high, but a man can dream.

**Comment by baichishow** [comment]
so nobody know how to fix it yet...

**Comment by ddeanto** [comment]
Has updating to v1+ helped mitigate the issue?

**Comment by beatslikeahelix** [comment]
Not been running bots recently, but back during summer I didn't experience the issue at all when using the new web socket implementation on 1+. Had a script running on an AWS server for about 5 days with no interruptions. Maybe I just got lucky though!

**Comment by Kospie** [comment]
I solved the issue by handling ConnectionError and restart the client like:

`from binance.client import Client, BinanceAPIException
from requests.exceptions import ConnectionError

client = Client(api_key=" ", api_secret=" ")
while True:
  try:
    #my code
    time.sleep(2)
  except (BinanceAPIException, ConnectionError) as e:
    print(e)
    client=Client(api_key=" ", api_secret=" ")
    time.sleep(2)
    continue`

I have the ConnectionError once in 2 days or so, but the code is running smoothly over 2 weeks.
I do not have BinanceAPIExcpetion nowadays but I still put the exception as I had the error when I started running this code.

**Comment by YunTaeIl** [comment]
Can't you just suppress the error itself? I tried every method I found, but in the end I got an error. Most of the answers are to create a new client in exception handling. This is not a workaround.

**Comment by beatslikeahelix** [comment]
Not sure what you mean by suppress. In Python warnings can be suppressed, but errors will break your code, meaning they need to be handled. Since the connection error is ultimately induced by Binance servers cutting you off, it stands to reason that reestablishing a connection (by reinitialising the client) is pretty much the only way to fix things.

**Comment by rumblefish07** [comment]
If i reinitialise the client, does the variables that script created before will be lost?
