### ISSUE TITLE
Get indicators

### ISSUE THREAD

**Issue by joaoantoniopereira** [sammchardy/python-binance#39]
Hi!
Thanks for this tool.
I cannot find the method to get the indicators such as DMI, OBV, etc. that are available on Exchange -> Advanced. Is this possible to get these values with binance api?
If not do you recommend other python library to get these values?
Thanks again!
João

**Comment by sammchardy** [comment]
Hi @joaoantoniopereira these indicators are not provided by the REST API.
I would recommend a library such as TA-Lib https://github.com/mrjbq7/ta-lib which will should have the indicators you need.

**Comment by joaoantoniopereira** [comment]
Thanks!
