### ISSUE TITLE
Asyncio python 3.7

### ISSUE THREAD

**Issue by thomas-leeee** [sammchardy/python-binance#391]
Hi, do you have any updates regarding asyncio support? How stable is the branch feature/async at the moment? Thank you.

**Comment by sammchardy** [comment]
Hi, the branch is quite stable. I have used it in a few projects now. 

I think I may replace the main version with this one now that python 3.6 support is more prevalent. Removing any existing python 2.7 legacy code which will solve a lot of issues for people I think. 

Try out the branch and let me know if you have any recommendations.

**Comment by thomas-leeee** [comment]
Thanks. Do you have some examples on how to get started? I could not get the async to run forever with the following

`
from binance.client_async import AsyncClient
from binance.websockets_async import BinanceSocketManager
import asyncio


async def candles_websocket():
    client = AsyncClient('', '')
    info = await client.get_exchange_info()
    trading = [dct['symbol'] for dct in info["symbols"] if dct['status'] == 'TRADING']
    bm = BinanceSocketManager(client, asyncio.get_running_loop())
    stream_names = ['{}@kline_{}'.format(symbol.lower(), '1m') for symbol in trading]  # pass a list of stream names
    conn_key = await bm.start_multiplex_socket(stream_names, process_m_message)


async def process_m_message(msg):
    ''' For multiplexed stream, append closed candle '''
    print("stream: {} data: {}".format(msg['stream'], msg['data']))

async def my_other_coro():
    pass

async def main():
    await asyncio.gather(candles_websocket(),my_other_coro())

if __name__ == "__main__":
    asyncio.run(main())
`

**Comment by sammchardy** [comment]
Hi @thomas-leeee I have updated the branch to include some examples in the README.rst.

I've also cleaned up the code a bit to make sure it's up to date with the existing library.

Let me know what you think.

https://github.com/sammchardy/python-binance/tree/feature/asyncio
