### ISSUE TITLE
create new (market) order specifying the quote asset, not the base asset

### ISSUE THREAD

**Issue by alvarolloret** [sammchardy/python-binance#392]
I wanted to know if it's possible to create a new market order from the quote asset.

For example, if in my account I have 100 USDT and I want to buy BTC worth 20$, how could I do that?

from what I see you can only place an order specifying the quantity of BTC you want to buy, not how many USDT you want to spend.

From the python API seems impossible to do so:

```
order = client.order_market_buy (

symbol='BTCUSDT',

quantity=0.01, #in BTC not in USDT

)
```
Thanks!

**Comment by p-i-** [comment]
Use `quoteOrderQty`
