### ISSUE TITLE
Orders issue

### ISSUE THREAD

**Issue by DanielJavierMartinez** [sammchardy/python-binance#394]
Hi, I'm having a problem with orders on Binance.

Before Binance platform got hacked my scripts were working fine, but since the security issue has been fixed I can't make market orders anymore (nor even test orders). I always receive 2015 error. 

Can you help me solve this problem?

Best regards.

**Comment by mtm85** [comment]
Everybody has to renew API keys. All API keys got erased. Good luck!

**Comment by DanielJavierMartinez** [comment]
I've already renewed the API keys (twice) just after the fix, but the problem still persists.

**Comment by Sladerix** [comment]
hi have the same issue, I'm trying to use the library on python, I just created the apikey but I got this error while creating an order
