### ISSUE TITLE
Async + Tornado

### ISSUE THREAD

**Issue by jonathan-daniel** [sammchardy/python-binance#397]
Hello, 

It seems that you are using aiohttp for the async branch, which does not work well with Tornado because it will give the following error:

```
RuntimeError: Timeout context manager should be used inside a task
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb77cab7e48>
```

I think the problem is that every aiohttp request uses Timeout and thats not supported with Tornado. 
Did you try using your async branch with tornado?

I will in the meantime write a version that doesnt use aiohttp and will work with tornado Tasks.

**Comment by HUMZZY** [comment]
Hay how would I no if people are hacking my stuff Shaik’s go missing difrebt ipcadress show and unknown activity it’s these little thief’s just send me the adress so I get my stuff back even I have stomp in there heads I’ve worked 10 years like a dog and they want to take it away from me not if I’m alive

**Comment by jonathan-daniel** [comment]
@HUMZZY your mistake was working like a dog
