### ISSUE TITLE
new to trading bot

### ISSUE THREAD

**Issue by Wouterdutoitpieter** [sammchardy/python-binance#40]
i would like to start using the trading bot but dont know how to start , if anyone can give a step by step of to start . Thanx

**Comment by jeffro256** [comment]
Take a look at the Documentation: https://python-binance.readthedocs.io/en/latest/

**Comment by sammchardy** [comment]
Left this open for a bit, maybe someone wanted to help you. Closing now as it's unrelated to the scope of the library.
