### ISSUE TITLE
need help with printing output

### ISSUE THREAD

**Issue by ebinum83** [sammchardy/python-binance#402]
ive been trying to code an app were the user enters a symbol and the app the prints the result to the screen with symbol and price. but with no joy as of yet.

can anyone give me some help please, her is a snippet of my code so far:

                                  def tickers(self):
                                        tickers = self.client.get_all_tickers(symbol, price)
                                        option = input()
                                        print('Enter Symbol')
                                        print('symbol : price')

**Comment by pisulski** [comment]
read about printing dictionary on python.
