### ISSUE TITLE
Problem with Price Filter.

### ISSUE THREAD

**Issue by pisulski** [sammchardy/python-binance#403]
Hello Sammchardy
I would like to ask you about explanation.
I am trying to write module for checking a filter restrictions.
I am using your code for formatting a amounts like this:

`return float("{:0.0{}f}".format(self.inputamount, self.precision))
`
I am trying to check conditions for price_filter. This condition

    

- price >= minPrice
- price <= maxPrice
- (price-minPrice) % tickSize == 0

Third condition is always True for this code.
```
amount = self.formatamount - self.cpy.returnminPrice()

if amount % float(self.cpy.returntickSize()) != 0:
```

What do I wrong? Why this condition is not equal 0?
Or what do I not understand.
I prepare order_test and tested it and Binance server do not ask about this amount . I have answare that only PERCENT_PRICE did not pass.

How to write code this condition?

Regards

**Comment by pisulski** [comment]
i used exactly this method from link and as i said third condition above did not pass.
https://github.com/sammchardy/python-binance/issues/91#issuecomment-391820545

**Comment by alexcrownjr** [comment]
this works for me

def floatPrecision(f, n):
	n = int(math.log10(1 / float(n)))
	f = math.floor(float(f) * 10 ** n) / 10 ** n
	f = "{:0.0{}f}".format(float(f), n)
	return str(int(f)) if int(n) == 0 else f

tick_size = deal.limitQty['tickSize']
round_price = floatPrecision(price, tick_size)
