### ISSUE TITLE
Invalid LOT size

### ISSUE THREAD

**Issue by jonathan-daniel** [sammchardy/python-binance#41]
2017-12-20 03:00:01 buying 0.00572925 at: 7.394e-05 (VENBTC)

gives me APIError(code=-1013): Filter failure: LOT_SIZE

I used client.order_market_buy()

**Comment by sammchardy** [comment]
@jonathan-daniel have a read of the Binance API docs regarding the LOT_SIZE here https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#lot_size

You can get the info about a symbol from the `get_exchange_info()` call, if you upgrade to v0.5.6 of python-binance there's a new `get_symbol_info()` call which you can use like so

```
bnbbtc_info = client.get_symbol_info('BNBBTC')
```

**Comment by jonathan-daniel** [comment]
Thank you it was the step size.
