### ISSUE TITLE
Missing  'filterType': 'MARKET_LOT_SIZE'

### ISSUE THREAD

**Issue by pisulski** [sammchardy/python-binance#413]
Missing limit parametrs for BCCBTC.
Your api do not want to return 'filterType': 'MARKET_LOT_SIZE' for  BCCBTC.

**Comment by pisulski** [comment]
should exist. otherwise mapping a parametrs i complicated.

**Comment by pisulski** [comment]
ok 'status': 'BREAK'.
everything clear

**Comment by pisulski** [comment]
This problem exist also on PHBBNB.
Can someone look on it?

**Comment by pisulski** [comment]
sammchardy is that problem in your API or on binance side?
Can you check and ask somebody from binance?

**Comment by sammchardy** [comment]
Hi @pisulski this is on the Binance side, not all symbols support all filter types.
