### ISSUE TITLE
Pip install python-binance issue

### ISSUE THREAD

**Issue by mkang1234** [sammchardy/python-binance#414]
I'm trying to install the asyncio branch of this package. Previously, I had v0.7.2 installed.  For some reason, I can't seem to get this new version installed. When I uninstalled the old version and tried to install this new package using pip install python-binance, it keeps installing the 0.7.2 version. 

I cleared out my pip cache folder and even tried doing a pip install python_binance==0.7.1 to try to force it to install the Async version.  When I did that, it created 3 different files in the site packages folder with files named:
1) websocket.py
2) websockets.py
3) websockets_old.py

These code in these files located in site packages dirrectory are not the same as the new code i'm trying to install.  Please help. 

Thank you

**Comment by vertic4l** [comment]
use the setup.py with setuptools module (pip install setuptools)

**Comment by mkang1234** [comment]
Didn't work

**Comment by sammchardy** [comment]
@mkang1234 I have bumped the version on the async branch, you can install using the git url of the branch may be the easiest

pip install git+https://github.com/sammchardy/python-binance@feature/asyncio

**Comment by mkang1234** [comment]
Now I'm getting this error. 

ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/sammchardy/python-binance 'C:\Users\MI\AppData\Local\Temp\pip-req-build-pwjnjurx'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by friliah** [comment]
> @mkang1234 I have bumped the version on the async branch, you can install using the git url of the branch may be the easiest
> 
> pip install git+https://github.com/sammchardy/python-binance@feature/asyncio

getting RuntimeError: Unable to determine version.


Branch 'feature/asyncio' set up to track remote branch 'feature/asyncio' from 'origin'.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\Maxim\AppData\Local\Temp\pip-req-build-jl96_7pb\setup.py", line 15, in <module>
        version = re.findall(r"^__version__ = '([^']+)'$", fp.read(), re.M)[0]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maxim\AppData\Local\Temp\pip-req-build-jl96_7pb\setup.py", line 17, in <module>
        raise RuntimeError('Unable to determine version.')
    RuntimeError: Unable to determine version.

**Comment by nikky78** [comment]
Hi,

I have the same problem on my end. How did you do?

**Comment by PromobyNW** [comment]
For many users including myself have faced issue of no idea where to start as per pip install python-binance command.
So basically if you have python 3.7 or any other version please do like this;
1.click search bar in task bar and type python
2.right click on python and click open file location
3.sometimes it may take u to folder which has the python shortcut if so right click shortcut and click properties and then click button open file location
4.now here you have arrived at directory where your python is installed
5.click file button in the top bar of the window this is the bar right  below the bar that have the minimize, maximize and close buttons.
6.then find option called open windows powershell or open cmd any is fine
7.I used powershell
8.go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download ad3 Catergory a whl file appropriate to your python version and windows build which is usually seen when you launch python.exe app in top of tab like python 3.7 (32-bit) as in my one.
as per my python build i need to download below file as cp37 means python 3.7 build and win 32 means 32-bit;
ad3‑2.2.1‑cp37‑cp37m‑win32.whl
9.then after download move this file ad3‑2.2.1‑cp37‑cp37m‑win32.whl to the place you arrived in step 4 and click rename and copy it's file name completely.
10. now go back to powershell and type;  py -3.7 -m pip install ad3‑2.2.1‑cp37‑cp37m‑win32.whl (you have to put ur appropriate file name here after install words) (also another thing to change is the build number where I have put as py -3.7 in code you will have to change if u have pythom 3.9 then it will be py -3.9 -m pip install ad3‑2.2.1‑cp37‑cp37m‑win32.whl)
11.  Then go to https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted and download the relevant cp37 or as per your build the appropriate file and put in place in step 4 and copy it's full file name as well
12. now go back to powershell and type; py -3.7 -m pip install Twisted-20.3.0-cp37-cp37m-win32.whl
13. sometimes your path may not be exactly same so in place in step 4 check for folder called scripts and inside there go and click file in top tab of window and open powershell from there and then continue next steps
14. now in this new powershell type as follows;  py -3.7 -m pip install python-binance (same advice as in step 10)

If the above helped save you time and ease your stress please click the smiley face in the top right of this message and leave your thanks:)
