### ISSUE TITLE
how to do it... help

### ISSUE THREAD

**Issue by pisulski** [sammchardy/python-binance#420]
Hello. How to add additional parametr to fuction process_message?
__
```
# start aggregated trade websocket for BNBBTC
def process_message(msg, ???):
    print("message type: {}".format(msg['e']))
    print(msg)
    # do something

from binance.websockets import BinanceSocketManager
bm = BinanceSocketManager(client)
bm.start_aggtrade_socket('BNBBTC', process_message)
bm.start()
```

**Comment by hurjapaa** [comment]
I don't think it is possible, since BinanceSocketManager calls  process_message -function implicit.

**Comment by sammchardy** [comment]
@pisulski you can always create a partial function to pass as the callback with the params you want set.

https://docs.python.org/2/library/functools.html#functools.partial
