### ISSUE TITLE
feature/asyncio: Unclosed client session

### ISSUE THREAD

**Issue by sapph1re** [sammchardy/python-binance#421]
**Describe the bug**
I simply instantiate AsyncClient like demonstrated in readme, and its usage is always followed with an "Unclosed client session" error.

**To Reproduce**
```
import asyncio
from binance import AsyncClient


async def main():
    client = await AsyncClient.create()
    print(await client.get_server_time())


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Output:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000029492976A58>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002949290DE88>, 3463537.656)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000029492976AC8>
{'serverTime': 1566977521778}
```

**Expected behavior**
Expected not to have errors. Should I somehow gracefully close/destroy AsyncClient?

**Environment (please complete the following information):**
 - Python version: 3.7
 - OS: Windows 10
 - python-binance: 0.7.3-asyncio, cloned from the repository: 00dc9a978590e79d4aa02e6c75106a3632990e8d

**Comment by cryptoflipper** [comment]
Yep same here. There's no AsyncClient and also the DepthCacheManager and BinanceSocketManager are elsewhere.
```
from library.binance.depthcache import DepthCacheManager
from library.binance.websockets import BinanceSocketManager
```
...perhaps?

**Comment by sapph1re** [comment]
Apparently, it's an error of aiohttp, which is used here. Its ClientSession is recommended to be run in a context manager:
https://stackoverflow.com/questions/46112848/python-package-aiohttp-has-a-warning-message-unclosed-client-session

Another way is closing the aiohttp.ClientSession explicitly: `await self.session.close()` but I'm not sure where exactly it would be good to do it. Make a special class method for that, like `stop()`? What would be the best approach?

**Comment by matze19999** [comment]
@sapph1re did you find a fix / workaround for this?

**Comment by sapph1re** [comment]
> @sapph1re did you find a fix / workaround for this?

I ended up ignoring it, as it only appeared on termination of a run in PyCharm, and not anywhere else. And on termination it didn't really matter.

**Comment by sapph1re** [comment]
> @sapph1re did you find a fix / workaround for this?

sorry, my previous (deleted) answer was misleading.
I made a `stop()` method in the exchange wrapper class, which explicitly calls `await self._client.session.close()` where `self._client` is the AsyncClient instance.

**Comment by gorkem2020** [comment]
I'm still getting this error. I guess it has not been fixed.

**Comment by Gorgosaurus** [comment]
I still get the error

**Comment by ImFranQ** [comment]
You need close conection

```
async def main():
    client = await AsyncClient.create()
    print(await client.get_server_time())
    # all code here
    await client.close_connection() # <--- you need this line. insert it in the end of main function
```
