### ISSUE TITLE
PyPI code v0.7.3 is different to repository code

### ISSUE THREAD

**Issue by sapph1re** [sammchardy/python-binance#422]
I've noticed that the version of this library installed with PyPI differs from the repository code.
I've installed it with:

`pip install python-binance`

It installed version 0.7.3, and in `binance/websockets.py` it defines a method:
`def start_margin_socket(self, callback)` on line 456.
But in the repository I don't see this method at all, not in master, not in the other branches.

I was using this method and I found that it doesn't work correctly, so I was going to make a PR with a fix, but now I see it's not even present in the repository code...

pip version: 19.0.3
Python version: 3.7

**Comment by sammchardy** [comment]
Merging PR into master
