### ISSUE TITLE
Faster order book updates

### ISSUE THREAD

**Issue by simaster123** [sammchardy/python-binance#423]
A couple days ago, Binance updated their websocket update rates from 1000ms to 100ms (see below).  Is anyone working on integrating this update with python-binance?

https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md

Faster order book data with 100ms updates: <symbol>@depth@100ms and <symbol>@depth#@100ms
Added "Update Speed:" to web-socket-streams.md
Removed deprecated v1 endpoints as per previous announcement:
GET api/v1/order
GET api/v1/openOrders
POST api/v1/order
DELETE api/v1/order
GET api/v1/allOrders
GET api/v1/account
GET api/v1/myTrades

**Comment by OpenCoderX** [comment]
This would be nice!
