### ISSUE TITLE
Getting diff updates up to a specified depth

### ISSUE THREAD

**Issue by StefanMallia** [sammchardy/python-binance#425]
Hello there,

For diff updates, it does not seem possible to specify a maximum depth for which updates are received. I am trying to maintain an order book locally that always has a depth of (e.g.) 100 price levels. However, the api seems to assume updates are to be received for all price levels, meaning that when a price level is deleted, it does not send the information of what price and volume should be appended to the end of the order book (see 'republishing' in Kraken).

Would anyone be able to confirm or correct my understanding of the above?

**Comment by wisepotato** [comment]
why was this closed?
