### ISSUE TITLE
helpers.py - february bug

### ISSUE THREAD

**Issue by kaaetech** [sammchardy/python-binance#428]
Whilst playing with historical data I was getting a bug and upon debugging I discovered the function: **date_to_milliseconds(date_str):** receiving the following argument "30 Feb, 2019" which causes my program to crash. My fix is the following to *cap the month at 28 days*:

```
    if "Feb" in date_str:
        date = int(date_str.split(" ")[0])
        year = date_str.split(", ")[1]
        if date > 28:
            date_str = "28 Feb "+year
```

**Comment by sammchardy** [comment]
@kaaetech where was that date coming from? Were you constructing it in some way?
