### ISSUE TITLE
ImportError: No module named 'binance'

### ISSUE THREAD

**Issue by kintzhao** [sammchardy/python-binance#43]
kint@ubuntu:~/block$ git clone https://github.com/binance-exchange/python-binance.git
Cloning into 'python-binance'...
remote: Counting objects: 939, done.
remote: Total 939 (delta 0), reused 0 (delta 0), pack-reused 939
Receiving objects: 100% (939/939), 154.13 KiB | 68.00 KiB/s, done.
Resolving deltas: 100% (613/613), done.
Checking connectivity... done.
kint@ubuntu:~/block$ pip install python-binance
Collecting python-binance
  Downloading python_binance-0.5.6-py2.py3-none-any.whl
Collecting requests (from python-binance)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 117kB/s 
Collecting six (from python-binance)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting autobahn (from python-binance)
  Downloading autobahn-17.10.1-py2.py3-none-any.whl (283kB)
    100% |████████████████████████████████| 286kB 35kB/s 
Collecting pyOpenSSL (from python-binance)
  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 41kB/s 
Collecting Twisted (from python-binance)
  Downloading Twisted-17.9.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 51kB/s 
Collecting service-identity (from python-binance)
  Downloading service_identity-17.0.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->python-binance)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 75kB/s 
Collecting idna<2.7,>=2.5 (from requests->python-binance)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 91kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->python-binance)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 48kB/s 
Collecting certifi>=2017.4.17 (from requests->python-binance)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 80kB/s 
Collecting txaio>=2.7.0 (from autobahn->python-binance)
  Downloading txaio-2.8.2-py2.py3-none-any.whl
Collecting cryptography>=2.1.4 (from pyOpenSSL->python-binance)
  Downloading cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 45kB/s 
Collecting zope.interface>=3.6.0 (from Twisted->python-binance)
  Downloading zope.interface-4.4.3-cp27-cp27mu-manylinux1_x86_64.whl (170kB)
    100% |████████████████████████████████| 174kB 91kB/s 
Collecting constantly>=15.1 (from Twisted->python-binance)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted->python-binance)
  Downloading incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted->python-binance)
  Downloading Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted->python-binance)
  Downloading hyperlink-17.3.1-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 91kB/s 
Collecting pyasn1 (from service-identity->python-binance)
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 87kB/s 
Collecting attrs (from service-identity->python-binance)
  Downloading attrs-17.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->python-binance)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 66kB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=2.1.4->pyOpenSSL->python-binance)
  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    100% |████████████████████████████████| 409kB 72kB/s 
Collecting enum34; python_version < "3" (from cryptography>=2.1.4->pyOpenSSL->python-binance)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.1.4->pyOpenSSL->python-binance)
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 41kB/s 
Collecting ipaddress; python_version < "3" (from cryptography>=2.1.4->pyOpenSSL->python-binance)
  Downloading ipaddress-1.0.19.tar.gz
Collecting setuptools (from zope.interface>=3.6.0->Twisted->python-binance)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 48kB/s 
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->python-binance)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 50kB/s 
Building wheels for collected packages: Twisted, ipaddress, pycparser
  Running setup.py bdist_wheel for Twisted ... done
  Stored in directory: /home/kint/.cache/pip/wheels/91/c7/95/0bb4d45bc4ed91375013e9b5f211ac3ebf4138d8858f84abbc
  Running setup.py bdist_wheel for ipaddress ... done
  Stored in directory: /home/kint/.cache/pip/wheels/d7/6b/69/666188e8101897abb2e115d408d139a372bdf6bfa7abb5aef5
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/kint/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built Twisted ipaddress pycparser
Installing collected packages: urllib3, idna, chardet, certifi, requests, six, txaio, autobahn, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, setuptools, zope.interface, constantly, incremental, attrs, Automat, hyperlink, Twisted, pyasn1, pyasn1-modules, service-identity, python-binance
Successfully installed Automat-0.6.0 Twisted-17.9.0 asn1crypto-0.24.0 attrs-17.3.0 autobahn-17.10.1 certifi-2017.11.5 cffi-1.11.2 chardet-3.0.4 constantly-15.1.0 cryptography-2.1.4 enum34-1.1.6 hyperlink-17.3.1 idna-2.6 incremental-17.5.0 ipaddress-1.0.19 pyOpenSSL-17.5.0 pyasn1-0.4.2 pyasn1-modules-0.2.1 pycparser-2.18 python-binance-0.5.6 requests-2.18.4 service-identity-17.0.0 setuptools-38.2.4 six-1.11.0 txaio-2.8.2 urllib3-1.22 zope.interface-4.4.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
kint@ubuntu:~/block$ cd python-binance/
kint@ubuntu:~/block/python-binance$ ls
binance  docs  LICENSE  PYPIREADME.rst  README.rst  requirements.txt  setup.cfg  setup.py  test-requirements.txt  tests  tox.ini
kint@ubuntu:~/block/python-binance$ cd tests/
kint@ubuntu:~/block/python-binance/tests$ python test
test_api_request.py  test.py              

kint@ubuntu:~/block/python-binance/tests$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from binance.client import Client
ImportError: No module named 'binance'

**Comment by jsgv** [comment]
Did you solve this?

**Comment by Hujjat** [comment]
I have the same issue

**Comment by kintzhao** [comment]
I  solve it  by create a new conda env .   and  reinstall it

**Comment by bhaktanishant** [comment]
I am getting this error. how to solve it
