### ISSUE TITLE
recvWindow

### ISSUE THREAD

**Issue by sbhadade** [sammchardy/python-binance#432]
I am getting this error while making a buy or sell call using the API . 
`Message : 'recvWindow' must be less than 60000.
Message : 'recvWindow' must be less than 60000.`
@sammchardy @mishaker @sujitnair @r41d  Plz guide

**Comment by augmen** [comment]
@sammchardy  am having same issue . Plz fix the bug #

**Comment by hurjapaa** [comment]
It's not a bug. It's Binance-api's feature:
"It recommended to use a small recvWindow of 5000 or less! The max cannot go beyond 60,000!"

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#timing-security

**Comment by augmen** [comment]
@hurjapaa  how to solve it  ? in our config file we have already set the recvWindow = 5000 . But still we are getting this error!

**Comment by hurjapaa** [comment]
Okey, then I don't know. I think you should post the the part of the code, where the error came, so that some one can help you. Is you system time, btw, correct?
