### ISSUE TITLE
The websocket is autoclose and not restart

### ISSUE THREAD

**Issue by galloclaudio** [sammchardy/python-binance#44]
I try to proccess all info using:
bm = BinanceSocketManager(client)
conn_key = bm.start_multiplex_socket(['bnbbtc@aggTrade'], process_m_message)
bm.start

But after appx 1h the socket is closed and the script stop receive the data i need do manual restarting the script to get the data. I try too using that with the same issue:
conn_key = bm.start_aggtrade_socket('BNBBTC', process_message)

After 1h +/- the socket is closed. How i can do an auto restart?

Thx!

**Comment by eSanity** [comment]
I have the same issue.

**Comment by sammchardy** [comment]
Hi @galloclaudio and @eSanity you are right, it was meant to be reconnecting on disconnect but it was confusing that with a manual close. I had seen it close after 24 hours.
I've updated to v0.5.9 which should reconnect properly now, test will be if it stays open for over 24 hours.
