### ISSUE TITLE
ECONRESET

### ISSUE THREAD

**Issue by emceef94** [sammchardy/python-binance#441]
Hello,
I have been using python-binance for over a year now and I have never had problems so far
Since 2 weeks i constantly keep getting this error at random times (the bot runs 24/7)

![VirtualBox_Linux_18_10_2019_07_36_31](https://user-images.githubusercontent.com/46846719/67068349-1d37a180-f17a-11e9-9952-9860f9833f47.png)

**Comment by simaster123** [comment]
Same issue started happening to me yesterday.  Did you figure out a resolution?

**Comment by emceef94** [comment]
No, it still happens randomly. Now I have 1 bot thats running 35 hours no problems, and 1 other bot had this error again after 4 hours... They both run on the same machine, on the same code. I have no idea why this happens
