### ISSUE TITLE
'BinanceSocketManager' has no attribute '_user_callback'

### ISSUE THREAD

**Issue by ehsueh** [sammchardy/python-binance#449]
I keep getting this error
```
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
```
Why were these functions removed? Now `self._user_callback` is never defined 🤔 

![image](https://user-images.githubusercontent.com/6699426/68503580-325f9780-0231-11ea-8f12-22720d4e5f59.png)

https://github.com/sammchardy/python-binance/commit/24a3588cacc846ae0bfb67dc2bc29f2f137a5222#diff-9e4e04c3f2e4e2c25506b650e2bc1ddb

Can you have a look? Thanks!

**Comment by ianmere** [comment]
I'm getting this with the latest pip version. anything to be concerned with? will the sockets still work?

**Comment by funoverip** [comment]
Hi, same issue. This lib is the best and easiest to use. I really like it. 
Is it still maintained ?   :(

**Comment by funoverip** [comment]
Downgraded to python-binance 0.7.3 . WebSocket Manager seems to work fine.

**Comment by SHBharadwaj** [comment]
> Downgraded to python-binance 0.7.3 . WebSocket Manager seems to work fine.

This worked for me! Thank you!!
