### ISSUE TITLE
client.ping() exception doesn't work

### ISSUE THREAD

**Issue by matze19999** [sammchardy/python-binance#450]
I wanna check if I can ping the binance server:

```
try:
      client.ping()
except:
      print("Server unreachable!")
      exit()
```
But the exception doesn't work, I always get a bunch of error messages.

**Comment by rayildirim** [comment]
Hello matze19999,
Did you find any solution for this problem?  I have the same problem in my script.

Thanks.

**Comment by matze19999** [comment]
No, I had many issues with this library, that's why I'm using the python Websocket library right know and the rest api with the requests module.

**Comment by fjfueyo33** [comment]
if you run this code, it won't catch the error:

    client = Client('poronga1','poronga2')

    try:
        client.ping()
        print("PING OK")
    except Exception:
        print("FALLA EL PING!")
    ...

but if you run this one instead

    try:
        client = Client('poronga1','poronga2')
        client.ping()
        print("PING OK")
    except Exception:
        print("FALLA EL PING!")
    ...

your code should run ok
