### ISSUE TITLE
"One cancels the other" not in python-binance

### ISSUE THREAD

**Issue by givenx** [sammchardy/python-binance#458]
Hi, I know you mentioned here [https://github.com/sammchardy/python-binance/issues/207](url) that OCO is not possible on Binance, but it seems to be, looking at the readme docs on Tony Ho's package using Java here: [https://github.com/tony-ho/binance-oco](url)
It is a feature on the exchange too (recently added?) so I am hoping it can be incorporated. Is it possible to add this to the package?

**Comment by cesarmassri** [comment]
please!!!

**Comment by zork0** [comment]
Please!!! (2)

**Comment by cesarmassri** [comment]
i did it with:

params='symbol':name,'side':'SELL','quantity':qty,'price':"%.8f"%precio_high,'stopPrice':"%.8f"%precio_sl,'stopLimitPrice':"%.8f"%precio_low,'stopLimitTimeInForce':'GTC'}
r = client._post('order/oco',True,data=params)

it worked!!!

**Comment by zork0** [comment]
> 
> 
> i did it with:
> 
> params={'symbol':name,'side':'SELL','quantity':qty,'price':"%.8f"%precio_high,'stopPrice':"%.8f"%precio_sl,'stopLimitPrice':"%.8f"%precio_low,'stopLimitTimeInForce':'GTC'}
> r = client._post('order/oco',True,data=params)
> 
> it worked!!!

Wow, so simple. Thank you!

**Comment by givenx** [comment]
@cesarmassri thanks a mill for cracking this one.  Any idea if there is a way to get the OCO working on the margin side?  I cannot get that side to work.  I can get this to work for a straight limit but not OCO:
`client._request_margin_api('post', 'margin/order', signed=True, data=params)`

**Comment by cesarmassri** [comment]
Mmm

I have no idea... I didnt read the documentation...

If I figure it out, i let you know

Kind Regards
Cesar

**Comment by givenx** [comment]
Tx @cesarmassri !  I don't think its part of the main exchange yet:
ie it is here:
`https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade`
but not here:
`https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md`
I don't know how to request this on the main binance-exchange.

**Comment by Karlheinzniebuhr** [comment]
> Tx @cesarmassri ! I don't think its part of the main exchange yet: ie it is here: `https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade` but not here: `https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md` I don't know how to request this on the main binance-exchange.

It is now: https://github.com/sammchardy/python-binance/issues/458#issuecomment-581877775
