### ISSUE TITLE
DepthCache

### ISSUE THREAD

**Issue by stephencostiniano** [sammchardy/python-binance#463]
Hello is it possible to increase the depth_cache to 1000  or 5000

**Comment by oliver-zehentleitner** [comment]
yes, should be possible with `limit`:
https://github.com/sammchardy/python-binance/blob/master/binance/depthcache.py#L124

https://github.com/binance-exchange/binance-official-api-docs/blob/025aedba3bec0418939857b49886a0ffce2a1b21/rest-api.md#order-book
`Valid limits:[5, 10, 20, 50, 100, 500, 1000, 5000]`
