### ISSUE TITLE
get_deposit_history() not working

### ISSUE THREAD

**Issue by JanAbraham** [sammchardy/python-binance#469]
Hi,

when I am calling get_deposit_history(), then it only provides me with one deposit. Same with withdraws. I am quite certain this issue is there since about 2 weeks.

Can you help?

Many thanks in advance,
Jan

**Comment by JanAbraham** [comment]
Hi,

could someone pls provide feedback on this one?

I am trying these:
deposits = client.get_deposit_history()
XRP_deposits = client.get_deposit_history(asset='XRP')

And get these results:
{'success': True, 'depositList': []} 
{'success': True, 'depositList': []}

I tried with different API keys and with different accounts. No success :-(

Many thanks in advance!
Jan

**Comment by DTrXuan** [comment]
Hello @JanAbraham  , could you tell me how can you solve this issue?
