### ISSUE TITLE
getDepositAddress

### ISSUE THREAD

**Issue by DizmalXC** [sammchardy/python-binance#47]
Does Binance support the getDepositAddress function?  I get "api not exist" when trying to use it.

Thanks

**Comment by sammchardy** [comment]
Hi @DizmalXC to fetch a deposit address for a symbol you can do this

```
from binance.client import Client
client = Client('<api_key>', '<api_secret>')
addr = client.get_deposit_address(asset='BNB')
print(addr)
```
