### ISSUE TITLE
Get APIError(code=-3008) Borrow Failed. You have pending transcation, please try again later.

### ISSUE THREAD

**Issue by HateNoSaiShi** [sammchardy/python-binance#471]
I got this error which I found weird.
I only place market order and check all oreders' status. If the order status is not 'FILLED', the code should raise error. So all orders should have been filled and I still got this APIError.
Besides, I cannot find such error code in binance official docs. I would be appreciate if any one can let me know why this error raised.

**Comment by LeaveMyYard** [comment]
I have spotted that this error seems to appear while server is processing the other lend request.
So it goes like that: you send a lend request, it starts to process. Then, you send another one (maybe in other thread). And server responds with this error saying that you have a pending transaction. Fun fact that i have not been able to find any documentation from binance on this error also. And they even made an error in word transaction ;)

**Comment by susemeee** [comment]
I also have the same issue while margin trading with 3007 error code.
