### ISSUE TITLE
Documentation for Client.get_historical_klines

### ISSUE THREAD

**Issue by pcko1** [sammchardy/python-binance#475]
`Client.get_historical_klines` returns a list of 12 elements,. What do all of them represent and where is this documented? 

[Documentation ](https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_historical_klines)only mentions the 5 OHLCV values, unless I am missing something.

**Comment by k3oni** [comment]
I know a bit late but check out https://github.com/binance-us/binance-official-api-docs/blob/master/rest-api.md#klinecandlestick-data for the response.

**Comment by sasa1901** [comment]
Thx you that helped me
