### ISSUE TITLE
Is it possible to fetch order history?

### ISSUE THREAD

**Issue by p-i-** [sammchardy/python-binance#479]
Traders will likely wish to download historical data for backtesting trading algorithms.

`examples/save_historical_data.py` demonstrates how to download historical OHLC data at a certain granularity (e.g. 1 min, 4h, etc).

Is it possible to achieve the ultimate granularity of downloading all individual _orders_ for a particular currency pair? I can see that http://live.bionictrader.io/bionic-trader streams this data from Binance. 
 So presumably the `websocket` API can retrieve it live. But can one get historical orders?

It seems to me that order-level granularity would be useful data for a trading algorithm.

**Comment by oliver-zehentleitner** [comment]
Hi!
As far as i know, its only possible via REST API! Websockets dont support this - I didnt find infos on binance docs to receive old data via WS.
Best regards,
Oliver
