### ISSUE TITLE
object has no attribute 'create_oco_order'

### ISSUE THREAD

**Issue by eelith** [sammchardy/python-binance#480]
from binance.client import Client

client.create_oco_order(
        symbol='USDCUSDT',
        side='SIDE_SELL',
        quantity= 10,
        stopPrice= 0.97,
        stopLimitPrice= 0.98,  
        price= 1.000)

AttributeError: 'Client' object has no attribute 'create_oco_order'

could someone explain to me how to make an OCO order?

**Comment by mahho** [comment]
What version of python-binance do you have? i have this error in 0.7.3, in 0.7.5 it looks like it's working

**Comment by eelith** [comment]
I'm using the version python-binance v0.7.5

Em dom, 16 de fev de 2020 10:37, mahho <notifications@github.com escreveu:

**Comment by eelith** [comment]
i got it, the version of python-binance was really out of date.

Em dom, 16 de fev de 2020 10:37, mahho <notifications@github.com escreveu:
