### ISSUE TITLE
ConnectionError : WSAECONNRESET

### ISSUE THREAD

**Issue by Pawiiii** [sammchardy/python-binance#485]
Hello everyone, I have some trouble with my program and this API.

My program works fine until this error :

('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

sample of my test program :
```
while 1 :
    
    if not run and i == 0:
       break;
        
    try:
        for symbol in params.symbols :
            value = client.get_symbol_ticker(symbol = symbol[0])
            price = value.get("price")

            time.sleep(55)
                        
   except KeyboardInterrupt:
        run = False
```
        

 - Python version: 3.7
 - Virtual Env: Spyder
 - OS: Windows Server 2016
 - python-binance version : 0.7.1

*

Any Ideas ? 
Regards

**Comment by oliver-zehentleitner** [comment]
hi Pawiii!

https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2
> Connection reset by peer.   An existing connection was forcibly closed by the remote host. This  normally results if the peer application on the remote host is suddenly  stopped, the host is rebooted, the host or remote network interface is  disabled, or the remote host uses a hard close (see setsockopt  for more information on the SO_LINGER option on the remote socket).  This error may also result if a connection was broken due to keep-alive  activity detecting a failure while one or more operations are in  progress. Operations that were in progress fail with WSAENETRESET.  Subsequent operations fail with WSAECONNRESET.

Best regards

**Comment by Pawiiii** [comment]
Hi, oliver-zehentleitner,

Ok it's perfect.
Thank you.

Regards.

**Comment by mshmurda** [comment]
> Hi, oliver-zehentleitner,
> 
> Ok it's perfect.
> Thank you.
> 
> Regards.

How did you solve this?

**Comment by Unterarzt** [comment]
> Hi, oliver-zehentleitner,
> 
> Ok it's perfect.
> Thank you.
> 
> Regards.

Yeah please explain how you solved this

**Comment by Karlheinzniebuhr** [comment]
> rcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or r

how did you solve it ?

**Comment by oliver-zehentleitner** [comment]
You cant "solve" it, you can just "handle" it! 
More info: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/discussions/255
