### ISSUE TITLE
async version bump

### ISSUE THREAD

**Issue by slangda** [sammchardy/python-binance#486]
I have been working with the async feature branch and am very happy with its performance. Recently the Binance futures have been added to the main branch. Are these changes coming to the async branch as well?

**Comment by yvdjee** [comment]
Can you help me with the async feature? what module should i install because AsyncClient is missing from the lib.

**Comment by slangda** [comment]
The async feature is another branch from main. Check the project's home page and select the branch feature/asyncio. On the right you can click 'Clone or download'. From there you can use the git link like:

- pip install git+https://github.com/sammchardy/python-binance.git 

OR download the zip file and install

- pip install python-binance-feature-asyncio.zip

I recommend to create a separate virtual environment to experiment with this branch

**Comment by yvdjee** [comment]
Thanks mate, I will try.

**Comment by Ak4zh** [comment]
@yvdjee You can also install the asyncio branch directly without manually downloading the zip file using:

`pip install git+https://github.com/sammchardy/python-binance.git@feature/asyncio`
