### ISSUE TITLE
websocket for binance futures?

### ISSUE THREAD

**Issue by MarceloDuhalde** [sammchardy/python-binance#489]
Hello Sam,
Is there any way, to start a multiplex_socket, with futures kline ?, I tried overriding the STREAM_URL, before starting the multiplex, and things like that, but without results.

**Comment by TheBereaved** [comment]
Would love to see if we could get the futures websocket added as well!

**Comment by sloth456** [comment]
I'd also be interested to know how to connect to the futures socket too

**Comment by konqueror1** [comment]
I am looking for the same. Is this possible with current version?

**Comment by sloth456** [comment]
For the time being I've been using Unicorn Binance Websockets to pull stream data from binance futures

https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api

```
from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import
import json

binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.com-futures")
binance_websocket_api_manager.create_stream(['aggTrade'], ['ethusdt'])

while True:
	stream = binance_websocket_api_manager.pop_stream_data_from_stream_buffer()
	if stream:
		jsonstream = json.loads(stream)
		data = jsonstream.get('data') 
		if data:
                    print(data)
```

**Comment by konqueror1** [comment]
> For the time being I've been using Unicorn Binance Websockets to pull stream data from binance futures
> 
> https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api
> 
> ```
> from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager
> import json
> 
> binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.com-futures")
> binance_websocket_api_manager.create_stream(['aggTrade'], ['ethusdt'])
> 
> while True:
> 	stream = binance_websocket_api_manager.pop_stream_data_from_stream_buffer()
> 	if stream:
> 		jsonstream = json.loads(stream)
> 		data = jsonstream.get('data') 
> 		if data:
>                     print(data)
> ```

Thanks, sloth456. Now I am playing with unicorn_binance_websocket_api_manager and I like it very much.

**Comment by MarceloDuhalde** [comment]
thank you very much sloth456, i will try binance unicorn.

**Comment by mprzydatek** [comment]
this is my code:

```
binance = await AsyncClient.create(config.API_KEY, config.API_SECRET)
bsm = BinanceSocketManager(binance)
async with bsm.futures_multiplex_socket(streams) as ms:
    while True:
        msg = await ms.recv()
        ...
```
