### ISSUE TITLE
Withdrawal Exception raised

### ISSUE THREAD

**Issue by Dynamikey** [sammchardy/python-binance#49]
Hi,

Thank you for sharing this great project!

I'm trying to automate the withdrawal process but am getting this error:

binance.exceptions.BinanceWithdrawException: BinanceWithdrawException: Name is empty.

`result = client.withdraw(asset = currency, address = addr, amount = 10)`

I thought the name field is optional?

Thank you,
Michael

**Comment by sammchardy** [comment]
Hi @Dynamikey as far as I'm aware the name parameter is not required. The official API documentation still shows it as optional https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#withdraw

The message you're seeing is coming from the Binance API servers and wrapped in a BinanceWithdrawException object. I'd recommend asking on the Binance API Telegram group https://t.me/binance_api_english

**Comment by Dynamikey** [comment]
May I ask if you @sammchardy get the same error when running the withdrawal function?

**Comment by sammchardy** [comment]
@Dynamikey I haven't tried a withdrawal through the API recently.

I did notice in the Telegram channel comments about creating a new API key with withdraw permissions and trying again.

**Comment by mattpearson** [comment]
Hi, thanks for developing this great project.

I am encountering the same issue -- BinanceWithdrawException: Name is empty.  -- when trying to programmatically withdraw funds.

I just created a new key with withdraw permissions as suggested earlier. 

Thoughts?

Thank you.

**Comment by Dynamikey** [comment]
Hi, got it working by making a withdrawal using that token. Worked like a charm after.

**Comment by mattpearson** [comment]
What token are you referring to? A new API key and secret?

**Comment by Dynamikey** [comment]
The token/coin you’re trying to withdraw from binance. You most likely have not done a withdrawal using that coin before on binance.

**Comment by priyen** [comment]
@Dynamikey I am also getting this issue, not sure what you mean by token. Im doing asset='LTC' and it is spitting out that error..

**Comment by RenegadeEagle** [comment]
@priyen 
I was just testing this and apparently name is not optional.
I'm not sure why this is, but you need to pass name as the form of the crypto you are trying to withdraw.

For example,
`
binance.withdraw(asset=currency, address=address, amount=quantity, name=currency)
`
works for me. Currency is equal to 'LTC'.

I would like to point out the code says this is optional, and it doesn't seem to be so. @sammchardy 
https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L1382

**Comment by sammchardy** [comment]
@RenegadeEagle is the value 'LTC' the Label/Name you gave to that address through the Binance Web interface?

It's strange that the official documentation is still indicating the name is optional. I can see the JS lib seems to have solved it by passing the string "API Withdraw" as the name parameter and not allowing the end user 

Maybe I can just pass the asset value as name if not set.

**Comment by mattpearson** [comment]
I too was able to get it to work by setting name and asset to the same value, in this case LTC. Not sure if it will work with others or just a fluke...

**Comment by RenegadeEagle** [comment]
@mattpearson I am trading many different types of cryptos and this seems to be the case for all of them.

This just seems to be a case of one of many of the issues in the Binance REST API.

**Comment by sammchardy** [comment]
Updated `withdraw` function to fill `name` with `asset` parameter if `name` is not passed.

**Comment by sanjaySbacancy** [comment]
Hello Support Team,

We have working on Withdraw API but some error facing when API call. We have enable Withdrawals option and add over current server IP Address in IP Access Restriction. Even then not working Withdraw API.

This error facing when API call :

signedRequest error: {"msg":"You don't have permission.","success":false} 
Array 
( 
[msg] => You don't have permission. 
[success] => 
)

Please find the attachment. Please solve issue as soon as possible. 
I hope you reply as soon possible.
