### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-1022): Signature for this request is not valid.

### ISSUE THREAD

**Issue by includeleec** [sammchardy/python-binance#5]
always...

**Comment by sammchardy** [comment]
@includeleec can you give an example of how you're using the API.

**Comment by includeleec** [comment]
```
from binance.client import Client

class Monitor:
    def __init__(self):
        self.bac = Client(KEY,SERCRET)
    def my_balance(self):
        print(self.bac.get_account(recvWindow=RECV_WINDOW))


m = Monitor()
m.my_balance()
```

sometimes ok,sometimes throw error.

**Comment by sammchardy** [comment]
@includeleec can you check the value you're using for recvWindow, the API docs indicate it should be an int for the number of milliseconds the request is valid for.

If I send a string of say "4000" then I also get the Signature invalid error back from the Binance API.

**Comment by includeleec** [comment]
RECV_WINDOW=6000000,
this setting i copy from binance example

**Comment by jmynes** [comment]
```
#!/usr/bin/env python

api_key = 'key_here'
api_secret = 'secret_here'

from binance.client import Client
client = Client(api_key, api_secret)

time_res = client.get_server_time()

RECV_WINDOW=6000000

class Monitor:
    def __init__(self):
        self.bac = Client(api_key,api_secret)
    def my_balance(self):
        print(self.bac.get_account(recvWindow=RECV_WINDOW))


m = Monitor()
m.my_balance()
```

It's working for me, did you set up your API key correctly?

**Comment by laurent101** [comment]
Hi, 

same issue with invalid invalid signature.

Thanks

**Comment by sammchardy** [comment]
@laurent101 please provide examples to add to the discussion.

There are a range of things that can cause this, some that I'm aware of are listed in the FAQ here https://github.com/sammchardy/python-binance#user-content-faq

**Comment by laurent101** [comment]
I ran the code as posted above by @jmynes and ended up with an invalid signature error message. Both my key and secret (both strings) are correct.

**Comment by laurent101** [comment]
I found the issue which is related to the API version issue I posted. I had added and changed the version of the REST API from 'v1' to 'v3' which is the update on the Binance website. As @sammchardy correctly pointed out this requires an amended signature. Sorry for the inconvenience caused.

**Comment by junw3i** [comment]
Im encountering the same issue on v1 as @includeleec even when I add "recvWindow=6000000" to the parameters.
the signature is sometimes valid and sometimes not valid.

**Comment by junkheadd** [comment]
same issue. seems to fail randomly

**Comment by frosty00** [comment]
Have the same issue, randomly fails for me :(

**Comment by shammy12** [comment]
For anyone still running into this issue, I've been referencing sammchardy's extremely helpful code here as a template for my own project, and I was continually running into this error as well. Here is an example standalone code snippet that I was finally able to get working:

api_key = ''
api_secret = ''

request_url = 'https://api.binance.com/api/v3/openOrders?'

timestamp =  int(time.time() * 1000)
symbol = 'BNBBTC'

querystring = urlencode({'symbol' : symbol, 'timestamp' : timestamp})

signature = hmac.new(api_secret.encode('utf-8'), querystring.encode('utf-8'), hashlib.sha256).hexdigest()

request_url += querystring + '&signature=' + signature

r = requests.get(request_url, headers={"X-MBX-APIKEY": api_key})

**Comment by tevonsb** [comment]
Has anyone found a fix for this yet? I am running into it when calling .getAccount(). I've tried setting RECV_WINDOW manually without success.

**Comment by 5outh** [comment]
I'm also running into this intermittently when initiating various sales.

**Comment by sammchardy** [comment]
I've updated some dependencies in v0.5.10 including certifi which has resolved this issue for me for the moment. Let me know if it helps.

**Comment by dafrizzy** [comment]
I just updated everything today but am also still receiving this error. All the signed GET withdraw api functions seem to work fine though (deposithistory, withdrawhistory, depositaddress). I've tried increasing the recvWindow up to 6000000 ms but with no success.

**Comment by meko0019** [comment]
getting this error when placing orders, has anyone been able to find a solution? 
tried @shammy12's solution but got a similar error >> " {'code': -1022, 'msg': 'Signature for this request is not valid.'}"

**Comment by 5outh** [comment]
@meko0019 Can you give an example function call that produces that error? I'm hitting it all over the place, but one common roadblock I'm seeming to hit is when _selling ADA_. ADA is only buyable/sellable in whole increments; I'm wondering if the API is expecting a decimal for the purposes of the signature...

(FWIW I have updated and am still seeing this pretty commonly as well)

**Comment by sammchardy** [comment]
I have released v0.5.13 which ensures orders are correct when generating signature and sending to server. This seems to resolve issues in my tests.

Let me know if it's still occurring.

**Comment by meko0019** [comment]
@5outh all of the order functions including test_order were producing that error. A new API key seems to have solved it for me.

**Comment by 5outh** [comment]
Very interesting, I'll have to try that. I was still seeing issues (with a 2-week old key) yesterday, but they seem less frequent. That may be because I'm placing fewer orders though...

Will ping back if changing the API key doesn't fix things. Thanks for your work on this project!

**Comment by vazzilly** [comment]
getting the same message with PHP
`
$ch = curl_init();
$timestamp = round(microtime(true) * 1000);
$secret = 'bmrLfulh***************************KladNAcI4qLg';
$querystring = urlencode("'timestamp' : ".$timestamp."}");
$signature = hash_hmac('SHA256', $secret, $querystring);

curl_setopt($ch, CURLOPT_URL, "https://api.binance.com/api/v3/order?symbol=LTCBTC&side=BUY&type=LIMIT&timeInForce=GTC&quantity=1&price=0.1&recvWindow=50000&timestamp=".$timestamp."&signature=".$signature."");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "X-Mbx-Apikey: EAXHTI2ZyuWqVdV**********ptYUnl2XYM9f";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
print_r($result);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
`

**Comment by sammchardy** [comment]
Going to close this now, v0.5.13.

Adding a note about regenerating API key and secret to FAQs

**Comment by Sharifdesigns22** [comment]
Can someone explain what the recv_window does?

**Comment by LiYijin** [comment]
my version is 0.5.17, but i still met this problem.
Thanks @sammchardy

**Comment by SkylerX** [comment]
@LiYijin kindly note now it's at version 0.6. Cheers

**Comment by jasonmellone** [comment]
> @5outh all of the order functions including test_order were producing that error. A new API key seems to have solved it for me.

I re-installed from git 
`sudo pip install git+git://github.com/sammchardy/python-binance.git`

and still received the error. then generated a new api key and reran. this resolved the problem.

**Comment by megapctr** [comment]
In my case only the `/api/v3/order` API endpoint returns this error. Other signed APIs, like `/api/v3/account`, work fine.

(please note that I'm not using this library, but this discussion seems to be directed at binance rather than this library anyway)

**Comment by amirvenus** [comment]
My problem was fixed upon using math.ceil() on the quantity

**Comment by lars71dkk** [comment]
I had this problem a lot, then I updated to 0.6.2 and generated a new API key. Havent' had the problem since! :-)

**Comment by megapctr** [comment]
I managed to resolve my problem. It seems that the last two query params need to be `timestamp` and `signature`, in this order.

**Comment by frosty00** [comment]
https://github.com/ccxt/ccxt

**Comment by UsernameGitiHub** [comment]
Hey There, i did find a solution for me with PHP and wated to share it to you, i was also getting this error amm the time and the following PHP Code did work then:

`
                        //--API Call
			$nonce=time();
			//--
			$uri='https://api.binance.com/api/v3/account?recvWindow=10000000000000000&timestamp='.$nonce;
			$strsign='recvWindow=10000000000000000&timestamp='.$nonce;
			//--
			$sign=hash_hmac('SHA256',$strsign,$apisecret);
			$uri=$uri.'&signature='.$sign;
			$ch = curl_init($uri);
			curl_setopt($ch, CURLOPT_HTTPHEADER, array('X-MBX-APIKEY:'.$apikey));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
			curl_setopt($ch, CURLOPT_URL, $uri);
			$execResult = curl_exec($ch);
			$Balances = json_decode($execResult, true);
                        var_dump($Balances);
`

**Comment by camaris** [comment]
Sorry is this is the wrong place to post my findings, but I struggled a lot with a similar issue on 'Signature for this request is not valid.'. Perhaps this can be added to the FAQ https://github.com/sammchardy/python-binance#user-content-faq.
Take care of having the correct parameters when you call a function:
client.order_market_buy(symbol='BTCUSDT',quantity=('0.001264',1234),timestamp=client.get_server_time())
=> ERROR 'Signature for this request is not valid.'
client.order_market_buy(symbol='BTCUSDT',quantity=('0.001264'),timestamp=client.get_server_time())
=> NO ERROR
client.order_market_buy(symbol='BTCUSDT',quantity='0.001264',1234,timestamp=client.get_server_time())
=> NO ERROR
Off course the parameter quantity=('0.001264',1234) is wrong but the message could be more clear (e.g. wrong amount)

**Comment by scottbecker** [comment]
If it helps anyone, passing None values to create_order will also cause this since the None parameter is used in the query_string used for calculating the signature but not in the query string sent to the server.

e.g. don't use create_order(price = None,.....)

**Comment by thirstygerry** [comment]
If someone still needs it, I created an example python script that returns your balances.
It includes a valid signature.
https://github.com/thirstygerry/binance-python

**Comment by noahwalugembe** [comment]
> I managed to resolve my problem. It seems that the last two query params need to be `timestamp` and `signature`, in this order.
pleas help me am geting the same problem
  timestamp = int(time.time() * 1000)
        params = {
           
           #'recvWindow': 5000,59999 6000000
           'recvWindow': 6000,
           'timestamp': timestamp
        }

**Comment by UsernameGitiHub** [comment]
> > I managed to resolve my problem. It seems that the last two query params need to be `timestamp` and `signature`, in this order.
> > pleas help me am geting the same problem
> > timestamp = int(time.time() * 1000)
> > params = {
> 
> ```
>        #'recvWindow': 5000,59999 6000000
>        'recvWindow': 6000,
>        'timestamp': timestamp
>     }
> ```

i dont know if anybody still have this problem with wrong nonce in the Request, but i can tell you all the right solution is easy, you just need to send instead of timestemp the timestemp in miliseconds and not in seconds, here is a example:

`$nonce=round(microtime(true) * 1000); //time();
			$recwindow=5000;
			//--
			$url='symbol='.$symbol.'&side=SELL&type=MARKET&quantity='.$VolumeCoin.'&recvWindow='.$recwindow.'&timestamp='.$nonce;
			//--
			$sign=hash_hmac('SHA256',$url,$apisecret);
			$url=$url.'&signature='.$sign;
			$ch = curl_init($url);
			curl_setopt($ch, CURLOPT_HTTPHEADER, array('X-MBX-APIKEY:'.$apikey));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
			curl_setopt($ch, CURLOPT_URL, "https://api.binance.com/api/v3/order");
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS,$url);
			$execResult = curl_exec($ch);
			$Auftrag = json_decode($execResult, true);`

**Comment by approved788** [comment]
May be my case would be helpful to someone. When I submitted wrong API key i got this error, so check once again if you entered your keys correctly. 
Then when i tried to trade "BTC USDT" i got the same. If you do not see 'Enable Futures' in api management - first create futures wallet. Than enable it, and PAY ATTENTION that after this step api_key is changed, so don`t forget it! Your api_secret_key will stay the same.
In 2021 need asked for this: RECV_WINDOW=60000

**Comment by den4ess** [comment]
Still having "Signature for this request is not valid" on async client.futures_account_balance. Tried with parameters and without them. Also tried different recvWindow.
1.0.16
