### ISSUE TITLE
python-binance/binance/websockets.py missing Ping/Keep-alive a listenKey every 30m timeout

### ISSUE THREAD

**Issue by xiaods** [sammchardy/python-binance#504]
**Describe the bug**
I found the UserDataStream's keeplive function is missing in current websocket.py.
so after every one hour, binance WebSocket conn is invalid.

**To Reproduce**
Code snippet to reproduce the behavior:
see binance API docs:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#pingkeep-alive-a-listenkey

**Expected behavior**
add keepalive logic in websocket.py

**Environment (please complete the following information):**
 - Python version: 3.6
 - Virtual Env: native
 - OS: Ubuntu 18.04
 - python-binance version: 0.75

**Comment by xiaods** [comment]
sample code
```
def initialize_arb():
          # ping user websocket every 30 minutes
    while True:
        get_margin_stream_keepalive(conn_key)
        time.sleep(60 * 30)

'''
Purpose: Keepalive a user data stream to prevent a time out. 
User data streams will close after 60 minutes. 
It's recommended to send a ping about every 30 minutes.
'''
def get_margin_stream_keepalive(listen_key):
    result = client.margin_stream_keepalive(listen_key)
    return result

```

**Comment by bizso09** [comment]
I can confirm that UserDataStream stops sending updates after some time. This is definitely a bug in the framework

**Comment by miraclix** [comment]
Here it works very well: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api

**Comment by astersnake** [comment]
@xiaods Why did you close this? This issue is still happening.

**Comment by eddiecheng86** [comment]
I also encountered a problem in UserDataStream. Lost the websocket connection randomly. Is there any suggested workaround that we can check/ping the connection as a temp solution? Thanks!

**Comment by xiaods** [comment]
> @xiaods Why did you close this? This issue is still happening.

you can have a try unicorn-binance-websocket-api, it works like a charm
