### ISSUE TITLE
asyncio branch - no module name 'websockets'

### ISSUE THREAD

**Issue by papapon** [sammchardy/python-binance#509]
I wanted to use asynchronous calls, so I used the feature/asyncio branch. 

I do: pip install git+https://github.com/sammchardy/python-binance.git@feature/asyncio

After I try to call get_exchange_info() in jupyter, I obtain "ModuleNotFoundError: No module named websockets". 
If I run it a second time, it works.
Here is my code:
```
from binance.client import Client        
client = Client('xxx', 'yyy')

client.get_exchange_info()

**Comment by fahadshery** [comment]
I had the same issue. I just had to install the `websockets` package and it was ok afterwards
