### ISSUE TITLE
ModuleNotFoundError: No module named 'binance'

### ISSUE THREAD

**Issue by Wakiwi** [sammchardy/python-binance#524]
Hi, i installed python-binance with pip.
But whenever i try to use it with `from binance.client import Client` i get this error `ModuleNotFoundError: No module named 'binance.`

I use Python 3.7.7 and the latest version of PyCharm.

Can anyone help me ? :(

**Comment by al91liwo** [comment]
Have you selected the correct interpreter in the settings?
In `File -> Settings -> Project -> Project Interpreter`, you can select the appropriate Python Interpreter.

[Here](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html) is a tutorial.

**Comment by Wakiwi** [comment]
I think so:

![image](https://user-images.githubusercontent.com/65931773/82893790-dbfa4200-9f51-11ea-9dd1-cae2bca2693f.png)

I aslo tried to install python-binance through pycharm and this message showed up:

![image](https://user-images.githubusercontent.com/65931773/82893996-30052680-9f52-11ea-86da-4f817ce7f9a8.png)
