### ISSUE TITLE
Method to know the value of all coins under my account? 

### ISSUE THREAD

**Issue by hellojinwoo** [sammchardy/python-binance#528]
<H2> Question </H2>

- Does the Binance API support to figure out the total value of coins in one account, regardless of which coin it has?
- For example, if I have 1 BTC, 1 ETH and 1 BNB under my account, does Binance support any method to let me know I have around '**USD 10220'**?
- The docs of this library does not have any information about it, so I am asking here!

**Comment by hellojinwoo** [comment]
I just made a function on my own

**Comment by sourovafrin** [comment]
Would you mind sharing it @hellojinwoo ?

**Comment by JayRama** [comment]
any chance you could share that function with us @hellojinwoo ?
