### ISSUE TITLE
Getting Symbol Price

### ISSUE THREAD

**Issue by rockstar8577** [sammchardy/python-binance#53]
Whenever I try and get the ticker price for 1 specific symbol it throws an error saying "TypeError: get_symbol_ticker() takes 1 positional argument but 2 were given",
I'm only sending in 1 argument
`price = client.get_symbol_ticker({"BTCUSDT"})`
I've tried in braces and without braces. Do you know about this issue or is it something on my end?

**Comment by sammchardy** [comment]
Hi @rockstar8577 call it like so

```
price = client.get_symbol_ticker(symbol="BTCUSDT")
```
