### ISSUE TITLE
Starting Kline Data websocket and callback???

### ISSUE THREAD

**Issue by aelkman** [sammchardy/python-binance#56]
What would be the best websocket to get the volume data for the last 1m in time?
Would it be the Kline Data websocket?

If so, I am trying to implement this way:
```

bm = BinanceSocketManager(self.binanceClient)
conn_key = self.socketManager.start_kline_socket(symbol, self.websocket_callback, interval='1m')
bm.start
```

with a callback :
```
	def websocket_callback(self, message):
		print("invoked websock_handler:", message)
```

but no message is printing, can you point me in the right direction?

Thanks!

**Comment by sammchardy** [comment]
@aelkman it doesn't look like you're calling the start function correctly, are you missing the function brackets. Make sure it's
```
bm.start()
```
