### ISSUE TITLE
order_market_buy return order with status EXPIRED  [testnet]

### ISSUE THREAD

**Issue by lr2bmail** [sammchardy/python-binance#569]
**Describe the bug**
testnet binance   order_market_buy return order with status EXPIRED  

**To Reproduce**
```
client = Client(apiKey, secret)
client.API_URL='https://testnet.binance.vision/api'
client.order_market(symbol='BTCUSDT', side='BUY', quantity=0.1)
```
`
{'symbol': 'BTCUSDT', 'orderId': 175294, 'orderListId': -1, 'clientOrderId': 'UoYbX7fleZUQ53X9IXZlA3', 'transactTime': 1597225914026, 'price': '0.00000000', 'origQty': '0.10000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'EXPIRED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 'fills': []}`

**Expected behavior**
to return FILLED order status 

**Environment  
 - Python version: 3.7.8
 - Virtual Env: virtualenv
 - OS: WIN10
 - python-binance 0.7.5

**Comment by lr2bmail** [comment]
oh my mistake   i need to use quoteOrderQty not quantity

**Comment by PeterGardas** [comment]
@lr2bmail can you please elaborate. My code also outputs `'EXPIRED'` but when I replace `quantity` with `quoteOrderQty` I get
 `binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL`.

Thanks for the help in advance.

Peter

**Comment by lr2bmail** [comment]
> 
> 
> @lr2bmail can you please elaborate. My code also outputs `'EXPIRED'` but when I replace `quantity` with `quoteOrderQty` I get
> `binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL`.
> 
> Thanks for the help in advance.
> 
> Peter

you need to switch to Live binance , testnet sandbox is not the best :(

**Comment by PeterGardas** [comment]
@lr2bmail But how am I supposed to backtest the bot if the sandbox does not work?
