### ISSUE TITLE
Precision for "price" float value when placing orders

### ISSUE THREAD

**Issue by jdhurwitz** [sammchardy/python-binance#57]
What is the max precision for the "price" variable when placing an order, such as a limit order? I'm getting: 

BinanceAPIException: APIError(code=-1111): Precision is over the maximum defined for this asset.

For the following float:
0.000614250470875

Is the trimming not handled by the API?

**Comment by sammchardy** [comment]
Hi @jdhurwitz no the API doesn't help you there at all.
Use the `get_symbol_info` function to get info about a particular symbol and then you can format your values for output using something like below
```
amount = 0.000614250470875
precision = 6
amount_str = "{:0.0{}f}".format(amount, precision)
```

**Comment by jessedhillon** [comment]
I'm just going to leave [this](https://docs.python.org/3.0/library/decimal.html) here...

**Comment by lilanxin6** [comment]
The parameters ‘price’ and 'quantity' should be decimal, not float.
