### ISSUE TITLE
Returning variables from websocket functions

### ISSUE THREAD

**Issue by msieg** [sammchardy/python-binance#58]
I'm running a symbol_ticker socket in order to buy, sell and cancel orders based on realtime orderbook info, but I can't figure out how to return a variable from the websocket process function. Since the process function acts as parameters in the socket function, I am not sure where or how to request output. Can someone fill me in? Thanks.

**Comment by sammchardy** [comment]
Hi @msieg have a look at the examples in the documentation https://python-binance.readthedocs.io/en/latest/websockets.html
Or have a look at the source code for the Depth Cache Manager which wraps interaction with websockets into a class. https://github.com/sammchardy/python-binance/blob/master/binance/depthcache.py#L119
