### ISSUE TITLE
Does testnet.binance work with this api?

### ISSUE THREAD

**Issue by PeterGardas** [sammchardy/python-binance#581]
The title says it all. I am just curious since I cant manage to buy or sell any assets if I do : 
`client.API_URL = 'https://testnet.binance.vision/api'`. 
Btw. this is truly an awesome project, keep up the hard work :).

Regards.

Peter.

**Comment by PeterGardas** [comment]
Ups. My bad. A quick poke around the issues solved my problem. Sorry for bothering anyone.

**Comment by CryptoFuturesAU** [comment]
Solution was ?

**Comment by jpx** [comment]
For reference, I can confirm that overriding `Client.*_URL` is a solution. For instance, to use the Futures testnet, set it after:

```py
from binance.client import Client

Client.FUTURES_URL = 'https://testnet.binancefuture.com/fapi'
```
