### ISSUE TITLE
Websocket keep closing

### ISSUE THREAD

**Issue by nikky78** [sammchardy/python-binance#583]
Hi,

From the logger, I get this:

DEBUG:websockets.protocol:client - state = CONNECTING
DEBUG:websockets.protocol:client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x00000248944CBD48>)
DEBUG:websockets.client:client > GET /ws/bnbusdt@depth5@100ms HTTP/1.1
DEBUG:websockets.client:client > Headers([('Host', 'fstream.binance.com'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'XXX'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.7 websockets/8.1')])
DEBUG:websockets.protocol:client - state = CONNECTING
DEBUG:websockets.protocol:client - event = data_received(<129 bytes>)
DEBUG:websockets.client:client < HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:client < Headers([('upgrade', 'websocket'), ('connection', 'upgrade'), ('sec-websocket-accept', 'XXX')])
DEBUG:websockets.protocol:client - state = OPEN
DEBUG:websockets.protocol:client - event = data_received(<324 bytes>)
DEBUG:websockets.protocol:client - event = data_received(<324 bytes>)
DEBUG:websockets.protocol:client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x00000248944F4C08>)
DEBUG:websockets.client:client > GET /ws/USER_KEY HTTP/1.1
DEBUG:websockets.client:client > Headers([('Host', 'fstream.binance.com'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'XXX'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.7 websockets/8.1')])
DEBUG:websockets.protocol:client - event = data_received(<325 bytes>)
DEBUG:websockets.protocol:client - event = data_received(<129 bytes>)
DEBUG:websockets.client:client < HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:client < Headers([('upgrade', 'websocket'), ('connection', 'upgrade'), ('sec-websocket-accept', 'XXX')])
DEBUG:websockets.protocol:client - state = OPEN
DEBUG:websockets.protocol:client - event = data_received(<325 bytes>)
.....
DEBUG:websockets.protocol:client - event = data_received(<401 bytes>)
DEBUG:websockets.protocol:client - state = CLOSING
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = data_received(<324 bytes>)
DEBUG:websockets.protocol:client - event = data_received(<324 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=8, data=b'\x03\xe8Bye', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = connection_lost(None)
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1000, reason = Bye
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:binance.websocket_api:ws exception:APIError(code=-2011): Unknown order sent.

It closes after barely 5 minutes.
Any idea what's going on please??

**Comment by oliver-zehentleitner** [comment]
Can you provide more infos what you are doing?

**Comment by kimchirichie** [comment]
i recomment to use `oliver-zehentleitner/unicorn-binance-websocket-api` for websockets.
