### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by Wyctus** [sammchardy/python-binance#589]
This is a great library with a large user base, but seems like not much happened in this year, many open issues and no commits since February. It would be sad to see this library to die. 

@sammchardy are you still working on this? What's up with the asyncio branch?

Thanks!

**Comment by Wyctus** [comment]
Yes, I've been using it for a long time, it was always a great library. You can still use it, don't worry too much, if anything changes on Binance's side you can usually fix it easily. But of course it's always better if the library itself is up to date and tested thoroughly  by the community.

**Comment by fede2442** [comment]
@latent-stack Hey I was thinking of creating a bot, have you started your project? Are you using this library or other resource?
Regards bro :)

**Comment by kimchirichie** [comment]
i am added as a new collaborator. while sammchardy is busy, i can start merging things in but i will need this community to start testing things and will only merge things in verified by multiple users

**Comment by Wyctus** [comment]
Great news @kimchirichie, thank you!

**Comment by kimchirichie** [comment]
i'm tagging PRs with 'pending verification' those are ones i deemed safe to merge and are waiting for community to chime in with verifying the PR is working as expected.

I will only merge in-demand PR's at this time.
