### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by jayjay991** [sammchardy/python-binance#59]
Hi,

I've tried installing this using pip3 (and pip) but it always ends in a "Segmentation fault (core dumped)" error. I've also searched around for the issue but there doesn't seem to be a clear or definitive solution. If anyone could please help that would be greatly appreciated.

Im using:
Ubuntu 17.04
Python 3.5.3

I'm relatively new to all of this so if you need any more info, just ask (and let me know how to get it :P))

**Comment by sammchardy** [comment]
Hi @jayjay991 are you still having this issue.

If so please post a log of the error and I may be able to help you narrow it down.

**Comment by Teigwaren** [comment]
Hi, maybe I can revive this thread a bit.

Got the same problem, pic related, and already found out, that this should be an error thrown by the c-compiler. I already checked cython, but cant find another solution right now.

System ist the same: 
Ubuntu 17.04
Python 3.5.3

I'm trying to install python-binance via pip3 and got some issues with the installation of Twisted not being wheeled correctly, but I could fix that in the end.

![python-binance-error](https://user-images.githubusercontent.com/33953653/35066402-bea6185e-fbd0-11e7-89b3-4b780c02a0a7.JPG)


I'd love to use your library and hope you can find a solution to this

Thanks in advance

**Comment by SkylerX** [comment]
@Teigwaren try this once more from beginning:
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y python3-pip
sudo apt-get install build-essential libssl-dev libffi-dev python-dev
pip3 install python-binance

**Comment by SkylerX** [comment]
@Teigwaren  if that does not work try this:
sudo aptitude install python3-setuptools
sudo easy_install3 pip
sudo pip-3.2 install python-binance

**Comment by jayjay991** [comment]
Hi all,

Thanks for the replies. The problem somehow fixed itself and unfortunately I can't say I know what I did as it was probably by accident while I was doing something else...

Maybe it was updates, upgrade and dist-upgrades or maybe it was removing all packages and installing it again ("pip3 uninstall ipython[all]" and "pip3 install ipython[all]" ).

Sorry I cant be more specific - I tried anything and everything and then gave up and did other stuff and when I came back to it, it just worked... If there is a way to show any changes I've made then I'll be happy to provide them - if you explain how!

**Comment by Teigwaren** [comment]
Setting it up again from the beginning worked for me. guess I loaded too much trash before.
Thanks for the replies though :)

**Comment by rafaeelaudibert** [comment]
I've already had this problems and if you track it down, you will find [this](https://bitbucket.org/cffi/cffi/issues/272/segfault-while-installing-via-pip).

You can easily solve the problem by running `pip3 install python-binance --no-binary :all:`

**Comment by mb2222** [comment]
Hi,
I have the same problem with xubuntu 18.04, I have tried "pip3 uninstall ipython[all]" and "pip3 install ipython[all]", it didn't help.
I have tried "pip3 install python-binance --no-binary :all:" but when I do "from binance.client import Client" in my python code, I get 
Traceback (most recent call last):
  File "./binance.py", line 2, in <module>
    from binance.client import Client as client
  File "/home/uranus/workspace/binance.py", line 2, in <module>
    from binance.client import Client as client
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package
Any idea ?
Thanks

**Comment by mb2222** [comment]
I forgot to mention that I am using python 3.6.7

**Comment by Sean-Bradley** [comment]
I was having segmentation fault with absolutely anything python,
```console
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y python3-pip
```
fixed it for me
