### ISSUE TITLE
Got HTTPS warning

### ISSUE THREAD

**Issue by brioapp** [sammchardy/python-binance#605]
Data returned successfully but got https warnings.

```
data = get_historical_klines('BTCUSDT', Client.KLINE_INTERVAL_4HOUR, 'October 15, 2020', 'October 20, 2020')

/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.binance.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by GitHubEmploy** [comment]
This happens because Binance does not support a sandbox API. This is fine and you can ignore it and continue on with whatever you want to do, or you can suppress the warning using 
```
import warnings
warnings.filterwarnings("ignore")
```

**Comment by brioapp** [comment]
> This happens because Binance does not support a sandbox API. This is fine and you can ignore it and continue on with whatever you want to do, or you can suppress the warning using
> 
> ```
> import warnings
> warnings.filterwarnings("ignore")
> ```
> 
> just make sure you put it before the data line

I'll try. Thanks.
