### ISSUE TITLE
I don't receive any error messages

### ISSUE THREAD

**Issue by VisionTrader** [sammchardy/python-binance#608]
Hi,

I have tried to catch any error messages from the exchange with the following code:
def process_message(msg):
	if 'e' in msg.keys():
		logging.error(msg)

In general the websocket is working fine so far, but i don't seem to have any control when different events happen.
For example i disconnected the Internet connection for 1 h and i didn't receive any message, error or not error. It is strange not to see any message about the disconnection, about the retry or anything. 

Could you please provide more details about the behavior of the websocket in case of disconnections and how can i see any error? 

Thank you!

**Comment by kimchirichie** [comment]
if you are trying to use websockets I recommend `oliver-zehentleitner/unicorn-binance-websocket-api/` instead of this lib. while you can use this lib for websockets, there hasnt been updates and is most likely outdated.
