### ISSUE TITLE
binance_python_exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

### ISSUE THREAD

**Issue by MennovDijk** [sammchardy/python-binance#61]
Hey there.

When trying to sent a order_limit_buy with following parameters:

`my_binance.order_limit_buy(symbol = "TRXBTC", quantity = 500, price = 0.00000243) `

It keeps returning this error:

```
File "C:/Users/ikdem/PycharmProjects/Test/Bot.py", line 135, in buy_algo
    response = self.limit_buy_binance(market="TRXBTC", quantity=500, rate = 0.00000243)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 921, in order_limit_buy
    return self.order_limit(timeInForce=timeInForce, **params)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 885, in order_limit
    return self.create_order(**params)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 848, in create_order
    return self._post('order', True, data=params)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 179, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 150, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 145, in _request
    return self._handle_response(response)
  File "C:\Users\ikdem\PycharmProjects\Test\binance_python.py", line 169, in _handle_response
    raise BinanceAPIException(response)
binance_python_exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
```

I know that it has to do with the amount of decimals that are present. If I try and execute the order with only 5 decimals in total it does work. (For example an order sent like this, where I posted an order at the price of 0.0003). 

`
12-27 16:12:35 | TRX/BTC | Limit | Buy | 0.00000242 | 0.00030000 | 10 | 10 | 0.00002420 | -- | Filled
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
`

Any fixes for this?

**Comment by sammchardy** [comment]
Hi @MennovDijk different symbols have different precision. You can get info about all symbol using the `get_exchange_info` or a particular symbol using the `get_symbol_info` call.
Read more about the filtering applied here https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters

**Comment by MennovDijk** [comment]
@sammchardy Thank you for your reply!

I had already done this specific check before but maybe I'm interpreting the results wrong. My order as shown below for the specific crypto (TRX) seems to be adhering to all the rules set by the symbol information in Binance. On top of that it says that the quote precision is 8 (which I assume are decimal numbers). 

Thank you for linking the github as well by the way, I've read through it but unfortunately it does not seem to contain any information with regards to the issue I'm facing.

**Comment by MennovDijk** [comment]
For the people that might stumble upon this issue from googling this issue. Converting the price in the order_limit_buy function from a float to a string (with decimal precision of 8) and then passing this string into the function will alleviate the issue. This could probably very easily be fixed in the code of this library,
