### ISSUE TITLE
Endpoints documentation as .md file?

### ISSUE THREAD

**Issue by mfiro** [sammchardy/python-binance#610]
Hi,

Firstly, thank you for maintaining this wonderful project:)

One thing which confuses me, is that there is no documentation (in github) that explaines which function represents which endpoint in [the official api documentation](https://binance-docs.github.io/apidocs/#change-log). We have docstring for each function, but if you want to look for a specific function, you need then to go source code and search for it.

My idea ist to have this as a .rst or .md file. To be more specific, I mean something like the Readme file of pycoingecko project on github ([link](https://github.com/man-c/pycoingecko)).

Actually, I started to write such a documentation, but the problem I am not familiar enough with different endpoint (futures, testnet and spot) honestly.

**Comment by kimchirichie** [comment]
yes, this is true. you'll need to dig through the source code to find out what end point each method will request.

I would be down to merge in a PR if you were willing to contribute

**Comment by mfiro** [comment]
ok, should it be done as a separate .md file or should be added to the main Readme file? I guess the former is better because the file will be long.

**Comment by kimchirichie** [comment]
separate md should be cool. perhaps a link from main readme to the new page would prove useful
