### ISSUE TITLE
Add isolated margin account and order

### ISSUE THREAD

**Issue by xulngx** [sammchardy/python-binance#612]
**Describe the bug**
I want to add isolated margin account_info and order functions myself but I don’t know how to do that. Can anyone help me please!!! 

**Expected behavior**
Add isolated margin account info and order functions.

**Environment (please complete the following information):**
Ubuntu 16
Python 3.7
Python-binance

**Comment by mfiro** [comment]
For this you should find the endpoint address from the official API documentation.  For **Query Isolated Margin Account Info (USER_DATA)** it is:
```
GET /sapi/v1/margin/isolated/account (HMAC SHA256)
```
Then try to add it to client.py. See other functions to know which prefix/variable represents ```/sapi/```. Also a PR is nice if everything works.

**Comment by xulngx** [comment]
Thanks a lot!!! It works fine for me, just add a function in client.py file.

**Comment by kimchirichie** [comment]
mind creating a PR for the community?

**Comment by xulngx** [comment]
Yes sure! I’m really glad that I can help, I’ll work on that😁

**Comment by ttamg** [comment]
How is this coming on on adding the isolated market functionality?  

I need to do the same in the next couple of weeks.  Do you want me to help with the PR or create it?  Thanks a lot.  Great work  :-)

**Comment by ttamg** [comment]
I see that the new get isolated account endpoint has just been merged into master.  Great stuff thanks!

There are a few other issues that mean python-binance doesn't yet have what is needed to trade on isolated margin.  I'm proposing creating a PR for the following over the coming days.  ... 
* There are a number of other missing isolated margin endpoints I need including - create isolated margin account, isolation margin account transfers,  As referenced in the main Binance docs  e.g. https://binance-docs.github.io/apidocs/spot/en/#isolated-margin-account-transfer-margin
* The margin order endpoints on Binance have an `isIsolated` parameter that enables us to trade the isolated margin accounts.  e.g. https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade.  But these parameters are not exposed in the python-binance docstrings and docs.  I think they will work out of the box but will test them and make sure the docs.
* The  docs page on Margin trading deals currently with cross margin.  https://python-binance.readthedocs.io/en/latest/margin.html  That's not clear in the docs and I only worked it out by testing it on my own exchange account for some time.  I can propose some documentation edits to add in the new endpoints and make the isolated- vs cross-margin a bit clearer.

Do you want a PR for this?

**Comment by ttamg** [comment]
I've now added the Binance isolated margin endpoints I need.  
And I have updated the docs for isolated margin.  

I'll post a PR now and you can review if you want to include @kimchirichie

**Comment by kimchirichie** [comment]
merged!

**Comment by ttamg** [comment]
Great.  Thanks @kimchirichie 
Do you have a plan for when to do the next Pypi release?
For now I will import from master branch.

**Comment by kimchirichie** [comment]
@ttamg 0.7.7 was released 4 days ago. thanks for waiting
