### ISSUE TITLE
User websocket not giving all the trades/orders

### ISSUE THREAD

**Issue by coalaroot** [sammchardy/python-binance#63]
Hi,
I'm using user socket to place an order to sell when i bought something, but the websocket seems to not notice sometimes some trades. Is it because of Binance API bug or something wrong with the library?

**Comment by sammchardy** [comment]
Hi @coalaroot if the websocket only seems to be returning some but not others it may be an issue with the Binance API itself. This library doesn't filter any messages.
Best place to get further help is the Binance API Telegram group https://t.me/binance_api_english
