### ISSUE TITLE
Order market buy and sell not shown on binance transaction history.

### ISSUE THREAD

**Issue by athenasaurav** [sammchardy/python-binance#642]
Hello Everyone

I m trying to use you this python binance to buy and sell crypto currency. 

Currently i have more than enough balance to place BTCUSDT trade of buy or sell in my account. I have written a simple script to buy crypto first and then after some delay time sell them using your following code : 

Place a market order

Use the helper functions to easily place a market buy or sell order

order = client.order_market_buy(
    symbol='BNBBTC',
    quantity=100)

order = client.order_market_sell(
    symbol='BNBBTC',
    quantity=100)

In the terminal i see no errors, buy and sell are successful i even get order id, trade id etc but when i check the history in SPOT order of trade history it doesn't appear in there. 

Terminal Window screenshot attached. But in the SPOT wallet order history or trade history it doesn't shows up. Only those trades are shown that I did manually. 

![ceb3fcc7-07f6-41ab-8287-a12cd90e6620](https://user-images.githubusercontent.com/530190/103789392-f35fe880-5065-11eb-894e-c600d44fbe07.jpg)

Please help 

Regards,

Kumar Saurav

**Comment by markeyev** [comment]
Hello Kumar,

It is just impossible to help you without any data about the actual code implementation of order creation.

**Comment by athenasaurav** [comment]
Hello @markeyev , I actually solved the issue.
