### ISSUE TITLE
Support for USDT-M or COIN-M Futures?

### ISSUE THREAD

**Issue by ashwinvenkatram** [sammchardy/python-binance#652]
Hello,

I'm looking to trade USDT-M Futures on Binance.

From the documentation available on the python-binance project, I found some of the common endpoints and data stream functions have already been implemented under margin trading.

Is anyone here developing the unique functions for USDT-M / COIN-M Futures on this project?
Eg: Funding Rate, USDT-M Margin Call, etc

I can implement this if necessary. Do let me know.

**Comment by markeyev** [comment]
Dear ashwinvenkatram,

I think this set of functions are for Futures endpoints https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L4815. At least I'm using them successfully for USDT-M Futures trading.

Best regards,
Ivan

**Comment by ashwinvenkatram** [comment]
Dear Ivan,

Thanks very much for sharing the location of the functions in the Client class. This is exactly what I'm looking for.

Good to know you've successfully used them for USDT-M Futures.

Best Regards,
Ashwin
