### ISSUE TITLE
Depth channel socket update messages

### ISSUE THREAD

**Issue by ngallot** [sammchardy/python-binance#70]
Hello guys,

 I thinks there's an issue on the way depth socket messages are handled by the DepthCacheManager. Playing around with it for several days and storing the values in a time series database, I noticed after some restarts that sometimes, either the best bid or best ask would not move until the next restart. I believe it's due to 2 things: 

1. 

The start_depth_socket() method of the BinanceSocketManager listens by default to the [Diff.Depth Stream endpoint](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#diff-depth-stream) and not to the [Depth Websocket EndPoint](https://www.binance.com/restapipub.html#depth-wss-endpoint) described on the api doc of Binance website. The difference between those 2 is that the diff depth stream endpoint provides a first_update_id and a last_update_id ('U' and 'u' in the json response). The DepthCacheManager does not handle this first_update_id as described [here](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#how-to-manage-a-local-order-book-correctly)

2. 

From the constructor of the DepthCacheManager: 
`self._start_socket()`
`self._init_cache()`

==> what can happen is that the self._start_socket() method takes longer than the self._init_cache(), in that case, the sate of the order book would not be consistent between the one returned by the rest api call and the one returned by the websocket. For example, _init_cache() could return a LastUpdateId = 1, and _start_socket() could return a first message with 'U' = 3 and 'u' = 4, which would mean we did not process the update 2.
So I think it is necessary to add code to wait for the websocket to have received at least 1 message before starting the rest call to get the state of the current order book, and also start processing websocket from U == LastUpdateId +1 (and not U <= LastUpdateId +1).

Also, another weird stuff I noticed (this time related directly to binance websocket api), is receiving messages like this when listening to the diff depth stream: 

{
  "e": "depthUpdate", // Event type
  "E": 123456789,     // Event time
  "s": "BNBBTC",      // Symbol
  "U": 157,           // First update ID in event
  "u": 160,           // Final update ID in event
  "b": [              // Bids to be updated
    [
      "0.0024",       // price level to be updated
      "10",
      []              // ignore
    ]
  ],
  "a": [              // Asks to be updated
    [
      "0.0026",       // price level to be updated
      "100",          // quantity
      []              // ignore
    ]
  ]
}
==> if 'U' = 157 and 'u' = 160, I am assuming I should see 4 update messages. But here, only 1 bid and 1 ask have been updated. Am I wrong in my assumption? (this json is from [binance official doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#diff-depth-stream) but I've observed similar messages myself).

**Comment by sammchardy** [comment]
Hi @ngallot thanks for the in depth report.

I've just released v0.5.14 which addresses a couple of your issues.

1. Wait for socket to connect initially before requesting depth cache

2. Check update id on messages to make sure they are sequential, if not start over

In regard to the websocket, it is listening to the diff responses. It may be confusing as my documentation didn't catch all the changes after changes a little while back. You can call the `start_depth_socket` without the `depth` parameter for diff messages, or with it for partial book messages.

You assumption about the case where 'U' = 157 and 'u' = 160 and expecting 4 updates may be correct. The case where I can see it not being the case is if there were multiple updates to the same price as the quantity is aggregated. I'm also making assumptions and you would be best to ask on the official Binance API telegram group to clarify it.

**Comment by ngallot** [comment]
Thanks @sammchardy, I'll test that! I'll write to binance telegram group and will let you know what they reply about the update ids.

**Comment by sammchardy** [comment]
Closing this issue for now.

**Comment by gitcnd** [comment]
Did you get to the bottom of the wrong IDs for "U"/"u" ?

Here's 2 messages, both with one update - the first has U=u and the second has U=u-1

{"stream":"cndbtc@depth","data":{"e":"depthUpdate","E":1518352077350,"s":"CNDBTC","U":9800282,"u":9800282,"b":[["0.00002044","293.00000000",[]]],"a":[]}}
{"stream":"rlcbtc@depth","data":{"e":"depthUpdate","E":1518352077351,"s":"RLCBTC","U":2288326,"u":2288327,"b":[],"a":[["0.00015980","12.99000000",[]]]}}
