### ISSUE TITLE
Issues with installing

### ISSUE THREAD

**Issue by zahor99** [sammchardy/python-binance#71]
Hello,

First of all, thank you for making these scripts. I am new to python and I intended to use it with anaconda and spyder. Would it work?

I tried many different ways and I got stuck. The standard pip did not work so I tried conda, however I got this message:
![image](https://user-images.githubusercontent.com/34937817/34482346-ac4f9b28-efb7-11e7-9449-65f59c2cb7b4.png)

**Comment by sammchardy** [comment]
Hi @zahor99 I will look into adding the package to conda.

For Windows errors can you see if the fixes described in this previous issue help. #46
