### ISSUE TITLE
User data stream became unreliable recently?

### ISSUE THREAD

**Issue by karlosss** [sammchardy/python-binance#712]
Hi!

I am using python-binance for the user data stream (websocket). Recently (like 1 week ago), the socket stops sending me updates after 1 - 4 hours (chosen pretty much at random every time I open the connection) without any signs of the connection being closed. It was working perfectly fine before.

I am wondering if anyone else is experiencing the same. Is there a recent change on Binance's side I am not aware of?

Thanks for sharing your thoughts!

**Comment by nexo01** [comment]
Got the same problem. No User-Messages after some random time without any Exception or message.
Did you find any solution for this ?

**Comment by karlosss** [comment]
Not really. I create and cancel an order every second and await the response in the stream - if it does not arrive within 5 seconds, I consider it disconnected and just restart my application.

**Comment by nexo01** [comment]
I got it!
I was able to fix the problem by checking out the master branch and using it in my application instead of the pip package. There is a corresponding commit message 4 days ago.

**Comment by GeniusShiki** [comment]
Hi, have you solved the problem? I got the same problem and it doesn't work by using the master branch instead of the pip packages.

**Comment by karlosss** [comment]
Works for me now, I run a separate thread (which i wrote myself from scratch) which sends keepalive every 5 minutes.

**Comment by GeniusShiki** [comment]
ok,thank you so much,I will try it

**Comment by guillemavila** [comment]
Just submitted a pull request to do it internally with no extra code, just change the user timeout when initializing the socket manager. Default is 30, you may change it to 5:

```python
bm = BinanceSocketManager(client, user_timeout=5*60)
```

Thanks for pointing out @karlosss
