### ISSUE TITLE
ModuleNotFoundError: No module named 'binance'

### ISSUE THREAD

**Issue by JensRozenveld** [sammchardy/python-binance#714]
I try to run this code with Flask:

from flask import Flask, render_template
import config, csv
from binance.client import Client

client = Client(config.API_KEY, config.API_SECRET)

app = Flask(__name__)

@app.route('/')
def index():
    title = 'CoinView'

    print(client)

    return render_template('index.html', title=title)

@app.route('/buy')
def buy():
    return 'buy'

@app.route('/sell')
def sell():
    return 'sell'

@app.route('/settings')
def settings():
    return 'settings'

But when I try to run it with flask run in my comandprom it says: 
File "CUsers\username\...\CoinView\app.py", line 3, in <modle> ModuleNotFoundError: No module named 'binance' 

what to do? Pleas help.

I use windows 10 pro.

**Comment by VGabriel45** [comment]
Install python-binance -> pip install python-binance
import it like this -> from binance.client import Client

**Comment by JensRozenveld** [comment]
@VGabriel45  I am using flask for my a local webserver and I get a Traceback with a message: File "C:\Users\Jens Rozenveld\Jens Python\CoinView\app.py", line 3, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
from flask so I think it is a problem with flask but I dond't no how to fix it. And the you were saying I tried all ready so manny times :D.

**Comment by VGabriel45** [comment]
Check out you Python version or Flask version, it may not be compatible.Or you can try to add the module manually.

**Comment by JensRozenveld** [comment]
I'am using: Python 3.9.2
and: Flask 1.1.2

**Comment by JensRozenveld** [comment]
Or how can I onstall it manually?

**Comment by JensRozenveld** [comment]
I see right now that this is the whole eror message: 
Traceback (most recent call last):
  File "c:\users\jens rozenveld\jens python\coinview\env\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\Jens Rozenveld\Jens Python\CoinView\app.py", line 3, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'

Do you now what this is?

**Comment by min0ru** [comment]
@JensRozenveld 
How did you installed flask and python-binance packages into your virtual environment?

Did you installed "binance" library with command like provided below?
`pip install python-binance`

Could you get a list of installed packages with command below and post it here?
`pip list`

Try to import binance library without launching flask application:
`python -c 'import binance; print(binance)'`
Do you get any error with that instruction?

**Comment by JensRozenveld** [comment]
Hi @min0ru  I install flask this way in my venv: go to my cmd and then to the correct file via 'cd'. Then typing: python -m venv env. Then env\Scripts\activate, then: set FLASK_APP=app.py, then flask run. 

Pip list command: 
appdirs           1.4.4      
astroid           2.4.2      
attributedict     0.3.0      
attrs             20.3.0     
autobahn          21.2.1
Automat           20.2.0
backtrader        1.9.76.123
backtrader2       1.9.76.123
beautifulsoup4    4.9.3
binance           0.3
binance-client    1.0.0
blessings         1.7
certifi           2020.12.5
cffi              1.14.5
chardet           4.0.0
click             7.1.2
codecov           2.1.11
colorama          0.4.4
coloredlogs       15.0
colour-runner     0.1.1
Command           0.1.0
config            0.5.0.post0
config2           0.3.2
console           0.9906
constantly        15.1.0
coverage          5.4
cryptography      3.4.5
csv342            1.0.1
datasource        0.2.0
dateparser        1.0.0
datetime2         0.7.5
debugger          1.3
debugpy           1.2.1
deepdiff          5.2.2
deepmerge         0.1.1
distlib           0.3.1
docopt            0.6.2
enums             0.0.2
ezenv             0.92
filelock          3.0.12
flash             1.0.3
Flask             1.1.2
humanfriendly     9.1
hyperlink         21.0.0
idna              2.10
incremental       17.5.0
inspecta          0.1.3
isort             5.7.0
itsdangerous      1.1.0
Jinja2            2.11.3
Js2Py             0.70
jsonify           0.5
jsonlib-python3   1.6.1
lazy-object-proxy 1.4.3
MarkupSafe        1.1.1
mccabe            0.6.1
mybad             0.1.4
numpy             1.20.1
ordered-set       4.0.2
orderedmultidict  1.0.1
packaging         20.9
pandas            1.2.2
pip               21.0.1
pipwin            0.5.1
plint             0.1
pluggy            0.13.1
pprintpp          0.4.0
psycopg2          2.8.6
py                1.10.0
pyasn1            0.4.8
pyasn1-modules    0.2.8
pycparser         2.20
Pygments          2.8.0
PyHamcrest        2.0.2
pyjsparser        2.7.1
pylint            2.6.0
pyOpenSSL         20.0.1
pyparsing         2.4.7
PyPrind           2.11.2
pyreadline        2.1
pySmartDL         1.3.4
python-binance    0.7.9
python-dateutil   2.8.1
pytz              2021.1
PyYAML            5.4.1
regex             2020.11.13
requests          2.25.1
rootpath          0.1.1
runpy2            2.5
service-identity  18.1.0
setupextras       0.1.5
setuptools        53.0.0
six               1.15.0
somepackage       1.2.3
soupsieve         2.2
stream-redirect   0.1.2
TA-Lib            0.4.19
template-render   0.1.0
termcolor         1.1.0
toml              0.10.2
tox               3.22.0
Twisted           20.3.0
txaio             20.12.1
tzlocal           2.1
ujson             4.0.2
urllib3           1.26.3
venv-dependencies 1.0.8
virtualenv        20.4.2
websocket-client  0.57.0
Werkzeug          1.0.1
wheel             0.36.2
wrapt             1.12.1
zope.interface    5.2.0

and when I type your command this is my outpout:
<module 'binance' from 'C:\\Users\\Jens Rozenveld\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\binance\\__init__.py'>

**Comment by min0ru** [comment]
I just checked your source code with:
python 3.9.2
flask 1.1.2
python-binance 0.7.9

It works for me so it's not packages/versions incompatibility or bug in your code.

As far as i can see you have run `pip list` and `python -c 'import binance; print(binance)'` without activating your virtual environment. So you have flask and python-binance installed in system (global environment). Now try to activate your virtual environment and run the same commands once again please. (`env\bin\activate; pip list`)

Or try to run pip of your "coinview" env directly to check that you have python-binance installed in your virtualenv:

`c:\users\jens rozenveld\jens python\coinview\env\bin\pip.exe list`

You have also installed packages 'binance 0.3' and 'binance-client 1.0.0' that potentially could lead to name conflicts with python-binance package. Consider uninstalling unnecessary packages from your system environment.

**Comment by JensRozenveld** [comment]
o thank you so so so mutch I think I'am a little stuppid... I didn't install python-binance in my env
So So thank you.

**Comment by JensRozenveld** [comment]
so now i have my second problem: when i want to use this code:
from flask import Flask, render_template
import config, csv
from binance.client import Client
from binance.enums import *
@ app.route ('/ buy')
def buy ():

    order = client.create_order (symbol = 'ETHEUR', side = SIDE_BUY, type = ORDER_TYPE_LIMIT, timeInForce = TIME_IN_FORCE_GTC, quantity = 100, price = '0.00001')
    
    return 'buy'

flask returns the following error: binance.exceptions.BinanceAPIException: APIError (code = -1013): Filter failure: PRICE_FILTER

what should I do?

**Comment by min0ru** [comment]
@JensRozenveld
This is server API error, not a python-binance client issue.
First of all you should check API documentation for error code (https://github.com/binance/binance-spot-api-docs/blob/master/errors.md). Unfortunately code '-1013' is not present in this doc, seems like it's a bit outdated. You could create corresponding issue in that repository.

My guess that your price value is not accepted by binance market because it's too low and out of some allowed price range (current ETH price is ~ 1238.20 EUR). Try other price values.
