### ISSUE TITLE
FLask eror: binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by JensRozenveld** [sammchardy/python-binance#719]
when i want to use this code:

from flask import Flask, render_template
import config, csv
from binance.client import Client
from binance.enums import *

@ app.route ('/ buy')
def buy ():

    order = client.create_order (symbol = 'ETHEUR', side = SIDE_BUY, type = ORDER_TYPE_LIMIT, timeInForce = TIME_IN_FORCE_GTC, quantity = 100, price = '0.00001')
    
    return 'buy'

flask returns the following error: binance.exceptions.BinanceAPIException: APIError (code = -1013): Filter failure: PRICE_FILTER

what should I do?

**Comment by Luminous13** [comment]
I guessing this one is associated to order sizes. You need to check a pair's limitation first. It's mostly about the number of decimal places.

**Comment by stwwrong** [comment]
check the price filter setting of ETHEUR, that said the minPrice is 0.01
```
  {
      "filterType": "PRICE_FILTER",
      "minPrice": "0.01000000",
      "maxPrice": "100000.00000000",
      "tickSize": "0.01000000"
  }
```

https://binance-docs.github.io/apidocs/spot/en/#filters

**Comment by Bob12345** [comment]
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#filters

**Comment by Bob12345** [comment]
Those filters are a pain in the butt, by the way.....

**Comment by hadisaadat** [comment]
Fuck You The developer,  this is the worst ever stupid error and pain in whole trade dev tools ever, Fuck you MF, Fuuuuuuuuuuuuuuuuck you, it never works Fuck you

**Comment by JensRozenveld** [comment]
thanks for help
