### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

### ISSUE THREAD

**Issue by Hujjat** [sammchardy/python-binance#72]
Hi,

I am using Windows 10 and Python 3.6.*
I could successfully install the module but when I use the demo code, it doesn't work. 

### Here is what I have done

created a binance.py file and wrote the following code

`from binance.client import Client`

just this much code. When I run it in the IDE, I get this error

```
Traceback (most recent call last):
  File "C:\Users\username\Desktop\python\binance.py", line 1, in <module>
    from binance.client import Client
  File "C:\Users\username\Desktop\python\binance.py", line 1, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

```

What's wrong with my code. 

Thanks

**Comment by sammchardy** [comment]
Hi @Hujjat, by calling your file `binance.py`, and then trying to import from `binance.client` python is looking in your `binance.py` file.

If you rename your local file then you won't have an issue.

**Comment by Hujjat** [comment]
They thank's 
that fixed the issue :)

**Comment by gacopl** [comment]
oh lol so fucking classic and stupid :) Thanks !

**Comment by mehmetcolgecen** [comment]
thank you silly me

**Comment by zmfb039** [comment]
Hi Guys i have a similar issue. I haven't been able to run a single Binance bot yet but i can get python 3.6 to run on for a few Bittrex bots.  I'm using windows 10 too. Keep getting "no module named "Binance".  Any ideas?

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: C:\Users\User\Documents\PYTHON\BinanceTrendBot-master\trend.py ==
Traceback (most recent call last):
  File "C:\Users\User\Documents\PYTHON\BinanceTrendBot-master\trend.py", line 3, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'

**Comment by sundarkast** [comment]
> Hi @Hujjat, by calling your file `binance.py`, and then trying to import from `binance.client` python is looking in your `binance.py` file.
> 
> If you rename your local file then you won't have an issue.

Perfect.. thanks . simple but was driving me crazy!!

**Comment by amitauman** [comment]
I don't understand. changing binance.py to binance1.py for example wont cause a problem later on using the package ? 
thanks

**Comment by Aldebaran-Industries** [comment]
I'm having the same issue, module installed on windows 10, name of file doesn't matter, can't seem to get it to work

**Comment by DrIanGregory** [comment]
Worked for me.

**Comment by janascc** [comment]
hi there, I'm still having the same issues, ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package.
experiencing the same issues either on win 10 or mac, no differences at all.
i don't really know what else should I do to fix it.
any advise would be really appreciate.
thanks in advance.

**Comment by IanFLee** [comment]
Hello friends. I solved this issue by using conda specifically (no other source worked):

`conda install twisted`

**Comment by Rens540** [comment]
Hello Friends, after struggling quit a while with Pycharm and Python 3.8 , I came to this simple sollution. I have Made Up Visual Studio 2019 , with Python 3.7 and it works without any problems. No updates or pip installs needed.

**Comment by michalhanak** [comment]
Uff it took me week to find this post. Many thanks.
