### ISSUE TITLE
client.get_account_snapshot()

### ISSUE THREAD

**Issue by lordAnubis** [sammchardy/python-binance#728]
**Describe the bug**
I get the error AttributeError: 'Client' object has no attribute 'get_account_snapshot'
when I call 

spot_info = client.get_account_snapshot() or
spot_info = client.get_account_snapshot("SPOT")

also in the documentation there is information missing >> https://github.com/sammchardy/python-binance/blob/master/docs/general.rst

"Get Get Daily Account Snapshot

Get daily account snapshot of specific type. Valid types: SPOT/MARGIN/FUTURES.
"
Where is the call info?

**To Reproduce**
type
"spot_info = client.get_account_snapshot("SPOT")"

**Expected behavior**
SPOT information

**Environment (please complete the following information):**
 - Python version: 3.9
 - OS: Mac
 - python-binance version the version that is installed with  pip instal , so I guess v0.7.9

**Logs or Additional context**
spot_info = client.get_account_snapshot()
AttributeError: 'Client' object has no attribute 'get_account_snapshot'

**Comment by AlexNik** [comment]
@lordAnubis Hello!
This feature haven't been releases yet.
It is in master branch only.
If you installed `python-binance` from pip you should wait for next release.
Or checkout master branch and build it by yourself.

**Comment by lordAnubis** [comment]
Thank you

any timespan available when the next release will become available in pip?

I am brand new too python and haven't develop the skills yet to build from GitHub. Any tut's about this for this package/modul?

**Comment by AlexNik** [comment]
@kimchirichie any news about next release?

**Comment by JeromeFr** [comment]
> @lordAnubis Hello!
> This feature haven't been releases yet.
> It is in master branch only.
> If you installed `python-binance` from pip you should wait for next release.
> Or checkout master branch and build it by yourself.

Thanks for that answer, I was getting crazy trying to run get_all_coins_info that is also not available yet in the latest release

**Comment by lordAnubis** [comment]
Is there a tutorial how to build this python code?

**Comment by AlexNik** [comment]
> 
> 
> Is there a tutorial how to build this python code?

@lordAnubis 
First you have to install git, python and pip on your PC.
Try this code in new dir:
```
git clone https://github.com/sammchardy/python-binance
cd python-binance
pip3 install -r requirements.txt
python3 setup.py install
```

If you use Windows change `pip3` and `python3` to `pip` `python`.

**Comment by lordAnubis** [comment]
oke, will do that.

**Comment by acurvers** [comment]
@AlexNik Hi Alex, kan we have a new release? I also would like the account snapshot endpoint

**Comment by AlexNik** [comment]
@acurvers Hi! I am not the owner of this tool.
You should ask @kimchirichie

**Comment by acurvers** [comment]
@kimchirichie great tool, can the new changes be released?

**Comment by acurvers** [comment]
> > Is there a tutorial how to build this python code?
> 
> @lordAnubis
> First you have to install git, python and pip on your PC.
> Try this code in new dir:
> 
> ```
> git clone https://github.com/sammchardy/python-binance
> cd python-binance
> pip3 install -r requirements.txt
> python3 setup.py install
> ```
> 
> If you use Windows change `pip3` and `python3` to `pip` `python`.

going through that staps my ide was still using the original/official 0.7.9 in my case it helped to change the version to 0.7.9.dev in setup.py  
then reinstall

**Comment by riphet** [comment]
I not have PC.
I not have Windows.

I have Smartphone with Android.
I have Pydroid3.

Then how to clone the python-binance ???...

**Comment by riphet** [comment]
Your answer will be valuable when you pay attention to my question.

1.- It's not about Windows, it's about ANDRIOD.
2.- It is about APP PYDROID3
3.- The question is: How to clone a GITHUB repository to use it on the Smartphone ???

I really appreciate your time and attention.

**Comment by lordAnubis** [comment]
The answer from AlexNik did work. Thank you
