### ISSUE TITLE
WEBSOCKET_DEPTH_1 still referenced in  v0.5.14

### ISSUE THREAD

**Issue by ngallot** [sammchardy/python-binance#73]
Hi @sammchardy , this enum has been removed, but it is still referenced in websocket.py, l 157:
`if depth and depth != self.WEBSOCKET_DEPTH_1:
            socket_name = '{}{}'.format(socket_name, depth)`

**Comment by sammchardy** [comment]
Thanks @ngallot this is fixed in v0.5.15
