### ISSUE TITLE
Timestamp was ahead of the server's time.

### ISSUE THREAD

**Issue by lindomar-oliveira** [sammchardy/python-binance#746]
I inevitably get the error `APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.` at least once a day.

I tried to solve it in several ways but without success, synchronizing my clock with an NTP server (time.nist.gov) and increasing the value of recvWindow.

Looking at the lib code, I realized that the difference between local time and the Binance server has been corrected. **Executed only once in the class constructor.**

https://github.com/sammchardy/python-binance/blob/2097ab31955df3e6585282793fe8dc51a9b9f6e4/binance/client.py#L135

However, the actual value of the `timestamp_offset` continues to vary, not always being the same, and this may be the cause of the error I receive.

**Environment**
 - Python version: 3.6.9
 - Virtual Env: virtualenv
 - OS: Ubuntu Server 18.04
 - python-binance version: lastest (branch master)

**Comment by Bob12345** [comment]
sync your computer's clock. several times, manually. windows is very bad at this.

**Comment by fmarzolo** [comment]
I'm working in a Raspbian environment, my clock is sychronized every 30 secs, but I receive the same message:

**Comment by lindomar-oliveira** [comment]
What I did to solve this problem was to create a `retry` decorator to deal with the error and correct the `timestamp_offset`, as seen in the code below:

https://github.com/lindomar-oliveira/backtrader-binance/blob/2492c1c411745c1c7c2f128a442e0d24c7b86c85/backtrader_binance/binance_store.py#L85-L100
