### ISSUE TITLE
[help] How can to get USDT balance from margin account?

### ISSUE THREAD

**Issue by avatar-lavventura** [sammchardy/python-binance#748]
I can get my balance as follows:

```
balances = client.get_account()
```

----

But I won't able to get margin balances especially `USDT`. Is there any way to get USDT balance from margin account?

**Comment by TheSeacfr** [comment]
Hello,

It might not be the most elegant way to do it, but you can try:

`def BalanceUSDT():
    try:
        b=client.futures_account_balance()
        b = pd.DataFrame.from_dict(b)
        b = b.loc[b['asset']=='USDT']
        balance_USDT = float(b['balance'].values)
    except:
        balance_USDT=0
    return balance_USDT`

**Comment by avatar-lavventura** [comment]
@TheSeacfr Working code:

```

def get_balance_margin_USDT():
    balance_USDT = 0
    try:
        b = client.futures_account_balance()
        b = pd.DataFrame.from_dict(b)
        b = b.loc[b['asset']['USDT']]
        balance_USDT = float(b["balance"].values)
    except:
        pass
    return balance_USDT
```

But still it returns `0` for the balance in margin.

**Comment by TheSeacfr** [comment]
I am sorry but I don't use margin so I cannot really test on my account.
However, based on what I have sent before, something like that should work:

> def get_balance_margin_USDT():
    try:
        b=client.get_margin_account()[1:]
        b = pd.DataFrame.from_dict(b)
        b = b.loc[b['asset']=='USDT']
        balance_USDT = float(b['free'].values)
    except:
        balance_USDT=0
    return balance_USDT

Maybe you'll need to modify it slightly since, as I said, I could not test it.

**Comment by avatar-lavventura** [comment]
`b=client.get_margin_account()[1:]` returns `*** TypeError: unhashable type: 'slice'`

**Comment by avatar-lavventura** [comment]
I verify that following code piece works:

```
def get_balance_margin_USDT():
    try:
	_len = len(client.get_margin_account()["userAssets"])
	for x in range(_len):
            if client.get_margin_account()["userAssets"][x]["asset"] == "USDT":
		return client.get_margin_account()["userAssets"][x]["free"]
    except:
        pass
    return 0
```

**Comment by luc77777** [comment]
works for me:
def get_balance_margin_asset(asset):
    balance_asset = 0
    try:
        b = client.futures_account_balance()
        b = pd.DataFrame.from_dict(b)
        b = b.loc[b.asset==asset, 'balance'].values[0]
        balance_asset = float(b)
    except:
        pass
    return balance_asset

to run e.g.: 
get_balance_margin_asset('USDT')
