### ISSUE TITLE
Support for HTTP/HTTPS proxies

### ISSUE THREAD

**Issue by csparpa** [sammchardy/python-binance#75]
Feature request as per title

Thanks

**Comment by ledil** [comment]
Why ? If you are a linux user you can still set environment variables for Proxy, this should not be a feature of a library (imho)

**Comment by csparpa** [comment]
And what if I'm not on Linux? What if I cannot set any env variable on my platform because I don't have enough privileges?

Having the possibility to set proxies on the library would be helpful then (possibly `requests `helps you to do this easily)

**Comment by sammchardy** [comment]
Hi @csparpa you can set a proxy for requests to use using environment variables, see documentation here http://docs.python-requests.org/en/master/user/advanced/#proxies

If on Windows you can read this about setting environment variables https://docs.python.org/3/using/windows.html#excursus-setting-environment-variables

**Comment by danerlt** [comment]
I add proxies params in client __init__ function 
![image](https://user-images.githubusercontent.com/14197717/103741821-bc251380-5034-11eb-8005-1b288b10c69b.png)
