### ISSUE TITLE
APIError(code=-1100): Illegal characters found in parameter 'price'

### ISSUE THREAD

**Issue by kuratkull** [sammchardy/python-binance#754]
Here's what's wrong with the price parameter. can i get information

          `
          symbolTicker = 'BNBBTC'
          quantity = 1
          prev_symbolPrice = 0

        list_of_tickers = client.get_all_tickers()
        for tick_2 in list_of_tickers:
            if tick_2["symbol"] == symbolTicker:
                prev_symbolPrice = float(tick_2["price"])
        
        order = client.create_order(
            symbol = symbolTicker,
            side = 'BUY',
            type = 'STOP_LOSS_LIMIT',
            quantity = quantity,
            price = round(prev_symbolPrice*1.001,7),
            stopPrice = round(prev_symbolPrice*1.002,7),
            timeInForce = 'GTC'
        )
`

**Comment by Bob12345** [comment]
can you print the price? it could be converted to scientific notation. print it and see.`print(str(round(prev_symbolPrice*1.001,7))`

**Comment by kuratkull** [comment]
that's all the code .can you check?
`
import config
from binance.client import Client
from binance.enums import *
import time
import numpy as np


client = Client(config.API_KEY, config.API_SECRET)

symbolTicker = 'ARPABTC'
quantity = 100
prev_symbolPrice = 0

list_of_tickers = client.get_all_tickers()
for tick_2 in list_of_tickers:
    if tick_2["symbol"] == symbolTicker:
        prev_symbolPrice = float(tick_2["price"])

order = client.create_order(
    symbol = symbolTicker,
    side = 'BUY',
    type = 'STOP_LOSS_LIMIT',
    quantity = quantity,
    price = round(prev_symbolPrice*1.001,7),
    print(str(round(prev_symbolPrice*1.001,7))),
    stopPrice = round(prev_symbolPrice*1.002,7),
    timeInForce = 'GTC'
    )   


while 1:
    time.sleep(5)

    list_of_tickers = client.get_all_tickers()
    for tick_2 in list_of_tickers:
        if tick_2["symbol"] == symbolTicker:
            current_symbolPrice = float(tick_2["price"])

    print("    Prev_Price = " + str(prev_symbolPrice))
    print(" Current_Price = " + str(current_symbolPrice))

    if ( prev_symbolPrice > current_symbolPrice):

        result = client.cancel_order(
            symbol = symbolTicker,
            orderId = order.get('orderId')
        )

        order = client.create_order(
            symbol = symbolTicker,
            side = 'BUY',
            type = 'STOP_LOSS_LIMIT',
            quantity = quantity,
            price = round(current_symbolPrice*1.001,7),
            print(str(round(prev_symbolPrice*1.001,7))),
            stopPrice = round(current_symbolPrice*1.002,7),
            timeInForce = 'GTC'
        )

        prev_symbolPrice = current_symbolPrice


`
