### ISSUE TITLE
SPOT Testnet API Endpoints not supported

### ISSUE THREAD

**Issue by MethylHaine** [sammchardy/python-binance#757]
|Python version|Virtual Env|OS|python-binance version|
|---|---|---|---|
| Python 3.9.2 | virtualenv | Arch Linux  x86_64 Linux 5.11.8-arch1-1| python-binance==0.7.9 |

Hi  everyone,

It seems SPOT Testnet API Endpoints are not supported :

``` python
try:
    client_test = Client(testnet_api_key, testnet_api_secret)
    return client_test.get_account()
except Exception as apiCallException:
    mylogger("There was an error trying to retrieve account info")
    mylogger(str(apiCallException))

[...]

[14:31:49] ERROR : There was an error trying to retrieve account info
[14:31:49] ERROR : APIError(code=-2015): Invalid API-key, IP, or permissions for action.
```
I believe this is due to the lack of support of the SPOT Testnet API Endpoints in `binance/client.py` ? :
``` python
class Client(object):

    API_URL = 'https://api.binance.{}/api'
    WITHDRAW_API_URL = 'https://api.binance.{}/wapi'
    MARGIN_API_URL = 'https://api.binance.{}/sapi'
[...]
```

Would it be possible to add a feature allowing to pass the target API Endpoint URL as a parameter to the `Client` ?
Something like :
``` python
client_test = Client(testnet_api_key, testnet_api_secret, testnet_api_base_endpoint)
```
Or something like what was made in the [python-binance-chain](https://github.com/sammchardy/python-binance-chain#environments) project :
``` python
from binance_chain.environment import BinanceEnvironment

# initialise with Testnet environment
testnet_env = BinanceEnvironment.get_testnet_env()
client = HttpApiClient(env=testnet_env)
```

All the best,

**Comment by DexterF** [comment]
I've managed to use to use the spot testnet by changing the `API_URL` after initialization (`test.API_URL="https://testnet.binance.vision/api"`) however, this would definitely make it easier to understand and also make cleaner code :)

**Comment by MethylHaine** [comment]
Hi @DexterF,
Thanks for your quick answer !
I am fine doing it this way for now haha,  maybe I'll submit a PR if I manage to find the time someday.
Have a nice day,

**Comment by KirillPleshakov** [comment]
@DexterF Thank you so much
Could you please explain (maybe with example) wixh part of the code you've changed

I've tried hardcoding this base url 'https://testnet.binance.vision/api' to BaseClient class variable API_URL

no luck

**Comment by KirillPleshakov** [comment]
found an example of sending the request with encryption with Python - I will try studying, coding it and replacing the BASE_URL  to testnets` https://github.com/binance-exchange/binance-signature-examples/blob/master/python/spot.py
