### ISSUE TITLE
websockets stop updating

### ISSUE THREAD

**Issue by h3y4w** [sammchardy/python-binance#76]
Hello,

Seem to have a problem where the websocket seems to drop or stop updating and running the callback.  I was originally using the multiplex socket function to run different streams but when I encountered the problem, I also tried with the start_symbol_ticket_socket function.  Sometimes it wouldn't connect from the start as well and stall.  Don't know exactly where the problem is coming from.

**Comment by kiko35** [comment]
Hello, i'm having exactly the same problem today. I think binance's servers are overloaded. Plus, they will disable new user registrations https://support.binance.com/hc/en-us/articles/115003773671

But the good question is how can we identify that a websocket is disconnect from binance's server?

Thanks for the work.

**Comment by sammchardy** [comment]
Hi @h3y4w and @kiko35 unfortunately the Binance API servers seem to be having issues at the moment. See more discussion on the Binance API Telegram group https://t.me/binance_api_english

The websocket tries to reconnect up to 5 times with a longer reconnect delay so should repair small connection issues.

**Comment by h3y4w** [comment]
@sammychardy Is there a way to maybe do something to what @kiko35 said?  Maybe pass along a callback function for when it runs across issues like this?

**Comment by sammchardy** [comment]
Ok, let me see what I can do about raising an Exception when it fails reconnecting

**Comment by echel0n** [comment]
I can confirm this issue does still happen and has forced me back to using API polling

**Comment by sammchardy** [comment]
In v0.6.0 I've added a message that's passed through the callback function to indicate the websocket disconnected and was unable to reconnect.

See documentation here https://python-binance.readthedocs.io/en/latest/websockets.html#websocket-errors

**Comment by kiko35** [comment]
Thank you.

**Comment by ahassaine** [comment]
Is the error message sent through the callback function specific to certain socket types? 
I am using a user socket. When it is disconnected, I don't any receive anything through the callback function. I am using v0.7.9.
Any workarounds to be notified when the user socket is disconnected?
