### ISSUE TITLE
Shift to Binance SAPI?

### ISSUE THREAD

**Issue by AndrewDowning** [sammchardy/python-binance#768]
Binance just announced discontinuation of WAPI as of 1st August 2021, to be replaced by SAPI.
Link: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

**Comment by expeluo** [comment]
As I have been able to see in the official documentation and how little I have been able to dive into the code, what changes is the URL of the call and, in some cases, the format of the response. From what I am seeing, this api does not process the response but returns it to the programmer. Therefore, if we change the call URLs for the new ones for each case (adding parameters if necessary) we would have the updated API. It would be the responsibility of each one to review the documentation (https://binance-docs.github.io/apidocs/spot/en/) and check if the response format has changed in relation to how it was received until now. We can even add a parameter to enable some backward compatibility. The question is, can we modify this project and also make it available to update via pip? All the best.

**Comment by hoomantah** [comment]
Looking at https://binance-docs.github.io/apidocs/spot/en/#withdraw-sapi in comparison with the https://binance-docs.github.io/apidocs/spot/en/#withdraw (old one), the parameter "asset" has changed to "coin".

Also the response has dropped two parameters of "msg" and "success"... which I see must reflect on our code at line 2385 of client.py:

https://github.com/sammchardy/python-binance/blob/master/binance/client.py#L2385 

ALSO, the withdraw endpoints URL must change accordingly.

**Comment by sammchardy** [comment]
This is included in the feature/asyncio branch that will be released as v1.0.0
