### ISSUE TITLE
get_all_coins_info_() error in v 0.710 

### ISSUE THREAD

**Issue by CyberPunkMetalHead** [sammchardy/python-binance#776]
info = client.get_all_coins_info() generates the following error when calling it from the Spot Testnet:
binance.exceptions.BinanceAPIException: APIError(code=-2008): Invalid Api-Key ID.

**Comment by CyberPunkMetalHead** [comment]
Yes, (mostly everything else works as expected). Another issue that I found is that python-binance is not returning the price for BCHUSDT and XLMUSDT, but that could be an issue with the Binance API itself.

**Comment by CyberPunkMetalHead** [comment]
My guess is that the function is not supported on the Testnet, but I have not confirmed it.

**Comment by faranazadi** [comment]
Is it returning the price for other pairs fine?

**Comment by CyberPunkMetalHead** [comment]
Yes

**Comment by lindomar-oliveira** [comment]
@sammchardy @kimchirichie
I noticed that a new version was published in the pip, but a new release was not generated.

**Comment by CyberPunkMetalHead** [comment]
Ok I figured it out, it turns out that the Spot testnet doesn't support all the coins from the mainnet. It's actually quite limited. You can check all the pairs available on the testnet by running `client.get_all_tickers()`
