### ISSUE TITLE
User_Socket Error

### ISSUE THREAD

**Issue by afia28** [sammchardy/python-binance#78]
Hello, 
I have been trying to connect to the user_socket but I've been getting APIErrors. I was wondering if this is an issue with Binance. The exact message I have been receiving is: {binance.exceptions.BinanceAPIException: APIError(code=-1000): An unknown error occured while processing the request.} 
I have used the exact same code without any issues before and this is the first time I've seen this

**Comment by sammchardy** [comment]
Hi @afia28 unfortunately the Binance API servers seem to be having issues at the moment. See more discussion on the Binance API Telegram group https://t.me/binance_api_english
