### ISSUE TITLE
get_historical_klines ignores end_str

### ISSUE THREAD

**Issue by ysautter** [sammchardy/python-binance#784]
**Describe the bug**
Commit `50a852f` introduced a bug in `binance/client.py` line 873, where it overrides the end_str parameter in `get_historical_klines`. This makes it impossible to manually set the end time. 

**To Reproduce**
Code snippet to reproduce the behavior:
```
import datetime

start = datetime.datetime.now() - datetime.timedelta(hours=48)
end = datetime.datetime.now() - datetime.timedelta(hours=24)
data = client.get_historical_klines(ticker, interval, str(start), str(end))
```

**Expected behavior**
`data` should only contain the data between start and end time.

**Environment (please complete the following information):**
 - Python version:  3.9
 - Virtual Env: pipenv
 - OS: Arch Linux
 - python-binance 0.7.11

**Comment by amit-sides** [comment]
I just noticed this bug as well. Came here to report it and found this issue.
The fix should probably be replacing the following line (client.py:873) from:
`return self._historical_klines(symbol, interval, start_str, end_str=None, limit=500, spot=True)`
to:
`return self._historical_klines(symbol, interval, start_str, end_str, limit, spot)`

**Comment by SteveChurch** [comment]
I thought I was going mad, to the point I started playing with PostMan to confirm whether I was going mad or not. Then I found this issue. 

+1

**Comment by sammchardy** [comment]
This is resolved in the feature/asyncio branch which I'll merge to master shortly. This will become v1.0.0
