### ISSUE TITLE
Web socket not getting anything

### ISSUE THREAD

**Issue by priyen** [sammchardy/python-binance#79]
I have the below code and it is not printing anything :/ 
client_binance is the client which I have setup with api key and secret a bit higher up in the code

`
def process_message(msg):
    print("message type: {}".format(msg['e']))
    print(msg)
    # do something

from binance.websockets import BinanceSocketManager
bm = BinanceSocketManager(client_binance)
bm.start_aggtrade_socket('BNBBTC', process_message)
bm.start()
`

**Comment by sammchardy** [comment]
Hi @priyen Binance has been having some issues with the websockets recently.

Your test code is returning messages when I run it so it is correct. I'd recommend checking the Binance API Telegram group https://t.me/binance_api_english if you see connection type issues.
