### ISSUE TITLE
Argument spot should default to True

### ISSUE THREAD

**Issue by ZENALC** [sammchardy/python-binance#790]
I have a project called [Algobot ](https://github.com/ZENALC/algobot)that extensively uses this module. I was updating it when I noticed that getting the earliest valid timestamp was failing because of the following code:
```

    def _get_earliest_valid_timestamp(self, symbol, interval, spot):
        """Get earliest valid open timestamp from Binance

        :param symbol: Name of symbol pair e.g BNBBTC
        :type symbol: str
        :param interval: Binance Kline interval
        :type interval: str
        :param spot: Spot endpoint, otherwise futures
        :type spot: bool

        :return: first valid timestamp

        """
        kline = self._klines(spot=spot,
                             symbol=symbol,
                             interval=interval,
                             limit=1,
                             startTime=0,
                             endTime=None
                             )
        return kline[0][0]
```

We didn't have the spot parameter before so we should default it to True as to improve compatibility with previous versions. Let me know if there's a reason to not default to True. If default is ok, I can submit a PR regarding this issue.

Cheers.

**Comment by sammchardy** [comment]
Thanks @ZENALC this is updated in the feature/asyncio branch that will be release as v1.0.0
