### ISSUE TITLE
Different REST version for signed requests

### ISSUE THREAD

**Issue by laurent101** [sammchardy/python-binance#8]
Hi,

while the project uses a version 'v1' for all REST requests, the Binance docs list a version 'v1' for unsigned and a version 'v3' for signed requests.

Cheers

**Comment by sammchardy** [comment]
Hi @laurent101,

v1 still works and provides the same functionality.

This has been a recent change to the docs. I have an update to handle the new signature hashing method.

Was holding off to see if all the endpoints were upgrading to v3 but may do an interim release with mixed endpoints.

**Comment by laurent101** [comment]
Hi,

thanks for the quick reply. Would be very grateful if you could share the interim update. 

Thanks

**Comment by sammchardy** [comment]
@laurent101 sorry for the delay. v0.1.6 has been pushed with v3 implementation.

**Comment by laurent101** [comment]
Thanks, @sammchardy. Much appreciated.
