### ISSUE TITLE
Memo for Lumen

### ISSUE THREAD

**Issue by jtweaver** [sammchardy/python-binance#81]
Is it possible to withdraw Stellar Lumen (with Memo) using this package or even the REST API? I noticed the withdraw method takes the param "name". Will this be translated to the memo field for a Lumen withdraw? Thanks.

**Comment by sammchardy** [comment]
Hi @jtweaver no the `name` field won't be. Looking at the Binance documentation there is an `addressTag` parameter that I haven't included in my documentation that I believe should be used for this purpose. See the documentation here https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#withdraw 

You can pass this yourself to the `withdraw` function as any params are just passed through.

```

    from binance.exceptions import BinanceApiException, BinanceWithdrawException
    try:
        result = client.withdraw(
            asset='XLM',
            address='<stellar_address>',
            addressTag='<xlm_address_tag>',
            amount=100)
    except BinanceAPIException as e:
        print(e)
    except BinanceWithdrawException as e:
        print(e)
    else:
        print("Success")

```

I will release a new version shortly that has documentation for the addressTag.

**Comment by jtweaver** [comment]
Great. Thanks @sammchardy !
