### ISSUE TITLE
How do I switch the domain so I can use Binance.us?

### ISSUE THREAD

**Issue by GrantDeWaay** [sammchardy/python-binance#812]
I cannot seem to find a config file, can someone point out how I would go about changing this?

**Comment by sammchardy** [comment]
Pass a `tld` parameter to the client when you create it like this
```
from binance.client import Client
client = Client(tld='us')
```
or async client
```from binance import AsyncClient, DepthCacheManager, BinanceSocketManager

async def main():

    # initialise the client
    client = await AsyncClient.create(tld='us')
```

This tld will also be passed to websocket streams that are given the client.

**Comment by GrantDeWaay** [comment]
worked perfectly, do you think this kind of thing should go in the FAQ section? It does say that different domains are a feature, but it doesn't elaborate?

**Comment by sammchardy** [comment]
Yes, have updated the docs with examples, let me know if they are sufficient.

**Comment by GrantDeWaay** [comment]
Looks good!
