### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.websockets'

### ISSUE THREAD

**Issue by phicha20224** [sammchardy/python-binance#813]
Name: python-binance
Version: 1.0.2
Summary: Binance REST API python implementation
Home-page: https://github.com/sammchardy/python-binance
Author: Sam McHardy
Author-email:
License: MIT
Location: c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages
Requires: six, requests, websockets, dateparser, aiohttp, ujson
Required-by:

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from binance.client import Client
>>> from binance.websockets import BinanceSocketManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'binance.websockets'
>>> from twisted.internet import reactor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'twisted'

**Comment by phicha20224** [comment]
Please help.. Thank You.

**Comment by sammchardy** [comment]
Hi @phicha20224 

As you can see in the Readme v1.0.0 has breaking changes related to websockets.

We no longer use Twisted and autobahn for websockets, but rather the websockets library and python asyncio.

**Comment by friday-james** [comment]
Yes, we have a new module for that now/
Please refer to readme in https://github.com/sammchardy/python-binance/blob/master/README.rst

import
```python
from binance import AsyncClient, DepthCacheManager, BinanceSocketManager
```

**Comment by phicha20224** [comment]
Thank You, 
Its cleary because I too far quickly dont read first..
