### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by ThySpecter** [sammchardy/python-binance#818]
I just found out there was a massive overhaul of the library, is there new documentation to support this? Websockets are working completely differently now.

**Comment by sammchardy** [comment]
Yes, though looks like readthedocs isn't updating.

Docs can be found here for now https://github.com/sammchardy/python-binance/tree/master/docs

Main readme has been updated with some examples https://github.com/sammchardy/python-binance

**Comment by sammchardy** [comment]
https://python-binance.readthedocs.io/

This doc is now up to date as well
