### ISSUE TITLE
x-mbx-* header access for a rate limit implementation with the async api

### ISSUE THREAD

**Issue by kpe** [sammchardy/python-binance#824]
First of all - thank you for your awesome library!

With an older version and the sync client, I was able to access `Client.response.headers` to check the current value of the `x-mbx-used-weight` headers.

Is there any way I can access the raw HTTP headers - with the `AsyncClient`?

**Comment by sammchardy** [comment]
Let me check and I'll update if it's not currently exposed properly.

**Comment by sammchardy** [comment]
Update in v1.0.5

docs here https://python-binance.readthedocs.io/en/latest/overview.html#api-rate-limit

**Comment by kpe** [comment]
@sammchardy - wow, that was quick! I've just tested it, and it works great!
