### ISSUE TITLE
User Data Streams (Futures)

### ISSUE THREAD

**Issue by Zakariaair** [sammchardy/python-binance#826]
Hi
I cant find a method for Futures User Data Streams. Does it exist? If not, when will it be added?
Thanks

**Comment by sammchardy** [comment]
Yes, it's `futures_socket` on the `BinanceSocketManager`

https://github.com/sammchardy/python-binance/blob/a6fd6989eb64d913b93b9d7f5647cd49dc4c6edb/binance/streams.py#L912
