### ISSUE TITLE
Error installing api wrapper through pip

### ISSUE THREAD

**Issue by skwelker** [sammchardy/python-binance#83]
Hey I am getting an error when installing the binance api wrapper that says it "Failed building wheel for twisted" and is saying that Microsoft Visual C++ 14.0 is required.  Do I just need to install Microsoft Visual C++ and that will resolve this issue?

Thx

**Comment by ronenshohat** [comment]
same issue, bump

**Comment by scoshil** [comment]
not sure if there's an easier way but I had the same issue and I went to:

http://landinghub.visualstudio.com/visual-cpp-build-tools

download and install the Build Tools 2015 on that link, then try installing again and it works.

**Comment by sammchardy** [comment]
Depending on the version of Python you're using the resolution may be different.

The Python Wiki gives a good run down of some fixes https://wiki.python.org/moin/WindowsCompilers, I'll add this to the documentation.

**Comment by sammchardy** [comment]
Added note to Getting Started and FAQ section of documentation

https://python-binance.readthedocs.io/en/latest/overview.html
