### ISSUE TITLE
get_symbol_info required symbol

### ISSUE THREAD

**Issue by Sifflex** [sammchardy/python-binance#830]
https://github.com/sammchardy/python-binance/blob/4b7faec9eb24f06885f8074eebbb16af02e8a508/binance/client.py#L502

Why making the symbol mandatory ? [The documentation](https://binance-docs.github.io/apidocs/spot/en/#exchange-information) doesn't require this symbol.

**Comment by Sifflex** [comment]
You're right, I don't know what I was thinking

**Comment by sammchardy** [comment]
No problem!
