### ISSUE TITLE
Websocket usage: asyncio coroutine not running

### ISSUE THREAD

**Issue by LeonhardOiler** [sammchardy/python-binance#836]
I am not able to make work the websocket usage with the AsyncClient. The same code as in the documentation (just under section Websocket Usage) does not print anything. 

I also tried to run a simple asyncio coroutine printing "hello world". The latter works in general but does not when I import the python-binance package in the script. 

Interesting is that all works fine in Jupyter Notebook, but not in a python script. 

Do you have an idea of what could be wrong?

Thanks.

**Comment by Unterarzt** [comment]
I've just defaulted to 0.7.11 before these issues get ironed out. The current library requires you to implement your own asynchronous updater, whereas the 'outdated' version abstracted it.
