### ISSUE TITLE
"listen key same: keepalive" message is being printed

### ISSUE THREAD

**Issue by mchangun** [sammchardy/python-binance#839]
When the websockets are running, this message gets printed to screen periodically:

`listen key same: keepalive`

https://github.com/sammchardy/python-binance/blob/a47cfabccdd6d5780b35fd67933044c6a1d1d316/binance/streams.py#L229

Can we remove or comment it out? Or move it to logging at the info level?

Thanks!

**Comment by Joren-vanGoethem** [comment]
i agree, this gets spammed in the console too often
