### ISSUE TITLE
"user_socket" fails to work and throws a Runtime Error: "Timeout context manager should be used inside a task."

### ISSUE THREAD

**Issue by aryan-f** [sammchardy/python-binance#842]
**Describe the bug**
Using `user_socket()` causes `aiohttp` to throw the following exception:

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Bot.update_loop() done, defined at ...\bot\main.py:90> exception=RuntimeError('Timeout context manager should be used inside a task')>
Traceback (most recent call last):
  File "...\bot\main.py", line 91, in update_loop
    async for update in self.account.updates():
  File "...\bot\accounts\binance.py", line 33, in updates
    async with manager.user_socket() as websocket:
  File "...\venv\lib\site-packages\binance\streams.py", line 51, in __aenter__
    await self.connect()
  File "...\venv\lib\site-packages\binance\streams.py", line 65, in connect
    await self._before_connect()
  File "...\venv\lib\site-packages\binance\streams.py", line 190, in _before_connect
    self._path = await self._get_listen_key()
  File "...\venv\lib\site-packages\binance\streams.py", line 204, in _get_listen_key
    listen_key = await self._client.stream_get_listen_key()
  File "...\venv\lib\site-packages\binance\client.py", line 6972, in stream_get_listen_key
    res = await self._post('userDataStream', False, data={})
  File "...\venv\lib\site-packages\binance\client.py", line 6506, in _post
    return await self._request_api('post', path, signed, version, **kwargs)
  File "...\venv\lib\site-packages\binance\client.py", line 6466, in _request_api
    return await self._request(method, uri, signed, **kwargs)
  File "...\venv\lib\site-packages\binance\client.py", line 6447, in _request
    async with getattr(self.session, method)(uri, **kwargs) as response:
  File "...\venv\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "...\venv\lib\site-packages\aiohttp\client.py", line 448, in _request
    with timer:
  File "...\venv\lib\site-packages\aiohttp\helpers.py", line 635, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

**To Reproduce**

I use the following function to retireve and return the events:

```python
async def updates(self):
    manager = BinanceSocketManager(self.client)
    async with manager.user_socket() as websocket:
        while self.running:
            message = await websocket.recv()
            yield message
```

The asynchronous coroutines are started like this:

```python
self.loop = asyncio.new_event_loop()
asyncio.set_event_loop(self.loop)
self.loop.create_task(self.main_loop())
self.loop.create_task(self.update_loop())
self.loop.run_forever()
```

**Expected behavior**
-

**Environment (please complete the following information):**
 - Python version: 3.9.5
 - Virtual Env: virtualenv
 - OS: Windows 10 (Build: 19042.928)
 - python-binance version: 1.0.7

**Logs or Additional context**
I work with `kline_socket` in a similar manner and that works just fine. I debugged the code and traced the exceptions. The cause of the issue is that when `aiohttp` calls `current_task()`, a function inside its `helpers` module, the `_loop` attribute is set to a wrong loop that isn't running, and therefore, the returned value is None. If it called `asyncio.current_task()` without passing it the loop it assumes is running, it would have received the correct loop and task. 

By further tracing the codes, `python-binance` seems to be setting the loop it believes to be running when creating the session. This value itself is calculated by calling `asyncio.get_event_loop()` inside the constructor of `AsyncClient`. I don't understand how this works for `kline_socket` but not for `user_socket`. Is there any difference between the two that I'm missing? Could it be due to the fact that `user_stream()` has to first get a `listenKey`?

**Comment by farahmand-m** [comment]
> @farahmand-m Did you figure out what was the problem ? I'm having a similar issue.

It was because I was instantiating `AsyncClient` before the first two lines where I created and set the new event loop. `AsyncClient` looks for loop in the constructor and takes the first one `asyncio` offers. You either need to instantiate the class after creating and setting the new event loop or replace the first two lines with the default event loop:

```python
loop = asyncio.get_event_loop()
```
