### ISSUE TITLE
coroutine 'KeepAliveWebsocket._keepalive_socket' was never awaited

### ISSUE THREAD

**Issue by Joren-vanGoethem** [sammchardy/python-binance#847]
https://github.com/sammchardy/python-binance/blob/66aebfa4c074fdfdd79fb4b56f66c7f3185321c6/binance/streams.py#L206

**Comment by sammchardy** [comment]
This is caused by using the `call_later` the coroutine is created, but then the program exits, or the timer is cancelled and the coroutine is not awaited.

This would be output as warning?

**Comment by Yimura** [comment]
This warning stops execution of any code after it, this error is recurring, nowhere in our code do we have any reference to `KeepAliveWebsocket._keepalive_socket`.

So we've looked into the code and the only occurrence/call to this function is found in the linked code above.
