### ISSUE TITLE
Websockets not receiving messages

### ISSUE THREAD

**Issue by kokojiji01** [sammchardy/python-binance#848]
I just upgraded from python-binance 1.0.4 to 1.0.9 and I cannot receive messages from multiplex_socket using symbol@bookTicker stream. I'm using the BinanceSocketManager with async. Other streams are working fine for example symbol@trade and symbol@depth stream. Also the book_ticker_socket() works.

Here is the most basic code:

`import asyncio
from binance import AsyncClient, BinanceSocketManager

async def listener(client):
    bm = BinanceSocketManager(client)
    symbols1 = ["btcusdt@trade"]
    symbols2 = ["btcusdt@bookTicker"]
    multi_socket = bm.multiplex_socket(symbols2)
    async with multi_socket as ms:
        while True:
            res = await ms.recv()
            print(res)

async def main():
    print("Client created")
    client = await AsyncClient.create()
    await listener(client)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())`

The result is that no messages arrive when using symbols2 and with symbols1 it works just fine.

Environment:

Python version: [e.g. 3.9]
OS: Windows
python-binance version 1.0.9

**Comment by sammchardy** [comment]
fixed issue with lowercasing passed stream names in v1.0.10
