### ISSUE TITLE
Wrong documentation/docstring for get_all_tickers method

### ISSUE THREAD

**Issue by erichamers** [sammchardy/python-binance#851]
Hey everyone,

I believe that the get_all_tickers method has incorrect documentation. [Here](https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_all_tickers) is the source code:

def get_all_tickers(self) -> Dict:
        """Latest price for a symbol or symbols.

        https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker

        :param symbol: optional
        :type symbol: str

        :returns: List of market tickers

        .. code-block:: python

            [
                {
                    "symbol": "LTCBTC",
                    "price": "4.00000200"
                },
                {
                    "symbol": "ETHBTC",
                    "price": "0.07946600"
                }
            ]

        :raises: BinanceRequestException, BinanceAPIException

        """
        return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
As you can see, method doesn't take any parameters, inspite of what the documentation and docstring show.

**Comment by sammchardy** [comment]
You're right, there's a mismatch.

Looking at the Binance docs (https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker) it can take an optional symbol so I'll add that in.

**Comment by sammchardy** [comment]
This is now updated v1.0.10
