### ISSUE TITLE
APIError(code=-1104): Not all sent parameters were read; read '8' parameter(s) but was sent '9'.

### ISSUE THREAD

**Issue by JMedon** [sammchardy/python-binance#87]
Hi when I send limit order with disable_validation=True I got above error.

order = client.order_limit_buy(
    symbol='TRXBTC',
    quantity=1000,
    price='0.00000500',
    disable_validation=True
    )

what is the difference between disable_validation=True vs False?

thanks

**Comment by sammchardy** [comment]
Hi @JMedon, the disable_validation parameter was referring to some old functionality which validated order parameters on the client side.

I have removed the reference to disable_validation from the docs.
