### ISSUE TITLE
Futures websocket: options_multiplex_socket() got an unexpected keyword argument 'futures_type'

### ISSUE THREAD

**Issue by AurelReb** [sammchardy/python-binance#875]
It seems that there is an error in the `start_futures_multiplex_socket()` function.

the socket_name is written as `options_multiplex_socket` instead of `futures_multiplex_socket`
This leads to an error when running the multiplex socket: `options_multiplex_socket() got an unexpected keyword argument 'futures_type'`

https://github.com/sammchardy/python-binance/blob/30efaffc303a55855889a607879e9ca0eacb5221/binance/streams.py#L1226

Please change it asap as it's a critical error

**Comment by greg2paris** [comment]
I was running into the same problem, I had to change the code myself as u suggested, replacing options_multiplex_socket string by futures_multiplex_socket, now its working like a charm thx !

**Comment by AurelReb** [comment]
Would be great if my pull request was accepted in a new release asap. I can't deploy my application in a good way without it 😅
