### ISSUE TITLE
raise BinanceAPIException when call futures_open_interest

### ISSUE THREAD

**Issue by Jeonghun-Ban** [sammchardy/python-binance#883]
**Describe the bug**
`BinanceAPIException` occurs when calling `futures_open_interest()`.

**To Reproduce**
Code snippet to reproduce the behavior: just call `futures_open_interest()` function.

**Expected behavior**

```json
{
  "openInterest": "33322.427", 
  "symbol": "BTCUSDT", 
  "time": 1622124079359
}
```

**Environment**
 - Python version: 3.9.0
 - Virtual Env: virtualenv
 - OS: Ubuntu
 - python-binance version: latest

**Logs or Additional context**

```
binance.exceptions.BinanceAPIException: APIError(code=0)
```

**Comment by sammchardy** [comment]
This has been fixed in v1.0.11
