### ISSUE TITLE
 cannot import name 'AsyncClient' from partially initialized module 'binance'

### ISSUE THREAD

**Issue by erfanmosaddeghi** [sammchardy/python-binance#887]
**Describe the bug**
Can't Import AsyncClient from binance

**Environment :**
 - Python version: 3.8
 - Virtual Env: virtualenv
 - OS: linux
 - python-binance version 1.0.1

**Logs or Additional context**
cannot import name 'AsyncClient' from partially initialized module 'binance' (most likely due to a circular import

**Comment by tperalta82** [comment]
This happened to me, make sure your don't have another module named binance in your code

**Comment by erfanmosaddeghi** [comment]
> This happened to me, make sure your don't have another module named binance in your code

thanks.
yes i found it.
file name: socket.py
it was because of this. i changed it.
