### ISSUE TITLE
How to determine the futures or spot type for get_historical_klines?

### ISSUE THREAD

**Issue by alishah79** [sammchardy/python-binance#911]
Hi.I don't know How to determine the futures or spot type for get_historical_klines function and I havent found any docs or examples on it.please help me.

klines_type=HistoricalKlinesType(SPOT) error

**Comment by AlexNik** [comment]
@alishah79 try `klines_type=HistoricalKlinesType. SPO)`

**Comment by alishah79** [comment]
> 
> 
> @alishah79 try `klines_type=HistoricalKlinesType.SPOT`

Hi.I tried that.but it didn't work.

**Comment by AlexNik** [comment]
@alishah79 what's the error?

**Comment by alishah79** [comment]
> 
> 
> @alishah79 what's the error?

Hi AlexNik.Thank you so much for helping me.It worked this time!!!
since you're so skilled,can you please take a look at this issue too?
 #https://github.com/mementum/bta-lib/issues/17
