### ISSUE TITLE
Leveraged tokens?

### ISSUE THREAD

**Issue by tsunamilx** [sammchardy/python-binance#922]
It seems that the leveraged token api (https://binance-docs.github.io/apidocs/spot/en/#blvt-endpoints) is not supported, is there any plan to get it supported? Or can I get some guidelines how to extend the api by myself?

Thanks.

**Comment by tsunamilx** [comment]
Never mind, looks like I can trade the leveraged token just using spot api.

**Comment by Fo3nix** [comment]
How did you manage to do it?

**Comment by tsunamilx** [comment]
@Fo3nix If you just need to trade the token, use the spot api.

**Comment by Fo3nix** [comment]
Sorry I don't really get what you mean. Are there differences in api?

My current code gave this error: binance.exceptions.BinanceAPIException: APIError(code=-2010): This action disabled is on this account.

How can I fix that?

**Comment by tsunamilx** [comment]
This might help
https://github.com/freqtrade/freqtrade/issues/3945

**Comment by Fo3nix** [comment]
Thanks for helping me this fast! I'll look into it tomorrow. Thanks again
