### ISSUE TITLE
Websocket API for user data not working.

### ISSUE THREAD

**Issue by avnkailash** [sammchardy/python-binance#94]
I created a binance trading algo, but mysteriously, it is not working on one machine while it is working flawlessly on another machine. The problem is, on the machine where it is not working, the user data stream is not working, i am not able to recieve any messages on that particular stream. Depth stream and kline stream are working fine. Did I miss anything?

**Configuration** 
Python : 2.7.14
python-binance : python-binance (0.5.17)

The configuration on the machine where the code is working without any issues is
Python : 2.7.12
python-binance : python-binance (0.5.15)

Is there any issue with the latest version?

**Comment by avnkailash** [comment]
The version 0.5.17 seems to be having issue with the user data stream, or may be I missed something. But when I downgraded the version to 0.5.15, it is working without issues.The python version had no impact on the program (atleast in my case)

**Comment by sammchardy** [comment]
Hi @avnkailash there are very minimal changes between 0.5.15 and 0.5.17 relating to the withdraw function, it's mostly just documentation updates. Nothing that should affect the user data stream.

**Comment by avnkailash** [comment]
Looks like the issue is still there. Let me check it today.

**Comment by shubhankar1904** [comment]
Hi, the issue is still there. I am trying to use depth socket and continuously getting error. I tried implementing the socket myself and still getting the error. Seems like its an issue from binance end. Please correct me if wrong.

**Comment by sammchardy** [comment]
Binance has had some websocket errors recently mostly because of the .

The library does the best it can at connecting and reconnecting on error. See the latest version and documentation around knowing when the websocket has disconnected https://python-binance.readthedocs.io/en/latest/websockets.html#websocket-errors

**Comment by coelias** [comment]
I am trying the example on the main page and the websocket part does not work I remember it working a couple of weeks ago. Is it a binance problem or a library problem?

c
