### ISSUE TITLE
Futures trading not possible:APIError(code=-4164): Order's notional must be no smaller than 5.0

### ISSUE THREAD

**Issue by alishah79** [sammchardy/python-binance#947]
Hi.
I'm trying to create a new futures order with a little money in order to test my bot but gives me errors:
`order=client.futures_create_order(symbol=sym,side=f'{signal}',type='MARKET',positionSide= "LONG",quantity=str(coinQuantity),leverage=10)`
error=binance.exceptions.BinanceAPIException: APIError(code=-4164): Order's notional must be no smaller than 5.0 (unless you choose reduce only)
I really don't know what notional means in here and what is restricting me,I did this change:
`order=client.futures_create_order(symbol=sym,side=f'{signal}',type='MARKET',positionSide= "LONG",quantity=str(coinQuantity),leverage=10,reduceOnly='true')`
but also this time it gives me this error:binance.exceptions.BinanceAPIException: APIError(code=-1106): Parameter 'reduceOnly' sent when not required.
coinQuantity is 0.001 and symbol is 'ETHUSDT'.
python 3.7.9

**Comment by mfiro** [comment]
Read [this](https://www.binance.com/en/support/announcement/1d762daf60dd417f9d8a05d44b06a25c)

**Comment by alishah79** [comment]
> 
> 
> Read [this](https://www.binance.com/en/support/announcement/1d762daf60dd417f9d8a05d44b06a25c)

Thank you so much..It works now.
since I used to trade in binance panel and get no error for notional less than 5,therefore I did not realize the poblem with my program.
