### ISSUE TITLE
.get_historical_klines not working

### ISSUE THREAD

**Issue by SkylerX** [sammchardy/python-binance#95]
klines = client.get_historical_klines("NEOBTC", KLINE_INTERVAL_1WEEK, "1 Jan, 2017")
AttributeError: 'Client' object has no attribute 'get_historical_klines'

also there is a little mistake at the end of the examples on the guide:
http://python-binance.readthedocs.io/en/latest/market_data.html#id5 

Can you please help!
Thanks.
Cheers

**Comment by sammchardy** [comment]
Hi @SkylerX make sure you up to the latest version v0.6.1

**Comment by SkylerX** [comment]
Thanks Sam!
Cheers
