### ISSUE TITLE
'testnet' argument not recognized on client creation

### ISSUE THREAD

**Issue by gschurck** [sammchardy/python-binance#951]
Hello,
I have an issue when trying to use testnet on a client.
```    
>   client = Client(api_key, secret_key, testnet=True)
TypeError: __init__() got an unexpected keyword argument 'testnet'
```

As writted in doc, it should work in this way to use testnet, no ?
What is wrong ?

 - Python version: 3.7
 - OS: Windows 10
 - python-binance version : 0.7.9
 
 Thanks.

**Comment by gtvCH** [comment]
Only python-binance version v1.0.4 or higher supports testnet.

**Comment by gtvCH** [comment]
Spot Testnet support added at version 1.0.3
Futures Testnet support added at version 1.0.4
Latest python-binance version: 1.0.12

**Comment by gschurck** [comment]
Oh lol why my library version was not updating with pip...

**Comment by gschurck** [comment]
Oh lol why my library version was not updating with pip...
