### ISSUE TITLE
client.get_symbol_ticker does'nt work on testnet

### ISSUE THREAD

**Issue by gschurck** [sammchardy/python-binance#954]
**Describe the bug**

I set testnet = true, and all the functions are working except get_symbol_ticker
Is it normal that this function is not working on testnet ? (it works normally)

**To Reproduce**
`get = client.get_symbol_ticker(symbol="DOGEUSDT")`
and I get this error :
`binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.`

 - Python version: 3.7
 - OS: Windows 10
 - python-binance version 1.0.12

**Comment by jlixfeld** [comment]
I believe there are only certain tickers that are available in `testnet`, and that might not be one of them.  You can use `client.get_all_tickers()` with `testnet` in your client setup to get a list of what's available.

**Comment by gschurck** [comment]
Ok thanks, I checked and yes there is only a few of them sadly.
