### ISSUE TITLE
Installing error in Windows 7 64bits

### ISSUE THREAD

**Issue by Lucxs001** [sammchardy/python-binance#958]
Hi guys, I'm trying to solve this a couple days

![image](https://user-images.githubusercontent.com/87201263/125292990-5ffbbe80-e2f9-11eb-93c1-3387f301cf7b.png)

I already tried installing python-binance using PyCharm and still occurring that error

**Comment by oliver-zehentleitner** [comment]
Actually you posted the solution:
![solution](https://user-images.githubusercontent.com/47597331/125958359-9ceb3900-9d6a-41ab-a670-18b3301df2ec.png)

**Comment by Lucxs001** [comment]
I already tried this, actually in using a Microsoft Visual C++ 16.0, and still occurring that error @oliver-zehentleitner
