### ISSUE TITLE
How to start Futures Account Websocket (subscribe to Futures User Data Stream)?

### ISSUE THREAD

**Issue by CryPtoSmartGuy420** [sammchardy/python-binance#989]
I've been searching for long, and all the community solutions from the past are now very confusing. As far as I understood, this option is now possible in the latest versions of python-binance?

I managed to successfully get my  Futures listenKey with 
`client.future_stream_get_listen_key()`

but when it comes to starting the websocket I have no idea what to do
https://binance-docs.github.io/apidocs/futures/en/#user-data-streams

**Comment by CryPtoSmartGuy420** [comment]
I'm sure there may be a "built-in" way to do this, and please show me how whenever, I will surely read it. But I managed to solve it like this:

`import websocket
import json

import config
from binance.client import Client

client = Client(config.API_KEY, config.API_SECRET)


SOCKET = "wss://fstream.binance.com/ws/YourListenKey"


def on_open(ws):
    print("opened connection to Binance streams")


def on_close(ws):
    print("closed connection to Binance streams")


def on_message(ws, message):
    print("message received from Binance streams")
    json_message = json.loads(message)
    print(json_message)
    

ws = websocket.WebSocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message)
ws.run_forever()`

Keep in mind, "pip install websocket-client" is needed to use some of these functions, and if I'm not mistaken, it is not the same as "pip install websocket," so keep that in mind.

**Comment by jypuigbo** [comment]
Hi @CryPtoSmartGuy420 , 
I'd love to know how did you manage did you successfully manage to get your listen_key with the function you mentioned. 

I can't find that method neither in the online repo, neither in my installed version of python-binance. 

Could you please elaborate?

Thank you for your contribution anyway!

**Comment by jypuigbo** [comment]
@CryPtoSmartGuy420 Sorry, I just got my answer. there was a typo in the command you wrote. It's correct in the official documentation. 

Again, thanks for your input. It helped me reach what I needed.
